# ExportDecompiled.py
# @category Stars
# @description: Export decompiled code for multiple functions to a file
#
# Usage (headless): -postScript ExportDecompiled.py <output_file> <func1> [func2] ...

import os
import sys

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor


def find_function_by_name(fm, name):
    """Find a function by exact name (case-insensitive)."""
    name_lower = name.lower()
    for f in fm.getFunctions(True):
        if f.getName().lower() == name_lower:
            return f
    return None


def decompile_function(func, decomp):
    """Decompile a function and return the C code."""
    try:
        monitor = ConsoleTaskMonitor()
        result = decomp.decompileFunction(func, 60, monitor)

        if result.decompileCompleted():
            return result.getDecompiledFunction().getC()
        else:
            return "// Decompilation failed: %s" % result.getErrorMessage()
    except Exception as e:
        return "// Decompilation error: %s" % str(e)


def main():
    args = getScriptArgs()

    if len(args) < 2:
        println("Usage: ExportDecompiled.py <output_file> <func1> [func2] ...")
        println("")
        println("Example: ExportDecompiled.py output.c LpflFromId LpplFromId Random")
        return

    output_file = args[0]
    func_names = args[1:]

    println("Output file: %s" % output_file)
    println("Functions to decompile: %s" % ", ".join(func_names))

    fm = currentProgram.getFunctionManager()

    decomp = DecompInterface()
    decomp.openProgram(currentProgram)

    try:
        with open(output_file, "w") as f:
            f.write("// Decompiled code from stars.exe (Stars! 2.60j RC3)\n")
            f.write("// Generated by Ghidra\n")
            f.write("// \n\n")

            for name in func_names:
                println("Processing: %s" % name)
                func = find_function_by_name(fm, name)

                f.write("// " + "=" * 70 + "\n")
                f.write("// Function: %s\n" % name)

                if func is None:
                    f.write("// NOT FOUND\n")
                    f.write("// " + "=" * 70 + "\n\n")
                    println("  NOT FOUND")
                    continue

                f.write("// Address: %s\n" % func.getEntryPoint())
                f.write("// " + "=" * 70 + "\n\n")

                code = decompile_function(func, decomp)
                if code:
                    f.write(code)
                    f.write("\n\n")
                    println("  OK")
                else:
                    f.write("// No code generated\n\n")
                    println("  No code")

        println("Output written to: %s" % output_file)

    finally:
        decomp.dispose()


if __name__ == "__main__":
    main()
