// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: DoMacintiAiTurn
// Address: 10a0:0008
// Segment: MEMORY_AI3
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10a00aea) */
/* WARNING: Removing unreachable block (ram,0x10a00c33) */
/* WARNING: Removing unreachable block (ram,0x10a0117d) */
/* WARNING: Removing unreachable block (ram,0x10a00ac9) */
/* WARNING: Removing unreachable block (ram,0x10a00c12) */
/* WARNING: Removing unreachable block (ram,0x10a016a5) */
/* WARNING: Removing unreachable block (ram,0x10a0133f) */
/* WARNING: Removing unreachable block (ram,0x10a0167c) */
/* WARNING: Removing unreachable block (ram,0x10a00aef) */
/* WARNING: Removing unreachable block (ram,0x10a00c38) */
/* WARNING: Removing unreachable block (ram,0x10a00c61) */
/* WARNING: Removing unreachable block (ram,0x10a00c66) */
/* WARNING: Removing unreachable block (ram,0x10a00e6d) */
/* WARNING: Removing unreachable block (ram,0x10a00ddc) */
/* WARNING: Removing unreachable block (ram,0x10a01263) */
/* WARNING: Removing unreachable block (ram,0x10a00eb7) */
/* WARNING: Removing unreachable block (ram,0x10a01b1f) */
/* WARNING: Removing unreachable block (ram,0x10a02475) */
/* WARNING: Removing unreachable block (ram,0x10a010d6) */
/* WARNING: Removing unreachable block (ram,0x10a0111e) */
/* WARNING: Removing unreachable block (ram,0x10a012c1) */

void DoMacintiAiTurn(PROD *rgprod)

{
  uint *puVar1;
  byte *pbVar2;
  SHDEF *pSVar3;
  undefined2 *puVar4;
  HullDef *pHVar5;
  undefined2 *puVar6;
  int iVar7;
  uint uVar8;
  uint uVar9;
  PLORD *pPVar10;
  POINT pt1;
  POINT pt;
  POINT pt2;
  short sVar11;
  ushort uVar12;
  uint uVar13;
  byte *pbVar14;
  PLANET *pPVar15;
  FLEET *pFVar16;
  int iVar17;
  undefined2 unaff_SI;
  SHDEF *pSVar18;
  undefined2 *puVar19;
  undefined2 unaff_DI;
  HullDef *pHVar20;
  undefined2 *puVar21;
  undefined2 uVar22;
  undefined2 unaff_SS;
  bool bVar23;
  long lVar24;
  ulong uVar25;
  PLANET *pPVar26;
  ulong uVar27;
  HullDef in_stack_0000feba;
  undefined1 ord [4];
  short iplDest;
  PLANET *lpplBest;
  ITEMACTION lLeast;
  undefined1 lDist [4];
  ITEMACTION IStack_b4;
  PART part;
  PROD *lpprod;
  byte rgRecycleSBShdef [10];
  short fTonsOfMinerals;
  short fWrite;
  undefined4 l;
  short iPlanet;
  FLEET *lpflAttack;
  undefined2 local_90;
  ushort rgCosts [4];
  short cFlMiners;
  short cFlMineLayersBase;
  byte *lpb;
  byte rgRecycleShdef [7];
  char local_77;
  undefined1 local_70;
  ushort cRecyclePeriod;
  short iLatestColony;
  short ipl;
  short iLatestDestroyer;
  short fUsingTempColonizer;
  short iLatestMiner;
  short iroCur;
  short cFr;
  short cRes;
  short cFlArmadas;
  short cGenesis;
  FLEET *lpfl;
  short i;
  short ifl;
  short iLatestBomber;
  short cFlCargo;
  PLANET *lppl;
  short iLatestBattle;
  short iAiLvl;
  short cshDestroyer;
  short cFlDestroyers;
  short fShouldColonize;
  short cFlMineLayers;
  undefined4 lpthWorm;
  short ishLastBattle;
  short iLatestCruiser;
  PLANET *lpplMac;
  undefined2 local_32;
  uint rgResAvail [8];
  FLEET *lpflEnemy;
  undefined2 local_1e;
  short j;
  short idPlanDst;
  uint rgResCost [8];
  short cColFleet;
  short iLatestCargo;
  
  uVar27 = CONCAT22(unaff_SI,unaff_DI);
  iAiLvl = *(uint *)((int)&rgplr[0].wMdPlr + idPlayer * 0xc0) >> 10 & 7;
  iPlanet = *(short *)((int)&rgplr[0].idPlanetHome + idPlayer * 0xc0);
  iroCur = IroEnsureAi(vrgAiMacintiResOrder,8,(short *)0x0,0xf);
  if (((uint)game.turn < 0x28) ||
     ((((uint)rgshdef[7].wFlags >> 9 & 1) == 0 &&
      (rgshdef[7].hul.ihuldef == ihuldefColonyShip)))) {
    fUsingTempColonizer = 1;
    sVar11 = FLookupPartX(&part,1,0xf);
    if ((sVar11 == 1) &&
       (((int)rgshdef[7].cExist == 0 && (rgshdef[7].cExist._2_2_ == 0)))) {
      pSVar18 = (SHDEF *)(rgshdef + 7);
      pHVar20 = (HullDef *)&stack0xfeba;
      for (iVar17 = 0x49; iVar17 != 0; iVar17 = iVar17 + -1) {
        pHVar5 = pHVar20;
        pHVar20 = pHVar20 + 1;
        pSVar3 = pSVar18;
        pSVar18 = (SHDEF *)(pSVar18->hul).rgTech;
        *pHVar5 = (pSVar3->hul).ihuldef;
      }
      *(char *)pHVar20 = (char)(pSVar18->hul).ihuldef;
      FChangeAiShdef((SHDEF *)&stack0xfeba,7);
      fUsingTempColonizer = 0;
    }
  }
  else {
    fUsingTempColonizer = 0;
  }
  ishLastBattle = 7 - fUsingTempColonizer;
  if (fUsingTempColonizer == 0) {
    MergeAllShdefs(0x3fc);
  }
  else {
    MergeAllShdefs(0x37c);
  }
  MergeAllShdefs(1);
  MergeAllShdefs(-0x4000);
  MergeAllShdefs(0x3000);
  j = 6;
  if (0x82 < (uint)game.turn) {
    j = (game.turn - 0x78U) / 0x14 + 6;
  }
  if (0x32 < (uint)j) {
    j = 0x32;
  }
  vrgAiArmadaPotency[0] = (byte)j;
  vrgAiArmadaPotency[1] = (byte)((ulong)(j & 0xff) / 2);
  j = 6;
  if (0x73 < (uint)game.turn) {
    j = (game.turn - 100U) / 0x16 + 6;
  }
  if (0xc < (uint)j) {
    j = 0xc;
  }
  vrgAiArmadaPotency[2] = (byte)j;
  if ((int)((uint)j / 2 - 1) < 4) {
    vrgAiArmadaPotency[3] = (char)((uint)j / 2) - 1;
  }
  else {
    vrgAiArmadaPotency[3] = 3;
  }
  _memset(rgRecycleShdef,0,0x10);
  if ((uint)game.turn < 0x78) {
    cRecyclePeriod = 0x32;
  }
  else if ((uint)game.turn < 200) {
    cRecyclePeriod = 0x46;
  }
  else {
    cRecyclePeriod = 100;
  }
  cshDestroyer = CheckAiShdefStatus(0xc,0xd,cRecyclePeriod,&iLatestDestroyer,rgRecycleShdef);
  for (i = 0xc; i < 0xe; i = i + 1) {
    if (((rgRecycleShdef[i] != 0) &&
        ((*(uint *)((int)&rgshdef[0].wFlags + i * 0x93) >> 9 & 1) == 0)) &&
       (*(int *)(i * 0x93 + 0x3f00) == 0x1d)) {
      rgRecycleShdef[i] = 0;
    }
  }
  CheckAiShdefStatus(0xe,0xf,5000,&iLatestMiner,rgRecycleShdef);
  if ((((uint)rgshdef[0xf].wFlags >> 9 & 1) == 0) &&
     (sVar11 = FLookupPartX(&part,0x80,6), sVar11 == 1)) {
    if (iLatestMiner == 0xe) {
      i = 0xf;
    }
    else {
      i = 0xe;
    }
    if ((rgshdef[0xe].hul.rghs[2].wFlags & 0xffU) == 6) {
      if ((((rgshdef[0xf].hul.rghs[2].wFlags & 0xffU) == 6) ||
          (sVar11 = FLookupPartX(&part,1,0xf), sVar11 != 1)) ||
         ((rgshdef[0xe].hul.rghs[0].wFlags & 0xffU) == 0xf)) goto LAB_10a0_03c3;
      i = 0xf;
    }
    else {
      i = 0xe;
    }
    if ((*(int *)((int)&rgshdef[0].cExist + i * 0x93) == 0) &&
       (*(int *)((int)&rgshdef[0].cExist + 2 + i * 0x93) == 0)) {
      puVar19 = (undefined2 *)(i * 0x93 + 0x3f00);
      puVar21 = (undefined2 *)&stack0xfeba;
      for (iVar17 = 0x49; iVar17 != 0; iVar17 = iVar17 + -1) {
        puVar6 = puVar21;
        puVar21 = puVar21 + 1;
        puVar4 = puVar19;
        puVar19 = puVar19 + 1;
        *puVar6 = *puVar4;
      }
      *(undefined1 *)puVar21 = *(undefined1 *)puVar19;
      FChangeAiShdef((SHDEF *)&stack0xfeba,i);
    }
    else {
      local_70 = 3;
    }
  }
LAB_10a0_03c3:
  CheckAiShdefStatus(10,0xb,cRecyclePeriod,&iLatestCargo,rgRecycleShdef);
  CheckAiShdefStatus(8,9,cRecyclePeriod,&iLatestBomber,rgRecycleShdef);
  CheckAiShdefStatus(2,4,cRecyclePeriod,&iLatestCruiser,rgRecycleShdef);
  CheckAiShdefStatus(5,ishLastBattle,cRecyclePeriod,&iLatestBattle,rgRecycleShdef);
  if (0x50 < (uint)game.turn) {
    SplitOutShdefs(rgRecycleShdef);
    _memset(rgRecycleSBShdef,0,10);
    rgRecycleSBShdef[0] = 2;
    SplitOutShdefs(rgRecycleSBShdef);
    _memset(rgRecycleSBShdef,0,10);
    rgRecycleSBShdef[1] = 2;
    SplitOutShdefs(rgRecycleSBShdef);
    _memset(rgRecycleSBShdef,0,10);
    l._0_2_ = 0x202;
    SplitOutShdefs(rgRecycleSBShdef);
    _memset(rgRecycleSBShdef,0,10);
    fTonsOfMinerals = 0x202;
    SplitOutShdefs(rgRecycleSBShdef);
  }
  EnsureMacintiShdefs();
  EnsureMacintiStarbaseDesigns(rgRecycleSBShdef);
  vAiMacRecycleSB = rgRecycleSBShdef;
  fShouldColonize = FShouldWeBuildColonizers(&cColFleet);
  if ((rgshdef[1].hul.rghs[0].wFlags & 0xffU) == 0xf) {
    iLatestColony = 1;
  }
  else if ((((uint)rgshdef[7].wFlags >> 9 & 1) == 0) &&
          (rgshdef[7].hul.ihuldef == ihuldefColonyShip)) {
    iLatestColony = 7;
  }
  else {
    iLatestColony = 1;
  }
  if (((iLatestColony == 1) && (fUsingTempColonizer != 0)) &&
     (5 < (uint)(game.turn - rgshdef[1].turn))) {
    local_77 = '\x02';
  }
  lpb = (byte *)CONCAT22(vlpbAiPlanet._2_2_,(byte *)vlpbAiPlanet + 0xe);
  for (i = 0; i < game.cPlanMax; i = i + 1) {
    *lpb = 0;
    lpb = (byte *)CONCAT22(lpb._2_2_,(byte *)lpb + 0x10);
  }
  cFlMiners = 0;
  cFlCargo = 0;
  cFlDestroyers = 0;
  cFlArmadas = 0;
  cFlMineLayers = 0;
  for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
    pFVar16 = ((FLEET **)rglpfl)[ifl];
    iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
    lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
    if ((pFVar16 == (FLEET *)0x0) && (iVar17 == 0)) break;
    if (pFVar16->iPlayer == idPlayer) {
      if ((iLatestMiner != -1) && ((pFVar16->rgcsh[0xe] != 0 || (pFVar16->rgcsh[0xf] != 0)))) {
        cFlMiners = cFlMiners + 1;
      }
      if (pFVar16->rgcsh[0] != 0) {
        cFlMineLayers = cFlMineLayers + 1;
      }
      if ((iLatestDestroyer != -1) && ((pFVar16->rgcsh[0xc] != 0 || (pFVar16->rgcsh[0xd] != 0)))) {
        cFlDestroyers = cFlDestroyers + 1;
      }
      if ((iLatestCargo != -1) &&
         ((((((pFVar16->rgcsh[10] != 0 || (pFVar16->rgcsh[0xb] != 0)) &&
             (cFlCargo = cFlCargo + 1, pFVar16->idPlanet == -1)) &&
            ((1 < pFVar16->cord && (((uint)((PLORD *)pFVar16->lpplord + 7)->wFlags >> 8 & 0xf) == 1)
             ))) && (iVar7 = *(int *)((int)pFVar16->rgwtMin + 0xe), -1 < iVar7)) &&
          ((0 < iVar7 || ((int)pFVar16->rgwtMin[3] != 0)))))) {
        ((byte *)vlpbAiPlanet)[*(int *)&((PLORD *)pFVar16->lpplord)[6].iordMax * 0x10 + 0xe]
             = ((byte *)vlpbAiPlanet)
               [*(int *)&((PLORD *)pFVar16->lpplord)[6].iordMax * 0x10 + 0xe] | 1;
      }
      for (i = 2; i < 10; i = i + 1) {
        if (pFVar16->rgcsh[i] != 0) {
          cFlArmadas = cFlArmadas + 1;
          break;
        }
      }
    }
  }
  cFlMineLayersBase = cFlMineLayers;
  lpb = (byte *)CONCAT22(vlpbAiPlanet._2_2_,(byte *)vlpbAiPlanet + 0xd);
  for (i = 0; i < game.cPlanMax; i = i + 1) {
    *lpb = 0;
    lpb = (byte *)CONCAT22(lpb._2_2_,(byte *)lpb + 0x10);
  }
  for (ipl = 0; ipl < vclpplAi; ipl = ipl + 1) {
                    /* WARNING: Load size is inaccurate */
    pPVar15 = ((PLANET **)vrglpplAi)[ipl];
    iVar17 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
    lppl = (PLANET *)CONCAT22(iVar17,pPVar15);
    if ((pPVar15 == (PLANET *)0x0) && (iVar17 == 0)) break;
    ((byte *)vlpbAiPlanet)[lppl->id * 0x10 + 0xd] = 1;
  }
  if (((uint)game.turn < 0x79) ||
     (sVar11 = FLookupPartX(&part,0x8000,0xd), sVar11 != 1)) {
    cGenesis = 0;
  }
  else {
    cGenesis = *(int *)((int)&rgplr[0].cPlanet + idPlayer * 0xc0) / 0x14;
    if (10 < cGenesis) {
      cGenesis = 10;
    }
  }
  UpdateProgressGauge(-0x39e);
  unique0x1000176d = (PLANET *)CONCAT22(lpPlanets._2_2_,(PLANET *)lpPlanets);
  lpplMac = (PLANET *)lpPlanets + cPlanet;
  local_32 = lpPlanets._2_2_;
  lppl = (PLANET *)CONCAT22(lpPlanets._2_2_,(PLANET *)lpPlanets);
  while ((PLANET *)lppl < lpplMac) {
    uVar22 = (undefined2)((ulong)lppl >> 0x10);
    if ((((PLANET *)lppl)->iPlayer != idPlayer) && (((PLANET *)lppl)->iPlayer != -1)) {
      i = (((PLANET *)lppl)->uGuesses & 0xfffU) / 0xfa + 1;
      if (6 < (uint)i) {
        i = 6;
      }
      if (((uint)((PLANET *)lppl)->wFlags >> 9 & 1) != 0) {
        i = i + 1;
      }
      ((byte *)vlpbAiPlanet)[lppl->id * 0x10 + 10] = (byte)i;
      ((byte *)vlpbAiPlanet)[lppl->id * 0x10 + 9] = 1;
    }
    lppl = (PLANET *)CONCAT22(uVar22,(PLANET *)lppl + 1);
  }
  for (ipl = 0; ipl < vclpplAi; ipl = ipl + 1) {
                    /* WARNING: Load size is inaccurate */
    pPVar15 = ((PLANET **)vrglpplAi)[ipl];
    iVar17 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
    lppl = (PLANET *)CONCAT22(iVar17,pPVar15);
    if ((pPVar15 == (PLANET *)0x0) && (iVar17 == 0)) break;
    if (((((uint)pPVar15->wFlags >> 9 & 1) != 0) &&
        (iVar7 = *(int *)((int)pPVar15->rgwtMin + 0xe), -1 < iVar7)) &&
       ((((0 < iVar7 || (199 < *(uint *)(pPVar15->rgwtMin + 3))) &&
         ((*(uint *)&pPVar15->field11_0x2c & 0xf) != 0)) &&
        (((*(uint *)&pPVar15->field11_0x2c & 0xf) != 1 || ((uint)game.turn < 0x1a)))))) {
      ChangeMainObjSel(1,lppl->id);
      uVar22 = (undefined2)((ulong)lppl >> 0x10);
      pPVar15 = (PLANET *)lppl;
      if (((*(int *)&pPVar15->lpplprod == 0) && (*(int *)((int)&pPVar15->lpplprod + 2) == 0)) ||
         (((PLPROD *)pPVar15->lpplprod)->iprodMac < 0x18)) {
        InitProduction(rgprod);
        fWrite = 0;
        lpprod._2_2_ = lpplProdGlob._2_2_;
        lpprod._0_2_ = (PROD *)(PLPROD *)lpplProdGlob;
        for (i = 0; lpprod._0_2_ = (PROD *)((PLPROD *)(PROD *)lpprod + 1),
            i < (int)(uint)((PLPROD *)lpplProdGlob)->iprodMac; i = i + 1) {
          uVar25 = __aFulshr(uVar27,in_stack_0000feba);
          if (((uint)uVar25 & 7) == 2) {
            uVar25 = __aFulshr(uVar27,in_stack_0000feba);
            if (((uint)uVar25 & 0x7f) < 0x10) break;
          }
        }
        if (i < (int)(uint)((PLPROD *)lpplProdGlob)->iprodMac) {
          FinishProduction(0);
        }
        else {
          cRes = CResourcesAtPlanet(lppl,idPlayer);
          if (0x78 < (uint)game.turn) {
            sVar11 = IWarpMAFromLppl(lppl,&j);
            if (9 < sVar11) {
              uVar22 = (undefined2)((ulong)lppl >> 0x10);
              iVar17 = *(int *)((int)((PLANET *)lppl)->rgwtMin + 0xe);
              if ((-1 < iVar17) &&
                 ((0 < iVar17 || (10000 < *(uint *)(((PLANET *)lppl)->rgwtMin + 3))))) {
                sVar11 = Random(4);
                if (sVar11 == 0) {
                  lpplBest = (PLANET *)0x0;
                  lLeast.wFlags = 0x86a0;
                  lDist._0_2_ = (byte *)0x1;
                  lpprod._2_2_ = lpplProdGlob._2_2_;
                  lpprod._0_2_ = (PROD *)(PLPROD *)lpplProdGlob;
                  for (i = 0; lpprod._0_2_ = (PROD *)((PLPROD *)(PROD *)lpprod + 1),
                      i < (int)(uint)((PLPROD *)lpplProdGlob)->iprodMac; i = i + 1) {
                    uVar25 = __aFulshr(uVar27,in_stack_0000feba);
                    if (((uint)uVar25 & 7) == 1) {
                      uVar25 = __aFulshr(uVar27,in_stack_0000feba);
                      if (0xd < ((uint)uVar25 & 0x7f)) {
                        uVar25 = __aFulshr(uVar27,in_stack_0000feba);
                        if (((uint)uVar25 & 0x7f) < 0x12) goto AI3_LTryCargo;
                      }
                    }
                  }
                  j = Random(3);
                  for (i = j; i < j + 3; i = i + 1) {
                    iVar17 = *(int *)((int)(((PLANET *)lppl)->rgwtMin + i % 3) + 2);
                    if ((-1 < iVar17) &&
                       ((0 < iVar17 ||
                        ((undefined *)&DAT_1120_1388 <
                         *(undefined **)(((PLANET *)lppl)->rgwtMin + i % 3))))) break;
                  }
                  if (i != j + 3) {
                    i = i % 3;
                    for (iplDest = 0; iplDest < vclpplAi; iplDest = iplDest + 1) {
                      lDist._2_2_ = *(undefined2 *)((PLANET **)vrglpplAi + iplDest);
                      IStack_b4.wFlags = *(int *)((int)((PLANET **)vrglpplAi + iplDest) + 2);
                      if (((PLANET *)lDist._2_2_ == (PLANET *)0x0) && (IStack_b4.wFlags == 0))
                      break;
                      uVar13 = *(uint *)((int)(((PLANET *)lDist._2_2_)->rgwtMin + i) + 2);
                      if (((int)uVar13 <= (int)lDist._0_2_) &&
                         (((int)uVar13 < (int)lDist._0_2_ ||
                          (*(uint *)(((PLANET *)lDist._2_2_)->rgwtMin + i) < (uint)lLeast.wFlags))))
                      {
                        sVar11 = IWarpMAFromLppl
                                           ((PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_),&j);
                        if (9 < sVar11) {
                          iVar17 = ((PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_))->id;
                          pt1.y = *(short *)((int)&rgptPlan[0].y + lppl->id * 4);
                          pt1.x = ((POINT *)rgptPlan + lppl->id)->x;
                          pt2.y = *(short *)((int)&rgptPlan[0].y + iVar17 * 4);
                          pt2.x = ((POINT *)rgptPlan + iVar17)->x;
                          uVar25 = LDistance2(pt1,pt2);
                          l = uVar25;
                          if ((long)uVar25 < 0x16444) {
                            lLeast.wFlags = *(short *)((long *)(lDist._2_2_ + 0x1c) + i);
                            lDist._0_2_ = *(undefined2 *)
                                           ((int)((long *)(lDist._2_2_ + 0x1c) + i) + 2);
                            lpplBest = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                          }
                        }
                      }
                    }
                    if (((PLANET *)lpplBest != (PLANET *)0x0) || (lpplBest._2_2_ != 0)) {
                      lVar24 = __aFldiv(CONCAT22(*(undefined2 *)
                                                          ((int)(((PLANET *)lppl)->rgwtMin + i) + 2)
                                                         ,(int)((PLANET *)lppl)->rgwtMin[i]),5);
                      if (CONCAT22(lDist._0_2_,lLeast.wFlags) < lVar24) {
                        lVar24 = __aFldiv(CONCAT22(*(undefined2 *)
                                                            ((int)(((PLANET *)lppl)->rgwtMin + i) +
                                                            2),(int)((PLANET *)lppl)->rgwtMin[i]),5)
                        ;
                        if (20000 < lVar24) {
                          lVar24 = 20000;
                        }
                        l = lVar24;
                        uVar25 = __aFldiv(lVar24,100);
                        l = uVar25;
                        AddItemToQueue(i + 0xe,(ushort)uVar25,grobjPlanet,1);
                        FinishProduction(1);
                        ord._2_2_ = lpplBest->id + 1;
                        sel.pl.wFlags =
                             sel.pl.wFlags & 0xc000U | 0x1c00 | ord._2_2_ & 0x3ff;
                        FLookupPlanet(-1,(PLANET *)&sel.pl);
                        goto LAB_10a0_0964;
                      }
                    }
                  }
                }
              }
            }
          }
AI3_LTryCargo:
          if (((iLatestCargo != -1) && (cFlCargo < 0x40)) &&
             (cFlCargo < *(int *)((int)&rgplr[0].cPlanet + idPlayer * 0xc0) / 4)) {
            sVar11 = Random(3);
            if (sVar11 == 0) {
              cFlCargo = cFlCargo + 1;
              AddItemToQueue(iLatestCargo,1,grobjFleet,1);
              fWrite = 1;
            }
          }
          if ((fShouldColonize == 0) ||
             ((0x28 < cColFleet && ((0x78 < (uint)game.turn || (100 < cColFleet)))))) {
            sVar11 = Random(100);
            if (sVar11 < 8) goto LAB_10a0_0ffc;
AI3_TryShip2:
            if (((iLatestMiner != -1) && (cFlMiners < 0x3c)) &&
               ((*(int *)((int)&rgshdef[0].cExist + 2 + iLatestMiner * 0x93) == 0 &&
                ((undefined *)
                 *(undefined2 *)((int)&rgshdef[0].cExist + iLatestMiner * 0x93) <
                 (undefined *)&DAT_1120_1388)))) {
              sVar11 = Random(2);
              if (sVar11 == 0) {
                lDist._0_2_ = lppl->id;
                lDist._2_2_ = 0;
                IStack_b4.wFlags = 0;
                for (ifl = 0; unique0x10002322 = (PLANET *)0x0, ifl < cFleet;
                    ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
                  pFVar16 = ((FLEET **)rglpfl)[ifl];
                  iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
                  lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
                  if ((pFVar16 == (FLEET *)0x0) && (unique0x1000231e = (PLANET *)0x0, iVar17 == 0))
                  break;
                  if (((byte *)pFVar16->idPlanet == (byte *)lDist._0_2_) &&
                     ((0 < pFVar16->rgcsh[iLatestMiner] && (pFVar16->iPlayer == idPlayer))))
                  {
                    join_0x00000008_0x00000000_ =
                         (PLANET *)CMineFromLpfl((FLEET *)CONCAT22(iVar17,pFVar16));
                    break;
                  }
                }
                if ((long)unique0x10001533 < 0x3e9) {
                  cFr = 0;
                  for (i = 0; i < 3; i = i + 1) {
                    cFr = cFr + (uint)((PLANET *)lppl)->rgMinConc[i];
                  }
                  cFr = cFr * 3;
                  if (((long)unique0x10001533 < (long)cFr) && (0x96 < cFr)) {
LAB_10a0_12f2:
                    cFlMiners = cFlMiners + 1;
                    AddItemToQueue(iLatestMiner,1,grobjFleet,1);
                    fWrite = 1;
                  }
                  else if (cFlMiners < 0x1e) {
                    sVar11 = Random(10);
                    if (sVar11 != 0) goto LAB_10a0_12f2;
                  }
                }
              }
            }
            if ((((rgshdef[0].hul.ihuldef == ihuldefFrigate) && (cFlMineLayers < 0x3c)) &&
                (*(int *)((int)&rgshdef[0].cExist + 2 + iLatestMiner * 0x93) == 0)) &&
               (*(uint *)((int)&rgshdef[0].cExist + iLatestMiner * 0x93) < 0x1d4c)) {
              sVar11 = Random(4);
              if (sVar11 == 0) {
                IStack_b4.wFlags = lppl->id;
                cFr = 0;
                for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
                  pFVar16 = ((FLEET **)rglpfl)[ifl];
                  iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
                  lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
                  if ((pFVar16 == (FLEET *)0x0) && (iVar17 == 0)) break;
                  if ((pFVar16->idPlanet == IStack_b4.wFlags) &&
                     ((0 < pFVar16->rgcsh[0] && (pFVar16->iPlayer == idPlayer)))) {
                    cFr = pFVar16->rgcsh[0];
                    break;
                  }
                }
                if (cFr < 10) {
LAB_10a0_1419:
                  sVar11 = Random(cFr * 2 + 1);
                  if (sVar11 == 0) {
                    cFlMineLayers = cFlMineLayers + 3;
                    AddItemToQueue(0,4,grobjFleet,1);
                    fWrite = 1;
                  }
                }
                else if (cFr < 0x11) {
                  sVar11 = Random(10);
                  if (sVar11 == 0) goto LAB_10a0_1419;
                }
              }
            }
            for (i = 0; i < 3; i = i + 1) {
              iVar17 = *(int *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
              if ((iVar17 < 1) &&
                 ((iVar17 < 0 ||
                  (*(undefined **)(((PLANET *)lppl)->rgwtMin + i) < (undefined *)&DAT_1120_1388))))
              break;
            }
            fTonsOfMinerals = (short)(i == 2);
            pPVar26 = unique0x10001562;
            if (((iLatestBomber != -1) && (cFlArmadas < 0x8c)) &&
               ((cFlArmadas < 0x3c || (2000 < cRes)))) {
              IStack_b4.wFlags = lppl->id;
              if (0x6e < cFlArmadas) {
                sVar11 = Random(3);
                if (sVar11 == 0) {
AI3_LAddBombers:
                  cFlArmadas = cFlArmadas + 2;
                  if (fTonsOfMinerals == 0) {
                    uVar12 = 4;
                  }
                  else {
                    uVar12 = 0xc;
                  }
                  AddItemToQueue(iLatestBomber,uVar12,grobjFleet,1);
                  fWrite = 1;
                  pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                  goto AI3_FinishProd_3;
                }
              }
              ifl = 0;
              while( true ) {
                pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                if (cFleet <= ifl) break;
                    /* WARNING: Load size is inaccurate */
                pFVar16 = ((FLEET **)rglpfl)[ifl];
                iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
                lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
                if ((pFVar16 == (FLEET *)0x0) &&
                   (pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_), iVar17 == 0)) break;
                if ((pFVar16->idPlanet == IStack_b4.wFlags) && (pFVar16->iPlayer == idPlayer)
                   ) {
                  sVar11 = FPotentMacWarFleet((FLEET *)CONCAT22(iVar17,pFVar16),(short *)0x0);
                  if (sVar11 != 0) {
                    if ((iLatestBomber != -1) &&
                       (uVar22 = (undefined2)((ulong)lpfl >> 0x10),
                       lDist._2_2_ = ((FLEET *)lpfl)->rgcsh[8] + ((FLEET *)lpfl)->rgcsh[9],
                       (int)lDist._2_2_ < (int)(uint)vrgAiArmadaPotency[2]))
                    goto AI3_LAddBombers;
                    pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                    break;
                  }
                }
                ifl = ifl + 1;
              }
            }
            if (0 < cGenesis) {
              uVar22 = (undefined2)((ulong)lppl >> 0x10);
              iVar17 = *(int *)((int)((PLANET *)lppl)->rgwtMin + 0xe);
              if ((-1 < iVar17) &&
                 ((0 < iVar17 || (10000 < *(uint *)(((PLANET *)lppl)->rgwtMin + 3))))) {
                lpprod._2_2_ = lpplProdGlob._2_2_;
                lpprod._0_2_ = (PROD *)(PLPROD *)lpplProdGlob;
                for (i = 0; lpprod._0_2_ = (PROD *)((PLPROD *)(PROD *)lpprod + 1),
                    i < (int)(uint)((PLPROD *)lpplProdGlob)->iprodMac; i = i + 1) {
                  unique0x10002376 = pPVar26;
                  uVar25 = __aFulshr(uVar27,in_stack_0000feba);
                  pPVar26 = stack0xff4a;
                  if (((uint)uVar25 & 7) == 1) {
                    uVar25 = __aFulshr(uVar27,in_stack_0000feba);
                    pPVar26 = stack0xff4a;
                    if (((uint)uVar25 & 0x7f) == 0xd) break;
                  }
                }
                lDist._2_2_ = SUB42(pPVar26,0);
                if ((int)(uint)((PLPROD *)lpplProdGlob)->iprodMac <= i) {
                  i = 0;
                  while( true ) {
                    if (2 < i) break;
                    uVar13 = *(uint *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
                    if (((int)uVar13 < 1) &&
                       (((int)uVar13 < 0 || (*(uint *)(((PLANET *)lppl)->rgwtMin + i) < 2000))))
                    break;
                    i = i + 1;
                  }
                  if (i != 2) {
                    IStack_b4.wFlags = 0;
                    for (i = 0; i < 3; i = i + 1) {
                      IStack_b4.wFlags = IStack_b4.wFlags + (uint)((PLANET *)lppl)->rgMinConc[i];
                    }
                    if (IStack_b4.wFlags < 0xf) {
LAB_10a0_1794:
                      cGenesis = cGenesis + -1;
                      AddItemToQueue(0xd,1,grobjPlanet,1);
                      AddItemToQueue(0xc,0x4b,grobjPlanet,1);
                      pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                      fWrite = 1;
                    }
                    else {
                      if (IStack_b4.wFlags < 0x1e) {
                        sVar11 = Random(3);
                        if (sVar11 != 0) goto LAB_10a0_1794;
                      }
                      pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                      if (IStack_b4.wFlags < 0x3c) {
                        sVar11 = Random(5);
                        pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
                        if (sVar11 != 0) goto LAB_10a0_1794;
                      }
                    }
                  }
                }
              }
            }
            if ((((iLatestCruiser != -1) && (cFlArmadas < 0x82)) && (0x14 < (uint)game.turn))
               && ((cFlArmadas < 0x32 || (2000 < cRes)))) {
              if (fTonsOfMinerals == 0) {
                unique0x1000237e = pPVar26;
                sVar11 = Random(3);
                pPVar26 = stack0xff4a;
                if (sVar11 != 0) goto AI3_TryShip3;
              }
              lDist._2_2_ = SUB42(pPVar26,0);
              if (iLatestBattle == -1) {
LAB_10a0_1846:
                IStack_b4.wFlags = iLatestCruiser;
              }
              else {
                unique0x10002386 = pPVar26;
                sVar11 = Random(3);
                if (sVar11 != 0) goto LAB_10a0_1846;
                IStack_b4.wFlags = iLatestBattle;
              }
              cFlArmadas = cFlArmadas + 1;
              if (fTonsOfMinerals == 0) {
                uVar12 = 2;
              }
              else {
                uVar12 = 10;
              }
              AddItemToQueue(IStack_b4.wFlags,uVar12,grobjFleet,1);
              pPVar26 = (PLANET *)CONCAT22(IStack_b4.wFlags,lDist._2_2_);
              fWrite = 1;
              if (fTonsOfMinerals != 0) goto AI3_FinishProd_3;
            }
AI3_TryShip3:
            if (iLatestDestroyer != -1) {
              if ((uint)game.turn < 0x78) {
                iVar17 = 0x50;
              }
              else {
                iVar17 = 0x3c;
              }
              if ((cFlDestroyers < iVar17) && (cshDestroyer < 2000)) {
                unique0x10002346 = pPVar26;
                GetResourcesAvailable(lppl,(long *)rgResAvail);
                GetProdQCost(lppl,(long *)rgResCost);
                for (i = 0; i < 4; i = i + 1) {
                  uVar8 = rgResCost[i * 2];
                  uVar9 = rgResCost[i * 2 + 1];
                  puVar1 = rgResAvail + i * 2;
                  uVar13 = *puVar1;
                  *puVar1 = *puVar1 - uVar8;
                  rgResAvail[i * 2 + 1] = (rgResAvail[i * 2 + 1] - uVar9) - (uint)(uVar13 < uVar8);
                  if (((int)rgResAvail[i * 2 + 1] < 1) &&
                     (pPVar26 = stack0xff4a, (int)rgResAvail[i * 2 + 1] < 0)) goto AI3_FinishProd_3;
                }
                GetTrueHullCost
                          (idPlayer,(HUL *)(HUL *)(iLatestDestroyer * 0x93 + 0x3f00),rgCosts)
                ;
                for (i = 0; i < 0x14; i = i + 1) {
                  for (j = 0; sVar11 = j, j < 4; j = j + 1) {
                    uVar8 = rgCosts[j];
                    puVar1 = rgResAvail + j * 2;
                    uVar13 = *puVar1;
                    *puVar1 = *puVar1 - uVar8;
                    rgResAvail[sVar11 * 2 + 1] = rgResAvail[sVar11 * 2 + 1] - (uint)(uVar13 < uVar8)
                    ;
                    if (((int)rgResAvail[j * 2 + 1] < 1) && ((int)rgResAvail[j * 2 + 1] < 0)) break;
                  }
                  if (j < 4) break;
                }
                pPVar26 = stack0xff4a;
                if (0 < i) {
                  fWrite = 1;
                  AddItemToQueue(iLatestDestroyer,i,grobjFleet,1);
                  cFlDestroyers = cFlDestroyers + 1;
                  pPVar26 = stack0xff4a;
                }
              }
            }
          }
          else {
LAB_10a0_0ffc:
            if ((0x31 < cColFleet) && (0x78 < (uint)game.turn)) goto AI3_TryShip2;
            i = 0;
            while( true ) {
              if (2 < i) break;
              uVar13 = *(uint *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
              if (((int)uVar13 < 1) &&
                 ((pPVar26 = unique0x10001903, (int)uVar13 < 0 ||
                  (*(uint *)(((PLANET *)lppl)->rgwtMin + i) < 0x1e)))) goto AI3_FinishProd_3;
              i = i + 1;
            }
            sVar11 = FShouldPlanetBuildColonizer(lppl);
            if (sVar11 == 0) goto AI3_TryShip2;
            cColFleet = cColFleet + 1;
            AddItemToQueue(iLatestColony,1,grobjFleet,1);
            fWrite = 1;
            pPVar26 = stack0xff4a;
            if (4 < (uint)game.turn) {
              sVar11 = PctTrueMaxGrowth(idPlayer);
              uVar22 = (undefined2)((ulong)lppl >> 0x10);
              uVar25 = __aFulmul(CONCAT22(*(undefined2 *)
                                                   ((int)((PLANET *)lppl)->rgwtMin + 0xe),
                                                  (int)((PLANET *)lppl)->rgwtMin[3]),(long)sVar11);
              l = uVar25;
              if (((0x8fc < (long)uVar25) && (0x23 < cRes)) && (0 < iAiLvl)) {
                cColFleet = cColFleet + 1;
                AddItemToQueue(iLatestColony,1,grobjFleet,1);
                if (((0xe10 < (long)l) && (0x32 < cRes)) && (1 < iAiLvl)) {
                  AddItemToQueue(iLatestColony,1,grobjFleet,1);
                }
              }
              goto AI3_TryShip2;
            }
          }
AI3_FinishProd_3:
          unique0x1000236a = pPVar26;
          FinishProduction(fWrite);
        }
      }
    }
LAB_10a0_0964:
  }
  UpdateProgressGauge(-0x39e);
  lpflAttack = (FLEET *)0x0;
  local_90 = 0;
  lpflEnemy = (FLEET *)0x0;
  local_1e = 0;
  for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
    pFVar16 = ((FLEET **)rglpfl)[ifl];
    iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
    lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
    if ((pFVar16 == (FLEET *)0x0) && (iVar17 == 0)) break;
    if ((1 < pFVar16->cord) && (((uint)((PLORD *)pFVar16->lpplord + 7)->wFlags >> 8 & 0xf) == 8)) {
      lLeast.wFlags = (&pFVar16->pt)->x - *(int *)&((PLORD *)pFVar16->lpplord)[5].iordMax;
      IStack_b4.wFlags = (pFVar16->pt).y - ((PLORD *)pFVar16->lpplord + 6)->wFlags;
      lpplBest = (PLANET *)__aFulmul((long)IStack_b4.wFlags,(long)IStack_b4.wFlags);
      uVar27 = __aFulmul((long)lLeast.wFlags,(long)lLeast.wFlags);
      lDist = (undefined1  [4])(lpplBest->rgpctMinLevel + (uVar27 - 6));
      if (40000 < (long)lDist) {
        ChangeMainObjSel(2,lpfl->id);
        sel.fl.cord = 1;
        ((PLORD *)sel.fl.lpplord)->iordMac = 1;
        FLookupFleet(-1,(FLEET *)&sel.fl);
      }
    }
    uVar22 = (undefined2)((ulong)lpfl >> 0x10);
    pFVar16 = (FLEET *)lpfl;
    if (pFVar16->iPlayer == idPlayer) {
      if ((pFVar16->rgcsh[0] < 1) || ((uint)game.turn < 0x29)) {
        if (((pFVar16->rgcsh[0xe] < 1) && (pFVar16->rgcsh[0xf] < 1)) || (pFVar16->cord != 1)) {
          sVar11 = FIsAiAttack(lpfl);
          if (sVar11 == 0) {
            sVar11 = FIsAiTransport(lpfl);
            if (sVar11 != 0) {
              idPlanDst = -1;
              uVar22 = (undefined2)((ulong)lpfl >> 0x10);
              pFVar16 = (FLEET *)lpfl;
              if ((pFVar16->cord < 2) ||
                 ((*(uint *)&((PLORD *)pFVar16->lpplord)[2].iordMax & 0xf) != 0)) {
                idPlanDst = pFVar16->idPlanet;
              }
              else if (((uint)((PLORD *)pFVar16->lpplord + 7)->wFlags >> 8 & 0xf) == 1) {
                idPlanDst = *(short *)&((PLORD *)pFVar16->lpplord)[6].iordMax;
              }
              if (idPlanDst != -1) {
                lppl = LpplFromId(idPlanDst);
                iVar17 = (int)((ulong)lppl >> 0x10);
                if ((((PLANET *)lppl == (PLANET *)0x0) && (iVar17 == 0)) ||
                   (((PLANET *)lppl)->iPlayer != idPlayer)) {
                  uVar22 = (undefined2)((ulong)lpfl >> 0x10);
                  if (((int)((FLEET *)lpfl)->rgwtMin[3] == 0) &&
                     (*(int *)((int)((FLEET *)lpfl)->rgwtMin + 0xe) == 0)) {
                    ChangeMainObjSel(2,lpfl->id);
                    sel.fl.cord = 1;
                    ((PLORD *)sel.fl.lpplord)->iordMac = 1;
                    FLookupFleet(-1,(FLEET *)&sel.fl);
                    ClearAiCurrentTask(lpfl,0);
                  }
                }
              }
            }
          }
          else {
            *(FLEET **)&((FLEET *)lpfl)->lpflNext = lpflAttack;
            *(undefined2 *)((int)&((FLEET *)lpfl)->lpflNext + 2) = local_90;
            lpflAttack = (FLEET *)lpfl;
            local_90 = lpfl._2_2_;
            for (j = 2; (j <= ishLastBattle && (((FLEET *)lpfl)->rgcsh[j] < 1)); j = j + 1) {
            }
            if ((j <= ishLastBattle) &&
               (((1 < ((FLEET *)lpfl)->cord &&
                 (((uint)((PLORD *)((FLEET *)lpfl)->lpplord + 7)->wFlags >> 8 & 0xf) == 1)) ||
                (((FLEET *)lpfl)->idPlanet != -1)))) {
              if ((((FLEET *)lpfl)->cord < 2) ||
                 (((uint)((PLORD *)((FLEET *)lpfl)->lpplord + 7)->wFlags >> 8 & 0xf) != 1)) {
                IStack_b4.wFlags = ((FLEET *)lpfl)->idPlanet;
              }
              else {
                IStack_b4.wFlags = *(short *)&((PLORD *)((FLEET *)lpfl)->lpplord)[6].iordMax;
              }
              pbVar14 = (byte *)vlpbAiPlanet + IStack_b4.wFlags * 0x10 + 10;
              pbVar2 = (byte *)CONCAT22(vlpbAiPlanet._2_2_,pbVar14);
              lDist = (undefined1  [4])CONCAT22(vlpbAiPlanet._2_2_,pbVar14);
              if (*(byte *)CONCAT22(vlpbAiPlanet._2_2_,pbVar14) != 0) {
                *(byte *)CONCAT22(vlpbAiPlanet._2_2_,pbVar14) =
                     *(byte *)CONCAT22(vlpbAiPlanet._2_2_,pbVar14) | 0x80;
                lDist = (undefined1  [4])pbVar2;
              }
            }
          }
        }
        else {
          if ((*(uint *)&((PLORD *)pFVar16->lpplord)[2].iordMax & 0xf) != 3) {
            ChangeMainObjSel(2,lpfl->id);
            uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
            *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
                 *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 3;
            FLookupFleet(-1,(FLEET *)&sel.fl);
            goto LAB_10a0_1a3b;
          }
          if (cFlMiners < 0x3b) {
            if (0x30 < cFlMiners) {
              sVar11 = Random(3);
              if (sVar11 != 0) goto LAB_10a0_1e15;
            }
          }
          else {
LAB_10a0_1e15:
            sVar11 = FFindBuddyAndJoinUp(lpfl,0xe,0xf,0x48,0x6c);
            if (sVar11 != 0) goto LAB_10a0_1a3b;
          }
          uVar22 = (undefined2)((ulong)lpfl >> 0x10);
          if (((FLEET *)lpfl)->idPlanet != -1) {
            lppl = LpplFromId(((FLEET *)lpfl)->idPlanet);
            uVar22 = (undefined2)((ulong)lppl >> 0x10);
            if ((lppl != (PLANET *)0x0) && (((PLANET *)lppl)->iPlayer == idPlayer)) {
              j = 0;
              for (i = 0; i < 3; i = i + 1) {
                j = j + (uint)((PLANET *)lppl)->rgMinConc[i];
              }
              if (j < 0x1e) {
LAB_10a0_1ee2:
                FRetargetMiner(lpfl);
                goto LAB_10a0_1a3b;
              }
              if (j < 0x3c) {
                sVar11 = Random(3);
                if (sVar11 == 0) goto LAB_10a0_1ee2;
              }
            }
          }
          sVar11 = Random(10);
          if (sVar11 == 0) {
            FRetargetMiner(lpfl);
          }
        }
LAB_10a0_2154:
        pFVar16 = (FLEET *)lpfl;
        uVar22 = (undefined2)((ulong)lpfl >> 0x10);
        if (((uint)game.turn < 0xb) && ((0 < pFVar16->rgcsh[0] || (pFVar16->rgcsh[2] != 0))))
        {
AI3_LRecycle:
          ChangeMainObjSel(2,lpfl->id);
          uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
          *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
               *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 5;
          FLookupFleet(-1,(FLEET *)&sel.fl);
        }
        else if (pFVar16->cord < 2) {
          if ((pFVar16->rgcsh[1] != 0) || ((fUsingTempColonizer != 0 && (pFVar16->rgcsh[7] != 0))))
          {
            if ((fUsingTempColonizer != 0) && ((iLatestColony == 1 && (pFVar16->idPlanet != -1))))
            goto AI3_LRecycle;
            if ((iAiLvl < 2) || (pFVar16->idPlanet == -1)) {
LAB_10a0_2388:
              idPlanDst = IdNearestColonizablePlanet(lpfl,(THING **)&lpthWorm);
              if (((idPlanDst == -1) && ((THING *)lpthWorm == (THING *)0x0)) &&
                 (lpthWorm._2_2_ == 0)) {
                if (((FLEET *)lpfl)->idPlanet != -1) {
                  ChangeMainObjSel(2,lpfl->id);
                  uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
                  *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
                       *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 5;
                  FLookupFleet(-1,(FLEET *)&sel.fl);
                }
              }
              else {
                ChangeMainObjSel(2,lpfl->id);
                uVar22 = (undefined2)((ulong)lpfl >> 0x10);
                if (((FLEET *)lpfl)->idPlanet != -1) {
                  lppl = LpplFromId(((FLEET *)lpfl)->idPlanet);
                  iVar17 = (int)((ulong)lppl >> 0x10);
                  pPVar15 = (PLANET *)lppl;
                  if ((pPVar15 == (PLANET *)0x0) && (iVar17 == 0)) {
                    uVar27 = 0;
                  }
                  else {
                    uVar27 = __aFldiv(CONCAT22(*(undefined2 *)((int)pPVar15->rgwtMin + 0xe),
                                                       (int)pPVar15->rgwtMin[3]),10);
                    if (0x19 < (long)uVar27) {
                      uVar27 = 0x19;
                    }
                  }
                  l._0_2_ = (uint)uVar27;
                  XferAiSupply(1,((FLEET *)lpfl)->idPlanet,2,lpfl->id,3,(uint)l);
                  l = uVar27;
                  FLookupFleet(lpfl->id,(FLEET *)&sel.fl);
                }
                if (idPlanDst == -1) {
                  FGotoWormholeAiFleet
                            (lpfl,(THING *)CONCAT22(lpthWorm._2_2_,(THING *)lpthWorm));
                }
                else {
                  FColonizeAiFleet(lpfl,idPlanDst);
                }
              }
            }
            else {
              pPVar26 = LpplFromId(pFVar16->idPlanet);
              IStack_b4.wFlags = (short)((ulong)pPVar26 >> 0x10);
              lDist._2_2_ = SUB42(pPVar26,0);
              if ((((((PLANET *)lDist._2_2_ == (PLANET *)0x0) && (IStack_b4.wFlags == 0)) ||
                   (((PLANET *)lDist._2_2_)->iPlayer == -1)) ||
                  ((((PLANET *)lDist._2_2_)->iPlayer == idPlayer ||
                   (((uint)((PLANET *)lDist._2_2_)->wFlags >> 9 & 1) != 0)))) ||
                 (0x31 < (((PLANET *)lDist._2_2_)->uGuesses & 0xfffU))) {
                if ((((PLANET *)lDist._2_2_ == (PLANET *)0x0) && (IStack_b4.wFlags == 0)) ||
                   (((PLANET *)lDist._2_2_)->iPlayer != -1)) goto LAB_10a0_2388;
                uVar22 = (undefined2)((ulong)lpfl >> 0x10);
                if (((int)((FLEET *)lpfl)->rgwtMin[3] == 0) &&
                   (*(int *)((int)((FLEET *)lpfl)->rgwtMin + 0xe) == 0)) {
                  FMoveToNearestStarbase(lpfl,1);
                }
                else {
                  ChangeMainObjSel(2,lpfl->id);
                  uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
                  *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
                       *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 2;
                  FLookupFleet(-1,(FLEET *)&sel.fl);
                }
              }
            }
          }
        }
        else if (((fUsingTempColonizer != 0) && (local_77 != '\0')) && (pFVar16->rgcsh[7] != 0)) {
          ChangeMainObjSel(2,lpfl->id);
          sel.fl.cord = 1;
          ((PLORD *)sel.fl.lpplord)->iordMac = 1;
          FLookupFleet(-1,(FLEET *)&sel.fl);
          FMoveToNearestStarbase(lpfl,0);
        }
      }
      else if (pFVar16->cord < 2) {
        if (cFlMineLayersBase < 0x38) {
          if (0x28 < cFlMineLayersBase) {
            sVar11 = Random(3);
            if (sVar11 != 0) goto LAB_10a0_1c04;
          }
        }
        else {
LAB_10a0_1c04:
          sVar11 = FFindBuddyAndJoinUp(lpfl,0,0,0x48,0x6c);
          if (sVar11 != 0) goto LAB_10a0_1a3b;
        }
        if (6 < ((FLEET *)lpfl)->rgcsh[0]) {
          sVar11 = Random(5);
          if (sVar11 == 0) {
            uVar22 = (undefined2)((ulong)lpfl >> 0x10);
            pt.y = (((FLEET *)lpfl)->pt).y;
            pt.x = (&((FLEET *)lpfl)->pt)->x;
            idPlanDst = IdRandomPlanetNearby(pt,0x69,1);
            if ((idPlanDst != -1) && (idPlanDst != ((FLEET *)lpfl)->idPlanet)) {
              ClearAiCurrentTask(lpfl,1);
              iplDest = idPlanDst;
              ord._0_2_ = ((POINT *)rgptPlan + idPlanDst)->x;
              ord._2_2_ = *(uint *)((int)&rgptPlan[0].y + idPlanDst * 4);
              lpplBest = (PLANET *)((ulong)lpplBest & 0xffffe000 | 0x1146);
              FMoveAiFleet(lpfl,(ORDER *)ord,0);
              goto LAB_10a0_2154;
            }
          }
        }
        pPVar10 = ((FLEET *)lpfl)->lpplord;
        if ((*(uint *)&((PLORD *)pPVar10)[2].iordMax & 0xf) == 6) goto LAB_10a0_2154;
        ChangeMainObjSel(2,lpfl->id);
        uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
        *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
             *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 6;
        ((PLORD *)sel.fl.lpplord + 3)->wFlags = 5;
        pbVar2 = &((PLORD *)sel.fl.lpplord)[3].iordMax;
        pbVar2[0] = 5;
        pbVar2[1] = 0;
        FLookupFleet(-1,(FLEET *)&sel.fl);
      }
      else if ((*(uint *)&((PLORD *)pFVar16->lpplord)[2].iordMax & 0xf) != 0) {
        ClearAiCurrentTask(lpfl,1);
      }
    }
    else {
      *(FLEET **)&pFVar16->lpflNext = lpflEnemy;
      *(undefined2 *)((int)&pFVar16->lpflNext + 2) = local_1e;
      lpflEnemy = pFVar16;
      local_1e = uVar22;
    }
LAB_10a0_1a3b:
  }
  for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
    pFVar16 = ((FLEET **)rglpfl)[ifl];
    iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
    lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
    if ((pFVar16 == (FLEET *)0x0) && (iVar17 == 0)) break;
    if ((pFVar16->iPlayer == idPlayer) && (pFVar16->cord < 2)) {
      sVar11 = FIsAiTransport((FLEET *)CONCAT22(iVar17,pFVar16));
      if (sVar11 != 0) {
        if (((FLEET *)lpfl)->iplan != 4) {
          ChangeMainObjSel(2,lpfl->id);
          sel.fl.iplan = 4;
          FLookupFleet(-1,(FLEET *)&sel.fl);
        }
        IdTargetMacFreighter(lpfl);
      }
    }
  }
  UpdateProgressGauge(-0x39e);
  for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
    pFVar16 = ((FLEET **)rglpfl)[ifl];
    iVar17 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
    lpfl = (FLEET *)CONCAT22(iVar17,pFVar16);
    if ((pFVar16 == (FLEET *)0x0) && (iVar17 == 0)) break;
    if (pFVar16->iPlayer == idPlayer) {
      for (i = 0; (i < 0x10 && ((pFVar16->rgcsh[i] < 1 || (rgRecycleShdef[i] != 0)))); i = i + 1) {
      }
      if (i != 0x10) goto LAB_10a0_2787;
      if (pFVar16->idPlanet != -1) {
        lppl = LpplFromId(pFVar16->idPlanet);
        uVar22 = (undefined2)((ulong)lppl >> 0x10);
        if ((lppl != (PLANET *)0x0) && (((PLANET *)lppl)->iPlayer == idPlayer)) {
          if (((uint)((PLANET *)lppl)->wFlags >> 9 & 1) == 0) {
            sVar11 = Random(5);
            if (sVar11 != 0) goto LAB_10a0_2735;
          }
          ChangeMainObjSel(2,lpfl->id);
          uVar22 = (undefined2)((ulong)sel.fl.lpplord >> 0x10);
          *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax =
               *(uint *)&((PLORD *)sel.fl.lpplord)[2].iordMax & 0xfff0 | 5;
          FLookupFleet(-1,(FLEET *)&sel.fl);
          goto LAB_10a0_25e7;
        }
      }
LAB_10a0_2735:
      uVar22 = (undefined2)((ulong)lpfl >> 0x10);
      pFVar16 = (FLEET *)lpfl;
      if (((pFVar16->cord < 2) || (pFVar16->idPlanet != -1)) ||
         (((uint)((PLORD *)pFVar16->lpplord + 7)->wFlags >> 8 & 0xf) != 1)) {
        sVar11 = FMoveToNearestStarbase(lpfl,0);
        if (sVar11 == 0) {
LAB_10a0_2787:
          i = 2;
LAB_10a0_28ad:
          if (i < 10) {
            if ((((FLEET *)lpfl)->rgcsh[i] < 1) || ((i == 7 && (fUsingTempColonizer != 0))))
            goto LAB_10a0_28a9;
            if (cFlArmadas < 0x65) {
              if (cFlArmadas < 0x5b) goto LAB_10a0_2898;
              sVar11 = Random(3);
              if (sVar11 != 0) goto LAB_10a0_2898;
            }
            l._0_2_ = 0;
            l._2_2_ = 0;
            for (j = 2; j < 10; j = j + 1) {
              uVar13 = ((FLEET *)lpfl)->rgcsh[j];
              bVar23 = CARRY2((uint)l,uVar13);
              l._0_2_ = (uint)l + uVar13;
              l._2_2_ = l._2_2_ + ((int)uVar13 >> 0xf) + (uint)bVar23;
            }
            uVar13 = Random(100);
            iVar17 = l._2_2_ + -1 + (uint)(9 < (uint)l);
            if ((iVar17 < (int)uVar13 >> 0xf) ||
               ((iVar17 <= (int)uVar13 >> 0xf && ((uint)l - 10 < uVar13)))) {
LAB_10a0_2867:
              sVar11 = FFindBuddyAndJoinUp(lpfl,2,9,100,200);
              if (sVar11 == 0) goto LAB_10a0_2898;
            }
            else {
              sVar11 = Random(0x14);
              if (sVar11 == 0) goto LAB_10a0_2867;
LAB_10a0_2898:
              TargetMacArmada(lpfl);
            }
          }
          if (9 < i) {
            sVar11 = FIsAiAttack(lpfl);
            if (sVar11 != 0) {
              uVar22 = (undefined2)((ulong)lpfl >> 0x10);
              if ((((FLEET *)lpfl)->cord < 2) ||
                 (pPVar10 = ((FLEET *)lpfl)->lpplord,
                 ((uint)((PLORD *)pPVar10 + 7)->wFlags >> 8 & 0xf) != 2)) {
                if ((uint)game.turn < 0x79) {
                  iVar17 = 0x46;
                }
                else {
                  iVar17 = 0x32;
                }
                if (iVar17 < cFlDestroyers) {
LAB_10a0_2950:
                  if (0x13 < ((FLEET *)lpfl)->rgcsh[iLatestDestroyer]) {
                    sVar11 = Random(0x14);
                    if (sVar11 != 0) goto LAB_10a0_29b2;
                  }
                  sVar11 = FFindBuddyAndJoinUp(lpfl,0xc,0xd,0x24,0x48);
                  if (sVar11 != 0) goto LAB_10a0_25e7;
                }
                else {
                  if ((uint)game.turn < 0x79) {
                    iVar17 = 0x3c;
                  }
                  else {
                    iVar17 = 0x28;
                  }
                  if (iVar17 < cFlDestroyers) {
                    sVar11 = Random(3);
                    if (sVar11 == 0) goto LAB_10a0_2950;
                  }
                }
LAB_10a0_29b2:
                IdTargetAttack(lpfl,(FLEET *)CONCAT22(local_90,lpflAttack),
                                    (FLEET *)CONCAT22(local_1e,lpflEnemy),
                                    (uint)game.wCrap >> 4 & 1);
              }
            }
          }
        }
      }
    }
LAB_10a0_25e7:
  }
  HandleBasicAiTasks(iroCur,rgprod,0,(long *)rgResAvail,(long *)rgResCost);
  FillProductionQueue();
  return;
LAB_10a0_28a9:
  i = i + 1;
  goto LAB_10a0_28ad;
}



// ======================================================================
// Function: EnsureMacintiShdefs
// Address: 10a0:2b3c
// Segment: MEMORY_AI3
// ======================================================================


void EnsureMacintiShdefs(void)

{
  SHDEF *pSVar1;
  HullDef *pHVar2;
  short sVar3;
  int iVar4;
  SHDEF *pSVar5;
  HullDef *pHVar6;
  undefined2 unaff_SS;
  undefined1 shdef [146];
  short fAdvanced;
  PART part;
  short i;
  short ish;
  
  for (ish = 0xe; ish < 0x10; ish = ish + 1) {
    if (((*(uint *)((int)&rgshdef[0].wFlags + ish * 0x93) >> 9 & 1) != 0) &&
       ((((fAdvanced = (short)(1 < (*(uint *)((int)&rgplr[0].wMdPlr +
                                             idPlayer * 0xc0) >> 10 & 7)), fAdvanced == 0 ||
          (ish != 0xf)) ||
         ('\x0e' < *(char *)((int)rgplr[0].rgTech + 3 + idPlayer * 0xc0))) &&
        ((sVar3 = FCreateAiShdef(ish,0x18 - (uint)(fAdvanced == 0),
                                      (byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                              ((ushort *)vrgMacIshAip)
                                                              [fAdvanced + 0x15])), sVar3 == 0 &&
         (ish == 0xe)))))) {
      if (fAdvanced == 0) {
        FCreateAiShdef(0xe,0x15,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x17])
                           );
      }
      else {
        FCreateAiShdef(0xe,0x16,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x16])
                           );
      }
    }
  }
  if (((((uint)rgshdef[0xc].wFlags >> 9 & 1) != 0) &&
      ('\x04' < *(char *)((int)rgplr[0].rgTech + 1 + idPlayer * 0xc0))) &&
     (('\x05' < *(char *)((int)rgplr[0].rgTech + 2 + idPlayer * 0xc0) &&
      (sVar3 = FCreateAiShdef(0xc,0x1d,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                    vrgMacIshAip[0x1e])), sVar3 == 0
      )))) {
    for (i = 0; i < 5; i = i + 1) {
      sVar3 = Random(4);
      sVar3 = FCreateAiShdef(0xc,6,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                ((ushort *)vrgMacIshAip)[sVar3]));
      if (sVar3 != 0) break;
    }
  }
  if ((((((uint)rgshdef[0xd].wFlags >> 9 & 1) != 0) &&
       ('\t' < *(char *)((int)rgplr[0].rgTech + 1 + idPlayer * 0xc0))) &&
      ('\b' < *(char *)((int)rgplr[0].rgTech + 2 + idPlayer * 0xc0))) &&
     (sVar3 = FCreateAiShdef(0xd,0x1d,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                   vrgMacIshAip[0x1e])), sVar3 == 0)
     ) {
    for (i = 0; i < 5; i = i + 1) {
      sVar3 = Random(4);
      sVar3 = FCreateAiShdef(0xd,6,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                ((ushort *)vrgMacIshAip)[sVar3 + 4])
                                 );
      if (sVar3 != 0) break;
    }
  }
  if ((((uint)rgshdef[10].wFlags >> 9 & 1) != 0) &&
     (sVar3 = FCreateAiShdef(10,2,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                               vrgMacIshAip[0x18])), sVar3 == 0)) {
    FCreateAiShdef(10,1,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x18]));
  }
  if (((uint)rgshdef[0xb].wFlags >> 9 & 1) != 0) {
    FCreateAiShdef(0xb,2,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x18]));
  }
  if ((((uint)game.turn < 0x14) && (((uint)rgshdef[2].wFlags >> 9 & 1) == 0)) &&
     (((int)rgshdef[2].cExist == 0 && (rgshdef[2].cExist._2_2_ == 0)))) {
    pSVar5 = (SHDEF *)(rgshdef + 2);
    pHVar6 = (HullDef *)shdef;
    for (iVar4 = 0x49; iVar4 != 0; iVar4 = iVar4 + -1) {
      pHVar2 = pHVar6;
      pHVar6 = pHVar6 + 1;
      pSVar1 = pSVar5;
      pSVar5 = (SHDEF *)(pSVar5->hul).rgTech;
      *pHVar2 = (pSVar1->hul).ihuldef;
    }
    *(char *)pHVar6 = (char)(pSVar5->hul).ihuldef;
    shdef._123_2_ = shdef._123_2_ & 0xfdff | 0x200;
    FChangeAiShdef((SHDEF *)shdef,2);
  }
  for (ish = 2; ish < 5; ish = ish + 1) {
    if (((*(uint *)((int)&rgshdef[0].wFlags + ish * 0x93) >> 9 & 1) != 0) &&
       ((ish == 2 ||
        (0x14 < (uint)(game.turn -
                      *(int *)((int)&rgshdef[0].turn + (ish + -1) * 0x93)))))) {
      for (i = 0; i < 5; i = i + 1) {
        sVar3 = Random(4);
        sVar3 = FCreateAiShdef(ish,7,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                  ((ushort *)vrgMacIshAip)
                                                                  [sVar3 + 0x19]));
        if (sVar3 != 0) break;
      }
    }
  }
  if (((uint)game.turn < 0x28) && (((uint)rgshdef[7].wFlags >> 9 & 1) != 0)) {
    FCreateAiShdef(7,0xf,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x14]));
  }
  sVar3 = FLookupPartX(&part,1,0xf);
  if ((((sVar3 == 1) && (((uint)rgshdef[1].wFlags >> 9 & 1) == 0)) &&
      ((int)rgshdef[1].cExist == 0)) &&
     ((rgshdef[1].cExist._2_2_ == 0 &&
      ((rgshdef[1].hul.rghs[0].wFlags & 0xffU) != 0xf)))) {
    pSVar5 = (SHDEF *)(rgshdef + 1);
    pHVar6 = (HullDef *)shdef;
    for (iVar4 = 0x49; iVar4 != 0; iVar4 = iVar4 + -1) {
      pHVar2 = pHVar6;
      pHVar6 = pHVar6 + 1;
      pSVar1 = pSVar5;
      pSVar5 = (SHDEF *)(pSVar5->hul).rgTech;
      *pHVar2 = (pSVar1->hul).ihuldef;
    }
    *(char *)pHVar6 = (char)(pSVar5->hul).ihuldef;
    shdef._123_2_ = shdef._123_2_ & 0xfdff | 0x200;
    FChangeAiShdef((SHDEF *)shdef,1);
    FCreateAiShdef(1,0xf,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[0x14]));
  }
  ish = 5;
  do {
    if (7 < ish) {
      for (ish = 8; ish < 10; ish = ish + 1) {
        if (((((*(uint *)((int)&rgshdef[0].wFlags + ish * 0x93) >> 9 & 1) != 0) &&
             ('\r' < *(char *)((int)rgplr[0].rgTech + 1 + idPlayer * 0xc0))) &&
            ((ish == 8 ||
             (((*(uint *)((int)&rgshdef[0].wFlags + (ish + -1) * 0x93) >> 9 & 1) == 0 &&
              (0xf < (uint)(game.turn -
                           *(int *)((int)&rgshdef[0].turn + (ish + -1) * 0x93)))))))) &&
           (sVar3 = FCreateAiShdef(ish,9,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                      vrgMacIshAip[0x13])),
           sVar3 == 0)) {
          if (ish == 8) {
            iVar4 = 8;
          }
          else {
            iVar4 = 9;
          }
          FCreateAiShdef(ish,0x13,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                               ((ushort *)vrgMacIshAip)[iVar4]));
        }
      }
      if (((((rgshdef[0].hul.ihuldef != ihuldefFrigate) &&
            (1 < (*(uint *)((int)&rgplr[0].wMdPlr + idPlayer * 0xc0) >> 10 & 7)))
           && ((int)rgshdef[0].cExist == 0)) &&
          ((rgshdef[0].cExist._2_2_ == 0 &&
           ('\x03' < *(char *)((int)rgplr[0].rgTech + 5 + idPlayer * 0xc0))))) &&
         ((('\x04' < *(char *)((int)rgplr[0].rgTech + 4 + idPlayer * 0xc0) &&
           (('\x05' < *(char *)((int)rgplr[0].rgTech + 3 + idPlayer * 0xc0) &&
            ('\x05' < *(char *)((int)rgplr[0].rgTech + 2 + idPlayer * 0xc0))))) &&
          ('\x05' < *(char *)((int)rgplr[0].rgTech + idPlayer * 0xc0))))) {
        pSVar5 = (SHDEF *)rgshdef;
        pHVar6 = (HullDef *)shdef;
        for (iVar4 = 0x49; iVar4 != 0; iVar4 = iVar4 + -1) {
          pHVar2 = pHVar6;
          pHVar6 = pHVar6 + 1;
          pSVar1 = pSVar5;
          pSVar5 = (SHDEF *)(pSVar5->hul).rgTech;
          *pHVar2 = (pSVar1->hul).ihuldef;
        }
        *(char *)pHVar6 = (char)(pSVar5->hul).ihuldef;
        shdef._123_2_ = shdef._123_2_ & 0xfdff | 0x200;
        FChangeAiShdef((SHDEF *)shdef,0);
        FCreateAiShdef(0,5,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip + vrgMacIshAip[10]));
      }
      return;
    }
    if (((*(uint *)((int)&rgshdef[0].wFlags + ish * 0x93) >> 9 & 1) != 0) &&
       ((ish == 5 ||
        (((*(uint *)((int)&rgshdef[0].wFlags + (ish + -1) * 0x93) >> 9 & 1) == 0 &&
         (0x14 < (uint)(game.turn -
                       *(int *)((int)&rgshdef[0].turn + (ish + -1) * 0x93)))))))) {
      if (ish == 5) {
        fAdvanced = 0xb;
      }
      else {
        fAdvanced = 0xf;
      }
      if (ish == 7) {
        sVar3 = Random(2);
        if (sVar3 == 0) {
          fAdvanced = 0xf;
        }
        else {
          fAdvanced = 0xb;
        }
      }
      sVar3 = Random(3);
      if ((sVar3 == 0) ||
         (sVar3 = FCreateAiShdef(ish,0x1d,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                       vrgMacIshAip[0x1d])),
         sVar3 == 0)) {
        for (i = 0; i < 5; i = i + 1) {
          sVar3 = Random(4);
          sVar3 = FCreateAiShdef(ish,9,(byte *)CONCAT22(0x10a0,(byte *)vrgMacAip +
                                                                    ((ushort *)vrgMacIshAip)
                                                                    [sVar3 + fAdvanced]));
          if (sVar3 != 0) break;
        }
      }
    }
    ish = ish + 1;
  } while( true );
}



// ======================================================================
// Function: FRetargetMiner
// Address: 10a0:336c
// Segment: MEMORY_AI3
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10a03402) */

short FRetargetMiner(FLEET *lpfl)

{
  PLANET *pPVar1;
  int iVar2;
  uint uVar3;
  short sVar4;
  long lVar5;
  POINT pt1;
  POINT pt2;
  PLANET *lpplBest;
  short ipl;
  short cConcCur;
  PLANET *lppl;
  short cConcBest;
  ORDER ord;
  short cConc;
  
  lpplBest = (PLANET *)0x0;
  cConcCur = 0;
  cConcBest = 0;
  ipl = 0;
  while( true ) {
    if (vclpplAi <= ipl) break;
                    /* WARNING: Load size is inaccurate */
    pPVar1 = ((PLANET **)vrglpplAi)[ipl];
    iVar2 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
    lppl = (PLANET *)CONCAT22(iVar2,pPVar1);
    if ((pPVar1 == (PLANET *)0x0) && (iVar2 == 0)) break;
    pt2.y = *(short *)((int)&rgptPlan[0].y + lppl->id * 4);
    pt2.x = ((POINT *)rgptPlan + lppl->id)->x;
    pt1.y = (((FLEET *)lpfl)->pt).y;
    pt1.x = (&((FLEET *)lpfl)->pt)->x;
    lVar5 = LDistance2(pt1,pt2);
    if (lVar5 < 0x1440) {
      cConc = (uint)pPVar1->rgMinConc[0] * 8 + (uint)pPVar1->rgMinConc[1] * 10 +
              (uint)pPVar1->rgMinConc[2] * 7;
      uVar3 = cConc;
      if (lppl->id != ((FLEET *)lpfl)->idPlanet) {
        uVar3 = cConcCur;
      }
      cConcCur = uVar3;
      if ((uint)cConcBest < (uint)cConc) {
        lpplBest = (PLANET *)CONCAT22(iVar2,pPVar1);
        cConcBest = cConc;
      }
    }
    ipl = ipl + 1;
  }
  if ((((PLANET *)lpplBest == (PLANET *)0x0) && (lpplBest._2_2_ == 0)) ||
     (cConcBest <= (cConcCur * 6) / 5)) {
    sVar4 = 0;
  }
  else {
    ord.id = lpplBest->id;
    ord.pt.x = ((POINT *)rgptPlan + lpplBest->id)->x;
    ord.pt.y = *(short *)((int)&rgptPlan[0].y + lpplBest->id * 4);
    ord.wFlags = ord.wFlags & 0xe000U | 0x1160;
    sVar4 = FMoveAiFleet(lpfl,&ord,0);
  }
  return sVar4;
}



// ======================================================================
// Function: IdTargetMacFreighter
// Address: 10a0:3524
// Segment: MEMORY_AI3
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10a03c5f) */
/* WARNING: Removing unreachable block (ram,0x10a03dac) */
/* WARNING: Removing unreachable block (ram,0x10a03d80) */
/* WARNING: Removing unreachable block (ram,0x10a037e9) */
/* WARNING: Removing unreachable block (ram,0x10a037a9) */
/* WARNING: Removing unreachable block (ram,0x10a0365d) */
/* WARNING: Removing unreachable block (ram,0x10a0363b) */
/* WARNING: Removing unreachable block (ram,0x10a0378e) */
/* WARNING: Removing unreachable block (ram,0x10a037c9) */
/* WARNING: Removing unreachable block (ram,0x10a03b31) */
/* WARNING: Removing unreachable block (ram,0x10a03dea) */
/* WARNING: Removing unreachable block (ram,0x10a03dcb) */
/* WARNING: Removing unreachable block (ram,0x10a03c81) */
/* WARNING: Type propagation algorithm not settling */

short IdTargetMacFreighter(FLEET *lpfl)

{
  uint *puVar1;
  int *piVar2;
  int iVar3;
  PLANET *pPVar4;
  int iVar5;
  uint uVar6;
  PLANET *pPVar7;
  POINT pt1;
  POINT pt1_00;
  POINT pt1_01;
  POINT pt2;
  POINT pt2_00;
  POINT pt2_01;
  short sVar8;
  short sVar9;
  int iVar10;
  FLEET *pFVar11;
  undefined2 uVar12;
  ulong uVar13;
  long lVar14;
  undefined2 uVar15;
  undefined2 uVar16;
  short iM;
  PLANET *lpplBest;
  short ipl;
  short i;
  short pctKilled;
  PLANET *lppl;
  short cResLost;
  short pctCapHere;
  short pctCapMost;
  PLANET *lpplHere;
  ORDER ord;
  short cResGain;
  undefined4 cColHaul;
  short cResGainMost;
  undefined4 cColLeft;
  undefined4 cMax;
  
  uVar12 = (undefined2)((ulong)lpfl >> 0x10);
  pFVar11 = (FLEET *)lpfl;
  if (pFVar11->idPlanet == -1) {
    lpplHere = (PLANET *)0x0;
  }
  else {
    lpplHere = LpplFromId(pFVar11->idPlanet);
    iVar10 = (int)((ulong)lpplHere >> 0x10);
    pPVar7 = (PLANET *)lpplHere;
    if (((pPVar7 != (PLANET *)0x0) || (iVar10 != 0)) && (pPVar7->iPlayer == idPlayer)) {
      sVar8 = PctPlanetCapacity(lpplHere);
      if ((0x19 < sVar8) &&
         ((iVar3 = *(int *)((int)pPVar7->rgwtMin + 0xe), 0 < iVar3 ||
          ((-1 < iVar3 && (999 < *(uint *)(pPVar7->rgwtMin + 3))))))) {
        cColHaul = LGetFleetStat(lpfl,2);
        for (i = 0; i < 3; i = i + 1) {
          cColHaul = cColHaul -
                     CONCAT22(*(undefined2 *)((int)(pFVar11->rgwtMin + i) + 2),
                              (int)pFVar11->rgwtMin[i]);
        }
        cMax = __aFldiv(CONCAT22(*(undefined2 *)((int)pPVar7->rgwtMin + 0xe),
                                         (int)pPVar7->rgwtMin[3]),0x14);
        if ((long)cMax < (long)cColHaul) {
          cColHaul = cMax;
        }
        if (0 < (long)cColHaul) {
          sVar8 = CResourcesAtPlanet(lpplHere,idPlayer);
          puVar1 = (uint *)(pPVar7->rgwtMin + 3);
          uVar6 = *puVar1;
          *puVar1 = *puVar1 - (uint)cColHaul;
          piVar2 = (int *)((int)pPVar7->rgwtMin + 0xe);
          *piVar2 = (*piVar2 - cColHaul._2_2_) - (uint)(uVar6 < (uint)cColHaul);
          sVar9 = CResourcesAtPlanet(lpplHere,idPlayer);
          iVar3 = sVar8 - sVar9;
          puVar1 = (uint *)(pPVar7->rgwtMin + 3);
          uVar6 = *puVar1;
          *puVar1 = *puVar1 + (uint)cColHaul;
          piVar2 = (int *)((int)pPVar7->rgwtMin + 0xe);
          *piVar2 = *piVar2 + cColHaul._2_2_ + (uint)CARRY2(uVar6,(uint)cColHaul);
          lpplBest = (PLANET *)0x0;
          cResGainMost = 0;
          for (ipl = 0; ipl < vclpplAi; ipl = ipl + 1) {
                    /* WARNING: Load size is inaccurate */
            pPVar4 = ((PLANET **)vrglpplAi)[ipl];
            iVar5 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
            lppl = (PLANET *)CONCAT22(iVar5,pPVar4);
            if ((pPVar4 == (PLANET *)0x0) && (iVar5 == 0)) break;
            if (((pPVar4 != pPVar7) || (iVar5 != iVar10)) &&
               ((((byte *)vlpbAiPlanet)[lppl->id * 0x10 + 0xe] & 1) == 0)) {
              pt1.y = (pFVar11->pt).y;
              pt1.x = (&pFVar11->pt)->x;
              pt2.y = *(short *)((int)&rgptPlan[0].y + lppl->id * 4);
              pt2.x = ((POINT *)rgptPlan + lppl->id)->x;
              lVar14 = LDistance2(pt1,pt2);
              if (lVar14 < 0x9c41) {
                if (lVar14 < 0x57e5) {
                  if (lVar14 < 0x2711) {
                    if (lVar14 < 0x9c5) {
                      pctKilled = 3;
                    }
                    else {
                      pctKilled = 6;
                    }
                  }
                  else {
                    pctKilled = 9;
                  }
                }
                else {
                  pctKilled = 0xc;
                }
                uVar16 = 0;
                uVar15 = 100;
                uVar13 = __aFulmul(cColHaul,(long)pctKilled);
                lVar14 = __aFldiv(uVar13,CONCAT22(uVar16,uVar15));
                cColLeft = cColHaul - lVar14;
                puVar1 = (uint *)(pPVar4->rgwtMin + 3);
                uVar6 = *puVar1;
                *puVar1 = *puVar1 + (uint)cColLeft;
                piVar2 = (int *)((int)pPVar4->rgwtMin + 0xe);
                *piVar2 = *piVar2 + (int)((ulong)cColLeft >> 0x10) +
                          (uint)CARRY2(uVar6,(uint)cColLeft);
                cResGain = CResourcesAtPlanet
                                     ((PLANET *)CONCAT22(iVar5,pPVar4),idPlayer);
                puVar1 = (uint *)(pPVar4->rgwtMin + 3);
                uVar6 = *puVar1;
                *puVar1 = *puVar1 - (uint)cColLeft;
                piVar2 = (int *)((int)pPVar4->rgwtMin + 0xe);
                *piVar2 = (*piVar2 - cColLeft._2_2_) - (uint)(uVar6 < (uint)cColLeft);
                sVar8 = CResourcesAtPlanet((PLANET *)CONCAT22(iVar5,pPVar4),idPlayer)
                ;
                cResGain = cResGain - sVar8;
                if (cResGainMost < cResGain) {
                  lpplBest = (PLANET *)CONCAT22(iVar5,pPVar4);
                  cResGainMost = cResGain;
                }
              }
            }
          }
          if ((((((PLANET *)lpplBest != (PLANET *)0x0) || (lpplBest._2_2_ != 0)) &&
               (iVar3 + 5 <= cResGainMost)) &&
              ((iVar3 + 10 <= cResGainMost || ((uint)game.turn < 0x51)))) &&
             ((iVar3 + 0xf <= cResGainMost || ((uint)game.turn < 0xa1)))) {
            ChangeMainObjSel(2,lpfl->id);
            XferAiSupply(1,pFVar11->idPlanet,2,lpfl->id,3,(uint)cColHaul);
            FLookupFleet(lpfl->id,(FLEET *)&sel.fl);
            ((byte *)vlpbAiPlanet)[lpplBest->id * 0x10 + 0xe] =
                 ((byte *)vlpbAiPlanet)[lpplBest->id * 0x10 + 0xe] | 1;
            goto AI3_LMoveToLpplBest;
          }
        }
      }
    }
  }
  if (((PLANET *)lpplHere != (PLANET *)0x0) || (lpplHere._2_2_ != 0)) {
    for (iM = 0; iM < 3; iM = iM + 1) {
      uVar6 = *(uint *)((int)(((PLANET *)lpplHere)->rgwtMin + iM) + 2);
      if ((-1 < (int)uVar6) &&
         ((0 < (int)uVar6 || (0x9c3 < *(uint *)(((PLANET *)lpplHere)->rgwtMin + iM))))) break;
    }
    if (iM < 3) {
      lpplBest = (PLANET *)0x0;
      cMax._0_2_ = 1000;
      cMax._2_2_ = 0;
      ipl = 0;
      while( true ) {
        if (vclpplAi <= ipl) break;
                    /* WARNING: Load size is inaccurate */
        pPVar7 = ((PLANET **)vrglpplAi)[ipl];
        iVar10 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
        lppl = (PLANET *)CONCAT22(iVar10,pPVar7);
        if ((pPVar7 == (PLANET *)0x0) && (iVar10 == 0)) break;
        if ((pPVar7 != (PLANET *)lpplHere) || (iVar10 != lpplHere._2_2_)) {
          pt1_00.y = (pFVar11->pt).y;
          pt1_00.x = (&pFVar11->pt)->x;
          pt2_00.y = *(short *)((int)&rgptPlan[0].y + lppl->id * 4);
          pt2_00.x = ((POINT *)rgptPlan + lppl->id)->x;
          lVar14 = LDistance2(pt1_00,pt2_00);
          if (lVar14 < 0x9c41) {
            uVar6 = *(uint *)((int)(pPVar7->rgwtMin + iM) + 2);
            if (((int)uVar6 <= cMax._2_2_) &&
               (((int)uVar6 < cMax._2_2_ || (*(uint *)(pPVar7->rgwtMin + iM) < (uint)cMax)))) {
              cMax._0_2_ = *(uint *)(pPVar7->rgwtMin + iM);
              cMax._2_2_ = *(int *)((int)(pPVar7->rgwtMin + iM) + 2);
              lpplBest = (PLANET *)CONCAT22(iVar10,pPVar7);
            }
          }
        }
        ipl = ipl + 1;
      }
      if ((((PLANET *)lpplBest != (PLANET *)0x0) ||
          (cMax = CONCAT22(cMax._2_2_,(uint)cMax), lpplBest._2_2_ != 0)) &&
         ((cMax = CONCAT22(cMax._2_2_,(uint)cMax), cMax._2_2_ < 1 &&
          ((cMax._2_2_ < 0 || (cMax = CONCAT22(cMax._2_2_,(uint)cMax), (uint)cMax < 200)))))) {
        uVar13 = LGetFleetStat(lpfl,2);
        for (i = 0; i < 3; i = i + 1) {
          uVar13 = uVar13 - CONCAT22(*(undefined2 *)((int)(pFVar11->rgwtMin + i) + 2),
                                     (int)pFVar11->rgwtMin[i]);
        }
        cColHaul = uVar13;
        cMax = __aFldiv(CONCAT22(*(undefined2 *)
                                          ((int)(((PLANET *)lpplHere)->rgwtMin + iM) + 2),
                                         (int)((PLANET *)lpplHere)->rgwtMin[iM]),5);
        if ((long)cMax < (long)cColHaul) {
          cColHaul = cMax;
        }
        if (0 < (long)cColHaul) {
          ChangeMainObjSel(2,lpfl->id);
        }
        XferAiSupply(1,pFVar11->idPlanet,2,lpfl->id,iM,(uint)cColHaul);
        FLookupFleet(lpfl->id,(FLEET *)&sel.fl);
        goto AI3_LMoveToLpplBest;
      }
    }
  }
  lpplBest = (PLANET *)0x0;
  pctCapMost = 0;
  for (ipl = 0; ipl < vclpplAi; ipl = ipl + 1) {
                    /* WARNING: Load size is inaccurate */
    pPVar7 = ((PLANET **)vrglpplAi)[ipl];
    iVar10 = *(int *)((int)((PLANET **)vrglpplAi + ipl) + 2);
    lppl = (PLANET *)CONCAT22(iVar10,pPVar7);
    if ((pPVar7 == (PLANET *)0x0) && (iVar10 == 0)) break;
    if ((pPVar7 != (PLANET *)lpplHere) || (iVar10 != lpplHere._2_2_)) {
      pt1_01.y = (pFVar11->pt).y;
      pt1_01.x = (&pFVar11->pt)->x;
      pt2_01.y = *(short *)((int)&rgptPlan[0].y + lppl->id * 4);
      pt2_01.x = ((POINT *)rgptPlan + lppl->id)->x;
      lVar14 = LDistance2(pt1_01,pt2_01);
      if (lVar14 < 0x9c41) {
        pctCapHere = PctPlanetCapacity((PLANET *)CONCAT22(iVar10,pPVar7));
        if (lVar14 < 0x57e5) {
          if (lVar14 < 0x2711) {
            if (0x9c4 < lVar14) {
              pctCapHere = pctCapHere + -2;
            }
          }
          else {
            pctCapHere = pctCapHere + -4;
          }
        }
        else {
          pctCapHere = pctCapHere + -6;
        }
        if (pctCapMost < pctCapHere) {
          lpplBest = (PLANET *)CONCAT22(iVar10,pPVar7);
          pctCapMost = pctCapHere;
        }
      }
    }
  }
  if (((PLANET *)lpplBest == (PLANET *)0x0) && (lpplBest._2_2_ == 0)) {
    return -1;
  }
AI3_LMoveToLpplBest:
  _memset(&ord,0,0x12);
  ord.pt.x = ((POINT *)rgptPlan + lpplBest->id)->x;
  ord.pt.y = *(short *)((int)&rgptPlan[0].y + lpplBest->id * 4);
  ord.id = lpplBest->id;
  ord.wFlags = ord.wFlags & 0xe000U | 0x1141;
  for (i = 0; i < 4; i = i + 1) {
    (ord.txp.rgia + i)->wFlags = (ord.txp.rgia + i)->wFlags & 0xfffU | 0x2000;
  }
  sVar8 = FMoveAiFleet(lpfl,&ord,0);
  if (sVar8 == 0) {
    sVar8 = -1;
  }
  else {
    sVar8 = lpplBest->id;
  }
  return sVar8;
}



// ======================================================================
// Function: TargetMacArmada
// Address: 10a0:3e3a
// Segment: MEMORY_AI3
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10a03e99) */

void TargetMacArmada(FLEET *lpfl)

{
  short *psVar1;
  ORDER *pOVar2;
  undefined2 uVar3;
  POINT pt1;
  POINT pt2;
  PLANET *pPVar4;
  short sVar5;
  int iVar6;
  FLEET *pFVar7;
  short *psVar8;
  ORDER *pOVar9;
  undefined2 uVar10;
  undefined2 unaff_SS;
  long lVar11;
  PLANET *lpplTarget;
  short cshWar;
  PLANET *lppl;
  short cshBomb;
  ORDER ord;
  FLEET *lpflTarget;
  
  uVar10 = (undefined2)((ulong)lpfl >> 0x10);
  pFVar7 = (FLEET *)lpfl;
  if (1 < pFVar7->cord) {
    uVar3 = *(undefined2 *)((int)&pFVar7->lpplord + 2);
    psVar8 = (short *)(*(int *)&pFVar7->lpplord + 0x16);
    pOVar9 = &ord;
    for (iVar6 = 9; iVar6 != 0; iVar6 = iVar6 + -1) {
      pOVar2 = pOVar9;
      pOVar9 = (ORDER *)&(pOVar9->pt).y;
      psVar1 = psVar8;
      psVar8 = psVar8 + 1;
      (pOVar2->pt).x = *psVar1;
    }
    pt1.y = (pFVar7->pt).y;
    pt1.x = (&pFVar7->pt)->x;
    pt2.y = ord.pt.y;
    pt2.x = ord.pt.x;
    lVar11 = LDistance2(pt1,pt2);
    if ((lVar11 < 0xf425) || (((uint)ord.wFlags >> 8 & 0xf) != 2)) {
      if (((uint)ord.wFlags >> 8 & 0xf) == 2) {
        return;
      }
      if (((uint)ord.wFlags >> 8 & 0xf) == 1) {
        lppl = LpplFromId(ord.id);
        iVar6 = (int)((ulong)lppl >> 0x10);
        pPVar4 = (PLANET *)lppl;
        if ((pPVar4 == (PLANET *)0x0) && (iVar6 == 0)) {
          return;
        }
        if (pPVar4->iPlayer != -1) {
          if (pPVar4->iPlayer != idPlayer) {
            return;
          }
          if (((uint)pPVar4->wFlags >> 9 & 1) != 0) {
            return;
          }
        }
        if (pPVar4->turn != game.turn) {
          return;
        }
      }
    }
  }
  FPotentMacWarFleet(lpfl,&cshWar);
  cshBomb = pFVar7->rgcsh[8] + pFVar7->rgcsh[9];
  pFVar7->wFlags = pFVar7->wFlags & 0x7fffU | 0x8000;
  ChangeMainObjSel(2,lpfl->id);
  if (pFVar7->idPlanet == -1) {
    MoveToNearestPlanetOrEnemy(lpfl,0x1c2);
    return;
  }
  lppl = LpplFromId(pFVar7->idPlanet);
  uVar10 = (undefined2)((ulong)lppl >> 0x10);
  if (((PLANET *)lppl)->iPlayer == idPlayer) {
    if ((cshWar < (int)(uint)vrgAiArmadaPotency[0]) ||
       (cshBomb < (int)(uint)vrgAiArmadaPotency[2])) {
      if ((*(uint *)((int)&rgplr[0].wMdPlr + idPlayer * 0xc0) >> 10 & 7) < 2) {
        return;
      }
      if ((cshWar <= (int)((uint)vrgAiArmadaPotency[0] * 2)) && (cshWar < 0x3c)) {
        return;
      }
      sVar5 = Random(10);
      if ((4 < sVar5) &&
         ((cshWar <= (int)((uint)vrgAiArmadaPotency[0] * 3) ||
          (sVar5 = Random(10), 6 < sVar5)))) {
        if (cshWar < 0x79) {
          return;
        }
        sVar5 = Random(10);
        if (6 < sVar5) {
          return;
        }
      }
    }
  }
  else if ((cshWar < (int)(uint)vrgAiArmadaPotency[1]) ||
          (cshBomb < (int)(uint)vrgAiArmadaPotency[3])) {
    ClearAiCurrentTask(lpfl,0);
    if (((*(uint *)((int)&rgplr[0].wMdPlr + idPlayer * 0xc0) >> 10 & 7) < 2) ||
       ((((cshWar <= (int)((uint)vrgAiArmadaPotency[0] * 2) ||
          (sVar5 = Random(10), 4 < sVar5)) &&
         ((cshWar <= (int)((uint)vrgAiArmadaPotency[0] * 4) ||
          (sVar5 = Random(10), 6 < sVar5)))) &&
        ((cshWar < 0x79 || (sVar5 = Random(10), 6 < sVar5)))))) {
      lpplTarget = LpplFindClosestEnum(lppl,FEnumOurStarbase);
      goto AI3_TargetEveryArmada;
    }
  }
  else if (((PLANET *)lppl)->iPlayer != -1) {
    return;
  }
  if (((uint)game.wCrap >> 4 & 1) == 0) {
    lpplTarget = (PLANET *)0x0;
  }
  else {
    lpplTarget = LpplFindBestEnum(lppl,FEnumCalcArmadaHumanDest);
  }
  if (((PLANET *)lpplTarget == (PLANET *)0x0) && (lpplTarget._2_2_ == 0)) {
    lpplTarget = LpplFindBestEnum(lppl,FEnumCalcArmadaDest);
  }
AI3_TargetEveryArmada:
  if (((PLANET *)lpplTarget == (PLANET *)0x0) && (lpplTarget._2_2_ == 0)) {
    lpflTarget = LpflFindClosestEnum(lpfl,FEnumCalcEnemyFleets);
    iVar6 = (int)((ulong)lpflTarget >> 0x10);
    pFVar7 = (FLEET *)lpflTarget;
    if ((pFVar7 == (FLEET *)0x0) && (iVar6 == 0)) {
      return;
    }
    ord.id = lpflTarget->id;
    ord.wFlags = ord.wFlags & 0xf0ffU | 0x200;
    ord.pt.x = (&pFVar7->pt)->x;
    ord.pt.y = (pFVar7->pt).y;
  }
  else {
    ((byte *)vlpbAiPlanet)[lpplTarget->id * 0x10 + 10] =
         ((byte *)vlpbAiPlanet)[lpplTarget->id * 0x10 + 10] | 0x80;
    ord.id = lpplTarget->id;
    ord.wFlags = ord.wFlags & 0xf0ffU | 0x100;
    ord.pt.x = ((POINT *)rgptPlan + lpplTarget->id)->x;
    ord.pt.y = *(short *)((int)&rgptPlan[0].y + lpplTarget->id * 4);
  }
  ord.wFlags = ord.wFlags & 0xef00U | 0x1040;
  FMoveAiFleet(lpfl,&ord,0);
  return;
}



// ======================================================================
// Function: FPotentMacWarFleet
// Address: 10a0:42ec
// Segment: MEMORY_AI3
// ======================================================================


short FPotentMacWarFleet(FLEET *lpfl,short *pcEquiv)

{
  short cEquiv;
  short ish;
  
  cEquiv = 0;
  ish = 2;
  while( true ) {
    if (4 < ish) break;
    cEquiv = cEquiv + ((FLEET *)lpfl)->rgcsh[ish];
    ish = ish + 1;
  }
  for (ish = 5; ish < 8; ish = ish + 1) {
    cEquiv = cEquiv + ((FLEET *)lpfl)->rgcsh[ish] * 2;
  }
  if (cEquiv < (int)(uint)vrgAiArmadaPotency[0]) {
    for (ish = 8; ish < 10; ish = ish + 1) {
      if (((((FLEET *)lpfl)->rgcsh[ish] != 0) &&
          ((*(uint *)((int)&rgshdef[0].wFlags + ish * 0x93) >> 9 & 1) == 0)) &&
         (*(int *)(ish * 0x93 + 0x3f00) == 9)) {
        cEquiv = cEquiv + ((FLEET *)lpfl)->rgcsh[ish] * 2;
      }
    }
    if (cEquiv <= (int)(uint)vrgAiArmadaPotency[0]) {
      return 0;
    }
  }
  if (pcEquiv != (short *)0x0) {
    *pcEquiv = cEquiv;
  }
  return 1;
}



