// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: MineWndProc
// Address: 1028:0000
// Segment: MEMORY_MINE
// ======================================================================


/* WARNING: Variable defined which should be unmapped: rc2 */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

long MineWndProc(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  char *pcVar1;
  BOOL BVar2;
  HCURSOR HVar3;
  HDC hdc_00;
  short fEnabled;
  undefined2 unaff_SI;
  ushort unaff_DI;
  undefined2 unaff_SS;
  COLORREF CVar4;
  COLORREF CVar5;
  DWORD DVar6;
  ulong uVar7;
  LRESULT LVar8;
  char *pcVar9;
  undefined1 *puVar10;
  RECT rc2;
  short cch;
  COLORREF crBack;
  RTLOGTHING rtlt;
  short fDetonate;
  RECT rc;
  PAINTSTRUCT ps;
  HDC hdc;
  
  if (message == WM_CREATE) {
    puVar10 = (undefined1 *)&DAT_1120_1120;
    pcVar9 = _szButton;
    pcVar1 = PszGetCompressedString(idsDetonateMineFieldYear);
    hwndMineCB =
         CreateWindow((LPCSTR)CONCAT22(puVar10,pcVar9),
                      (LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,pcVar1),0x40000003,100,100,0x96,
                      dyArial8,hwnd,0,hInst,(void *)0x0);
    SendMessage(hwndMineCB,0x30,rghfontArial8[1],0);
    SetMineralTitleBar(hwnd);
  }
  else if (message == WM_PAINT) {
    hdc_00 = BeginPaint(hwnd,(undefined2 *)CONCAT22(unaff_SS,&ps));
    GetClientRect(hwnd,(undefined2 *)CONCAT22(unaff_SS,&rc));
    SetRect((undefined2 *)CONCAT22(unaff_SS,&rc2),4,4,rc.right + -4,dyArial8 * 2 + -4);
    _Draw3dFrame();
    CVar4 = SetTextColor(hdc_00,CONCAT22(crButtonText._2_2_,
                                         (undefined2)crButtonText));
    rtlt.fDetonate = (short)CVar4;
    CVar5 = SetBkColor(hdc_00,CONCAT22(crButtonFace._2_2_,
                                       (undefined2)crButtonFace));
    cch = _strlen((char *)szMineralTitle);
    rtlt.idFull = (rc2.right - rc2.left) + -0x18;
    while ((0 < cch &&
           (DVar6 = GetTextExtent(hdc_00,szMineralTitle,cch),
           (uint)rtlt.idFull < (uint)DVar6))) {
      cch = cch + -1;
    }
    rc2.right = rc2.right + -8;
    RcCtrTextOut(hdc_00,&rc2,(char *)szMineralTitle,cch);
    rc2.right = rc2.right + 8;
    SetTextColor(hdc_00,CONCAT22((int)(CVar4 >> 0x10),rtlt.fDetonate));
    SetBkColor(hdc_00,CVar5);
    SetRect((undefined2 *)CONCAT22(unaff_SS,&rc2),(rc2.right - (rc2.bottom - rc2.top)) + 2,
            rc2.top + 3,rc2.right + -4,rc2.bottom + -2);
    fEnabled = FOtherStuffAtScanSel();
    DrawSelectionArrow(hdc_00,&rc2,fEnabled);
    rc.top = rc.top + dyArial8 * 2 + -4;
    DrawMineSurvey(hdc_00,&rc);
    EndPaint(hwnd,(undefined2 *)CONCAT22(unaff_SS,&ps));
  }
  else {
    if (message == WM_ERASEBKGND) {
      GetClientRect(hwnd,(undefined2 *)CONCAT22(unaff_SS,&rc));
      FillRect(wParam,(undefined2 *)CONCAT22(unaff_SS,&rc),hbrButtonFace);
      return 1;
    }
    if (message == WM_CTLCOLOR) {
      SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
      return (ulong)hbrButtonFace;
    }
    if (message == WM_SETCURSOR) {
      GetCursorPos((short *)CONCAT22(unaff_SS,&rtlt.fDetonate));
      ScreenToClient(hwnd,(short *)CONCAT22(unaff_SS,&rtlt.fDetonate));
      GetClientRect(hwnd,(short *)CONCAT22(unaff_SS,&rc2.bottom));
      BVar2 = PtInRect((undefined2 *)CONCAT22(&rc2.bottom,fDetonate),rtlt.fDetonate);
      if (BVar2 != 0) {
        rtlt.idFull = HtMineWindow(hwnd,rtlt.fDetonate,fDetonate);
        if (rtlt.idFull != 0) {
          HVar3 = hcurHand;
          if (rtlt.idFull != 9) {
            HVar3 = hcurArrowHelp;
          }
          setcursor(HVar3);
          return 1;
        }
        rtlt.idFull = 0;
      }
MINE_Default_7:
      LVar8 = DefWindowProc(hwnd,message,wParam,lParam);
      return LVar8;
    }
    if (message == WM_COMMAND) {
      if (((HWND)lParam == hwndMineCB) &&
         (uVar7 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),rc2.left), (int)uVar7 == 0)) {
        LVar8 = SendMessage(hwndMineCB,0x400,0,0);
        rtlt.fDetonate = (short)LVar8;
        rtlt.idFull = ((THING *)lpThings + sel.scan.ith)->idFull;
        WriteMemRt(0x2b,4,&rtlt);
        ((THING *)lpThings)[sel.scan.ith].rgb[7] = (byte)LVar8;
      }
    }
    else {
      if (((message != WM_LBUTTONDOWN) && (message != WM_LBUTTONDBLCLK)) &&
         (message != WM_RBUTTONDOWN)) goto MINE_Default_7;
      if (hwndPopup == 0) {
        uVar7 = __aFulshr(CONCAT22(wParam,message),unaff_DI);
        MineClick((HWND)lParam,(short)uVar7,message,wParam);
      }
    }
  }
  return 0;
}



// ======================================================================
// Function: InvalidateMineralBars
// Address: 1028:040a
// Segment: MEMORY_MINE
// ======================================================================


void InvalidateMineralBars(void)

{
  HDC HVar1;
  HGDIOBJ HVar2;
  char *pcVar3;
  ushort uVar4;
  int iVar5;
  int iVar6;
  uint uVar7;
  undefined2 unaff_SS;
  DWORD DVar8;
  DWORD DVar9;
  undefined1 *puVar10;
  HDC HVar11;
  RECT rc;
  short dxPop;
  short dx;
  RECT rcPop;
  HFONT hfontSav;
  short dyRow;
  HDC hdc;
  
  GetClientRect(hwndMine,(undefined2 *)CONCAT22(unaff_SS,&rc));
  HVar1 = GetDC(hwndMine);
  HVar2 = SelectObject(HVar1,rghfontArial8[0]);
  HVar11 = HVar1;
  pcVar3 = PszGetCompressedString(idsN999mr);
  DVar8 = GetTextExtent(HVar11,(LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,pcVar3),5);
  rc.right = rc.right - ((int)DVar8 + 6);
  SelectObject(HVar1,rghfontArial8[1]);
  HVar11 = HVar1;
  pcVar3 = PszGetCompressedString(idsPopulation1000000);
  DVar8 = GetTextExtent(HVar11,(LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,pcVar3),0x15);
  puVar10 = (undefined1 *)&DAT_1120_1120;
  pcVar3 = DAT_1120_0480;
  HVar11 = HVar1;
  uVar4 = _strlen(DAT_1120_0480);
  DVar9 = GetTextExtent(HVar11,(LPCSTR)CONCAT22(puVar10,pcVar3),uVar4);
  iVar5 = (int)DVar9 + 6;
  iVar6 = iVar5 * 4;
  if (iVar6 - rc.right == 0 || iVar6 < rc.right) {
    rc.left = rc.left + iVar5;
  }
  else {
    DVar9 = GetTextExtent(HVar1,(LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,DAT_1120_0480),4);
    rc.left = rc.left + (int)DVar9 + 6;
  }
  SelectObject(HVar1,HVar2);
  ReleaseDC(hwndMine,HVar1);
  rc.top = rc.top + dyArial8 * 2 + -4;
  rcPop.top = rc.top + 2;
  rcPop.bottom = rcPop.top + dyArial8;
  rcPop.right = rc.right;
  rcPop.left = rc.right - ((int)DVar8 + 6);
  InvalidateRect(hwndMine,(undefined2 *)CONCAT22(unaff_SS,&rcPop),1);
  uVar7 = ((rc.bottom - rc.top) + dyArial8 * -4 + -2) / 6 + 1U & 0xfffe;
  rc.top = rc.top + (dyArial8 * 5 >> 1) + uVar7 * 3 + 1;
  rc.bottom = uVar7 * 3 + rc.top;
  InvalidateRect(hwndMine,(undefined2 *)CONCAT22(unaff_SS,&rc),0);
  return;
}



// ======================================================================
// Function: GetMineFieldCounts
// Address: 1028:05ac
// Segment: MEMORY_MINE
// ======================================================================


void GetMineFieldCounts(ushort id,short *pithm,short *pcthm)

{
  short sVar1;
  THING *lpthMac;
  THING *lpth;
  short ithFound;
  short cthTotal;
  
  ithFound = 0;
  cthTotal = 0;
  lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
  while ((THING *)lpth < (THING *)lpThings + cThing) {
    sVar1 = ithFound;
    if ((((uint)lpth->idFull >> 0xd == 0) && (((uint)lpth->idFull >> 9 & 0xf) == idPlayer))
       && (cthTotal = cthTotal + 1, sVar1 = cthTotal, lpth->idFull != id)) {
      sVar1 = ithFound;
    }
    ithFound = sVar1;
    lpth = (THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1);
  }
  *pithm = ithFound;
  *pcthm = cthTotal;
  return;
}



// ======================================================================
// Function: DrawMineSurvey
// Address: 1028:065a
// Segment: MEMORY_MINE
// ======================================================================


/* WARNING: Variable defined which should be unmapped: cMines */
/* WARNING: Removing unreachable block (ram,0x10281e94) */
/* WARNING: Removing unreachable block (ram,0x10281e54) */
/* WARNING: Removing unreachable block (ram,0x10283270) */
/* WARNING: Removing unreachable block (ram,0x10280be1) */
/* WARNING: Removing unreachable block (ram,0x1028101a) */

void DrawMineSurvey(HDC hdc,RECT *prc)

{
  uint *puVar1;
  int *piVar2;
  PLAYER *pPVar3;
  PLAYER *pPVar4;
  char cVar5;
  FLEET *pFVar6;
  uint uVar7;
  bool bVar8;
  POINT pt;
  undefined4 uVar9;
  undefined4 uVar10;
  undefined4 uVar11;
  undefined4 uVar12;
  HDC HVar13;
  short sVar14;
  short *psVar15;
  short sVar16;
  char *pcVar17;
  ushort uVar18;
  int iVar19;
  int iVar20;
  uint uVar21;
  StringId SVar22;
  uint uVar23;
  int iVar24;
  int iVar25;
  HGDIOBJ HVar26;
  int iVar27;
  int iVar28;
  int iVar29;
  int iVar30;
  undefined2 unaff_SI;
  PLAYER *pPVar31;
  PLAYER *pPVar32;
  undefined2 unaff_DI;
  char *unaff_SS;
  bool bVar33;
  bool bVar34;
  COLORREF CVar35;
  THING *pTVar36;
  DWORD DVar37;
  DWORD DVar38;
  ulong uVar39;
  long lVar40;
  HBITMAP HVar41;
  undefined2 uVar42;
  undefined1 *puVar43;
  HDC HVar44;
  undefined2 uVar45;
  short sVar46;
  long cMines;
  short ifl;
  long rglT [3];
  short iPass;
  short dNum;
  short xBeg;
  short dx;
  short dxLabels;
  short rgMax [3];
  short rgCost [3];
  short iCur;
  short dxRLabels;
  short xR;
  short dxNum;
  short dxBar;
  short c_2;
  short yCur;
  short xEnd;
  short iMin;
  PLAYER plrSav;
  short dy;
  short fShortLabels;
  short yBot;
  undefined2 uStack_de;
  short iMax;
  short dyRow;
  uint uStack_d8;
  short rgMin [3];
  HBITMAP hbmpSav_2;
  RECT rc;
  long l;
  short grobj;
  char szT [80];
  RECT rcGauge;
  short cch;
  char *psz;
  short bkMode;
  HDC hdcMem;
  COLORREF crBack;
  FLEET *lpfl;
  short i;
  short c;
  long rgl [3];
  short c2;
  COLORREF crFore;
  long l2;
  HBRUSH hbrSav;
  PLANET pl;
  
  HVar13 = CreateCompatibleDC(hdc);
  CVar35 = SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
  ;
  crFore = SetTextColor(hdc,0xffff);
  sVar14 = SetBkMode(hdc,2);
  uVar12._2_2_ = (undefined2)rglT[2];
  uVar12._0_2_ = rglT[1]._2_2_;
  uVar11._2_2_ = (undefined2)rglT[2];
  uVar11._0_2_ = rglT[1]._2_2_;
  uVar10._2_2_ = (undefined2)rglT[1];
  uVar10._0_2_ = rglT[0]._2_2_;
  uVar9._2_2_ = (undefined2)rglT[1];
  uVar9._0_2_ = rglT[0]._2_2_;
  grobj = sel.scan.grobj;
  if (sel.scan.grobj == grobjOther) {
    if ((sel.scan.grobjFull & grobjPlanet) == grobjNone) {
      if ((sel.scan.grobjFull & grobjFleet) == grobjNone) {
        if ((sel.scan.grobjFull & grobjThing) == grobjNone) {
          grobj = 0;
        }
        else {
          grobj = 8;
        }
      }
      else {
        grobj = 2;
      }
    }
    else {
      grobj = 1;
    }
  }
  l2 = CONCAT22(l2._2_2_,(undefined2)l2);
  if (grobj == 0) goto MINE_FinishUp_5;
  if (grobj == 2) {
    rgMin._2_4_ = rgMin._2_4_ & 0xffff;
    l2 = CONCAT22(l2._2_2_,(undefined2)l2);
    rglT._2_4_ = uVar10;
    rglT._6_4_ = uVar12;
    if (sel.scan.ifl != -1) {
      rgMin[0] = prc->left + 6;
      rgMin[2] = 0;
      rgMin[1] = prc->top + 6;
      hbrSav = SelectObject(hdc,hbrButtonShadow);
      PatBlt(hdc,rgMin[0],rgMin[1],0x46,2,0xf00021);
      PatBlt(hdc,rgMin[0],rgMin[1] + 2,2,0x44,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x10,rgMin[1] + 0x44,2,0x26,0xf00021);
      hbrSav = SelectObject(hdc,hbrButtonHilite);
      PatBlt(hdc,rgMin[0] + 2,rgMin[1] + 0x44,0xf,1,0xf00021);
      PatBlt(hdc,rgMin[0] + 1,rgMin[1] + 0x45,0xf,1,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x34,rgMin[1] + 0x44,0x12,2,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x44,rgMin[1] + 2,2,0x42,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x45,rgMin[1] + 1,1,1,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x11,rgMin[1] + 0x68,0x25,2,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x10,rgMin[1] + 0x69,1,1,0xf00021);
      PatBlt(hdc,rgMin[0] + 0x34,rgMin[1] + 0x46,2,0x22,0xf00021);
      PatBlt(hdc,rgMin[0] + 2,rgMin[1] + 2,0x42,0x42,0x42);
      PatBlt(hdc,rgMin[0] + 0x12,rgMin[1] + 0x44,0x22,0x24,0x42);
      SelectObject(hdc,hbrSav);
                    /* WARNING: Load size is inaccurate */
      pFVar6 = ((FLEET **)rglpfl)[sel.scan.ifl];
      iVar27 = *(int *)((int)((FLEET **)rglpfl + sel.scan.ifl) + 2);
      lpfl = (FLEET *)CONCAT22(iVar27,pFVar6);
      DrawFleetBitmap
                ((FLEET *)CONCAT22(iVar27,pFVar6),hdc,rgMin[0] + 2,rgMin[1] + 2,0,-1,0,0,-1,0);
      uVar21 = *(uint *)((int)&rgplr[0].wMdPlr + ((uint)lpfl->id >> 9 & 0xf) * 0xc0) >> 3;
      SelectPalette(hdc,vhpal,0);
      RealizePalette(hdc);
      DibBlt(hdc,rgMin[0] + 0x13,rgMin[1] + 0x47,0x20,0x20,hdibRaces,
                      (uVar21 & 7) << 5,(3 - ((int)(uVar21 & 0x1f) >> 3)) * 0x20,0x20,0x20,0xcc0020)
      ;
      SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
      SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
      SelectObject(hdc,rghfontArial8[1]);
      dyRow = 0;
      for (i = 0; i < 0x10; i = i + 1) {
        dyRow = dyRow + pFVar6->rgcsh[i];
      }
      CchGetString(idsShipCountLd,szT);
      c = _WSPRINTF((LPSTR)CONCAT22(dyRow,unaff_SS),(LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),
                    (char *)szWork);
      TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
      iVar19 = rgMin[1] + dyArial8 + 2;
      rgMin[1] = iVar19;
      if (((pFVar6->wFlags & 0xffU) == 7) || ((pFVar6->wFlags & 0xffU) == 4)) {
        lVar40 = WtFromLpfl((FLEET *)CONCAT22(iVar27,pFVar6));
        rgMin[2] = (short)lVar40;
        c = CchGetString(idsFuel2,szT);
        DVar37 = GetTextExtent(hdc,(LPCSTR)CONCAT22(unaff_SS,szT),c);
        c2 = CchGetString(idsCargo,(char *)szWork);
        l2 = GetTextExtent(hdc,szWork,c2);
        if ((long)DVar37 < l2) {
          DVar37 = l2;
        }
        l._0_2_ = (int)DVar37;
        SetRect((undefined2 *)CONCAT22(unaff_SS,&rcGauge),prc->left + 0x5a + (int)l,rgMin[1],
                prc->right + -4,rgMin[1] + dyArial8);
        if (rcGauge.left < rcGauge.right) {
          TextOut(hdc,prc->left + 0x56,rgMin[1],(LPCSTR)CONCAT22(unaff_SS,szT),c);
          rgMin[1] = rgMin[1] + dyArial8 + 2;
          TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c2);
          DrawFleetGauge(hdc,&rcGauge,(FLEET *)CONCAT22(iVar27,pFVar6),4);
          OffsetRc(&rcGauge,0,dyArial8 + 4);
          DrawFleetGauge(hdc,&rcGauge,(FLEET *)CONCAT22(iVar27,pFVar6),5);
          rgMin[1] = rgMin[1] + dyArial8 + 2;
        }
      }
      else {
        rgMin[2] = pFVar6->rgdv->dp;
      }
      if (((uint)gd.wFlags >> 3 & 1) == 0) {
        SVar22 = idsFleetMassLdkt;
      }
      else {
        SVar22 = idsMassLdkt;
      }
      c = CchGetString(SVar22,szT);
      c = _WSPRINTF((LPSTR)CONCAT22(rgMin[2],unaff_SS),(LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),
                    (char *)szWork);
      TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
      rgMin[1] = rgMin[1] + dyArial8 + 2;
      if ((pFVar6->wFlags & 0xffU) == 7) {
        uVar42 = *(undefined2 *)((int)&pFVar6->lpplord + 2);
        psVar15 = (short *)(*(int *)&pFVar6->lpplord + 4);
        if (1 < pFVar6->cord) {
          psVar15 = (short *)(*(int *)&pFVar6->lpplord + 0x16);
        }
        _yBot = (short *)CONCAT22(uVar42,psVar15);
        if (((uint)gd.wFlags >> 3 & 1) == 0) {
          SVar22 = idsWaypointS;
        }
        else {
          SVar22 = idsWpS;
        }
        CchGetString(SVar22,plrSav.szNames + 8);
        if (pFVar6->cord == 1) {
          pcVar17 = PszGetCompressedString(idsNone);
          c = _WSPRINTF((LPSTR)CONCAT22(pcVar17,unaff_SS),
                        (LPCSTR)CONCAT22(plrSav.szNames + 8,unaff_SS),szT);
        }
        else {
          pcVar17 = PszGetLocName((uint)psVar15[3] >> 8 &
                                        (grobjThing|grobjOther|grobjFleet|grobjPlanet),psVar15[2],
                                        *_yBot,psVar15[1]);
          c = _WSPRINTF((LPSTR)CONCAT22(pcVar17,unaff_SS),
                        (LPCSTR)CONCAT22(plrSav.szNames + 8,unaff_SS),szT);
        }
        TextOut(hdc,prc->left + 0x56,rgMin[1],(LPCSTR)CONCAT22(unaff_SS,szT),c);
        if (((uint)gd.wFlags >> 3 & 1) == 0) {
          SVar22 = idsWaypointTaskS;
        }
        else {
          SVar22 = idsTaskS;
        }
        rgMin[1] = rgMin[1] + dyArial8 + 2;
        CchGetString(SVar22,szT);
        pcVar17 = PszGetCompressedString((psVar15[3] & 0xfU) + idsTaskHere);
        c = _WSPRINTF((LPSTR)CONCAT22(pcVar17,unaff_SS),(LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120)
                      ,(char *)szWork);
        TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
        rgMin[1] = rgMin[1] + dyArial8 + 2;
        if (pFVar6->cord < 2) {
          if (((uint)gd.wFlags >> 3 & 1) == 0) {
            SVar22 = idsWarpSpeedStopped;
          }
          else {
            SVar22 = idsWarpStopped;
          }
          c = CchGetString(SVar22,(char *)szWork);
        }
        else if (((uint)psVar15[3] >> 4 & 0xf) == 0xb) {
          c = CchGetString(idsUseStargate,(char *)szWork);
        }
        else {
          if (((uint)gd.wFlags >> 3 & 1) == 0) {
            SVar22 = idsWarpSpeedD;
          }
          else {
            SVar22 = idsWarpD;
          }
          CchGetString(SVar22,szT);
          c = _WSPRINTF((LPSTR)((ulong)CONCAT22((uint)psVar15[3] >> 4,unaff_SS) & 0xfffff),
                        (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
        }
        TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
        rgMin[1] = rgMin[1] + dyArial8 + 2;
        lVar40 = CMineSweepFromLpfl((FLEET *)CONCAT22(iVar27,pFVar6));
        if (0 < lVar40) {
          plrSav.szNames._6_2_ = PszGetCompressedString(idsFleetCanDestroyLdMinesPerYear);
          c = _WSPRINTF((LPSTR)CONCAT22((int)lVar40,(char *)&DAT_1120_1120),
                        (LPCSTR)CONCAT22(plrSav.szNames._6_2_,(char *)&DAT_1120_1120),
                        (char *)szWork);
          TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
          rgMin[1] = rgMin[1] + dyArial8 + 2;
        }
      }
      else if (((uint)pFVar6->wFlags >> 4 & 1) != 0) {
        if ((pFVar6->wFlags & 0xfU) == 0) {
          if (((uint)gd.wFlags >> 3 & 1) == 0) {
            SVar22 = idsWarpSpeedStopped;
          }
          else {
            SVar22 = idsWarpStopped;
          }
          c = CchGetString(SVar22,(char *)szWork);
        }
        else {
          if (((uint)gd.wFlags >> 3 & 1) == 0) {
            SVar22 = idsWarpSpeedD;
          }
          else {
            SVar22 = idsWarpD;
          }
          CchGetString(SVar22,szT);
          c = _WSPRINTF((LPSTR)((ulong)CONCAT22(pFVar6->wFlags,unaff_SS) & 0xfffff),
                        (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
        }
        TextOut(hdc,prc->left + 0x56,rgMin[1],szWork,c);
        rgMin[1] = rgMin[1] + dyArial8 + 2;
      }
    }
    goto MINE_FinishUp_5;
  }
  if (grobj != 8) {
    if (sel.scan.idpl != -1) {
      sVar16 = FLookupPlanet(sel.scan.idpl,&pl);
      if (sVar16 != 0) {
        pPVar31 = (PLAYER *)rgplr + idPlayer;
        pPVar32 = &plrSav;
        for (iVar27 = 0x60; iVar27 != 0; iVar27 = iVar27 + -1) {
          pPVar4 = pPVar32;
          pPVar32 = (PLAYER *)&pPVar32->cPlanet;
          pPVar3 = pPVar31;
          pPVar31 = (PLAYER *)&pPVar31->cPlanet;
          cVar5 = pPVar3->cShDef;
          pPVar4->iPlayer = pPVar3->iPlayer;
          pPVar4->cShDef = cVar5;
        }
        rc.left = prc->left;
        rc.top = prc->top;
        rc.right = prc->right;
        rc.bottom = prc->bottom;
        sVar16 = GetRaceStat((PLAYER *)rgplr + idPlayer,rsMajorAdv);
        if (((sVar16 == 3) && (pl.iPlayer != -1)) &&
           ((idPlayer == pl.iPlayer ||
            (*(char *)(idPlayer * 0xc0 + 0x5a12 + pl.iPlayer) == '\x01')))) {
          for (c_2 = 0; c_2 < 3; c_2 = c_2 + 1) {
            *(undefined1 *)(idPlayer * 0xc0 + 0x59b2 + c_2) =
                 *(undefined1 *)(pl.iPlayer * 0xc0 + 0x59b2 + c_2);
            *(undefined1 *)(idPlayer * 0xc0 + 0x59b5 + c_2) =
                 *(undefined1 *)(pl.iPlayer * 0xc0 + 0x59b5 + c_2);
            *(undefined1 *)(idPlayer * 0xc0 + 0x59b8 + c_2) =
                 *(undefined1 *)(pl.iPlayer * 0xc0 + 0x59b8 + c_2);
          }
        }
        SelectObject(hdc,rghfontArial8[0]);
        HVar44 = hdc;
        pcVar17 = PszGetCompressedString(idsN999mr);
        DVar37 = GetTextExtent(HVar44,(LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,pcVar17),5);
        SelectObject(hdc,rghfontArial8[1]);
        puVar43 = (undefined1 *)&DAT_1120_1120;
        pcVar17 = DAT_1120_0480;
        HVar44 = hdc;
        uVar18 = _strlen(DAT_1120_0480);
        DVar38 = GetTextExtent(HVar44,(LPCSTR)CONCAT22(puVar43,pcVar17),uVar18);
        dxLabels = (int)DVar38 + 6;
        bVar34 = dxLabels * 4 - rc.right != 0;
        bVar33 = rc.right <= dxLabels * 4;
        bVar8 = bVar34 && bVar33;
        if (bVar8) {
          DVar38 = GetTextExtent(hdc,(LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,DAT_1120_0480),4)
          ;
          dxLabels = (int)DVar38 + 6;
        }
        sVar16 = rc.top;
        iVar19 = rc.left + dxLabels;
        iVar20 = rc.right - ((int)DVar37 + 6);
        uVar21 = ((rc.bottom - rc.top) + dyArial8 * -4 + -2) / 6 + 1U & 0xfffe;
        iVar27 = rc.top + 2;
        if (((uint)pl.wFlags >> 9 & 1) != 0) {
          rglT[2]._2_2_ = CreateCompatibleDC(hdc);
          HVar26 = SelectObject(rglT[2]._2_2_,hbmpMono);
          rglT._2_4_ = SetTextColor(hdc,0);
          rglT._6_4_ = SetBkColor(hdc,0xffffff);
          BitBlt(hdc,rc.right + -0x16,sVar16 + 4,0xd,0x10,rglT[2]._2_2_,0,0xc,0x8800c6);
          SetTextColor(hdc,0xffff);
          SetBkColor(hdc,0);
          BitBlt(hdc,rc.right + -0x16,sVar16 + 4,0xd,0x10,rglT[2]._2_2_,0,0xc,0xee0086);
          SetTextColor(hdc,rglT._2_4_);
          SetBkColor(hdc,rglT._6_4_);
          SelectObject(rglT[2]._2_2_,HVar26);
          DeleteDC(rglT[2]._2_2_);
        }
        if (2 < (pl.wFlags & 0xffU)) {
          sVar16 = CchGetString((!bVar34 || !bVar33) + idsVal,(char *)szWork);
          DVar37 = GetTextExtent(hdc,szWork,sVar16);
          SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText)
                      );
          TextOut(hdc,iVar19,iVar27,szWork,sVar16);
          sVar16 = PctPlanetDesirability((PLANET *)CONCAT22(unaff_SS,&pl),idPlayer);
          sVar46 = _WSPRINTF((LPSTR)CONCAT22(sVar16,(char *)&DAT_1120_1120),
                             (LPCSTR)CONCAT22(PCTDPCTPCT,(char *)&DAT_1120_1120),
                             (char *)szWork);
          if (sVar16 < 0) {
            uVar23 = 0xff;
          }
          else {
            uVar23 = 0x7f00;
          }
          SetTextColor(hdc,(ulong)uVar23);
          TextOut(hdc,iVar19 + (int)DVar37,iVar27,szWork,sVar46);
          if (!bVar34 || !bVar33) {
            DVar38 = GetTextExtent(hdc,szWork,sVar46);
            sVar46 = PctPlanetOptValue((PLANET *)CONCAT22(unaff_SS,&pl),idPlayer);
            if (sVar16 < sVar46) {
              if (0 < sVar46) {
                if (sVar46 < 0xb) {
                  uVar23 = 0x7f7f;
                }
                else {
                  uVar23 = 0x7f00;
                }
                SetTextColor(hdc,(ulong)uVar23);
              }
              sVar16 = _WSPRINTF((LPSTR)CONCAT22(sVar46,(char *)&DAT_1120_1120),(LPCSTR)0x4fa1120,
                                 (char *)szWork);
              TextOut(hdc,iVar19 + (int)DVar37 + (int)DVar38,iVar27,szWork,sVar16);
            }
          }
        }
        SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
        if (pl.iPlayer != -1) {
          pcVar17 = PszGetCompressedString((!bVar34 || !bVar33) + idsPop);
          _strcpy(szT,pcVar17);
        }
        if ((pl.wFlags & 0xffU) == 7) {
          uVar18 = _strlen(szT);
          uVar39 = __aFulmul(CONCAT22(pl.rgwtMin[3]._2_2_,(undefined2)pl.rgwtMin[3]),100);
          sVar16 = CommaFormatLong(szT + uVar18,uVar39);
          RightTextOut(hdc,iVar20,iVar27,szT,uVar18 + sVar16,0);
        }
        else if (pl.iPlayer == -1) {
          sVar16 = CchGetString(idsUninhabited,szT);
          RightTextOut(hdc,iVar20,iVar27,szT,sVar16,0);
        }
        else {
          if (2 < (pl.wFlags & 0xffU)) {
            lVar40 = __aFlshl(CONCAT22(unaff_SI,unaff_DI),(ushort)cMines);
            rglT[2]._2_2_ = (uint)lVar40;
            _strcpy((char *)szWork,szT);
            uVar18 = _strlen(szT);
            if ((lVar40 < 0) || ((lVar40 < 0x10000 && (rglT[2]._2_2_ == 0)))) {
              iVar28 = CchGetString(idsMsg1264,(char *)szWork + uVar18);
            }
            else {
              uVar42 = 0xb1;
              pcVar17 = PszGetCompressedString(idsCLd00);
              iVar28 = _WSPRINTF((LPSTR)CONCAT22(uVar42,(char *)&DAT_1120_1120),
                                 (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),
                                 (char *)szWork + uVar18);
            }
            c_2 = uVar18 + iVar28;
            RightTextOut(hdc,iVar20,iVar27,(char *)szWork,c_2,0);
          }
          SetTextColor(hdc,0xff);
          sVar46 = 0;
          sVar16 = 0;
          pcVar17 = PszPlayerName(pl.iPlayer,0,1,0,0,(PLAYER *)0x0);
          RightTextOut(hdc,iVar20,iVar27 + dyArial8 + -2,pcVar17,sVar16,sVar46);
        }
        iVar27 = iVar27 + dyArial8 + -2;
        iVar28 = game.turn - pl.turn;
        if (iVar28 == 0) {
          if (bVar8) {
            SVar22 = idsCurrent;
          }
          else {
            SVar22 = idsReportCurrent;
          }
          pcVar17 = PszGetCompressedString(SVar22);
          c_2 = _WSPRINTF((LPSTR)CONCAT22(unaff_DI,(char *)&DAT_1120_1120),
                          (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),(char *)szWork)
          ;
        }
        else if (bVar8) {
          iVar24 = iVar28;
          pcVar17 = PszGetCompressedString(idsOld2);
          c_2 = _WSPRINTF((LPSTR)CONCAT22(iVar24,(char *)&DAT_1120_1120),
                          (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),(char *)szWork)
          ;
        }
        else {
          iVar24 = iVar28;
          pcVar17 = PszGetCompressedString(idsReportDYear);
          c_2 = _WSPRINTF((LPSTR)CONCAT22(iVar24,(char *)&DAT_1120_1120),
                          (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),(char *)szWork)
          ;
          if (1 < iVar28) {
            _strcat((char *)szWork,(char *)0x502);
            c_2 = c_2 + 1;
          }
          sVar16 = CchGetString(idsOld,(char *)szWork + c_2);
          c_2 = c_2 + sVar16;
        }
        if (iVar28 < 6) {
          uVar23 = 0;
        }
        else {
          uVar23 = 0xff;
        }
        SetTextColor(hdc,(ulong)uVar23);
        TextOut(hdc,iVar19,iVar27,szWork,c_2);
        yCur = iVar27 + dyArial8;
        hbrSav = SelectObject(hdc,hbrButtonShadow);
        PatBlt(hdc,iVar19,yCur,iVar20 - iVar19,1,0xf00021);
        PatBlt(hdc,iVar19 + 1,yCur + 1,(iVar20 - iVar19) + -2,uVar21 * 3 + -1,0x42);
        PatBlt(hdc,iVar19,yCur,1,uVar21 * 3,0xf00021);
        PatBlt(hdc,iVar19 + 2,yCur + uVar21,(iVar20 - iVar19) + -4,1,0xf00021);
        PatBlt(hdc,iVar19 + 2,uVar21 * 2 + yCur,(iVar20 - iVar19) + -4,1,0xf00021);
        SelectObject(hdc,hbrButtonHilite);
        PatBlt(hdc,iVar20 + -1,yCur + 1,1,uVar21 * 3,0xf00021);
        PatBlt(hdc,iVar19,uVar21 * 3 + yCur,iVar20 - iVar19,1,0xf00021);
        SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
        SetBkMode(hdc,1);
        sVar16 = FCanTerraformLppl((PLANET *)CONCAT22(unaff_SS,&pl),rgMin,rgMax,rgCost,1);
        iVar27 = (iVar20 - iVar19) + -4;
        iVar28 = (int)(uVar21 - dyArial8) >> 1;
        for (i = 0; i < 3; i = i + 1) {
          iVar24 = (int)*(char *)(idPlayer * 0xc0 + 0x59b5 + i);
          cVar5 = *(char *)(idPlayer * 0xc0 + 0x59b8 + i);
          iVar25 = (int)pl.rgEnvVar[i];
          if (bVar8) {
            pcVar17 = (char *)*(undefined2 *)(i * 2 + 0x492);
          }
          else {
            pcVar17 = (char *)*(undefined2 *)(i * 2 + 0x47e);
          }
          RightTextOut(hdc,iVar19 + -2,yCur + iVar28,pcVar17,0,0);
          if (2 < (pl.wFlags & 0xffU)) {
            pcVar17 = PszCalcEnvVar(i,iVar25);
            uVar18 = _strlen(pcVar17);
            SelectObject(hdc,rghfontArial8[0]);
            TextOut(hdc,iVar20 + 2,yCur + iVar28,
                    (LPCSTR)CONCAT22((undefined1 *)&DAT_1120_1120,pcVar17),uVar18);
          }
          SelectObject(hdc,rghfontArial8[1]);
          SelectObject(hdc,(*((ushort (*) [2])rghbrPlanetAttr + i))[0]);
          HVar44 = hdc;
          sVar46 = MulDiv(iVar24,iVar27,100);
          iVar30 = iVar19 + 2 + sVar46;
          iVar29 = yCur + 2;
          sVar46 = MulDiv(cVar5 - iVar24,iVar27,100);
          PatBlt(HVar44,iVar30,iVar29,sVar46,uVar21 - 3,0xf00021);
          if (2 < (pl.wFlags & 0xffU)) {
            SelectObject(hdc,*(HGDIOBJ *)((int)rghbrPlanetAttr[0] + 2 + i * 4));
            sVar46 = MulDiv((int)pl.rgEnvVarOrig[i],iVar27,100);
            rglT[2]._2_2_ = iVar19 + 2 + sVar46;
            iVar24 = (int)uVar21 / 2 + yCur;
            c_2 = (int)uVar21 / 4 + -1;
            if (c_2 < 2) {
              c_2 = 2;
            }
            PatBlt(hdc,rglT[2]._2_2_ - c_2,iVar24,c_2 * 2 + 1,1,0xf00021);
            PatBlt(hdc,rglT[2]._2_2_,iVar24 - c_2,1,c_2 * 2 + 1,0xf00021);
            c_2 = 1;
            sVar46 = MulDiv(iVar25,iVar27,100);
            xBeg = iVar19 + 2 + sVar46;
            iMax = yCur + 3;
            iVar24 = yCur + uVar21 + -3;
            while( true ) {
              PatBlt(hdc,xBeg,iMax,1,1,0xf00021);
              PatBlt(hdc,xBeg + c_2 + -1,iMax,1,1,0xf00021);
              if (iVar24 < iMax + 1) break;
              PatBlt(hdc,xBeg,iVar24,1,1,0xf00021);
              PatBlt(hdc,xBeg + c_2 + -1,iVar24,1,1,0xf00021);
              xBeg = xBeg + -1;
              c_2 = c_2 + 2;
              iMax = iMax + 1;
              iVar24 = iVar24 + -1;
            }
            if (sVar16 != 0) {
              if (rgMin[i] == -1) {
                dxBar = 0;
              }
              else if ((uint)(iVar25 - rgMin[i]) < 0x8000) {
                dxBar = iVar25 - rgMin[i];
              }
              else {
                dxBar = 0;
              }
              sVar46 = MulDiv(iVar25 - dxBar,iVar27,100);
              iVar24 = iVar19 + 2 + sVar46;
              if (rgMax[i] == -1) {
                dxBar = 0;
              }
              else if ((uint)(rgMax[i] - iVar25) < 0x8000) {
                dxBar = rgMax[i] - iVar25;
              }
              else {
                dxBar = 0;
              }
              sVar46 = MulDiv(iVar25 + dxBar,iVar27,100);
              PatBlt(hdc,iVar24,iMax,((iVar19 + sVar46) - iVar24) + 3,1,0xf00021);
            }
          }
          yCur = yCur + uVar21;
        }
        yCur = yCur + (dyArial8 >> 1);
        SelectObject(hdc,hbrButtonShadow);
        PatBlt(hdc,iVar19,yCur,iVar20 - iVar19,1,0xf00021);
        PatBlt(hdc,iVar19 + 1,yCur + 1,(iVar20 - iVar19) + -2,uVar21 * 3 + 1,0x42);
        PatBlt(hdc,iVar19,yCur,1,uVar21 * 3 + 2,0xf00021);
        SelectObject(hdc,hbrButtonHilite);
        PatBlt(hdc,iVar20 + -1,yCur + 1,1,uVar21 * 3 + 2,0xf00021);
        PatBlt(hdc,iVar19,uVar21 * 3 + yCur + 2,iVar20 - iVar19,1,0xf00021);
        SelectObject(hdc,rghfontArial7[0]);
        sVar16 = _WSPRINTF((LPSTR)CONCAT22(cMinGrafMax,(char *)&DAT_1120_1120),
                           (LPCSTR)CONCAT22(PCTD,(char *)&DAT_1120_1120),
                           (char *)szWork);
        DVar37 = GetTextExtent(hdc,szWork,sVar16);
        iVar27 = (iVar20 - iVar19) + -3;
        iVar28 = cMinGrafMax / (iVar27 / (((int)DVar37 >> 1) + (int)DVar37));
        if (cMinGrafMax < 500) {
          dNum = ((iVar28 + 0x31) / 0x32) * 10;
        }
        else if (cMinGrafMax < 1000) {
          dNum = ((iVar28 + 0x31) / 0x32) * 0x32;
        }
        else if (cMinGrafMax < 0x9c4) {
          dNum = ((iVar28 + 99) / 100) * 100;
        }
        else if (cMinGrafMax < 0x1d4c) {
          dNum = ((iVar28 + 0xf9) / 0xfa) * 0xfa;
        }
        else if (cMinGrafMax < 15000) {
          dNum = ((iVar28 + 499) / 500) * 500;
        }
        else {
          dNum = ((iVar28 + 999) / 1000) * 1000;
        }
        iVar28 = cMinGrafMax / dNum;
        SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
        iVar24 = uVar21 * 3 + yCur + 4;
        for (i = 0; i <= iVar28; i = i + 1) {
          iVar29 = cMinGrafMax >> 0xf;
          iVar30 = iVar27 >> 0xf;
          iVar25 = iVar27;
          sVar16 = cMinGrafMax;
          uVar39 = __aFulmul((long)i,(long)dNum);
          uVar39 = __aFulmul(uVar39,CONCAT22(iVar30,iVar25));
          lVar40 = __aFldiv(uVar39,CONCAT22(iVar29,sVar16));
          iVar25 = (int)lVar40 + iVar19;
          PatBlt(hdc,iVar25,yCur + 2,1,uVar21 * 3 + -1,0xf00021);
          sVar16 = _WSPRINTF((LPSTR)CONCAT22(i * dNum,(char *)&DAT_1120_1120),
                             (LPCSTR)CONCAT22(PCTD,(char *)&DAT_1120_1120),
                             (char *)szWork);
          CtrTextOut(hdc,iVar25,iVar24,(char *)szWork,sVar16);
        }
        RightTextOut(hdc,iVar19 + -4,iVar24,(char *)0x504,2,0);
        if (pl.iPlayer == idPlayer) {
          EstMineralsMined((PLANET *)CONCAT22(unaff_SS,&pl),rgl,-1,0);
        }
        else {
          rgl[2]._0_2_ = 0;
          rgl[2]._2_2_ = 0;
          rgl[1]._0_2_ = 0;
          rgl[1]._2_2_ = 0;
          rgl[0]._0_2_ = 0;
          rgl[0]._2_2_ = 0;
          if (pl.iPlayer == -1) {
            for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
              pFVar6 = ((FLEET **)rglpfl)[ifl];
              iVar28 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
              if ((pFVar6 == (FLEET *)0x0) && (iVar28 == 0)) break;
              if ((pFVar6->idPlanet == pl.id) &&
                 (((pFVar6->iPlayer == idPlayer && (((uint)pFVar6->wFlags >> 10 & 1) == 0))
                  && ((*(uint *)&((PLORD *)pFVar6->lpplord)[2].iordMax & 0xf) == 3)))) {
                lVar40 = CMineFromLpfl((FLEET *)CONCAT22(iVar28,pFVar6));
                if (0 < lVar40) {
                  EstMineralsMined((PLANET *)CONCAT22(unaff_SS,&pl),rglT,lVar40,0);
                  for (iPass = 0; iPass < 3; iPass = iPass + 1) {
                    uVar7 = *(uint *)(rglT + iPass);
                    iVar28 = *(int *)((int)rglT + iPass * 4 + 2);
                    puVar1 = (uint *)(rgl + iPass);
                    uVar23 = *puVar1;
                    *puVar1 = *puVar1 + uVar7;
                    piVar2 = (int *)((int)rgl + iPass * 4 + 2);
                    *piVar2 = *piVar2 + iVar28 + (uint)CARRY2(uVar23,uVar7);
                  }
                }
              }
            }
          }
        }
        SelectObject(hdc,rghfontArial8[1]);
        iVar28 = ((int)(uVar21 - dyArial8) >> 1) + 2;
        for (i = 0; i < 3; i = i + 1) {
          SetTextColor(hdc,CONCAT22(*(undefined2 *)(i * 4 + 0x44a),*(undefined2 *)(i * 4 + 0x448)));
          sVar16 = 0;
          if (bVar8) {
            uVar18 = 4;
          }
          else {
            uVar18 = _strlen((char *)*(undefined2 *)(i * 2 + 0x4cc));
          }
          RightTextOut
                    (hdc,iVar19 + -2,yCur + iVar28,(char *)*(undefined2 *)(i * 2 + 0x4cc),uVar18,
                     sVar16);
          iVar24 = cMinGrafMax >> 0xf;
          iVar25 = *(int *)((int)rgl + i * 4 + 2) + *(int *)((int)pl.rgwtMin + i * 4 + 2) +
                   (uint)CARRY2(*(uint *)(rgl + i),*(uint *)(pl.rgwtMin + i));
          if ((iVar25 < iVar24) ||
             ((iVar29 = cMinGrafMax, iVar30 = iVar24, iVar25 <= iVar24 &&
              (*(uint *)(rgl + i) + *(uint *)(pl.rgwtMin + i) <= (uint)cMinGrafMax)))) {
            iVar29 = *(uint *)(rgl + i) + *(uint *)(pl.rgwtMin + i);
            iVar30 = *(int *)((int)rgl + i * 4 + 2) + *(int *)((int)pl.rgwtMin + i * 4 + 2) +
                     (uint)CARRY2(*(uint *)(rgl + i),*(uint *)(pl.rgwtMin + i));
          }
          sVar16 = cMinGrafMax;
          uVar39 = __aFulmul((long)iVar27,CONCAT22(iVar30,iVar29));
          lVar40 = __aFldiv(uVar39,CONCAT22(iVar24,sVar16));
          SetRect((undefined2 *)CONCAT22(unaff_SS,&rcGauge),iVar19 + 1,yCur + 4,
                  iVar19 + (int)lVar40 + 1,yCur + uVar21 + -1);
          if ((int)lVar40 != 0) {
            FillRect(hdc,(undefined2 *)CONCAT22(unaff_SS,&rcGauge),
                     *(HBRUSH *)((int)rghbrMinSum[0] + 2 + i * 4));
          }
          rglT[2]._2_2_ = *(uint *)(rgl + i) + *(uint *)(pl.rgwtMin + i);
          iVar24 = *(int *)((int)rgl + i * 4 + 2) + *(int *)((int)pl.rgwtMin + i * 4 + 2) +
                   (uint)CARRY2(*(uint *)(rgl + i),*(uint *)(pl.rgwtMin + i));
          if ((cMinGrafMax >> 0xf <= iVar24) &&
             ((cMinGrafMax >> 0xf < iVar24 || ((uint)cMinGrafMax < rglT[2]._2_2_)))) {
            SetTextColor(hdc,CONCAT22(crButtonText._2_2_,
                                      (undefined2)crButtonText));
            TextOut(hdc,iVar20,yCur + iVar28,(LPCSTR)0x11200507,1);
          }
          iVar25 = cMinGrafMax >> 0xf;
          iVar24 = *(int *)((int)pl.rgwtMin + i * 4 + 2);
          if ((iVar24 < iVar25) ||
             ((sVar16 = cMinGrafMax, iVar29 = iVar25, iVar24 <= iVar25 &&
              (*(uint *)(pl.rgwtMin + i) <= (uint)cMinGrafMax)))) {
            sVar16 = (short)pl.rgwtMin[i];
            iVar29 = *(int *)((int)pl.rgwtMin + i * 4 + 2);
          }
          sVar46 = cMinGrafMax;
          uVar39 = __aFulmul((long)iVar27,CONCAT22(iVar29,sVar16));
          lVar40 = __aFldiv(uVar39,CONCAT22(iVar25,sVar46));
          SetRect((undefined2 *)CONCAT22(unaff_SS,&rcGauge),iVar19 + 1,yCur + 4,
                  iVar19 + (int)lVar40 + 1,yCur + uVar21 + -1);
          if ((int)lVar40 != 0) {
            FillRect(hdc,(undefined2 *)CONCAT22(unaff_SS,&rcGauge),
                     (*((ushort (*) [2])rghbrMinSum + i))[0]);
          }
          if (2 < (pl.wFlags & 0xffU)) {
            for (iPass = 0; iPass < 2; iPass = iPass + 1) {
              SelectObject(hdc,((ushort (*) [2])rghbrMinSum)[i][iPass]);
              c_2 = 1;
              if (pl.rgMinConc[i] < 0x65) {
                uVar23 = (uint)pl.rgMinConc[i];
              }
              else {
                uVar23 = 100;
              }
              sVar16 = MulDiv(uVar23,(iVar20 - iVar19) + -0xb,100);
              xBeg = iVar19 + 1 + iPass + sVar16;
              iMax = yCur + 4;
              iVar24 = yCur + uVar21 + -2;
              while( true ) {
                PatBlt(hdc,xBeg,iMax,c_2,1,0xf00021);
                if (iVar24 < iMax + 1) break;
                PatBlt(hdc,xBeg,iVar24,c_2,1,0xf00021);
                c_2 = c_2 + 2;
                xBeg = xBeg + -1;
                iMax = iMax + 1;
                iVar24 = iVar24 + -1;
              }
            }
          }
          yCur = yCur + uVar21;
        }
        SetBkMode(hdc,2);
        SelectObject(hdc,hbrSav);
        pPVar31 = (PLAYER *)rgplr + idPlayer;
        pPVar32 = &plrSav;
        for (iVar27 = 0x60; l2 = CONCAT22(l2._2_2_,(undefined2)l2), iVar27 != 0;
            iVar27 = iVar27 + -1) {
          pPVar4 = pPVar31;
          pPVar31 = (PLAYER *)&pPVar31->cPlanet;
          pPVar3 = pPVar32;
          pPVar32 = (PLAYER *)&pPVar32->cPlanet;
          cVar5 = pPVar3->cShDef;
          pPVar4->iPlayer = pPVar3->iPlayer;
          pPVar4->cShDef = cVar5;
        }
        goto MINE_FinishUp_5;
      }
    }
    l2 = CONCAT22(l2._2_2_,(undefined2)l2);
    if (sel.scan.idpl != -1) {
      HVar26 = SelectObject(HVar13,hbmpUnknownPlanet);
      SetTextColor(hdc,0);
      BitBlt(hdc,((prc->right - prc->left) + -0x40 >> 1) + prc->left,
             ((prc->bottom - prc->top) + -0x40 >> 1) + prc->top,0x40,0x40,HVar13,0,0,0xcc0020);
      SelectObject(HVar13,HVar26);
      l2 = CONCAT22(l2._2_2_,(undefined2)l2);
    }
    goto MINE_FinishUp_5;
  }
  l2 = CONCAT22(l2._2_2_,(undefined2)l2);
  rglT._2_4_ = uVar9;
  rglT._6_4_ = uVar11;
  if (sel.scan.ith == -1) goto MINE_FinishUp_5;
  rgMin[2] = lpThings._2_2_;
  rgMin[1] = (short)((THING *)lpThings + sel.scan.ith);
  uVar21 = *(uint *)((int)&rgplr[0].wMdPlr + (*(uint *)rgMin._2_4_ >> 9 & 0xf) * 0xc0) >>
           3;
  iVar27 = prc->left;
  iVar19 = prc->top;
  hbmpSav_2 = iVar19 + 6;
  hbrSav = SelectObject(hdc,hbrButtonShadow);
  PatBlt(hdc,iVar27 + 6,hbmpSav_2,0x46,2,0xf00021);
  PatBlt(hdc,iVar27 + 6,iVar19 + 8,2,0x44,0xf00021);
  if (*(uint *)rgMin._2_4_ >> 0xd == 0) {
    dyRow = (short)*(byte *)((int)rgMin._2_4_ + 0xc);
  }
  else if (*(uint *)rgMin._2_4_ >> 0xd == 1) {
    dyRow = ((*(uint *)((int)rgMin._2_4_ + 6) >> 10 & 0xf) != 0) + 3;
  }
  else if (*(uint *)rgMin._2_4_ >> 0xd == 3) {
    dyRow = 6;
  }
  else {
    dyRow = 5;
  }
  SelectPalette(hdc,vhpal,0);
  RealizePalette(hdc);
  if ((*(uint *)rgMin._2_4_ >> 0xd == 2) || (*(uint *)rgMin._2_4_ >> 0xd == 3)) {
    SelectObject(hdc,hbrButtonHilite);
    PatBlt(hdc,iVar27 + 8,iVar19 + 0x4a,0x44,1,0xf00021);
    PatBlt(hdc,iVar27 + 7,iVar19 + 0x4b,0x45,1,0xf00021);
    PatBlt(hdc,iVar27 + 0x4a,iVar19 + 8,2,0x42,0xf00021);
    PatBlt(hdc,iVar27 + 0x4b,iVar19 + 7,1,1,0xf00021);
    PatBlt(hdc,iVar27 + 8,iVar19 + 8,0x42,0x42,0x42);
  }
  else {
    PatBlt(hdc,iVar27 + 0x16,iVar19 + 0x4a,2,0x26,0xf00021);
    SelectObject(hdc,hbrButtonHilite);
    PatBlt(hdc,iVar27 + 8,iVar19 + 0x4a,0xf,1,0xf00021);
    PatBlt(hdc,iVar27 + 7,iVar19 + 0x4b,0xf,1,0xf00021);
    PatBlt(hdc,iVar27 + 0x3a,iVar19 + 0x4a,0x12,2,0xf00021);
    PatBlt(hdc,iVar27 + 0x4a,iVar19 + 8,2,0x42,0xf00021);
    PatBlt(hdc,iVar27 + 0x4b,iVar19 + 7,1,1,0xf00021);
    PatBlt(hdc,iVar27 + 0x17,iVar19 + 0x6e,0x25,2,0xf00021);
    PatBlt(hdc,iVar27 + 0x16,iVar19 + 0x6f,1,1,0xf00021);
    PatBlt(hdc,iVar27 + 0x3a,iVar19 + 0x4c,2,0x22,0xf00021);
    PatBlt(hdc,iVar27 + 8,iVar19 + 8,0x42,0x42,0x42);
    PatBlt(hdc,iVar27 + 0x18,iVar19 + 0x4a,0x22,0x24,0x42);
    DibBlt(hdc,iVar27 + 0x19,iVar19 + 0x4d,0x20,0x20,hdibRaces,(uVar21 & 7) << 5,
                    (3 - ((int)(uVar21 & 0x1f) >> 3)) * 0x20,0x20,0x20,0xcc0020);
  }
  SelectObject(hdc,hbrSav);
  DibBlt(hdc,iVar27 + 8,iVar19 + 8,0x40,0x40,hdibThings,dyRow << 6,0,0x40,0x40,
                  0xcc0020);
  if (*(uint *)rgMin._2_4_ >> 0xd == 1) {
    iVar27 = iVar27 + 0x56;
    SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
    SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    SelectObject(hdc,rghfontArial8[1]);
    if ((*(uint *)((int)rgMin._2_4_ + 6) >> 10 & 0xf) != 0) {
      CchGetString(idsTravelingWarpD,szT);
      c = _WSPRINTF((LPSTR)CONCAT22((*(uint *)((int)rgMin._2_4_ + 6) >> 10 & 0xf) + 4,unaff_SS),
                    (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
      TextOut(hdc,iVar27,hbmpSav_2,szWork,c);
      hbmpSav_2 = hbmpSav_2 + dyArial8 + 2;
      CchGetString(idsDestination,szT);
      pcVar17 = PszGetPlanetName(*(uint *)((int)rgMin._2_4_ + 6) & 0x3ff);
      _strcat(szT,pcVar17);
      pcVar17 = szT;
      HVar41 = hbmpSav_2;
      iVar19 = iVar27;
      HVar44 = hdc;
      uVar18 = _strlen(szT);
      TextOut(HVar44,iVar19,HVar41,(LPCSTR)CONCAT22(unaff_SS,pcVar17),uVar18);
    }
    hbmpSav_2 = hbmpSav_2 + (dyArial8 * 3) / 2;
    puVar43 = (undefined1 *)&DAT_1120_1120;
    pcVar17 = DAT_1120_04d0;
    HVar44 = hdc;
    uVar18 = _strlen(DAT_1120_04d0);
    DVar37 = GetTextExtent(HVar44,(LPCSTR)CONCAT22(puVar43,pcVar17),uVar18);
    iVar27 = iVar27 + (int)DVar37;
    i = 0;
    while( true ) {
      l2 = CONCAT22(l2._2_2_,(undefined2)l2);
      if (2 < i) break;
      uVar42 = *(undefined2 *)(i * 2 + 0x4cc);
      pcVar17 = PszGetCompressedString(idsS2);
      c = _WSPRINTF((LPSTR)CONCAT22(uVar42,(char *)&DAT_1120_1120),
                    (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),(char *)szWork);
      RightTextOut(hdc,iVar27,hbmpSav_2,(char *)szWork,c,0);
      c = _WSPRINTF((LPSTR)CONCAT22(*(undefined2 *)(rgMin[1] + 8 + i * 2),(char *)&DAT_1120_1120),
                    (LPCSTR)CONCAT22(PCTDKT,(char *)&DAT_1120_1120),(char *)szWork)
      ;
      TextOut(hdc,iVar27,hbmpSav_2,szWork,c);
      hbmpSav_2 = hbmpSav_2 + dyArial8 + 2;
      i = i + 1;
    }
    goto MINE_FinishUp_5;
  }
  if (*(uint *)rgMin._2_4_ >> 0xd != 2) {
    if (*(uint *)rgMin._2_4_ >> 0xd == 3) {
      SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
      SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
      SelectObject(hdc,rghfontArial8[1]);
      SetRect((undefined2 *)CONCAT22(unaff_SS,&rc),iVar27 + 0x56,hbmpSav_2,prc->right + -8,
              prc->bottom + -8);
      if ((1 << ((byte)idPlayer & 0x1f) & *(uint *)((int)rgMin._2_4_ + 0xc)) == 0) {
        pcVar17 = PszGetCompressedString(idsTraderRequestsInterestedPartiesSendFleetLeast);
        puVar43 = (undefined1 *)&DAT_1120_1120;
        HVar44 = hdc;
        uVar18 = _strlen(pcVar17);
        sVar16 = DRAWTEXT(HVar44,(LPCSTR)CONCAT22(puVar43,pcVar17),uVar18,
                          (undefined2 *)CONCAT22(unaff_SS,&rc),0x810);
        hbmpSav_2 = hbmpSav_2 + sVar16 + 8;
      }
      uVar21 = *(uint *)((int)rgMin._2_4_ + 10) & 0xf;
      pcVar17 = PszGetCompressedString(idsTraderTravelingWarpD);
      sVar16 = _WSPRINTF((LPSTR)CONCAT22(uVar21,(char *)&DAT_1120_1120),
                         (LPCSTR)CONCAT22(pcVar17,(char *)&DAT_1120_1120),(char *)szWork);
      TextOut(hdc,iVar27 + 0x56,hbmpSav_2,szWork,sVar16);
      l2 = CONCAT22(l2._2_2_,(undefined2)l2);
    }
    else {
      l2 = CONCAT22(l2._2_2_,(undefined2)l2);
      if (*(uint *)rgMin._2_4_ >> 0xd == 0) {
        iVar27 = iVar27 + 0x56;
        SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
        SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
        SelectObject(hdc,rghfontArial8[1]);
        CchGetString(idsLocationDD,szT);
        c = _WSPRINTF((LPSTR)CONCAT22(*(undefined2 *)((int)rgMin._2_4_ + 2),unaff_SS),
                      (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
        TextOut(hdc,iVar27,hbmpSav_2,szWork,c);
        iVar19 = hbmpSav_2 + dyArial8 + 2;
        CchGetString(idsFieldTypeS,szT);
        c = _WSPRINTF((LPSTR)CONCAT22(*(undefined2 *)
                                       ((uint)*(byte *)((int)rgMin._2_4_ + 0xc) * 2 + 0x4f2),
                                      unaff_SS),(LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),
                      (char *)szWork);
        TextOut(hdc,iVar27,iVar19,szWork,c);
        iVar19 = iVar19 + dyArial8 + 2;
        CchGetString(idsFieldRadiusDLYLdMines,szT);
        sVar16 = SUB42(rgMin._2_4_,2);
        iVar20 = (int)rgMin._2_4_;
        uVar42 = *(undefined2 *)(iVar20 + 8);
        uVar45 = *(undefined2 *)(iVar20 + 6);
        _sqrt(SUB84((double)*(long *)(iVar20 + 6),0),
                      (double)CONCAT26(uVar42,CONCAT24(uVar45,(long)((qword)(double)*(long *)(iVar20
                                                                                             + 6) >>
                                                                    0x20))));
        lVar40 = __ftol((double)CONCAT26(unaff_SI,CONCAT24(unaff_DI,CONCAT22(uVar42,uVar45))
                                                ));
        c = _WSPRINTF((LPSTR)CONCAT22((int)lVar40,unaff_SS),
                      (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
        TextOut(hdc,iVar27,iVar19,szWork,c);
        iVar19 = iVar19 + dyArial8 + 2;
        sVar16 = GetRaceStat((PLAYER *)rgplr + (*(uint *)rgMin._2_4_ >> 9 & 0xf),
                                   rsMajorAdv);
        sVar46 = SUB42(rgMin._2_4_,2);
        iVar20 = (int)rgMin._2_4_;
        pt.y = *(short *)(iVar20 + 4);
        pt.x = *(short *)(iVar20 + 2);
        sVar46 = CPlanetsInCircle
                           (pt,CONCAT22(*(undefined2 *)(iVar20 + 8),*(undefined2 *)(iVar20 + 6)));
        uStack_d8 = ((uint)(sVar16 != 5) * 3 + 1) * sVar46 + 2;
        rgMin[0] = (int)uStack_d8 >> 0xf;
        if ((-1 < rgMin[0]) && ((0 < rgMin[0] || (0x32 < uStack_d8)))) {
          uStack_d8 = 0x32;
          rgMin[0] = 0;
        }
        sVar16 = SUB42(rgMin._2_4_,2);
        iVar20 = (int)rgMin._2_4_;
        if (*(char *)(iVar20 + 0xd) != '\0') {
          bVar33 = 0xffe6 < uStack_d8;
          uStack_d8 = uStack_d8 + 0x19;
          rgMin[0] = rgMin[0] + (uint)bVar33;
        }
        uVar45 = 0;
        uVar42 = 100;
        uVar39 = __aFulmul(CONCAT22(*(undefined2 *)(iVar20 + 8),*(undefined2 *)(iVar20 + 6))
                                   ,CONCAT22(rgMin[0],uStack_d8));
        lVar40 = __aFldiv(uVar39,CONCAT22(uVar45,uVar42));
        if (lVar40 < CONCAT22(rgMin[0],uStack_d8)) {
          lVar40 = CONCAT22(rgMin[0],uStack_d8);
        }
        uStack_de = (undefined2)lVar40;
        if ((*(char *)((int)rgMin._2_4_ + 0xc) != '\x02') && (lVar40 < 10)) {
          uStack_de = 10;
        }
        CchGetString(idsDecayRateLdYear,szT);
        c = _WSPRINTF((LPSTR)CONCAT22(uStack_de,unaff_SS),
                      (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
        TextOut(hdc,iVar27,iVar19,szWork,c);
        iVar20 = dyArial8 + 2;
        if ((*(uint *)rgMin._2_4_ >> 9 & 0xf) == idPlayer) {
          GetMineFieldCounts(*(ushort *)rgMin._2_4_,&i,&c2);
          CchGetString(idsFieldDD,szT);
          c = _WSPRINTF((LPSTR)CONCAT22(i,unaff_SS),(LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),
                        (char *)szWork);
          TextOut(hdc,iVar27,iVar19 + iVar20,szWork,c);
        }
        l2 = CONCAT22(l2._2_2_,(undefined2)l2);
      }
    }
    goto MINE_FinishUp_5;
  }
  SetTextColor(hdc,CONCAT22(crButtonText._2_2_,(undefined2)crButtonText));
  SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
  SelectObject(hdc,rghfontArial8[1]);
  sVar16 = CchGetString(idsLocation,szT);
  DVar37 = GetTextExtent(hdc,(LPCSTR)CONCAT22(unaff_SS,szT),sVar16);
  iVar27 = iVar27 + (int)DVar37 + 0x78;
  RightTextOut(hdc,iVar27 + -4,hbmpSav_2,szT,sVar16,0);
  CchGetString(idsDD5,szT);
  c = _WSPRINTF((LPSTR)CONCAT22(*(undefined2 *)((int)rgMin._2_4_ + 2),unaff_SS),
                (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
  TextOut(hdc,iVar27,hbmpSav_2,szWork,c);
  iVar19 = hbmpSav_2 + (dyArial8 * 3) / 2;
  c = CchGetString(idsDestination2,(char *)szWork);
  RightTextOut(hdc,iVar27 + -4,iVar19,(char *)szWork,c,0);
  if ((1 << ((byte)idPlayer & 0x1f) & *(uint *)((int)rgMin._2_4_ + 10)) == 0) {
LAB_1028_19f8:
    c = CchGetString(idsUnknown2,(char *)szWork);
  }
  else {
    pTVar36 = LpthFromId(*(short *)((int)rgMin._2_4_ + 0xc));
    if (pTVar36 == (THING *)0x0) goto LAB_1028_19f8;
    c = _WSPRINTF((LPSTR)CONCAT22((&((THING *)pTVar36)->pt)->x,unaff_SS),
                  (LPCSTR)CONCAT22(szT,(char *)&DAT_1120_1120),(char *)szWork);
  }
  TextOut(hdc,iVar27,iVar19,szWork,c);
  iVar19 = iVar19 + (dyArial8 * 3) / 2;
  c = CchGetString(idsStability,(char *)szWork);
  RightTextOut(hdc,iVar27 + -4,iVar19,(char *)szWork,c,0);
  pcVar17 = (char *)szWork;
  sVar16 = PctWormholeMoves((THING *)rgMin._2_4_);
  c = CchGetString(sVar16 + idsRockSolid,pcVar17);
  TextOut(hdc,iVar27,iVar19,szWork,c);
  l2 = CONCAT22(l2._2_2_,(undefined2)l2);
MINE_FinishUp_5:
  SetBkMode(hdc,sVar14);
  SetTextColor(hdc,crFore);
  SetBkColor(hdc,CVar35);
  DeleteDC(HVar13);
  return;
}



// ======================================================================
// Function: HtMineWindow
// Address: 1028:37ac
// Segment: MEMORY_MINE
// ======================================================================


short HtMineWindow(HWND hwnd,short x,short y)

{
  int iVar1;
  short sVar2;
  uint uVar3;
  undefined2 unaff_SS;
  RECT rc;
  short grobj;
  short yCur;
  short dyRow;
  PLANET pl;
  
  grobj = sel.scan.grobj;
  if (sel.scan.grobj == grobjOther) {
    if ((sel.scan.grobjFull & grobjPlanet) == grobjNone) {
      if ((sel.scan.grobjFull & grobjFleet) == grobjNone) {
        grobj = 0;
      }
      else {
        grobj = 2;
      }
    }
    else {
      grobj = 1;
    }
  }
  GetClientRect(hwnd,(undefined2 *)CONCAT22(unaff_SS,&rc));
  rc.top = rc.top + dyArial8 * 2;
  if ((((y < rc.top + -5) && (4 < y)) && (x < rc.right + -4)) &&
     ((rc.right - rc.top < x && (sVar2 = FOtherStuffAtScanSel(), sVar2 != 0)))) {
    sVar2 = 9;
  }
  else if ((grobj == 2) ||
          (((grobj == 8 &&
            ((uint)((THING *)lpThings + sel.scan.ith)->idFull >> 0xd != 2)) &&
           ((uint)((THING *)lpThings + sel.scan.ith)->idFull >> 0xd != 3)))) {
    if (((x < rc.left + 0x19) || (rc.left + 0x39 <= x)) ||
       ((y < rc.top + 0x47 || (rc.top + 0x67 <= y)))) {
      if (((grobj == 8) &&
          ((uint)((THING *)lpThings + sel.scan.ith)->idFull >> 0xd == 0)) &&
         ((rc.left + 9 <= x && (((x < rc.left + 0x49 && (rc.top + 9 <= y)) && (y < rc.top + 0x49))))
         )) {
        sVar2 = 0xe;
      }
      else if (grobj == 8) {
        sVar2 = 0;
      }
      else if (((x < rc.left + 9) || (rc.left + 0x49 <= x)) ||
              ((y < rc.top + 9 || (rc.top + 0x49 <= y)))) {
        if (((x < rc.left + 0x5c) || (y < rc.top + 4)) || (rc.top + 7 + dyArial8 <= y)) {
          sVar2 = 0;
        }
        else {
          sVar2 = 0xb;
        }
      }
      else {
        sVar2 = 0xb;
      }
    }
    else {
      sVar2 = 10;
    }
  }
  else if ((sel.scan.idpl == -1) ||
          (sVar2 = FLookupPlanet(sel.scan.idpl,&pl), sVar2 == 0)) {
    sVar2 = 0;
  }
  else {
    uVar3 = ((rc.bottom - (rc.top + -4)) + dyArial8 * -4 + -2) / 6 + 1U & 0xfffe;
    iVar1 = rc.top + dyArial8 * 2 + -4;
    if (y < iVar1) {
      if (rc.top + -4 < y) {
        if (x < rc.right + -0x18) {
          if ((((pl.iPlayer == idPlayer) || (x <= (rc.right * 3) / 5)) ||
              (y < iVar1 - dyArial8)) || (pl.iPlayer == -1)) {
            sVar2 = 0xc;
          }
          else {
            sVar2 = 10;
          }
        }
        else if (((uint)pl.wFlags >> 9 & 1) == 0) {
          sVar2 = 0;
        }
        else {
          sVar2 = 0xd;
        }
      }
      else {
        sVar2 = 0;
      }
    }
    else if (y < (int)(uVar3 * 3 + iVar1)) {
      sVar2 = (y - iVar1) / (int)uVar3 + 6;
    }
    else {
      iVar1 = iVar1 + uVar3 * 3 + (dyArial8 >> 1) + 1;
      if (y < (int)(uVar3 * 3 + iVar1)) {
        sVar2 = (y - iVar1) / (int)uVar3 + 1;
      }
      else {
        sVar2 = 5;
      }
    }
  }
  return sVar2;
}



// ======================================================================
// Function: MineClick
// Address: 1028:3b4e
// Segment: MEMORY_MINE
// ======================================================================

// Decompilation failed: Exception while decompiling 1028:3b4e: process: timeout


// ======================================================================
// Function: SetMineralTitleBar
// Address: 1028:47dc
// Segment: MEMORY_MINE
// ======================================================================


void SetMineralTitleBar(HWND hwnd)

{
  bool bVar1;
  GrobjClass GVar2;
  short sVar3;
  uint uVar4;
  undefined2 unaff_SS;
  bool bVar5;
  RECT rc;
  short grobj;
  char *psz;
  short fVisCB;
  char szSummary [40];
  char szDeepSpace [40];
  
  bVar5 = false;
  CchGetString(idsDeepSpace,szDeepSpace);
  CchGetString(idsSummary,szSummary);
  GVar2 = sel.scan.grobjFull;
  if (sel.scan.grobj != grobjOther) {
    GVar2 = sel.scan.grobj;
  }
  if ((GVar2 & grobjPlanet) == grobjNone) {
    if ((GVar2 & grobjFleet) == grobjNone) {
      if ((GVar2 & grobjThing) == grobjNone) {
        psz = szDeepSpace;
      }
      else {
        bVar5 = sel.scan.ith != -1;
        if (bVar5) {
          psz = PszGetThingName(((THING *)lpThings + sel.scan.ith)->idFull);
          _strcat(psz,szSummary);
        }
      }
    }
    else if (sel.scan.ifl != -1) {
      psz = PszGetFleetName(((FLEET **)rglpfl)[sel.scan.ifl]->id);
      _strcat(psz,szSummary);
    }
  }
  else if (sel.scan.idpl != -1) {
    psz = PszGetPlanetName(sel.scan.idpl);
    _strcat(psz,szSummary);
  }
  _strcpy((char *)szMineralTitle,psz);
  InvalidateRect(hwnd,(undefined2 *)0x0,1);
  bVar1 = false;
  if (bVar5) {
    if (((((uint)((THING *)lpThings + sel.scan.ith)->idFull >> 0xd == 0) &&
         (((THING *)lpThings)[sel.scan.ith].rgb[6] == 0)) &&
        (((uint)((THING *)lpThings + sel.scan.ith)->idFull >> 9 & 0xf) ==
         idPlayer)) &&
       (sVar3 = GetRaceStat((PLAYER *)rgplr + idPlayer,rsMajorAdv),
       sVar3 == 5)) {
      bVar1 = true;
    }
    else {
      bVar1 = false;
    }
  }
  if (bVar1) {
    SendMessage(hwndMineCB,0x401,
                (uint)(((THING *)lpThings)[sel.scan.ith].rgb[7] != 0),0);
  }
  GetClientRect(hwnd,(undefined2 *)CONCAT22(unaff_SS,&rc));
  if (bVar1) {
    uVar4 = 0x40;
  }
  else {
    uVar4 = 0x80;
  }
  SetWindowPos(hwndMineCB,0,0x50,rc.bottom + dyArial8 * -2,rc.right + -0x58,
               dyArial8 + 4,uVar4 | 4);
  return;
}



// ======================================================================
// Function: DrawSelectionArrow
// Address: 1028:4a68
// Segment: MEMORY_MINE
// ======================================================================


void DrawSelectionArrow(HDC hdc,RECT *prc,short fEnabled)

{
  HDC HVar1;
  HGDIOBJ HVar2;
  int iVar3;
  short sVar4;
  short sVar5;
  short xCtr;
  HDC hdcMem;
  HBITMAP hbmpSav;
  
  HVar1 = CreateCompatibleDC(hdc);
  HVar2 = SelectObject(HVar1,hbmpScanner);
  iVar3 = (prc->right - prc->left) / 2 + prc->left;
  BitBlt(hdc,iVar3 + -5,(prc->bottom - prc->top >> 1) + prc->top + -5,0xb,0xc,HVar1,0x23,0x39,
         0x8800c6);
  if (fEnabled == 0) {
    sVar4 = 0;
    sVar5 = 0x2d;
  }
  else {
    sVar4 = 0x18;
    sVar5 = 0x39;
  }
  BitBlt(hdc,iVar3 + -5,(prc->bottom - prc->top >> 1) + prc->top + -5,0xb,0xc,HVar1,sVar4,sVar5,
         0xee0086);
  SelectObject(HVar1,HVar2);
  DeleteDC(HVar1);
  return;
}



// ======================================================================
// Function: DrawDiamond
// Address: 1028:4b60
// Segment: MEMORY_MINE
// ======================================================================


void DrawDiamond(HDC hdc,RECT *prc,HBRUSH hbr)

{
  int iVar1;
  int iVar2;
  int iVar3;
  HGDIOBJ HVar4;
  short xCur;
  short dx;
  short xCtr;
  short yBot;
  short yTop;
  HBRUSH hbrSav;
  
  iVar3 = (prc->right - prc->left) / 2 + prc->left;
  yTop = prc->top;
  iVar1 = prc->bottom;
  HVar4 = SelectObject(hdc,hbrButtonHilite);
  yBot = iVar1 + -2;
  xCur = iVar3;
  while (yTop = yTop + 1, xCur = xCur + -1, yTop <= yBot) {
    PatBlt(hdc,xCur,yTop,2,1,0xf00021);
    PatBlt(hdc,xCur,yBot,2,1,0xf00021);
    yBot = yBot + -1;
  }
  SelectObject(hdc,hbrButtonShadow);
  PatBlt(hdc,iVar3,prc->top,1,1,0xf00021);
  PatBlt(hdc,iVar3,prc->bottom + -1,1,1,0xf00021);
  yTop = prc->top;
  xCur = iVar3;
  yBot = prc->bottom + -2;
  while (yTop = yTop + 1, yTop <= yBot) {
    PatBlt(hdc,xCur,yTop,2,1,0xf00021);
    PatBlt(hdc,xCur,yBot,2,1,0xf00021);
    xCur = xCur + 1;
    yBot = yBot + -1;
  }
  iVar1 = prc->top;
  iVar2 = prc->bottom;
  dx = 1;
  SelectObject(hdc,hbr);
  xCur = iVar3;
  yBot = iVar2 + -5;
  yTop = iVar1 + 4;
  while (yTop <= yBot) {
    PatBlt(hdc,xCur,yTop,dx,1,0xf00021);
    PatBlt(hdc,xCur,yBot,dx,1,0xf00021);
    dx = dx + 2;
    xCur = xCur + -1;
    yBot = yBot + -1;
    yTop = yTop + 1;
  }
  SelectObject(hdc,HVar4);
  return;
}



// ======================================================================
// Function: FOtherStuffAtScanSel
// Address: 1028:4d6e
// Segment: MEMORY_MINE
// ======================================================================


short FOtherStuffAtScanSel(void)

{
  int iVar1;
  int iVar2;
  short sVar3;
  undefined2 uVar4;
  bool bVar5;
  THING *lpthMac;
  FLEET *lpfl;
  THING *lpth;
  short i;
  short c;
  
  if ((sel.scan.idpl == -1) ||
     ((sel.scan.ifl == -1 && (sel.scan.ith == -1)))) {
    if (sel.scan.ifl != -1) {
      if (sel.scan.ith != -1) {
        return 1;
      }
      c = 1;
      for (i = 0; i < cFleet; i = i + 1) {
        iVar1 = *(int *)((FLEET **)rglpfl + i);
        iVar2 = *(int *)((int)((FLEET **)rglpfl + i) + 2);
        if ((iVar1 == 0) && (iVar2 == 0)) break;
        if ((*(int *)(iVar1 + 8) == sel.scan.pt.x) &&
           ((*(int *)(iVar1 + 10) == sel.scan.pt.y && (bVar5 = c == 0, c = c + -1, bVar5))
           )) {
          return 1;
        }
      }
    }
    if (sel.scan.ith != -1) {
      c = 1;
      lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
      while ((THING *)lpth < (THING *)lpThings + cThing) {
        uVar4 = (undefined2)((ulong)lpth >> 0x10);
        if ((((&((THING *)lpth)->pt)->x == sel.scan.pt.x) &&
            ((((THING *)lpth)->pt).y == sel.scan.pt.y)) &&
           (bVar5 = c == 0, c = c + -1, bVar5)) {
          return 1;
        }
        lpth = (THING *)CONCAT22(uVar4,(THING *)lpth + 1);
      }
    }
    sVar3 = 0;
  }
  else {
    sVar3 = 1;
  }
  return sVar3;
}



// ======================================================================
// Function: PopupMineralScanChoices
// Address: 1028:4ecc
// Segment: MEMORY_MINE
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10285231) */
/* WARNING: Removing unreachable block (ram,0x10285166) */

void PopupMineralScanChoices(HWND hwnd,short x,short y)

{
  short *psVar1;
  SCAN *pSVar2;
  int iVar3;
  FLEET *pFVar4;
  short sVar5;
  int iVar6;
  short *psVar7;
  SCAN *pSVar8;
  undefined2 uVar9;
  undefined2 unaff_SS;
  bool bVar10;
  PLANET *pPVar11;
  SCAN scan;
  short iChecked;
  short idNew;
  long rgid [100];
  THING *lpthMac;
  FLEET *lpfl;
  THING *lpth;
  short c;
  short i;
  PLANET *lppl;
  short fOurs;
  short id;
  short fSep;
  
  iChecked = -1;
  if (sel.scan.idpl == -1) {
    c = 0;
  }
  else {
    rgid[0]._2_2_ = sel.scan.idpl >> 0xf;
    rgid[0]._0_2_ = sel.scan.idpl;
    rgid[1]._0_2_ = 0xffff;
    rgid[1]._2_2_ = 0xffff;
    c = 2;
    if (sel.scan.grobj == grobjPlanet) {
      iChecked = 0;
    }
  }
  for (i = 0; i < cFleet; i = i + 1) {
                    /* WARNING: Load size is inaccurate */
    pFVar4 = ((FLEET **)rglpfl)[i];
    iVar6 = *(int *)((int)((FLEET **)rglpfl + i) + 2);
    lpfl = (FLEET *)CONCAT22(iVar6,pFVar4);
    if ((pFVar4 == (FLEET *)0x0) && (iVar6 == 0)) break;
    if ((sel.scan.pt.x == (&pFVar4->pt)->x) && (sel.scan.pt.y == (pFVar4->pt).y)
       ) {
      if ((sel.scan.grobj == grobjFleet) &&
         (((FLEET **)rglpfl)[sel.scan.ifl]->id == lpfl->id)) {
        iChecked = c;
      }
      iVar3 = lpfl->id;
      iVar6 = c + 1;
      *(int *)(rgid + c) = iVar3;
      *(uint *)((int)rgid + c * 4 + 2) = iVar3 >> 0xf | 0x8000;
      c = iVar6;
      if (99 < iVar6) break;
    }
  }
  if ((c == 2) && (sel.scan.idpl != -1)) {
    c = 1;
  }
  bVar10 = c == 0;
  lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
  while ((THING *)lpth < (THING *)lpThings + cThing) {
    uVar9 = (undefined2)((ulong)lpth >> 0x10);
    if ((sel.scan.pt.x == (&((THING *)lpth)->pt)->x) &&
       (sel.scan.pt.y == (((THING *)lpth)->pt).y)) {
      if (!bVar10) {
        *(undefined2 *)(rgid + c) = 0xffff;
        *(undefined2 *)((int)rgid + c * 4 + 2) = 0xffff;
        bVar10 = true;
        c = c + 1;
      }
      if ((sel.scan.grobj == grobjThing) &&
         (((int)(THING *)lpth - (int)(THING *)lpThings) / 0x12 == sel.scan.ith)) {
        iChecked = c;
      }
      *(short *)(rgid + c) = lpth->idFull;
      *(undefined2 *)((int)rgid + c * 4 + 2) = 0x2000;
      c = c + 1;
    }
    lpth = (THING *)CONCAT22(uVar9,(THING *)lpth + 1);
  }
  sVar5 = PopupMenu(hwnd,x,y,c,rgid,(char **)0x0,iChecked,1);
  if (-1 < sVar5) {
    psVar7 = (short *)&sel.scan;
    pSVar8 = &scan;
    for (iVar6 = 8; iVar6 != 0; iVar6 = iVar6 + -1) {
      pSVar2 = pSVar8;
      pSVar8 = (SCAN *)&(pSVar8->pt).y;
      psVar1 = psVar7;
      psVar7 = psVar7 + 1;
      (pSVar2->pt).x = *psVar1;
    }
    if ((*(uint *)((int)rgid + sVar5 * 4 + 2) & 0x8000) == 0) {
      if ((*(uint *)((int)rgid + sVar5 * 4 + 2) & 0x2000) == 0) {
        scan.grobj = grobjPlanet;
        idNew = sel.scan.idpl;
        pPVar11 = LpplFromId(sel.scan.idpl);
        bVar10 = ((PLANET *)pPVar11)->iPlayer == idPlayer;
      }
      else {
        scan.grobj = grobjThing;
        lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
        while (((THING *)lpth < (THING *)lpThings + cThing &&
               (lpth->idFull != (int)rgid[sVar5]))) {
          lpth = (THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1);
        }
        scan.ith = ((int)(THING *)lpth - (int)(THING *)lpThings) / 0x12;
        idNew = lpth->idFull;
        bVar10 = false;
      }
    }
    else {
      scan.grobj = grobjFleet;
      idNew = (short)rgid[sVar5];
      for (i = 0; i < cFleet; i = i + 1) {
                    /* WARNING: Load size is inaccurate */
        pFVar4 = ((FLEET **)rglpfl)[i];
        iVar6 = *(int *)((int)((FLEET **)rglpfl + i) + 2);
        lpfl = (FLEET *)CONCAT22(iVar6,pFVar4);
        if (((pFVar4 == (FLEET *)0x0) && (iVar6 == 0)) || (lpfl->id == idNew)) break;
      }
      scan.ifl = i;
      bVar10 = ((FLEET *)lpfl)->iPlayer == idPlayer;
    }
    ChangeScanSel(&scan,2);
    if (bVar10) {
      RedrawScanSel(0,0);
      ChangeMainObjSel(scan.grobj,idNew);
      RedrawScanSel(0,1);
    }
  }
  return;
}



// ======================================================================
// Function: EstMineralsMined
// Address: 1028:5362
// Segment: MEMORY_MINE
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10285712) */
/* WARNING: Removing unreachable block (ram,0x102854bf) */
/* WARNING: Removing unreachable block (ram,0x102856b7) */
/* WARNING: Removing unreachable block (ram,0x102856ca) */
/* WARNING: Removing unreachable block (ram,0x102854c4) */
/* WARNING: Removing unreachable block (ram,0x102856cf) */
/* WARNING: Removing unreachable block (ram,0x102856ee) */
/* WARNING: Removing unreachable block (ram,0x102856f3) */
/* WARNING: Removing unreachable block (ram,0x10285717) */
/* WARNING: Removing unreachable block (ram,0x1028582c) */
/* WARNING: Removing unreachable block (ram,0x1028563d) */
/* WARNING: Removing unreachable block (ram,0x10285775) */
/* WARNING: Removing unreachable block (ram,0x10285806) */

void EstMineralsMined(PLANET *lppl,long *plQuan,long cMines,short fApply)

{
  uint *puVar1;
  byte bVar2;
  FLEET *pFVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  bool bVar7;
  bool bVar8;
  short sVar9;
  PLANET *pPVar10;
  ushort unaff_DI;
  undefined2 uVar11;
  ulong uVar12;
  long lVar13;
  long lVar14;
  ulong uVar15;
  long lVar16;
  undefined2 uVar17;
  undefined2 uVar18;
  uint uVar19;
  FLEET *lpfl;
  short ifl;
  long rglQuan [3];
  long lMineEff;
  long lMine;
  short fRemote;
  short fMacintosh;
  long lQuan;
  short i;
  long lQuanAct;
  long lQuanRem;
  
  bVar8 = cMines == -1;
  uVar11 = (undefined2)((ulong)lppl >> 0x10);
  pPVar10 = (PLANET *)lppl;
  if ((pPVar10->iPlayer == -1) ||
     (sVar9 = GetRaceStat((PLAYER *)rgplr + pPVar10->iPlayer,rsMajorAdv), sVar9 != 8
     )) {
    bVar7 = false;
  }
  else {
    bVar7 = true;
  }
  if (cMines == -1) {
    if ((pPVar10->iPlayer == -1) ||
       (((int)pPVar10->rgwtMin[3] == 0 && (*(int *)((int)pPVar10->rgwtMin + 0xe) == 0)))) {
      for (i = 0; i < 3; i = i + 1) {
        *(undefined2 *)(plQuan + i) = 0xffff;
        *(undefined2 *)((int)(plQuan + i) + 2) = 0xffff;
      }
      return;
    }
    sVar9 = CMinesOperating(lppl);
    cMines = (long)sVar9;
    if (bVar7) {
      lMineEff._0_2_ = 10;
      lMineEff._2_2_ = 0;
    }
    else {
      lMineEff._0_2_ = GetRaceStat((PLAYER *)rgplr + pPVar10->iPlayer,rsMineProd);
      lMineEff._2_2_ = (short)lMineEff >> 0xf;
    }
  }
  else {
    lMineEff._0_2_ = 10;
    lMineEff._2_2_ = 0;
  }
  lVar16 = CONCAT22(rglQuan[1]._2_2_,(undefined2)rglQuan[1]);
  i = 0;
  do {
    if (2 < i) {
      if ((bVar7) && (bVar8)) {
        for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
          pFVar3 = ((FLEET **)rglpfl)[ifl];
          iVar4 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
          if ((pFVar3 == (FLEET *)0x0) && (iVar4 == 0)) {
            return;
          }
          if ((((pFVar3->idPlanet == lppl->id) && (pFVar3->iPlayer == pPVar10->iPlayer)) &&
              (((uint)pFVar3->wFlags >> 10 & 1) == 0)) &&
             ((pFVar3->cord < 2 && ((*(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf) == 3))))
          {
            rglQuan[1] = lVar16;
            lVar14 = CMineFromLpfl((FLEET *)CONCAT22(iVar4,pFVar3));
            lVar16 = rglQuan[1];
            if ((-1 < lVar14) && ((0 < (int)((ulong)lVar14 >> 0x10) || ((int)lVar14 != 0)))) {
              EstMineralsMined(lppl,rglQuan,lVar14,fApply);
              for (i = 0; i < 3; i = i + 1) {
                uVar5 = *(uint *)(rglQuan + i);
                iVar6 = *(int *)((int)rglQuan + i * 4 + 2);
                puVar1 = (uint *)(plQuan + i);
                uVar19 = *puVar1;
                *puVar1 = *puVar1 + uVar5;
                puVar1 = (uint *)((int)(plQuan + i) + 2);
                *puVar1 = *puVar1 + iVar6 + (uint)CARRY2(uVar19,uVar5);
              }
              lVar16 = rglQuan[1];
              if (fApply != 0) {
                pFVar3->wFlags = pFVar3->wFlags & 0xdfff;
              }
            }
          }
        }
      }
      return;
    }
    rglQuan[2]._0_2_ = (uint)pPVar10->rgMinConc[i];
    if ((((uint)rglQuan[2] < 0x1e) && (((uint)pPVar10->wFlags >> 10 & 1) != 0)) &&
       ((bVar8 || (bVar7)))) {
      rglQuan[2]._0_2_ = 0x1e;
    }
    rglQuan[2]._2_2_ = 0;
    rglQuan[1] = lVar16;
    uVar12 = __aFulmul(cMines,(ulong)(uint)rglQuan[2]);
    uVar15 = uVar12;
    if (bVar8) {
      uVar18 = 0;
      uVar17 = 10;
      uVar15 = __aFulmul(uVar12,CONCAT22(lMineEff._2_2_,(short)lMineEff));
      uVar15 = __aFldiv(uVar15,CONCAT22(uVar18,uVar17));
    }
    lVar13 = __aFlrem(uVar15,100);
    lVar14 = __aFldiv(uVar15,100);
    lQuanRem._0_2_ = (int)lVar13;
    lVar16 = rglQuan[1];
    if ((lVar13 != 0) && (((uint)gd._0_2_ >> 1 & 1) != 0)) {
      sVar9 = Random(100);
      lVar16 = CONCAT22(sVar9,(undefined2)rglQuan[1]);
      if (sVar9 < (int)lQuanRem) {
        lVar14 = lVar14 + 1;
        lVar16 = CONCAT22(sVar9,(undefined2)rglQuan[1]);
      }
    }
    lQuan._2_2_ = (uint)((ulong)lVar14 >> 0x10);
    lQuan._0_2_ = (uint)lVar14;
    *(uint *)(plQuan + i) = (uint)lQuan;
    *(uint *)((int)(plQuan + i) + 2) = lQuan._2_2_;
    if (fApply != 0) {
      puVar1 = (uint *)(pPVar10->rgwtMin + i);
      uVar19 = *puVar1;
      *puVar1 = *puVar1 + (uint)lQuan;
      puVar1 = (uint *)((int)(pPVar10->rgwtMin + i) + 2);
      *puVar1 = *puVar1 + lQuan._2_2_ + (uint)CARRY2(uVar19,(uint)lQuan);
      rglQuan[1] = lVar16;
      lVar14 = __aFldiv(uVar12,100);
      lVar16 = rglQuan[1];
      while( true ) {
        if ((lVar14 < 1) || (pPVar10->rgMinConc[i] < 2)) goto LAB_1028_588f;
        rglQuan[0]._0_2_ = (uint)pPVar10->rgpctMinLevel[i];
        bVar2 = pPVar10->rgMinConc[i];
        lpfl._2_2_ = (uint)bVar2;
        if ((uint)rglQuan[0] == 0) {
          rglQuan[0]._0_2_ = 0x100;
        }
        rglQuan[0]._2_2_ = 0;
        if (bVar2 < 0x65) {
          if (bVar2 < 5) {
            lpfl._2_2_ = 10;
          }
          else if (bVar2 < 0x19) {
            lpfl._2_2_ = 0x19;
          }
        }
        else {
          lpfl._2_2_ = 100;
        }
        ifl = 0;
        uVar18 = 0;
        uVar17 = 0x100;
        uVar19 = lpfl._2_2_;
        rglQuan[1] = lVar16;
        uVar15 = __aFulmul((ulong)(uint)rglQuan[0],0x30d4);
        lVar16 = __aFldiv(uVar15,CONCAT22(uVar18,uVar17));
        lVar16 = __aFldiv(lVar16,CONCAT22(ifl,uVar19));
        if (lVar14 < lVar16) break;
        lVar14 = lVar14 - lVar16;
        pPVar10->rgMinConc[i] = pPVar10->rgMinConc[i] - 1;
        pPVar10->rgpctMinLevel[i] = 0;
      }
      rglQuan[1] = lVar16;
      lVar16 = __aFldiv(0x30d4,(ulong)lpfl._2_2_);
      lVar14 = __aFlshl(lVar16,unaff_DI);
      lVar16 = __aFldiv(lVar14,lVar16);
      if (lVar16 < 1) {
        lVar16 = 1;
      }
      if (CONCAT22(rglQuan[0]._2_2_,(uint)rglQuan[0]) <= lVar16) {
        lVar16 = CONCAT22(rglQuan[0]._2_2_ + -1 + (uint)((uint)rglQuan[0] != 0),(uint)rglQuan[0] - 1
                         );
      }
      pPVar10->rgpctMinLevel[i] = (byte)lVar16;
      if (lVar16 == 0) {
        pPVar10->rgMinConc[i] = pPVar10->rgMinConc[i] - 1;
      }
    }
LAB_1028_588f:
    i = i + 1;
  } while( true );
}



