// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: RaceCreationWizard
// Address: 10e0:0000
// Segment: MEMORY_RACE
// ======================================================================


short RaceCreationWizard(HWND hwndParent,short fReadOnly,short fDontWrite)

{
  short sVar1;
  int iVar2;
  char *pcVar3;
  FARPROC pvVar4;
  long lVar5;
  short cpts;
  RECT rgrcStack [17];
  undefined4 lpProc;
  short mdRet;
  
                    /* Segment:    29
                       Offset:     000c8f00
                       Length:     662c
                       Min Alloc:  662c
                       Flags:      1d10
                           Code
                           Discardable
                           Moveable
                           LoadOnCall
                           Impure (Non-shareable)
                        */
  vrgrcRCW = rgrcStack;
  fRCWReadOnly = fReadOnly;
  hwndRaceParent = hwndParent;
RACE_Step1:
  iPanelActive = 1;
  pvVar4 = MakeProcInstance(RaceWizardDlg1,hInst);
  lpProc = pvVar4;
  mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x92,hwndRaceParent),(HWND)((ulong)pvVar4 >> 0x10),
                    (char)pvVar4);
  FreeProcInstance(lpProc);
  if (mdRet == 0) {
    sVar1 = 0;
    lVar5 = lSaltCur;
LAB_10e0_03a6:
    lSaltCur._2_2_ = (undefined2)((ulong)lVar5 >> 0x10);
    lSaltCur._0_2_ = (undefined2)lVar5;
    return sVar1;
  }
  if (mdRet == 3) goto RACE_Finish;
RACE_Step2:
  do {
    iPanelActive = 2;
    pvVar4 = MakeProcInstance(RaceWizardDlg4,hInst);
    lpProc = pvVar4;
    mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x95,hwndRaceParent),
                      (HWND)((ulong)pvVar4 >> 0x10),(char)pvVar4);
    FreeProcInstance(lpProc);
    if (mdRet == 0) {
      sVar1 = 0;
      lVar5 = lSaltCur;
      goto LAB_10e0_03a6;
    }
    if (mdRet == 1) goto RACE_Step1;
    if (mdRet == 3) goto RACE_Finish;
RACE_Step3:
    iPanelActive = 3;
    pvVar4 = MakeProcInstance(RaceWizardDlg5,hInst);
    lpProc = pvVar4;
    mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x96,hwndRaceParent),
                      (HWND)((ulong)pvVar4 >> 0x10),(char)pvVar4);
    FreeProcInstance(lpProc);
    if (mdRet == 0) {
      sVar1 = 0;
      lVar5 = lSaltCur;
      goto LAB_10e0_03a6;
    }
    if (mdRet != 1) {
      if (mdRet == 3) goto RACE_Finish;
RACE_Step4:
      iPanelActive = 4;
      pvVar4 = MakeProcInstance((FARPROC)0x10e01060,hInst);
      lpProc = pvVar4;
      mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x93,hwndRaceParent),
                        (HWND)((ulong)pvVar4 >> 0x10),(char)pvVar4);
      FreeProcInstance(lpProc);
      if (mdRet == 0) {
        sVar1 = 0;
        lVar5 = lSaltCur;
        goto LAB_10e0_03a6;
      }
      if (mdRet != 1) {
        if (mdRet == 3) goto RACE_Finish;
RACE_Step5:
        iPanelActive = 5;
        pvVar4 = MakeProcInstance(RaceWizardDlg3,hInst);
        lpProc = pvVar4;
        mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x94,hwndRaceParent),
                          (HWND)((ulong)pvVar4 >> 0x10),(char)pvVar4);
        FreeProcInstance(lpProc);
        if (mdRet == 0) {
          sVar1 = 0;
          lVar5 = lSaltCur;
          goto LAB_10e0_03a6;
        }
        if (mdRet != 1) {
          if (mdRet == 3) goto RACE_Finish;
          while( true ) {
            iPanelActive = 6;
            pvVar4 = MakeProcInstance(RaceWizardDlg6,hInst);
            lpProc = pvVar4;
            mdRet = DialogBox(0,(LPCSTR)CONCAT22(0x97,hwndRaceParent),
                              (HWND)((ulong)pvVar4 >> 0x10),(char)pvVar4);
            FreeProcInstance(lpProc);
            if (mdRet == 0) {
              sVar1 = 0;
              lVar5 = lSaltCur;
              goto LAB_10e0_03a6;
            }
            if (mdRet == 1) break;
RACE_Finish:
            if (fRCWReadOnly != 0) {
              sVar1 = 0;
              lVar5 = lSaltCur;
              goto LAB_10e0_03a6;
            }
            sVar1 = CAdvantagePoints((PLAYER *)&vplr);
            if (-1 < sVar1) {
              lVar5 = LSaltFromSz((char *)&szRacePass);
              lSaltLast._0_2_ = 0xfffb;
              lSaltLast._2_2_ = 0xffff;
              lSaltCur = lVar5;
              sVar1 = FCheckPassword();
              if (sVar1 == 0) goto RACE_Step1;
              if (szRaceFile == '\0') {
                pcVar3 = (char *)s_stars_r1_1120_1328;
              }
              else {
                pcVar3 = (char *)&szRaceFile;
              }
              sVar1 = FSaveRace(pcVar3,(PLAYER *)&vplr);
              if (sVar1 == 0) goto RACE_Step1;
              sVar1 = 1;
              lVar5 = lSaltCur;
              goto LAB_10e0_03a6;
            }
            iVar2 = -sVar1;
            pcVar3 = PszGetCompressedString(idsAdvantagePointsCurrentlyHoleDPointsCannot);
            _wsprintf(szWork,(char *)CONCAT22(0x1120,pcVar3),iVar2);
            AlertSz((char *)szWork,0x10);
            if (iPanelActive == 2) goto RACE_Step2;
            if (iPanelActive == 3) goto RACE_Step3;
            if (iPanelActive == 4) goto RACE_Step4;
            if (iPanelActive == 5) break;
            if (iPanelActive != 6) goto RACE_Step1;
          }
          goto RACE_Step5;
        }
        goto RACE_Step4;
      }
      goto RACE_Step3;
    }
  } while( true );
}



// ======================================================================
// Function: RaceWizardDlg1
// Address: 10e0:03ac
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg1(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  PLAYER *pPVar3;
  POINT PVar4;
  POINT PVar5;
  POINT PVar6;
  short sVar7;
  BOOL BVar8;
  UINT UVar9;
  HWND HVar10;
  uint uVar11;
  char *pcVar12;
  HBRUSH HVar13;
  int iVar14;
  undefined2 unaff_SI;
  undefined2 *puVar15;
  undefined2 unaff_DI;
  PLAYER *pPVar16;
  undefined2 unaff_SS;
  ulong uVar17;
  LRESULT LVar18;
  long lVar19;
  ushort in_stack_0000ffba;
  undefined8 rcGBox;
  short cch;
  short j;
  undefined1 ps [4];
  short iCur;
  short iDir;
  RECT *szBuf;
  short bt;
  int pt;
  uint local_16;
  HDC hdc;
  HWND pt__18;
  short iPlrBmp;
  undefined8 rc;
  short i;
  
  if (message == WM_PAINT) {
    pt__18 = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)ps));
    for (j = 0x10f; j < 0x117; j = j + 1) {
      UVar9 = IsDlgButtonChecked(hwnd,j);
      if (UVar9 != 0) break;
    }
    if (j < 0x116) {
      hdc = (j + -0x10f) * 0xc0 + 0xda2;
    }
    else {
      hdc = (HDC)&vplr;
    }
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    DrawRaceAdvantagePoints(pt__18,(RECT *)&rc,(PLAYER *)hdc);
    HVar10 = GetDlgItem(hwnd,0x10f);
    GetWindowRect(HVar10,(RECT *)CONCAT22(unaff_SS,(RECT *)&rcGBox));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&rcGBox));
    HVar10 = GetDlgItem(hwnd,0x116);
    GetWindowRect(HVar10,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)((int)&rc + 4)));
    rcGBox._4_2_ = rc._4_2_;
    rcGBox._6_2_ = rc._6_2_;
    ExpandRc((RECT *)&rcGBox,dyArial8,dyArial8 >> 1);
    _Draw3dFrame();
    SelectObject(pt__18,rghfontArial8[1]);
    SetBkColor(pt__18,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    cch = CchGetString(idsPredefinedRaces,(char *)szWork);
    TextOut(pt__18,(int)rcGBox + 8,rcGBox._2_2_ - (dyArial8 >> 1),szWork,cch);
    HVar10 = GetDlgItem(hwnd,0x81a);
    GetWindowRect(HVar10,(RECT *)CONCAT22(unaff_SS,(RECT *)&rcGBox));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)((int)&rcGBox + 4)));
    pt = rcGBox._4_2_ + 0x20;
    local_16 = rcGBox._6_2_ - 0x20;
    iPlrBmp = vplr.wMdPlr >> 3 & 0x1f;
    if (0x1f < (uint)iPlrBmp) {
      iPlrBmp = 0;
    }
    SelectPalette(pt__18,vhpal,0);
    RealizePalette(pt__18);
    DibBlt(pt__18,pt,local_16,0x20,0x20,hdibRaces,(iPlrBmp & 7U) << 5,
                    (3 - (iPlrBmp >> 3)) * 0x20,0x20,0x20,0xcc0020);
    if (fRCWReadOnly == 0) {
      SetRect(rgrcBuildSpin,pt + 2,local_16 + 0x23,pt + 0x10,local_16 + 0x31);
      rgrcBuildSpin[1].left = rgrcBuildSpin[0].left;
      rgrcBuildSpin[1].top = rgrcBuildSpin[0].top;
      rgrcBuildSpin[1].right = rgrcBuildSpin[0].right;
      rgrcBuildSpin[1].bottom = rgrcBuildSpin[0].bottom;
      OffsetRect(rgrcBuildSpin + 1,0xe,0);
      for (i = 0; i < 2; i = i + 1) {
        if (i == 0) {
          uVar11 = 2;
        }
        else {
          uVar11 = 3;
        }
        DrawBtn(pt__18,(RECT *)rgrcBuildSpin + i,uVar11 | 0x20,0,(char *)0x0);
      }
    }
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)ps));
    HVar13 = 1;
    lVar19 = vplr.lSalt;
    goto LAB_10e0_1057;
  }
  if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc),hbrButtonFace);
    HVar13 = 1;
    lVar19 = vplr.lSalt;
    goto LAB_10e0_1057;
  }
  if (message == WM_CTLCOLOR) {
    for (i = 0x10f; i < 0x117; i = i + 1) {
      iPlrBmp = (short)lParam;
      HVar10 = GetDlgItem(hwnd,i);
      if (iPlrBmp == HVar10) break;
    }
    if (0x116 < i) {
      uVar17 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000ffba);
      if ((int)uVar17 != 6) goto LAB_10e0_1051;
    }
    SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    HVar13 = hbrButtonFace;
    lVar19 = vplr.lSalt;
    goto LAB_10e0_1057;
  }
  if (message == WM_INITDIALOG) {
    iPlrBmp = vplr.wMdPlr >> 3 & 0x1f;
    SetRCWTitle(hwnd,iPanelActive);
    SetDlgItemText(hwnd,0x10c,vplr.szName);
    SetDlgItemText(hwnd,0x81b,vplr.szNames);
    if (vplr.szName[0] == '\0') {
      GetDlgItemText(hwnd,0x10f,vplr.szName,0x10);
      SetDlgItemText(hwnd,0x10c,vplr.szName);
    }
    StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
    if ((((game.wCrap >> 3 & 1) == 0) || (idPlayer != 0)) ||
       (fRCWReadOnly == 0)) {
      for (i = 0; i < 7; i = i + 1) {
        local_16 = *(uint *)(i * 0xc0 + 0xda8) >> 3 & 0x1f;
        vplr.wMdPlr = vplr.wMdPlr & 0xff07 | local_16 << 3;
        sVar7 = __fmemcmp(&vplr,
                                  (void *)CONCAT22(0x1120,(void *)(i * 0xc0 + 0xda2)),0x80);
        if (sVar7 == 0) break;
      }
      vplr.wMdPlr = vplr.wMdPlr & 0xff07 | (iPlrBmp & 0x1fU) << 3;
    }
    else {
      i = 0;
    }
    CheckRadioButton(hwnd,0x10f,0x116,i + 0x10f);
    SendDlgItemMessage(hwnd,0x10c,0x415,0xf,0);
    SendDlgItemMessage(hwnd,0x81b,0x415,0xf,0);
    SendDlgItemMessage(hwnd,0x10d,0x415,0x10,0);
    pt__18 = GetDlgItem(hwnd,0x81a);
    for (i = 0x106; i < 0x10b; i = i + 1) {
      hdc = (HDC)PszGetCompressedString(i);
      SendMessage(pt__18,0x403,0,(LPARAM)CONCAT22(0x1120,hdc));
    }
    i = GetRaceStat((PLAYER *)&vplr,rsUseLeftover);
    SendMessage(pt__18,0x40e,i,0);
    if (vplr.lSalt != 0) {
      SetDlgItemText(hwnd,0x10d,&szRacePass);
    }
    if (fRCWReadOnly != 0) {
      for (i = 0x10c; i < 0x10e; i = i + 1) {
        HVar10 = GetDlgItem(hwnd,i);
        EnableWindow(HVar10,0);
      }
      HVar10 = GetDlgItem(hwnd,0x81b);
      EnableWindow(HVar10,0);
      for (i = 0x10f; i < 0x117; i = i + 1) {
        HVar10 = GetDlgItem(hwnd,i);
        EnableWindow(HVar10,0);
      }
      EnableWindow(pt__18,0);
    }
    HVar13 = 1;
    lVar19 = vplr.lSalt;
    goto LAB_10e0_1057;
  }
  if (message == WM_COMMAND) {
    if (wParam == 0x76) {
      WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x3ff);
      HVar13 = 1;
      lVar19 = vplr.lSalt;
      goto LAB_10e0_1057;
    }
    i = 0;
    while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
      i = i + 1;
    }
    if (i < 4) {
      if (wParam != 2) {
        iPlrBmp = vplr.wMdPlr >> 3 & 0x1f;
        for (pt__18 = 0x10f; (int)pt__18 < 0x117; pt__18 = pt__18 + 1) {
          UVar9 = IsDlgButtonChecked(hwnd,pt__18);
          if (UVar9 != 0) break;
        }
        if ((int)pt__18 < 0x116) {
          hdc = pt__18 - 0x10f;
          puVar15 = (undefined2 *)(hdc * 0xc0 + 0xda2);
          pPVar16 = (PLAYER *)&vplr;
          for (iVar14 = 0x60; iVar14 != 0; iVar14 = iVar14 + -1) {
            pPVar3 = pPVar16;
            pPVar16 = (PLAYER *)&pPVar16->cPlanet;
            puVar1 = puVar15;
            puVar15 = puVar15 + 1;
            uVar2 = *puVar1;
            pPVar3->iPlayer = (char)uVar2;
            pPVar3->cShDef = (char)((uint)uVar2 >> 8);
          }
        }
        GetDlgItemText(hwnd,0x10c,vplr.szName,0x20);
        GetDlgItemText(hwnd,0x81b,vplr.szNames,0x20);
        GetRaceStat((PLAYER *)&vplr,rsUseLeftover);
        GetDlgItemText(hwnd,0x10d,&szRacePass,0x10);
        HVar10 = GetDlgItem(hwnd,0x81a);
        LVar18 = SendMessage(HVar10,0x407,0,0);
        pt__18 = (HWND)LVar18;
        SetRaceStat((PLAYER *)&vplr,rsUseLeftover,pt__18);
        lVar19 = LSaltFromSz((char *)&szRacePass);
        vplr.wMdPlr = vplr.wMdPlr & 0xff07 | (iPlrBmp & 0x1fU) << 3;
        vplr.lSalt = lVar19;
      }
      StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
      EndDialog(hwnd,i);
      HVar13 = 1;
      lVar19 = vplr.lSalt;
      goto LAB_10e0_1057;
    }
    uVar17 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000ffba);
    if ((((int)uVar17 == 0) && (0x10e < wParam)) && (wParam < 0x117)) {
      _memset((void *)vplr.szName,0,0x20);
      GetDlgItemText(hwnd,0x10c,vplr.szName,0x20);
      _memset((void *)vplr.szNames,0,0x20);
      GetDlgItemText(hwnd,0x81b,vplr.szNames,0x20);
      GetDlgItemText(hwnd,wParam,(LPSTR)CONCAT22(unaff_SS,&stack0xffd0),0x20);
      for (i = 0; i < 7; i = i + 1) {
        pcVar12 = PszGetCompressedString(i + idsHumanoid);
        sVar7 = _strcmp((char *)vplr.szName,pcVar12);
        if (sVar7 == 0) break;
      }
      if ((i < 7) && (wParam < 0x116)) {
        _memset((void *)vplr.szName,0,0x20);
        CchGetString
                  (wParam + idsWarningReceivingPlanetMustHaveMassDriver2,
                   (char *)vplr.szName);
        SetDlgItemText(hwnd,0x10c,vplr.szName);
        _memset((void *)vplr.szNames,0,0x20);
        iDir = (short)PszPlayerName(0,1,1,0,0,(PLAYER *)&vplr);
        _strcpy((char *)vplr.szNames,(char *)iDir);
        SetDlgItemText(hwnd,0x81b,vplr.szNames);
      }
      if (wParam < 0x116) {
        iPlrBmp = (wParam - 0x10f) * 0xc0 + 0xda2;
      }
      else {
        iPlrBmp = (short)&vplr;
      }
      InvalidateAdvPtsRect(hwnd);
      i = GetRaceStat((PLAYER *)iPlrBmp,rsUseLeftover);
      HVar10 = GetDlgItem(hwnd,0x81a);
      SendMessage(HVar10,0x40e,i,0);
      HVar10 = GetDlgItem(hwnd,0x42f);
      EnableWindow(HVar10,(uint)(wParam != 0x115));
      iDir = *(uint *)(iPlrBmp + 6) >> 3 & 0x1f;
      vplr.wMdPlr = vplr.wMdPlr & 0xff07 | iDir << 3;
      HVar10 = GetDlgItem(hwnd,0x81a);
      GetWindowRect(HVar10,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
      ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)((int)&rc + 4)));
      rc._0_2_ = rc._4_2_ + 0x20;
      rc._2_2_ = rc._6_2_ + -0x20;
      rc._4_2_ = rc._4_2_ + 0x40;
      InvalidateRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc),1);
    }
  }
  else if ((message == WM_LBUTTONDOWN) || (message == WM_LBUTTONDBLCLK)) {
    pt__18 = (short)lParam;
    uVar17 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000ffba);
    iPlrBmp = (short)uVar17;
    if (fRCWReadOnly == 0) {
      PVar4.y = iPlrBmp;
      PVar4.x = pt__18;
      BVar8 = PtInRect(rgrcBuildSpin,PVar4);
      if (BVar8 == 0) {
        PVar5.y = iPlrBmp;
        PVar5.x = pt__18;
        BVar8 = PtInRect(rgrcBuildSpin + 1,PVar5);
        if (BVar8 == 0) goto LAB_10e0_1051;
      }
      PVar6.y = iPlrBmp;
      PVar6.x = pt__18;
      BVar8 = PtInRect(rgrcBuildSpin,PVar6);
      if (BVar8 == 0) {
        iDir = 1;
        bt = 0x23;
        szBuf = (RECT *)(rgrcBuildSpin + 1);
      }
      else {
        iDir = -1;
        bt = 0x22;
        szBuf = (RECT *)rgrcBuildSpin;
      }
      iCur = vplr.wMdPlr >> 3 & 0x1f;
      if (0x1f < (uint)iCur) {
        iCur = 0;
      }
      hdc = GetDC(hwnd);
      SelectPalette(hdc,vhpal,0);
      RealizePalette(hdc);
      InitBtnTrack((BTNT *)&stack0xffd4,hwnd,0,szBuf,bt,0x50,0,0,(char *)0x0);
      while( true ) {
        sVar7 = FTrackBtn((BTNT *)&stack0xffd4);
        if (sVar7 == 0) break;
        iCur = (iCur + 0x20 + iDir) % 0x20;
        DibBlt(hdc,rgrcBuildSpin[0].left + -2,
                        rgrcBuildSpin[0].top + -0x23,0x20,0x20,hdibRaces,
                        (iCur & 7U) << 5,(3 - (iCur >> 3)) * 0x20,0x20,0x20,0xcc0020);
      }
      vplr.wMdPlr = vplr.wMdPlr & 0xff07 | (iCur & 0x1fU) << 3;
      ReleaseDC(hwnd,hdc);
      HVar13 = 1;
      lVar19 = vplr.lSalt;
      goto LAB_10e0_1057;
    }
  }
LAB_10e0_1051:
  HVar13 = 0;
  lVar19 = vplr.lSalt;
LAB_10e0_1057:
  vplr.lSalt._2_2_ = (undefined2)((ulong)lVar19 >> 0x10);
  vplr.lSalt._0_2_ = (undefined2)lVar19;
  return HVar13;
}



// ======================================================================
// Function: RaceWizardDlg2
// Address: 10e0:1060
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg2(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  POINT pt_00;
  POINT pt_01;
  RECT *pRVar1;
  int iVar2;
  HWND HVar3;
  short sVar4;
  undefined2 unaff_SI;
  RECT *pRVar5;
  undefined2 unaff_DI;
  RECT *pRVar6;
  undefined2 unaff_SS;
  DWORD DVar7;
  ulong uVar8;
  LRESULT LVar9;
  ushort in_stack_0000ffce;
  undefined1 ps [22];
  short cch;
  short dxLabel;
  short dxMiddle;
  short dy;
  HDC pt;
  HDC hdc;
  RECT rc;
  short i;
  
  uVar8 = CONCAT22(unaff_SI,unaff_DI);
  if (message == WM_PAINT) {
    hdc = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)ps));
    viStore = -2;
    DrawRace2(hwnd,hdc,-1);
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)ps));
    sVar4 = 1;
  }
  else if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,&rc),hbrButtonFace);
    sVar4 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      for (i = 0x123; i < 0x126; i = i + 1) {
        hdc = (HDC)lParam;
        HVar3 = GetDlgItem(hwnd,i);
        if (hdc == HVar3) break;
      }
      if ((i < 0x126) || (uVar8 = __aFulshr(uVar8,in_stack_0000ffce), (int)uVar8 == 6)) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else if (message == WM_SETCURSOR) {
      GetCursorPos((POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffee));
      ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffee));
      pt_00.y = hdc;
      pt_00.x = pt;
      sVar4 = IrcRaceDlgHitTest(pt_00);
      if (-1 < sVar4) {
        setcursor(hcurHand);
        return 1;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        SetRCWTitle(hwnd,iPanelActive);
        viStore = -1;
        hdc = GetDC(hwnd);
        GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
        ps._0_2_ = SelectObject(hdc,rghfontArial8[1]);
        cch = CchGetString(idsTemperature,ps + 2);
        DVar7 = GetTextExtent(hdc,(LPCSTR)CONCAT22(unaff_SS,ps + 2),cch);
        dxLabel = (int)DVar7 + 10;
        DVar7 = GetTextExtent(hdc,(LPCSTR)0x11201331,5);
        dxMiddle = (rc.right - dxLabel) - ((int)DVar7 + 10);
        dy = (dyArial8 * 3) / 2;
        pt = dyArial8 * 3;
        SetRect((RECT *)CONCAT22(0x1120,vrgrcRCW),dxLabel,pt,dxLabel + dy,pt + dy);
        SetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + 1),dxLabel + dy + 6,pt,
                ((dxLabel + dxMiddle) - dy) + -6,pt + dy);
        SetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + 2),(dxLabel + dxMiddle) - dy,pt,
                dxLabel + dxMiddle,pt + dy);
        SetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + 3),dxLabel,pt + dy + 4,dy * 3 + dxLabel
                ,dy * 2 + pt + 4);
        SetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + 4),dxLabel + dxMiddle + dy * -3,
                pt + dy + 4,dxLabel + dxMiddle,dy * 2 + pt + 4);
        for (i = 0; i < 5; i = i + 1) {
          pRVar5 = vrgrcRCW + i;
          pRVar6 = vrgrcRCW + i + 5;
          pRVar6->left = pRVar5->left;
          pRVar6->top = pRVar5->top;
          pRVar6->right = pRVar5->right;
          pRVar6->bottom = pRVar5->bottom;
          OffsetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + i + 5),0,dy * 3);
          pRVar5 = vrgrcRCW + i;
          pRVar6 = vrgrcRCW + i + 10;
          pRVar6->left = pRVar5->left;
          pRVar6->top = pRVar5->top;
          pRVar6->right = pRVar5->right;
          pRVar6->bottom = pRVar5->bottom;
          OffsetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + i + 10),0,dy * 6);
        }
        for (i = 0; i < 3; i = i + 1) {
          HVar3 = GetDlgItem(hwnd,i + 0x123);
          SetWindowPos(HVar3,0,dy * 3 + dxLabel + 6,vrgrcRCW[i * 5 + 3].top,
                       dxMiddle + dy * -6 + -0xc,dy,4);
          CheckDlgButton(hwnd,i + 0x123,
                         (uint)(*(char *)((int)vplr.rgEnvVarMax + i) < '\0'));
        }
        cch = CchGetString(idsMaximumColonistGrowthRatePerYear,(char *)szWork);
        DVar7 = GetTextExtent(hdc,(LPCSTR)0x11201337,3);
        iVar2 = (int)DVar7;
        DVar7 = GetTextExtent(hdc,szWork,cch);
        (vrgrcRCW + 0xf)->left = dxLabel + (int)DVar7 + iVar2 + 4;
        vrgrcRCW[0xf].top = dy * 9 + pt + -3;
        vrgrcRCW[0xf].right = (vrgrcRCW + 0xf)->left + 0xf;
        vrgrcRCW[0xf].bottom = (dyArial8 >> 1) + vrgrcRCW[0xf].top + 3
        ;
        pRVar1 = vrgrcRCW;
        pRVar5 = vrgrcRCW + 0x10;
        pRVar6 = vrgrcRCW + 0xf;
        (vrgrcRCW + 0x10)->left = (vrgrcRCW + 0xf)->left;
        pRVar5->top = pRVar6->top;
        pRVar1[0x10].right = pRVar1[0xf].right;
        pRVar1[0x10].bottom = pRVar1[0xf].bottom;
        OffsetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + 0x10),0,
                   (vrgrcRCW[0xf].bottom - vrgrcRCW[0xf].top) + -1);
        crcRCW = 0x11;
        SelectObject(hdc,ps._0_2_);
        ReleaseDC(hwnd,hdc);
        if (fRCWReadOnly != 0) {
          for (i = 0x123; i < 0x126; i = i + 1) {
            HVar3 = GetDlgItem(hwnd,i);
            EnableWindow(HVar3,0);
          }
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
        return 1;
      }
      if (message == WM_COMMAND) {
        if (wParam == 0x76) {
          WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x41d);
          return 1;
        }
        i = 0;
        while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
          i = i + 1;
        }
        if (i < 4) {
          StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
          EndDialog(hwnd,i);
          return 1;
        }
        if ((0x122 < wParam) && (wParam < 0x126)) {
          HVar3 = GetDlgItem(hwnd,wParam);
          LVar9 = SendMessage(HVar3,0x400,0,0);
          i = (short)LVar9;
          hdc = wParam - 0x123;
          if (i == 1) {
            ((char *)rgbCur + 0x2ef)[wParam] = -1;
            ((char *)rgbCur + 0x2f5)[wParam] = -1;
            ((char *)rgbCur + 0x2f2)[wParam] = -1;
          }
          else {
            ((char *)rgbCur + 0x2f2)[wParam] = '\x14';
            ((char *)rgbCur + 0x2f5)[wParam] = 'P';
            ((char *)rgbCur + 0x2ef)[wParam] = '2';
          }
          DrawRace2(hwnd,0,1 << ((byte)hdc & 0x1f) | 0xff00);
        }
      }
      else if ((message == WM_LBUTTONDOWN) || (message == WM_LBUTTONDBLCLK)) {
        pt = (HDC)lParam;
        uVar8 = __aFulshr(uVar8,in_stack_0000ffce);
        hdc = (HDC)uVar8;
        pt_01.y = hdc;
        pt_01.x = pt;
        sVar4 = FTrackRaceDlg2(hwnd,pt_01,wParam);
        return sVar4;
      }
    }
    sVar4 = 0;
  }
  return sVar4;
}



// ======================================================================
// Function: DrawRace2
// Address: 10e0:179a
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10e01fce) */

void DrawRace2(HWND hwnd,HDC hdc,short iDraw)

{
  char *szText;
  short sVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  StringId ids;
  ushort unaff_DI;
  undefined2 unaff_SS;
  bool bVar5;
  DWORD DVar6;
  ulong uVar7;
  long lVar8;
  undefined2 uVar9;
  HDC HVar11;
  undefined2 uVar12;
  ulong uVar10;
  short cch;
  short iStore;
  char szT [100];
  uint l2;
  short cch__74;
  RECT rc;
  short bt1;
  short cch__62;
  short dx;
  char *psz;
  short iMod;
  short i;
  short xRLabel;
  short fCreatedDC;
  short bkMode;
  short iMin;
  short dy;
  char szT__42 [32];
  short iMax;
  short bt;
  short iPit;
  
  fCreatedDC = 0;
  if (fRCWReadOnly == 0) {
    bt1 = 0;
  }
  else {
    bt1 = 4;
  }
  if (hdc == 0) {
    fCreatedDC = 1;
    hdc = GetDC(hwnd);
  }
  GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
  DrawRaceAdvantagePoints(hdc,&rc,(PLAYER *)0x0);
  bkMode = SetBkMode(hdc,1);
  SelectObject(hdc,rghfontArial8[1]);
  xRLabel = (rc.right - vrgrcRCW[2].right) / 2 + vrgrcRCW[2].right;
  for (i = 0; i < 3; i = i + 1) {
    if ((1 << ((byte)i & 0x1f) & iDraw) != 0) {
      if (iDraw != -1) {
        SelectObject(hdc,hbrButtonFace);
        cch__74 = vrgrcRCW[i * 5 + 4].bottom;
        PatBlt(hdc,vrgrcRCW[2].right,vrgrcRCW[i * 5 + 2].top,
               rc.right - vrgrcRCW[2].right,cch__74 - vrgrcRCW[i * 5 + 2].top,
               0xf00021);
      }
      if (*(char *)((int)vplr.rgEnvVarMax + i) < '\0') {
        cch__62 = CchGetString(idsN2,szT__42);
        CtrTextOut(hdc,xRLabel,vrgrcRCW[i * 5 + 2].top + 1 + dyArial8,
                            szT__42,cch__62);
      }
      else {
        psz = PszCalcEnvVar(i,(int)*(char *)((int)vplr.rgEnvVarMin + i));
        CtrTextOut(hdc,xRLabel,vrgrcRCW[i * 5 + 2].top + 1,psz,0);
        cch__62 = CchGetString(idsTo2,szT__42);
        CtrTextOut(hdc,xRLabel,vrgrcRCW[i * 5 + 2].top + 1 + dyArial8,
                            szT__42,cch__62);
        psz = PszCalcEnvVar(i,(int)*(char *)((int)vplr.rgEnvVarMax + i));
        cch__74 = dyArial8 * 2;
        CtrTextOut(hdc,xRLabel,vrgrcRCW[i * 5 + 2].top + 1 + cch__74,psz,0);
      }
      if (iDraw == -1) {
        cch__74 = dyArial8 / 4;
        RightTextOut
                  (hdc,(vrgrcRCW + i * 5)->left + -4,
                   cch__74 + vrgrcRCW[i * 5].top,(char *)*(undefined2 *)(i * 2 + 0x47e),0,
                   0);
      }
    }
  }
  iPit = 0;
  iMod = 0;
  for (i = 0; i < 0xf; i = i + 1) {
    if (4 < iMod) {
      iMod = 0;
    }
    if (*(char *)((int)vplr.rgEnvVarMax + i / 5) < '\0') {
      bt = 4;
    }
    else {
      bt = 0;
    }
    if ((iMod == 0) || (iMod == 2)) {
      if ((iDraw & 0xfff0U) != 0) {
        if (iMod == 0) {
          uVar4 = 2;
        }
        else {
          uVar4 = 3;
        }
        DrawBtn(hdc,vrgrcRCW + i,uVar4 | bt | bt1,0,(char *)0x0);
      }
    }
    else if (iMod == 1) {
      if (((1 << ((byte)iPit & 0x1f) & iDraw) != 0) &&
         (PatBlt(hdc,(vrgrcRCW + i)->left,vrgrcRCW[i].top,
                 vrgrcRCW[i].right - (vrgrcRCW + i)->left,
                 vrgrcRCW[i].bottom - vrgrcRCW[i].top,0x42), bt == 0)) {
        iMin = (short)*(char *)((int)vplr.rgEnvVarMin + iPit);
        iMax = (short)*(char *)((int)vplr.rgEnvVarMax + iPit);
        dx = (vrgrcRCW[i].right - (vrgrcRCW + i)->left) + -2;
        dy = (vrgrcRCW[i].bottom - vrgrcRCW[i].top) + -2;
        SelectObject(hdc,(*((ushort (*) [2])rghbrPlanetAttr + iPit))[0]);
        HVar11 = hdc;
        sVar1 = MulDiv(iMin,dx,100);
        iVar2 = sVar1 + (vrgrcRCW + i)->left + 1;
        iVar3 = vrgrcRCW[i].top + 1;
        sVar1 = MulDiv(iMax - iMin,dx,100);
        PatBlt(HVar11,iVar2,iVar3,sVar1,dy,0xf00021);
      }
      iPit = iPit + 1;
    }
    else if ((iDraw & 0xfff0U) != 0) {
      if (iMod == 3) {
        szText = (char *)0x133b;
      }
      else {
        szText = (char *)0x1345;
      }
      DrawBtn(hdc,vrgrcRCW + i,bt | 8U | bt1,0,szText);
    }
    iMod = iMod + 1;
  }
  if ((iDraw & 8U) != 0) {
    if (iDraw == -1) {
      cch__74 = CchGetString(idsMaximumColonistGrowthRatePerYear,(char *)szWork);
      TextOut(hdc,vrgrcRCW->left,vrgrcRCW[0xf].top + 3,szWork,cch__74)
      ;
      DrawBtn(hdc,vrgrcRCW + 0xf,bt1 | 0xa0,0,(char *)0x0);
      DrawBtn(hdc,vrgrcRCW + 0x10,bt1 | 0xa1,0,(char *)0x0);
    }
    else {
      DVar6 = GetTextExtent(hdc,(LPCSTR)0x1120134f,3);
      dx = (short)DVar6;
      SelectObject(hdc,hbrButtonFace);
      PatBlt(hdc,((vrgrcRCW + 0xf)->left + -4) - dx,vrgrcRCW[0xf].top + 3,dx,
             dyArial8,0xf00021);
    }
    cch__74 = _wsprintf(szWork,(char *)CONCAT22(0x1120,PCTDPCTPCT),
                        (int)vplr.pctIdealGrowth);
    RightTextOut
              (hdc,(vrgrcRCW + 0xf)->left + -4,vrgrcRCW[0xf].top + 3,
               (char *)szWork,cch__74,0);
  }
  lVar8 = CONCAT22(cch__74,l2);
  if ((iDraw & 7U) != 0) {
    uVar7 = 1;
    for (i = 0; i < 3; i = i + 1) {
      if ((*(char *)((int)vplr.rgEnvVarMax + i) < '\0') ||
         ((int)*(char *)((int)vplr.rgEnvVarMax + i) -
          (int)*(char *)((int)vplr.rgEnvVarMin + i) == 100)) {
        uVar7 = __aFulmul(uVar7,100);
      }
      else if (i == 2) {
        uVar7 = __aFulmul(uVar7,(long)((int)vplr.rgEnvVarMax[2] -
                                              (int)vplr.rgEnvVarMin[2]));
      }
      else {
        l2 = 0;
        cch__74 = 0;
        for (iStore = (short)*(char *)((int)vplr.rgEnvVarMin + i);
            iStore <= *(char *)((int)vplr.rgEnvVarMax + i); iStore = iStore + 1) {
          if (iStore < 10) {
            bVar5 = CARRY2(l2,iStore);
            l2 = l2 + iStore;
            cch__74 = cch__74 + (iStore >> 0xf) + (uint)bVar5;
          }
          else if (iStore < 0x5a) {
            bVar5 = 0xfff5 < l2;
            l2 = l2 + 10;
            cch__74 = cch__74 + (uint)bVar5;
          }
          else {
            uVar4 = 100 - iStore;
            bVar5 = CARRY2(l2,uVar4);
            l2 = l2 + uVar4;
            cch__74 = cch__74 + ((int)uVar4 >> 0xf) + (uint)bVar5;
          }
        }
        uVar12 = 0;
        uVar9 = 9;
        uVar7 = __aFulmul(uVar7,CONCAT22(cch__74,l2));
        uVar7 = __aFldiv(uVar7,CONCAT22(uVar12,uVar9));
      }
    }
    if ((long)uVar7 < 1) {
      uVar7 = 1;
    }
    uVar10 = uVar7;
    lVar8 = __aFlshr(uVar7,unaff_DI);
    lVar8 = __aFldiv(lVar8 + 1000000,uVar10);
    cch__74 = (short)((ulong)lVar8 >> 0x10);
    l2 = (uint)lVar8;
    iStore = l2;
    if (uVar7 == 1000000) {
      iStore = 0;
    }
    if (iStore != viStore) {
      viStore = iStore;
      if (lVar8 == 1) {
        if (uVar7 == 1000000) {
          ids = idsPlanetsWillHabitableRace;
        }
        else {
          ids = idsVirtuallyPlanetsWillHabitableRace;
        }
        cch = CchGetString(ids,(char *)szWork);
      }
      else {
        CchGetString(idsCanExpect1DPlanetsWillHabitable,szT);
        cch = _wsprintf(szWork,(char *)CONCAT22(unaff_SS,szT),l2,cch__74);
      }
      rc.left = vrgrcRCW->left;
      rc.top = vrgrcRCW[0xf].top + dyArial8 + 8;
      rc.right = vrgrcRCW[0xf].right + 0x14;
      rc.bottom = dyArial8 * 3 + rc.top;
      SelectObject(hdc,hbrButtonFace);
      PatBlt(hdc,rc.left,rc.top,rc.right - rc.left,rc.bottom - rc.top,0xf00021);
      DRAWTEXT(hdc,szWork,cch,(RECT *)CONCAT22(unaff_SS,&rc),0x10);
      lVar8 = CONCAT22(cch__74,l2);
    }
  }
  cch__74 = (short)((ulong)lVar8 >> 0x10);
  l2 = (uint)lVar8;
  SetBkMode(hdc,bkMode);
  if (fCreatedDC != 0) {
    ReleaseDC(hwnd,hdc);
  }
  return;
}



// ======================================================================
// Function: IrcRaceDlgHitTest
// Address: 10e0:2164
// Segment: MEMORY_RACE
// ======================================================================


short IrcRaceDlgHitTest(POINT pt)

{
  BOOL BVar1;
  short i;
  
  if (fRCWReadOnly == 0) {
    i = 0;
    while ((i < crcRCW &&
           (BVar1 = PtInRect((RECT *)CONCAT22(0x1120,vrgrcRCW + i),pt), BVar1 == 0))) {
      i = i + 1;
    }
    if (i < crcRCW) {
      if ((iPanelActive == 4) &&
         (*(char *)((int)vplr.rgEnvVarMax + i / 5) < '\0')) {
        i = -1;
      }
    }
    else {
      i = -1;
    }
  }
  else {
    i = -1;
  }
  return i;
}



// ======================================================================
// Function: FTrackRaceDlg2
// Address: 10e0:2204
// Segment: MEMORY_RACE
// ======================================================================


short FTrackRaceDlg2(HWND hwnd,POINT pt,short kbd)

{
  char cVar1;
  char cVar2;
  short sVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  short sVar7;
  int iVar8;
  short dx;
  short dWidth;
  char *psz;
  short iMod;
  short irc;
  short i;
  char iMin;
  char iMax;
  short dShift;
  short bt;
  BTNT btnt;
  
  sVar3 = IrcRaceDlgHitTest(pt);
  if (sVar3 < 0) {
    sVar3 = 0;
  }
  else {
    iVar8 = sVar3 % 5;
    iVar4 = sVar3 / 5;
    if ((iVar8 == 1) && (sVar3 < 0xf)) {
      SetCapture(hwnd);
      setcursor(hcurCloseGrab);
      iVar8 = ((int)*(char *)((int)vplr.rgEnvVarMax + iVar4) -
              (int)*(char *)((int)vplr.rgEnvVarMin + iVar4)) / 2;
      while (sVar7 = FGetMouseMove(&pt), sVar7 != 0) {
        if (pt.x < (vrgrcRCW + sVar3)->left) {
          pt.x = (vrgrcRCW + sVar3)->left;
        }
        if (vrgrcRCW[sVar3].right < pt.x) {
          pt.x = vrgrcRCW[sVar3].right;
        }
        sVar7 = MulDiv(pt.x - (vrgrcRCW + sVar3)->left,100,
                       vrgrcRCW[sVar3].right - (vrgrcRCW + sVar3)->left);
        iVar5 = sVar7;
        if (100 - iVar8 <= sVar7) {
          iVar5 = 100 - iVar8;
        }
        iVar6 = iVar8;
        if ((iVar8 <= iVar5) && (iVar6 = sVar7, 100 - iVar8 <= sVar7)) {
          iVar6 = 100 - iVar8;
        }
        if ((int)*(char *)((int)vplr.rgEnvVarMax + iVar4) != iVar6 + iVar8) {
          *(char *)((int)vplr.rgEnvVarMin + iVar4) = (char)iVar6 - (char)iVar8;
          *(char *)((int)vplr.rgEnvVarMax + iVar4) = (char)iVar6 + (char)iVar8;
          *(char *)((int)vplr.rgEnvVar + iVar4) =
               *(char *)((int)vplr.rgEnvVarMin + iVar4) +
               (char)(((int)*(char *)((int)vplr.rgEnvVarMax + iVar4) -
                      (int)*(char *)((int)vplr.rgEnvVarMin + iVar4)) / 2);
          DrawRace2(hwnd,0,1 << ((byte)iVar4 & 0x1f));
        }
      }
      ReleaseCapture();
      sVar3 = 1;
    }
    else {
      dWidth = 0;
      dShift = 0;
      psz = (char *)0x0;
      if (sVar3 == 0xf) {
        dShift = 1;
        bt = 0xa0;
      }
      else if (sVar3 == 0x10) {
        dShift = -1;
        bt = 0xa1;
      }
      else if (iVar8 == 0) {
        dShift = -1;
        bt = 2;
      }
      else if (iVar8 == 2) {
        dShift = 1;
        bt = 3;
      }
      else if (iVar8 == 3) {
        dWidth = 1;
        bt = 8;
        psz = vrgszRCWWidth[0];
      }
      else {
        dWidth = -1;
        bt = 8;
        psz = pcRam11201306;
      }
      InitBtnTrack(&btnt,hwnd,0,vrgrcRCW + sVar3,bt,0x50,0,0,psz);
      if ((kbd & 4U) != 0) {
        dWidth = dWidth * 10;
        dShift = dShift * 10;
      }
      while (sVar7 = FTrackBtn(&btnt), sVar7 != 0) {
        cVar1 = (char)dShift;
        if ((sVar3 == 0xf) || (sVar3 == 0x10)) {
          cVar1 = vplr.pctIdealGrowth + cVar1;
          cVar2 = cVar1;
          if (cVar1 < '\x01') {
            cVar2 = '\x01';
          }
          if (cVar2 < '\x15') {
            if (cVar1 < '\x01') {
              cVar1 = '\x01';
            }
          }
          else {
            cVar1 = '\x14';
          }
          if (cVar1 != vplr.pctIdealGrowth) {
            vplr.pctIdealGrowth = cVar1;
            DrawRace2(hwnd,btnt.hdc,8);
          }
        }
        else {
          iMin = *(char *)((int)vplr.rgEnvVarMin + iVar4) - ((char)dWidth - cVar1);
          iMax = *(char *)((int)vplr.rgEnvVarMax + iVar4) + (char)dWidth + cVar1;
          if ('d' < iMax) {
            iMin = iMin - (iMax + -100);
            iMax = 'd';
          }
          if (iMin < '\0') {
            if ((int)iMax - (int)iMin < 0x65) {
              iMax = iMax - iMin;
            }
            else {
              iMax = 'd';
            }
            iMin = '\0';
          }
          if ((int)iMax - (int)iMin < 0x14) {
            cVar1 = (char)(0x14 - ((int)iMax - (int)iMin) >> 1);
            iMin = iMin - cVar1;
            iMax = iMax + cVar1;
          }
          if ((*(char *)((int)vplr.rgEnvVarMin + iVar4) != iMin) ||
             (*(char *)((int)vplr.rgEnvVarMax + iVar4) != iMax)) {
            *(char *)((int)vplr.rgEnvVarMin + iVar4) = iMin;
            *(char *)((int)vplr.rgEnvVarMax + iVar4) = iMax;
            *(char *)((int)vplr.rgEnvVar + iVar4) =
                 *(char *)((int)vplr.rgEnvVarMin + iVar4) +
                 (char)(((int)*(char *)((int)vplr.rgEnvVarMax + iVar4) -
                        (int)*(char *)((int)vplr.rgEnvVarMin + iVar4)) / 2);
            DrawRace2(hwnd,btnt.hdc,1 << ((byte)iVar4 & 0x1f));
          }
        }
      }
      if (sVar3 < 0xf) {
        *(char *)((int)vplr.rgEnvVar + iVar4) =
             *(char *)((int)vplr.rgEnvVarMin + iVar4) +
             (char)(((int)*(char *)((int)vplr.rgEnvVarMax + iVar4) -
                    (int)*(char *)((int)vplr.rgEnvVarMin + iVar4)) / 2);
      }
      sVar3 = 1;
    }
  }
  return sVar3;
}



// ======================================================================
// Function: RaceWizardDlg3
// Address: 10e0:2792
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg3(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  POINT pt_00;
  POINT pt_01;
  WPARAM WVar1;
  HWND HVar2;
  short sVar3;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar4;
  LRESULT LVar5;
  UINT UVar6;
  ushort in_stack_0000ffd0;
  HDC pt;
  HDC hdc;
  RECT rc;
  short i;
  
  uVar4 = CONCAT22(unaff_SI,unaff_DI);
  if (message == WM_PAINT) {
    hdc = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)&stack0xffd0));
    DrawRace3(hwnd,hdc,-1);
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,(PAINTSTRUCT *)&stack0xffd0));
    sVar3 = 1;
  }
  else if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,&rc),hbrButtonFace);
    sVar3 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      hdc = (HDC)lParam;
      HVar2 = GetDlgItem(hwnd,0x123);
      if ((hdc == HVar2) || (uVar4 = __aFulshr(uVar4,in_stack_0000ffd0), (int)uVar4 == 6)) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else if (message == WM_SETCURSOR) {
      GetCursorPos((POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffee));
      ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffee));
      pt_00.y = hdc;
      pt_00.x = pt;
      sVar3 = IrcRaceDlgHitTest(pt_00);
      if (-1 < sVar3) {
        setcursor(hcurHand);
        return 1;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        SetRCWTitle(hwnd,iPanelActive);
        HVar2 = GetDlgItem(hwnd,0x123);
        UVar6 = 0x401;
        WVar1 = GetRaceGrbit((PLAYER *)&vplr,ibitRaceCheapFact);
        SendMessage(HVar2,UVar6,WVar1,0);
        if ((fRCWReadOnly != 0) ||
           (sVar3 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv), sVar3 == raMacintosh)) {
          HVar2 = GetDlgItem(hwnd,0x123);
          EnableWindow(HVar2,0);
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
        return 1;
      }
      if (message == WM_COMMAND) {
        if (wParam == 0x76) {
          WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x420);
          return 1;
        }
        i = 0;
        while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
          i = i + 1;
        }
        if (i < 4) {
          StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
          EndDialog(hwnd,i);
          return 1;
        }
        if (wParam == 0x123) {
          HVar2 = GetDlgItem(hwnd,0x123);
          LVar5 = SendMessage(HVar2,0x400,0,0);
          i = (short)LVar5;
          SetRaceGrbit((PLAYER *)&vplr,ibitRaceCheapFact,i);
          DrawRace3(hwnd,0,99);
        }
      }
      else if ((message == WM_LBUTTONDOWN) || (message == WM_LBUTTONDBLCLK)) {
        pt = (HDC)lParam;
        uVar4 = __aFulshr(uVar4,in_stack_0000ffd0);
        hdc = (HDC)uVar4;
        pt_01.y = hdc;
        pt_01.x = pt;
        sVar3 = FTrackRaceDlg3(hwnd,pt_01,wParam);
        return sVar3;
      }
    }
    sVar3 = 0;
  }
  return sVar3;
}



// ======================================================================
// Function: DrawRace3
// Address: 10e0:2aa4
// Segment: MEMORY_RACE
// ======================================================================


void DrawRace3(HWND hwnd,HDC hdc,short iDraw)

{
  short sVar1;
  HWND HVar2;
  RECT *pRVar3;
  RECT *pRVar4;
  undefined2 unaff_SS;
  DWORD DVar5;
  RECT rc;
  short cch;
  short dx;
  short dxDig;
  short irc;
  short i;
  short dxkT;
  short fCreatedDC;
  short bkMode;
  COLORREF crBkSav;
  short ids;
  short bt;
  short yTop;
  short fMacintosh;
  short idsT;
  short dxItem;
  
  fCreatedDC = 0;
  if (fRCWReadOnly == 0) {
    bt = 0;
  }
  else {
    bt = 4;
  }
  sVar1 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv);
  fMacintosh = (short)(sVar1 == raMacintosh);
  if (hdc == 0) {
    fCreatedDC = 1;
    hdc = GetDC(hwnd);
  }
  GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
  DrawRaceAdvantagePoints(hdc,&rc,(PLAYER *)0x0);
  bkMode = SetBkMode(hdc,2);
  crBkSav = SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace)
                      );
  SetTextColor(hdc,CONCAT22(crWindowText._2_2_,(undefined2)crWindowText));
  SelectObject(hdc,rghfontArial8[1]);
  yTop = dyArial8 * 3 + 6;
  DVar5 = GetTextExtent(hdc,(LPCSTR)0x11201353,1);
  dxDig = (short)DVar5;
  DVar5 = GetTextExtent(hdc,(LPCSTR)0x11201355,2);
  dxkT = (short)DVar5;
  ids = 0xf6;
  irc = 0;
  for (i = 0; i < 7; i = i + 1) {
    if ((i == 1) && (fMacintosh != 0)) {
      SetTextColor(hdc,CONCAT22(crButtonShadow._2_2_,(undefined2)crButtonShadow)
                  );
      bt = 4;
    }
    if (i == 4) {
      if (iDraw == -1) {
        HVar2 = GetDlgItem(hwnd,0x123);
        SetWindowPos(HVar2,0,6,yTop,rc.right + -0xc,(dyArial8 * 3) / 2,4);
      }
      yTop = yTop + (dyArial8 * 5) / 2;
    }
    if ((fMacintosh == 0) || (ids != 0xf6)) {
      idsT = ids;
    }
    else {
      idsT = 0x104;
    }
    ids = ids + 1;
    cch = CchGetString(idsT,(char *)szWork);
    if (iDraw == -1) {
      TextOut(hdc,6,yTop,szWork,cch);
    }
    DVar5 = GetTextExtent(hdc,szWork,cch);
    dx = (int)DVar5 + 6;
    sVar1 = _abs((int)((char *)rgRW3Width)[i]);
    dxItem = sVar1 * dxDig;
    sVar1 = GetRaceStat((PLAYER *)&vplr,(int)((char *)rgRW3IStat)[i]);
    _wsprintf(szWork,(char *)CONCAT22(0x1120,PCTD),sVar1);
    if ((((char *)rgRW3Width)[i] < '\0') && ((0 < i || (fMacintosh == 0)))) {
      dxItem = dxItem + dxkT;
      if (i == 0) {
        _strcat((char *)szWork,(char *)0x1358);
      }
      else {
        _strcat((char *)szWork,(char *)0x135b);
      }
    }
    dx = dx + dxItem;
    if ((iDraw == -1) || (iDraw == i)) {
      RightTextOut(hdc,dx,yTop,(char *)szWork,0,dxItem);
    }
    (vrgrcRCW + irc)->left = dx + 4;
    vrgrcRCW[irc].top = yTop + -3;
    vrgrcRCW[irc].right = (vrgrcRCW + irc)->left + 0xf;
    vrgrcRCW[irc].bottom = (dyArial8 >> 1) + vrgrcRCW[irc].top + 3;
    pRVar3 = vrgrcRCW + irc;
    pRVar4 = vrgrcRCW + irc + 1;
    pRVar4->left = pRVar3->left;
    pRVar4->top = pRVar3->top;
    pRVar4->right = pRVar3->right;
    pRVar4->bottom = pRVar3->bottom;
    OffsetRect((RECT *)CONCAT22(0x1120,vrgrcRCW + irc + 1),0,
               (vrgrcRCW[irc].bottom - vrgrcRCW[irc].top) + -1);
    if (iDraw == -1) {
      DrawBtn(hdc,vrgrcRCW + irc,bt | 0xa0,0,(char *)0x0);
      DrawBtn(hdc,vrgrcRCW + irc + 1,bt | 0xa1,0,(char *)0x0);
      if ((fMacintosh == 0) || (ids != 0xf7)) {
        idsT = ids;
      }
      else {
        idsT = 0x105;
      }
      cch = CchGetString(idsT,(char *)szWork);
      TextOut(hdc,vrgrcRCW[irc].right + 4,yTop,szWork,cch);
    }
    ids = ids + 1;
    irc = irc + 2;
    yTop = yTop + (((char *)rgRW3Spacing)[i] * dyArial8) / 2;
  }
  if (fMacintosh == 0) {
    crcRCW = irc;
  }
  else {
    crcRCW = 2;
  }
  SetBkColor(hdc,crBkSav);
  SetBkMode(hdc,bkMode);
  if (fCreatedDC != 0) {
    ReleaseDC(hwnd,hdc);
  }
  return;
}



// ======================================================================
// Function: FTrackRaceDlg3
// Address: 10e0:2fb8
// Segment: MEMORY_RACE
// ======================================================================


short FTrackRaceDlg3(HWND hwnd,POINT pt,short kbd)

{
  uint uVar1;
  int iDraw;
  short sVar2;
  short sVar3;
  short iStat;
  short iMod;
  short irc;
  short i;
  short dShift;
  short bt;
  BTNT btnt;
  
  uVar1 = IrcRaceDlgHitTest(pt);
  if ((int)uVar1 < 0) {
    sVar2 = 0;
  }
  else {
    iDraw = (int)uVar1 >> 1;
    if ((uVar1 & 1) == 0) {
      dShift = 1;
      bt = 0xa0;
    }
    else {
      dShift = -1;
      bt = 0xa1;
    }
    InitBtnTrack(&btnt,hwnd,0,vrgrcRCW + uVar1,bt,0x50,0,0,(char *)0x0);
    if ((kbd & 4U) != 0) {
      dShift = dShift * 3;
    }
    while (sVar2 = FTrackBtn(&btnt), sVar2 != 0) {
      sVar2 = GetRaceStat((PLAYER *)&vplr,(int)((char *)rgRW3IStat)[iDraw]);
      sVar3 = SetRaceStat((PLAYER *)&vplr,(int)((char *)rgRW3IStat)[iDraw],sVar2 + dShift)
      ;
      if (sVar3 != sVar2) {
        DrawRace3(hwnd,btnt.hdc,iDraw);
      }
    }
    sVar2 = 1;
  }
  return sVar2;
}



// ======================================================================
// Function: GetRaceStat
// Address: 10e0:30d2
// Segment: MEMORY_RACE
// ======================================================================


short GetRaceStat(PLAYER *pplr,RaceStat iStat)

{
  return (int)pplr->rgAttr[iStat];
}



// ======================================================================
// Function: SetRaceStat
// Address: 10e0:3114
// Segment: MEMORY_RACE
// ======================================================================


short SetRaceStat(PLAYER *pplr,RaceStat iStat,short iVal)

{
  if (iVal < ((char *)rgRaceStatMin)[iStat]) {
    iVal = (short)((char *)rgRaceStatMin)[iStat];
  }
  if (((char *)rgRaceStatMax)[iStat] < iVal) {
    iVal = (short)((char *)rgRaceStatMax)[iStat];
  }
  pplr->rgAttr[iStat] = (char)iVal;
  return iVal;
}



// ======================================================================
// Function: GetRaceGrbit
// Address: 10e0:3176
// Segment: MEMORY_RACE
// ======================================================================


short GetRaceGrbit(PLAYER *pplr,RaceGrbit ibit)

{
  short sVar1;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  long lVar2;
  ushort in_stack_0000fffc;
  
  lVar2 = __aFlshl(CONCAT22(unaff_SI,unaff_DI),in_stack_0000fffc);
  if ((((uint)lVar2 & (uint)pplr->grbitAttr) == 0) &&
     (((uint)((ulong)lVar2 >> 0x10) & *(uint *)((int)&pplr->grbitAttr + 2)) == 0)) {
    sVar1 = 0;
  }
  else {
    sVar1 = 1;
  }
  return sVar1;
}



// ======================================================================
// Function: SetRaceGrbit
// Address: 10e0:31b8
// Segment: MEMORY_RACE
// ======================================================================


void SetRaceGrbit(PLAYER *pplr,RaceGrbit ibit,short fSet)

{
  uint *puVar1;
  uint uVar2;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  long lVar3;
  ushort in_stack_0000fff8;
  
  lVar3 = __aFlshl(CONCAT22(unaff_SI,unaff_DI),in_stack_0000fff8);
  uVar2 = (uint)((ulong)lVar3 >> 0x10);
  if (fSet == 0) {
    *(uint *)&pplr->grbitAttr = (uint)pplr->grbitAttr & ~(uint)lVar3;
    puVar1 = (uint *)((int)&pplr->grbitAttr + 2);
    *puVar1 = *puVar1 & ~uVar2;
  }
  else {
    *(uint *)&pplr->grbitAttr = (uint)pplr->grbitAttr | (uint)lVar3;
    puVar1 = (uint *)((int)&pplr->grbitAttr + 2);
    *puVar1 = *puVar1 | uVar2;
  }
  return;
}



// ======================================================================
// Function: RaceWizardDlg4
// Address: 10e0:320a
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg4(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  HWND HVar1;
  short sVar2;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar3;
  short sVar4;
  short sVar5;
  ushort in_stack_0000fd6c;
  int local_292;
  short cch;
  PAINTSTRUCT ps;
  short ids;
  char szT [600];
  HDC hdc;
  undefined8 rc;
  short i;
  
  uVar3 = CONCAT22(unaff_SI,unaff_DI);
  if (message == WM_PAINT) {
    hdc = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    DrawRaceAdvantagePoints(hdc,(RECT *)&rc,(PLAYER *)0x0);
    SelectObject(hdc,rghfontArial8[1]);
    SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    HVar1 = GetDlgItem(hwnd,0x10f);
    GetWindowRect(HVar1,(RECT *)CONCAT22(unaff_SS,(RECT *)&stack0xfd6c));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xfd6c));
    HVar1 = GetDlgItem(hwnd,0x118);
    GetWindowRect(HVar1,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)((int)&rc + 4)));
    ExpandRc((RECT *)&stack0xfd6c,dyArial8 + 2,dyArial8 >> 1);
    _Draw3dFrame();
    sVar2 = CchGetString(idsPrimaryRacialTrait,(char *)szWork);
    TextOut(hdc,in_stack_0000fd6c + 8,(local_292 + -4) - (dyArial8 >> 1),szWork,
            sVar2);
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    rc._2_2_ = rc._6_2_ + 0xc;
    rc._0_2_ = (int)rc + 0xc;
    rc._4_2_ = rc._4_2_ + -0xc;
    HVar1 = GetDlgItem(hwnd,0x76);
    GetWindowRect(HVar1,(RECT *)CONCAT22(unaff_SS,(RECT *)&stack0xfd6c));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xfd6c));
    rc._6_2_ = local_292 + -10;
    _Draw3dFrame();
    sVar2 = CchGetString(idsDescriptionTrait,(char *)szWork);
    TextOut(hdc,(int)rc + 8,rc._2_2_ - (dyArial8 >> 1),szWork,sVar2);
    sVar2 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv);
    ids = sVar2 * 3 + 0x114;
    cch = 0;
    for (i = 0; i < 3; i = i + 1) {
      sVar2 = CchGetString(ids,szT + cch);
      cch = cch + sVar2;
      ids = ids + 1;
    }
    ExpandRc((RECT *)&rc,-2 - dyArial8,-(dyArial8 >> 1));
    rc._2_2_ = rc._2_2_ + 4;
    DRAWTEXT(hdc,(LPCSTR)CONCAT22(unaff_SS,szT),cch,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc),0x10);
    rcCargo.left = (int)rc;
    rcCargo.top = rc._2_2_;
    rcCargo.right = rc._4_2_;
    rcCargo.bottom = rc._6_2_;
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    sVar2 = 1;
  }
  else if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc),hbrButtonFace);
    sVar2 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      for (i = 0x10f; i < 0x119; i = i + 1) {
        hdc = (HDC)lParam;
        HVar1 = GetDlgItem(hwnd,i);
        if (hdc == HVar1) break;
      }
      if ((i < 0x119) || (uVar3 = __aFulshr(uVar3,in_stack_0000fd6c), (int)uVar3 == 6)) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        SetRCWTitle(hwnd,iPanelActive);
        sVar5 = 0x10f;
        sVar4 = 0x118;
        HVar1 = hwnd;
        sVar2 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv);
        CheckRadioButton(HVar1,sVar5,sVar4,sVar2 + 0x10f);
        if (fRCWReadOnly != 0) {
          for (i = 0x10f; i < 0x119; i = i + 1) {
            HVar1 = GetDlgItem(hwnd,i);
            EnableWindow(HVar1,0);
          }
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
        return 1;
      }
      if (message == WM_COMMAND) {
        if (wParam == 0x76) {
          WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x408);
          return 1;
        }
        i = 0;
        while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
          i = i + 1;
        }
        if (i < 4) {
          StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
          EndDialog(hwnd,i);
          return 1;
        }
        uVar3 = __aFulshr(uVar3,in_stack_0000fd6c);
        if ((((int)uVar3 == 0) && (0x10e < wParam)) && (wParam < 0x119)) {
          i = wParam - 0x10f;
          SetRaceStat((PLAYER *)&vplr,rsMajorAdv,i);
          sVar2 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv);
          if (sVar2 == raMacintosh) {
            SetRaceStat((PLAYER *)&vplr,rsFactProd,10);
            SetRaceStat((PLAYER *)&vplr,rsFactBuild,10);
            SetRaceStat((PLAYER *)&vplr,rsFactOperate,10);
            SetRaceStat((PLAYER *)&vplr,rsMineProd,10);
            SetRaceStat((PLAYER *)&vplr,rsMineBuild,5);
            SetRaceStat((PLAYER *)&vplr,rsMineOperate,10);
            SetRaceGrbit((PLAYER *)&vplr,ibitRaceCheapFact,0);
          }
          InvalidateAdvPtsRect(hwnd);
          InvalidateRect(hwnd,&rcCargo,0);
        }
      }
    }
    sVar2 = 0;
  }
  return sVar2;
}



// ======================================================================
// Function: RaceWizardDlg5
// Address: 10e0:378e
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg5(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  char *pcVar1;
  WPARAM WVar2;
  HWND HVar3;
  short sVar4;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar5;
  LRESULT LVar6;
  UINT UVar7;
  ushort in_stack_0000ffc6;
  int local_38;
  POINT local_36;
  short cch;
  PAINTSTRUCT ps;
  HWND hwndCtl;
  RECT rc;
  short i;
  
  uVar5 = CONCAT22(unaff_SI,unaff_DI);
  if (message == WM_PAINT) {
    hwndCtl = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
    DrawRaceAdvantagePoints(hwndCtl,&rc,(PLAYER *)0x0);
    SelectObject(hwndCtl,rghfontArial8[1]);
    SetBkColor(hwndCtl,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    HVar3 = GetDlgItem(hwnd,0x130);
    GetWindowRect(HVar3,(RECT *)CONCAT22(unaff_SS,(RECT *)&stack0xffc6));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,&local_36));
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
    rc.top = local_36.y + 0xc;
    rc.left = rc.left + 0xc;
    rc.right = rc.right + -0xc;
    HVar3 = GetDlgItem(hwnd,0x76);
    GetWindowRect(HVar3,(RECT *)CONCAT22(unaff_SS,(RECT *)&stack0xffc6));
    ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffc6));
    rc.bottom = local_38 + -0xc;
    _Draw3dFrame();
    rcCargo.left = rc.left;
    rcCargo.right = rc.right;
    rcCargo.bottom = rc.bottom;
    rcCargo.top = rc.top - (dyArial8 >> 1);
    cch = CchGetString
                    (cColDrop + idsImprovedFuelEfficiency,(char *)szWork);
    TextOut(hwndCtl,rc.left + 8,rc.top - (dyArial8 >> 1),szWork,cch);
    cch = CchGetString
                    (cColDrop + idsGivesFuelMizerGalaxyScoopEnginesIncreases,
                     (char *)szWork);
    ExpandRc(&rc,-2 - dyArial8,-(dyArial8 >> 1));
    rc.top = rc.top + 4;
    DRAWTEXT(hwndCtl,szWork,cch,(RECT *)CONCAT22(unaff_SS,&rc),0x10);
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    sVar4 = 1;
  }
  else if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,&rc),hbrButtonFace);
    sVar4 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      for (i = 0x123; i < 0x131; i = i + 1) {
        hwndCtl = (HWND)lParam;
        HVar3 = GetDlgItem(hwnd,i);
        if (hwndCtl == HVar3) break;
      }
      if ((i < 0x131) || (uVar5 = __aFulshr(uVar5,in_stack_0000ffc6), (int)uVar5 == 6)) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        SetRCWTitle(hwnd,iPanelActive);
        cColDrop = 0;
        for (i = 0; i < 0xe; i = i + 1) {
          HVar3 = GetDlgItem(hwnd,i + 0x123);
          hwndCtl = HVar3;
          pcVar1 = PszGetCompressedString(i + idsImprovedFuelEfficiency);
          SetWindowText(HVar3,(LPCSTR)CONCAT22(0x1120,pcVar1));
          UVar7 = 0x401;
          HVar3 = hwndCtl;
          WVar2 = GetRaceGrbit((PLAYER *)&vplr,i);
          SendMessage(HVar3,UVar7,WVar2,0);
          if (fRCWReadOnly != 0) {
            EnableWindow(hwndCtl,0);
          }
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
        return 1;
      }
      if (message == WM_COMMAND) {
        if (wParam == 0x76) {
          WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x411);
          return 1;
        }
        i = 0;
        while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
          i = i + 1;
        }
        if (i < 4) {
          StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
          EndDialog(hwnd,i);
          return 1;
        }
        if ((0x122 < wParam) && (wParam < 0x131)) {
          HVar3 = GetDlgItem(hwnd,wParam);
          LVar6 = SendMessage(HVar3,0x400,0,0);
          i = (short)LVar6;
          cColDrop = wParam - 0x123;
          SetRaceGrbit((PLAYER *)&vplr,cColDrop,i);
          InvalidateAdvPtsRect(hwnd);
          InvalidateRect(hwnd,&rcCargo,0);
        }
      }
    }
    sVar4 = 0;
  }
  return sVar4;
}



// ======================================================================
// Function: RaceWizardDlg6
// Address: 10e0:3bae
// Segment: MEMORY_RACE
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RaceWizardDlg6(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  int iVar1;
  int iVar2;
  char *pcVar3;
  WPARAM WVar4;
  HWND HVar5;
  short sVar6;
  short sVar7;
  HBRUSH HVar8;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar9;
  LRESULT LVar10;
  UINT UVar11;
  ushort in_stack_0000ffc6;
  int local_38;
  short cch;
  PAINTSTRUCT ps;
  HDC hdc;
  undefined8 rc;
  short i;
  
  uVar9 = CONCAT22(unaff_SI,unaff_DI);
  if (message == WM_PAINT) {
    hdc = BeginPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    DrawRaceAdvantagePoints(hdc,(RECT *)&rc,(PLAYER *)0x0);
    SelectObject(hdc,rghfontArial8[1]);
    SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    for (i = 0; i < 6; i = i + 1) {
      HVar5 = GetDlgItem(hwnd,i * 3 + 0x10f);
      GetWindowRect(HVar5,(RECT *)CONCAT22(unaff_SS,(RECT *)&stack0xffc6));
      ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)&stack0xffc6));
      HVar5 = GetDlgItem(hwnd,i * 3 + 0x111);
      GetWindowRect(HVar5,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
      ScreenToClient(hwnd,(POINT *)CONCAT22(unaff_SS,(POINT *)((int)&rc + 4)));
      ExpandRc((RECT *)&stack0xffc6,dyArial8,dyArial8 >> 1);
      _Draw3dFrame();
      sVar6 = CchGetString(i + idsEnergy,(char *)szWork);
      sVar7 = CchGetString(idsResearch,(char *)szWork + sVar6);
      TextOut(hdc,in_stack_0000ffc6 + 8,local_38 - (dyArial8 >> 1),szWork,
              sVar6 + sVar7);
    }
    EndPaint(hwnd,(PAINTSTRUCT *)CONCAT22(unaff_SS,&ps));
    return 1;
  }
  if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc));
    FillRect(wParam,(RECT *)CONCAT22(unaff_SS,(RECT *)&rc),hbrButtonFace);
    return 1;
  }
  if (message == WM_CTLCOLOR) {
    for (i = 0x10f; i < 0x121; i = i + 1) {
      hdc = (HDC)lParam;
      HVar5 = GetDlgItem(hwnd,i);
      if (hdc == HVar5) break;
    }
    if (0x120 < i) {
      hdc = (HDC)lParam;
      HVar5 = GetDlgItem(hwnd,0x123);
      if ((hdc != HVar5) && (uVar9 = __aFulshr(uVar9,in_stack_0000ffc6), (int)uVar9 != 6))
      goto LAB_10e0_409f;
    }
    SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    HVar8 = hbrButtonFace;
  }
  else {
    if (message == WM_INITDIALOG) {
      SetRCWTitle(hwnd,iPanelActive);
      for (i = 0; i < 6; i = i + 1) {
        iVar1 = i * 3 + 0x10f;
        iVar2 = i * 3 + 0x111;
        HVar5 = hwnd;
        hdc = GetRaceStat((PLAYER *)&vplr,i + rsTechBonus1);
        CheckRadioButton(HVar5,iVar1,iVar2,i * 3 + 0x10f + hdc);
      }
      if (fRCWReadOnly != 0) {
        for (i = 0x10f; i < 0x121; i = i + 1) {
          HVar5 = GetDlgItem(hwnd,i);
          EnableWindow(HVar5,0);
        }
      }
      sVar6 = GetRaceStat((PLAYER *)&vplr,rsMajorAdv);
      iVar1 = (sVar6 == raNone) + 3;
      pcVar3 = PszGetCompressedString(idsCosts75ExtraResearchFieldsStartTech);
      _wsprintf(szWork,(char *)CONCAT22(0x1120,pcVar3),iVar1);
      HVar5 = GetDlgItem(hwnd,0x123);
      SetWindowText(HVar5,szWork);
      HVar5 = GetDlgItem(hwnd,0x123);
      UVar11 = 0x401;
      WVar4 = GetRaceGrbit((PLAYER *)&vplr,ibitRaceTech3);
      SendMessage(HVar5,UVar11,WVar4,0);
      if (fRCWReadOnly != 0) {
        HVar5 = GetDlgItem(hwnd,0x123);
        EnableWindow(HVar5,0);
      }
      StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,1);
      return 1;
    }
    if (message == WM_COMMAND) {
      if (wParam == 0x76) {
        WinHelp(hwnd,(LPCSTR)CONCAT22(0x1120,_szHelpFile),1,0x421);
        return 1;
      }
      i = 0;
      while ((i < 4 && (wParam != *(ushort *)((ushort_0_ *)&rgidRaceBtn + i * 2)))) {
        i = i + 1;
      }
      if (i < 4) {
        StickyDlgPos(hwnd,(POINT *)&ptStickyRaceDlg,0);
        EndDialog(hwnd,i);
        return 1;
      }
      uVar9 = __aFulshr(uVar9,in_stack_0000ffc6);
      if ((((int)uVar9 == 0) && (0x10e < wParam)) && (wParam < 0x121)) {
        i = wParam - 0x10f;
        SetRaceStat((PLAYER *)&vplr,i / 3 + rsTechBonus1,i % 3);
        InvalidateAdvPtsRect(hwnd);
      }
      else if (wParam == 0x123) {
        HVar5 = GetDlgItem(hwnd,0x123);
        LVar10 = SendMessage(HVar5,0x400,0,0);
        i = (short)LVar10;
        SetRaceGrbit((PLAYER *)&vplr,ibitRaceTech3,i);
        InvalidateAdvPtsRect(hwnd);
      }
    }
LAB_10e0_409f:
    HVar8 = 0;
  }
  return HVar8;
}



// ======================================================================
// Function: BoundsCheckPlayer
// Address: 10e0:40ae
// Segment: MEMORY_RACE
// ======================================================================


void BoundsCheckPlayer(PLAYER *pplr)

{
  short i;
  
  for (i = 0; i < 3; i = i + 1) {
    if (pplr->rgEnvVarMin[i] == -1) {
      if ((pplr->rgEnvVarMax[i] != -1) || (pplr->rgEnvVar[i] != -1)) {
        pplr->rgEnvVar[i] = -1;
        pplr->rgEnvVarMax[i] = -1;
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
    }
    else {
      if (pplr->rgEnvVarMin[i] < '\0') {
        pplr->rgEnvVarMin[i] = '\0';
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
      if ('d' < pplr->rgEnvVarMin[i]) {
        pplr->rgEnvVarMin[i] = 'd';
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
      if ('d' < pplr->rgEnvVarMax[i]) {
        pplr->rgEnvVarMax[i] = 'd';
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
      if (pplr->rgEnvVarMax[i] < pplr->rgEnvVarMin[i]) {
        pplr->rgEnvVarMax[i] = pplr->rgEnvVarMin[i];
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
      if ((int)pplr->rgEnvVar[i] !=
          (int)pplr->rgEnvVarMin[i] + ((int)pplr->rgEnvVarMax[i] - (int)pplr->rgEnvVarMin[i]) / 2) {
        pplr->rgEnvVar[i] =
             pplr->rgEnvVarMin[i] +
             (char)(((int)pplr->rgEnvVarMax[i] - (int)pplr->rgEnvVarMin[i]) / 2);
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
      }
    }
  }
  if ('\x14' < pplr->pctIdealGrowth) {
    pplr->pctIdealGrowth = '\x14';
    pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
  }
  for (i = 0; i < 0x10; i = i + 1) {
    if (pplr->rgAttr[i] < ((char *)rgRaceStatMin)[i]) {
      pplr->rgAttr[i] = ((char *)rgRaceStatMin)[i];
      pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
    }
    if (((char *)rgRaceStatMax)[i] < pplr->rgAttr[i]) {
      pplr->rgAttr[i] = ((char *)rgRaceStatMax)[i];
      pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
    }
  }
  return;
}



// ======================================================================
// Function: CAdvantagePoints
// Address: 10e0:444c
// Segment: MEMORY_RACE
// ======================================================================


short CAdvantagePoints(PLAYER *pplr)

{
  long lVar1;
  char cVar2;
  short sVar3;
  short sVar4;
  short sVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  short sVar9;
  uint uVar10;
  uint unaff_DI;
  bool bVar11;
  long lVar12;
  ulong uVar13;
  ulong uVar14;
  long lVar15;
  short cProduce;
  short cOperate;
  short raMajor;
  short cGood;
  short i;
  short cCur;
  short cBad;
  char *cPoints;
  int local_a;
  short iSpread;
  short pctGrowth;
  
  cPoints = (char *)0x672;
  BoundsCheckPlayer(pplr);
  sVar3 = GetRaceStat(pplr,rsMajorAdv);
  lVar15 = (ulong)unaff_DI << 0x10;
  lVar12 = LInnateRaceHabitability(pplr);
  uVar13 = __aFldiv(lVar12,lVar15);
  if (pplr->pctIdealGrowth < '\x15') {
    cVar2 = pplr->pctIdealGrowth;
  }
  else {
    cVar2 = '\x14';
  }
  if (cVar2 < '\x01') {
    iSpread = 1;
  }
  else if (pplr->pctIdealGrowth < '\x15') {
    iSpread = (short)pplr->pctIdealGrowth;
  }
  else {
    iSpread = 0x14;
  }
  if (iSpread != pplr->pctIdealGrowth) {
    iSpread = 1;
    pplr->pctIdealGrowth = '\x01';
    pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
  }
  sVar9 = iSpread;
  if (iSpread < 6) {
    uVar14 = __aFulmul((long)(6 - iSpread),0x1068);
    uVar14 = uVar14 + 0x672;
  }
  else {
    if (iSpread < 0xe) {
      if (iSpread == 6) {
        cPoints = (char *)s__s__d_1120_147d + 5;
      }
      else if (iSpread == 7) {
        cPoints = (char *)0xf3c;
      }
      else if (iSpread == 8) {
        cPoints = (char *)0x8ca;
      }
      else if (iSpread == 9) {
        cPoints = (char *)0x753;
      }
      iSpread = (iSpread + -5) * 2 + 5;
    }
    else if (iSpread < 0x14) {
      iSpread = (iSpread + -0xd) * 3 + 0x15;
    }
    else {
      iSpread = 0x2d;
    }
    uVar14 = ZEXT24(cPoints);
  }
  lVar12 = 0x18;
  uVar13 = __aFulmul(uVar13,(long)iSpread);
  lVar12 = __aFldiv(uVar13,lVar12);
  lVar12 = uVar14 - lVar12;
  cGood = 0;
  i = 0;
  while( true ) {
    local_a = (int)((ulong)lVar12 >> 0x10);
    cPoints = (char *)lVar12;
    if (2 < i) break;
    if (pplr->rgEnvVar[i] < '\0') {
      cGood = cGood + 1;
    }
    else {
      sVar4 = _abs(pplr->rgEnvVar[i] + -0x32);
      lVar12 = lVar12 + sVar4 * 4;
    }
    i = i + 1;
  }
  if (1 < cGood) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 0x96),(int)cPoints - 0x96);
  }
  sVar4 = GetRaceStat(pplr,rsFactOperate);
  sVar5 = GetRaceStat(pplr,rsFactProd);
  if ((10 < sVar4) || (10 < sVar5)) {
    if (sVar4 + -9 < 1) {
      iVar6 = 1;
    }
    else {
      iVar6 = sVar4 + -9;
    }
    if (sVar5 + -9 < 1) {
      iVar7 = 1;
    }
    else {
      iVar7 = sVar5 + -9;
    }
    if (sVar3 == raCheapCol) {
      iVar8 = 3;
    }
    else {
      iVar8 = 2;
    }
    if (cGood < 2) {
      lVar15 = 9;
      uVar14 = (ulong)sVar9;
      uVar13 = __aFulmul((long)iVar6,(long)(iVar8 * iVar7));
      uVar13 = __aFulmul(uVar13,uVar14);
      lVar15 = __aFldiv(uVar13,lVar15);
      lVar12 = lVar12 - lVar15;
    }
    else {
      lVar15 = 2;
      uVar14 = (ulong)sVar9;
      uVar13 = __aFulmul((long)iVar6,(long)(iVar8 * iVar7));
      uVar13 = __aFulmul(uVar13,uVar14);
      lVar15 = __aFldiv(uVar13,lVar15);
      lVar12 = lVar12 - lVar15;
    }
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  iVar6 = GetRaceStat(pplr,rsResGen);
  if (0x18 < iVar6) {
    iVar6 = 0x19;
  }
  if (iVar6 < 8) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 0x960),(int)cPoints - 0x960);
  }
  else if (iVar6 == 8) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 0x4ec),(int)cPoints - 0x4ec);
  }
  else if (iVar6 == 9) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 600),(int)cPoints - 600);
  }
  else if (10 < iVar6) {
    lVar12 = lVar12 + (iVar6 + -10) * 0x78;
  }
  if (sVar3 == raMacintosh) {
    lVar12 = lVar12 + 0xd2;
  }
  else {
    sVar9 = GetRaceStat(pplr,rsFactProd);
    iVar7 = 10 - sVar9;
    sVar9 = GetRaceStat(pplr,rsFactBuild);
    iVar6 = 10 - sVar9;
    sVar9 = GetRaceStat(pplr,rsFactOperate);
    iVar8 = 10 - sVar9;
    if (iVar7 < 1) {
      cCur = iVar7 * 0x79;
    }
    else {
      cCur = iVar7 * 100;
    }
    if (iVar6 < 0) {
      iVar6 = iVar6 * -0x37;
    }
    else {
      iVar6 = iVar6 * iVar6 * -0x3c;
    }
    cCur = cCur + iVar6;
    if (iVar8 < 1) {
      iVar6 = iVar8 * 0x23;
    }
    else {
      iVar6 = iVar8 * 0x28;
    }
    cCur = cCur + iVar6;
    if (700 < cCur) {
      cCur = (cCur + -700) / 3 + 700;
    }
    if (iVar8 < -6) {
      if (iVar8 < -0xb) {
        if (iVar8 < -0xe) {
          cCur = cCur + -0x168;
        }
        else {
          cCur = cCur - ((-0xc - iVar8) * 0x2d + 0xe1);
        }
      }
      else {
        cCur = cCur + (-6 - iVar8) * -0x1e;
      }
    }
    if (iVar7 < -2) {
      cCur = cCur + (-2 - iVar7) * -0x3c;
    }
    lVar12 = lVar12 + cCur;
    sVar9 = GetRaceGrbit(pplr,ibitRaceCheapFact);
    if (sVar9 != 0) {
      lVar12 = CONCAT22((int)((ulong)lVar12 >> 0x10) - (uint)((uint)lVar12 < 0xaf),
                        (uint)lVar12 - 0xaf);
    }
    sVar9 = GetRaceStat(pplr,rsMineProd);
    iVar7 = 10 - sVar9;
    sVar9 = GetRaceStat(pplr,rsMineBuild);
    sVar4 = GetRaceStat(pplr,rsMineOperate);
    iVar6 = 10 - sVar4;
    if (iVar7 < 1) {
      cCur = iVar7 * 0xa9;
    }
    else {
      cCur = iVar7 * 100;
    }
    if (3 - sVar9 < 1) {
      cCur = cCur - ((3 - sVar9) * 0x41 + -0x50);
    }
    else {
      cCur = cCur + -0x168;
    }
    if (iVar6 < 1) {
      iVar6 = iVar6 * 0x23;
    }
    else {
      iVar6 = iVar6 * 0x28;
    }
    cCur = cCur + iVar6;
    lVar12 = lVar12 + cCur;
  }
  lVar12 = lVar12 - ((short *)rgRacePrimaryTrait)[sVar3];
  cBad = 0;
  cGood = 0;
  for (i = 0; i < 0xe; i = i + 1) {
    sVar9 = GetRaceGrbit(pplr,i);
    if (sVar9 != 0) {
      if (((short *)rgRaceAdvDisPts)[i] < 0) {
        cBad = cBad + 1;
      }
      else {
        cGood = cGood + 1;
      }
      lVar12 = lVar12 + ((short *)rgRaceAdvDisPts)[i];
    }
  }
  if (4 < cBad + cGood) {
    lVar12 = lVar12 - (cBad + cGood) * 10 * (cBad + cGood + -4);
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  if (3 < cGood - cBad) {
    iVar6 = (cGood - cBad) + -3;
    uVar10 = iVar6 * 0x3c;
    lVar12 = CONCAT22((local_a - ((int)uVar10 >> 0xf)) - (uint)(cPoints < uVar10),
                      (int)cPoints + iVar6 * -0x3c);
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  if (3 < cBad - cGood) {
    iVar6 = (cBad - cGood) + -3;
    uVar10 = iVar6 * 0x28;
    lVar12 = CONCAT22((local_a - ((int)uVar10 >> 0xf)) - (uint)(cPoints < uVar10),
                      (int)cPoints + iVar6 * -0x28);
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  sVar9 = GetRaceGrbit(pplr,ibitRaceNoAdvScanner);
  if (sVar9 != 0) {
    if (sVar3 == raMassAccel) {
      lVar12 = CONCAT22(local_a - (uint)(cPoints < 0x118),(int)cPoints - 0x118);
    }
    else if (sVar3 == raStealth) {
      lVar12 = CONCAT22(local_a - (uint)(cPoints < 200),(int)cPoints - 200);
    }
    else if (sVar3 == raNone) {
      lVar12 = CONCAT22(local_a - (uint)(cPoints < 0x28),(int)cPoints - 0x28);
    }
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  cCur = 0;
  for (i = 8; i < 0xe; i = i + 1) {
    sVar9 = GetRaceStat(pplr,i);
    cCur = cCur + sVar9 + -1;
  }
  if (cCur < 1) {
    if (cCur < 0) {
      iVar6 = ((short *)rgRaceDisEnvPts)[-1 - cCur];
      lVar1 = lVar12 + iVar6;
      uVar10 = (uint)lVar1;
      lVar15 = lVar12 + iVar6;
      lVar12 = lVar12 + iVar6;
      if ((cCur != -4 && 3 < -cCur) &&
         (sVar9 = GetRaceStat(pplr,rsResGen), lVar12 = lVar15, sVar9 < 10)) {
        lVar12 = CONCAT22((int)((ulong)lVar1 >> 0x10) - (uint)(uVar10 < 0xbe),uVar10 - 0xbe);
      }
    }
  }
  else {
    uVar10 = cCur * cCur * 0x82;
    bVar11 = cPoints < uVar10;
    cPoints = (char *)((int)cPoints + cCur * cCur * -0x82);
    local_a = (local_a - ((int)uVar10 >> 0xf)) - (uint)bVar11;
    if (cCur == 6) {
      bVar11 = 0xfa69 < cPoints;
      cPoints = (char *)((int)cPoints + 0x596);
      local_a = local_a + (uint)bVar11;
    }
    else if (cCur == 5) {
      bVar11 = 0xfdf7 < cPoints;
      cPoints = (char *)((int)cPoints + 0x208);
      local_a = local_a + (uint)bVar11;
    }
    lVar12 = CONCAT22(local_a,cPoints);
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  sVar9 = GetRaceGrbit(pplr,ibitRaceTech3);
  if (sVar9 != 0) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 0xb4),(int)cPoints - 0xb4);
  }
  local_a = (int)((ulong)lVar12 >> 0x10);
  cPoints = (char *)lVar12;
  if ((sVar3 == raMacintosh) && (sVar3 = GetRaceStat(pplr,rsTechBonus1), sVar3 == 2)) {
    lVar12 = CONCAT22(local_a - (uint)(cPoints < 100),(int)cPoints - 100);
  }
  lVar12 = __aFldiv(lVar12,3);
  return (short)lVar12;
}



// ======================================================================
// Function: LInnateRaceHabitability
// Address: 10e0:4c6e
// Segment: MEMORY_RACE
// ======================================================================


long LInnateRaceHabitability(PLAYER *pplr)

{
  PLAYER *pPVar1;
  undefined2 *puVar2;
  PLAYER *pPVar3;
  char cVar4;
  short sVar5;
  uint uVar6;
  int iVar7;
  undefined2 unaff_SI;
  PLAYER *pPVar8;
  undefined2 *puVar9;
  undefined2 unaff_DI;
  PLAYER *pPVar10;
  undefined2 unaff_SS;
  bool bVar11;
  ulong uVar12;
  long lVar13;
  undefined2 uVar14;
  undefined2 uVar15;
  undefined2 in_stack_0000feac;
  undefined2 in_stack_0000feae;
  long local_14c;
  short pctTerra;
  double lInnate;
  short k;
  uint pctDesire;
  int local_136;
  short iDelta;
  double l3;
  int rgBase [3];
  long l1;
  short j;
  short iTerra;
  short i;
  int rgInc [3];
  short fTotalTerra;
  short rgDelta;
  short local_110;
  short local_10e;
  undefined2 plrT [96];
  int rgSteps [3];
  double l2;
  PLANET pl;
  short iTry;
  
  pPVar8 = (PLAYER *)rgplr;
  puVar9 = plrT;
  for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
    puVar2 = puVar9;
    puVar9 = puVar9 + 1;
    pPVar1 = pPVar8;
    pPVar8 = (PLAYER *)&pPVar8->cPlanet;
    *puVar2 = *(undefined2 *)pPVar1;
  }
  fTotalTerra = GetRaceGrbit(pplr,ibitRaceTT);
  pPVar10 = (PLAYER *)rgplr;
  pPVar8 = pplr;
  for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
    pPVar3 = pPVar10;
    pPVar10 = (PLAYER *)&pPVar10->cPlanet;
    pPVar1 = pPVar8;
    pPVar8 = (PLAYER *)&pPVar8->cPlanet;
    cVar4 = pPVar1->cShDef;
    pPVar3->iPlayer = pPVar1->iPlayer;
    pPVar3->cShDef = cVar4;
  }
  local_10e = 0;
  local_110 = 0;
  rgDelta = 0;
  for (iTerra = 0; iTerra < 3; iTerra = iTerra + 1) {
    if (iTerra == 0) {
      pctTerra = 0;
    }
    else if (iTerra == 1) {
      if (fTotalTerra == 0) {
        pctTerra = 5;
      }
      else {
        pctTerra = 8;
      }
    }
    else if (fTotalTerra == 0) {
      pctTerra = 0xf;
    }
    else {
      pctTerra = 0x11;
    }
    for (i = 0; i < 3; i = i + 1) {
      if (((((('d' < pplr->rgEnvVar[i]) || ('d' < pplr->rgEnvVarMin[i])) ||
            ('d' < pplr->rgEnvVarMax[i])) ||
           ((pplr->rgEnvVar[i] < '\0' || (pplr->rgEnvVarMin[i] < '\0')))) ||
          (pplr->rgEnvVarMax[i] < '\0')) &&
         (((pplr->rgEnvVar[i] != -1 || (pplr->rgEnvVarMin[i] != -1)) || (pplr->rgEnvVarMax[i] != -1)
          ))) {
        pplr->rgEnvVarMax[i] = -1;
        pplr->rgEnvVarMin[i] = -1;
        pplr->rgEnvVar[i] = -1;
        pplr->wFlags = pplr->wFlags & 0xffef | 0x10;
        pPVar10 = (PLAYER *)rgplr;
        pPVar8 = pplr;
        for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
          pPVar3 = pPVar10;
          pPVar10 = (PLAYER *)&pPVar10->cPlanet;
          pPVar1 = pPVar8;
          pPVar8 = (PLAYER *)&pPVar8->cPlanet;
          cVar4 = pPVar1->cShDef;
          pPVar3->iPlayer = pPVar1->iPlayer;
          pPVar3->cShDef = cVar4;
        }
      }
      if (pplr->rgEnvVar[i] < '\0') {
        rgBase[i] = 0x32;
        rgInc[i] = 0xb;
        rgSteps[i] = 1;
      }
      else {
        rgBase[i] = pplr->rgEnvVarMin[i] - pctTerra;
        if (rgBase[i] < 0) {
          rgBase[i] = 0;
        }
        iTry = pplr->rgEnvVarMax[i] + pctTerra;
        if (100 < iTry) {
          iTry = 100;
        }
        rgInc[i] = iTry - rgBase[i];
        rgSteps[i] = 0xb;
      }
    }
    for (i = 0; i < rgSteps[0]; i = i + 1) {
      if ((i == 0) || (rgSteps[0] < 2)) {
        iTry = rgBase[0];
      }
      else {
        iTry = (i * rgInc[0]) / (rgSteps[0] + -1) + rgBase[0];
      }
      if ((iTerra != 0) && (-1 < pplr->rgEnvVar[0])) {
        iVar7 = pplr->rgEnvVar[0] - iTry;
        sVar5 = _abs(iVar7);
        if (pctTerra < sVar5) {
          if (iVar7 < 0) {
            iDelta = iVar7 + pctTerra;
          }
          else {
            iDelta = iVar7 - pctTerra;
          }
        }
        else {
          iDelta = 0;
        }
        rgDelta = iDelta;
        iTry = pplr->rgEnvVar[0] - iDelta;
      }
      pl.rgEnvVar[0] = (char)iTry;
      l2 = 0.0;
      for (j = 0; j < rgSteps[1]; j = j + 1) {
        if ((j == 0) || (rgSteps[1] < 2)) {
          iTry = rgBase[1];
        }
        else {
          iTry = (j * rgInc[1]) / (rgSteps[1] + -1) + rgBase[1];
        }
        if ((iTerra != 0) && (-1 < pplr->rgEnvVar[1])) {
          iVar7 = pplr->rgEnvVar[1] - iTry;
          sVar5 = _abs(iVar7);
          if (pctTerra < sVar5) {
            if (iVar7 < 0) {
              iDelta = iVar7 + pctTerra;
            }
            else {
              iDelta = iVar7 - pctTerra;
            }
          }
          else {
            iDelta = 0;
          }
          local_110 = iDelta;
          iTry = pplr->rgEnvVar[1] - iDelta;
        }
        pl.rgEnvVar[1] = (char)iTry;
        l1 = 0;
        for (k = 0; k < rgSteps[2]; k = k + 1) {
          if ((k == 0) || (rgSteps[2] < 2)) {
            iTry = rgBase[2];
          }
          else {
            iTry = (k * rgInc[2]) / (rgSteps[2] + -1) + rgBase[2];
          }
          if ((iTerra != 0) && (-1 < pplr->rgEnvVar[2])) {
            iVar7 = pplr->rgEnvVar[2] - iTry;
            sVar5 = _abs(iVar7);
            if (pctTerra < sVar5) {
              if (iVar7 < 0) {
                iDelta = iVar7 + pctTerra;
              }
              else {
                iDelta = iVar7 - pctTerra;
              }
            }
            else {
              iDelta = 0;
            }
            local_10e = iDelta;
            iTry = pplr->rgEnvVar[2] - iDelta;
          }
          pl.rgEnvVar[2] = (char)iTry;
          pctDesire = PctPlanetDesirability((PLANET *)CONCAT22(unaff_SS,&pl),0);
          local_136 = (int)pctDesire >> 0xf;
          iVar7 = rgDelta + local_110 + local_10e;
          if (pctTerra < iVar7) {
            uVar6 = iVar7 - pctTerra;
            bVar11 = pctDesire < uVar6;
            pctDesire = pctDesire - uVar6;
            local_136 = (local_136 - ((int)uVar6 >> 0xf)) - (uint)bVar11;
            if ((local_136 < 1) && (local_136 < 0)) {
              pctDesire = 0;
              local_136 = 0;
            }
          }
          uVar12 = __aFulmul(CONCAT22(local_136,pctDesire),CONCAT22(local_136,pctDesire));
          if (iTerra == 0) {
            uVar12 = __aFulmul(uVar12,7);
          }
          else if (iTerra == 1) {
            uVar12 = __aFulmul(uVar12,5);
          }
          else {
            uVar12 = __aFulmul(uVar12,6);
          }
          l1 = uVar12 + l1;
        }
        if (pplr->rgEnvVar[2] < '\0') {
          l1 = __aFulmul(l1,0xb);
        }
        else {
          uVar15 = 0;
          uVar14 = 100;
          uVar12 = __aFulmul(l1,(long)rgInc[2]);
          l1 = __aFldiv(uVar12,CONCAT22(uVar15,uVar14));
        }
        l2 = l2 + (double)l1;
      }
      if (pplr->rgEnvVar[1] < '\0') {
        l2 = l2 * 11.0;
      }
      else {
        local_14c = (long)rgInc[1];
        in_stack_0000feac = 100;
        in_stack_0000feae = 0;
        l2 = ((double)local_14c * l2) / 100.0;
      }
    }
    if (-1 < pplr->rgEnvVar[0]) {
      in_stack_0000feac = 100;
      in_stack_0000feae = 0;
    }
  }
  if (pplr != (PLAYER *)rgplr) {
    puVar9 = plrT;
    pPVar8 = (PLAYER *)rgplr;
    for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
      pPVar1 = pPVar8;
      pPVar8 = (PLAYER *)&pPVar8->cPlanet;
      puVar2 = puVar9;
      puVar9 = puVar9 + 1;
      uVar14 = *puVar2;
      pPVar1->iPlayer = (char)uVar14;
      pPVar1->cShDef = (char)((uint)uVar14 >> 8);
    }
  }
  lVar13 = __ftol((double)CONCAT26(in_stack_0000feae,
                                           CONCAT24(in_stack_0000feac,CONCAT22(unaff_SI,unaff_DI))))
  ;
  return lVar13;
}



// ======================================================================
// Function: InvalidateAdvPtsRect
// Address: 10e0:54d4
// Segment: MEMORY_RACE
// ======================================================================


void InvalidateAdvPtsRect(HWND hwnd)

{
  HGDIOBJ HVar1;
  undefined2 unaff_SS;
  DWORD DVar2;
  HFONT hfontSav;
  RECT rc;
  short dx;
  HFONT hfont;
  short dyBig;
  LOGFONT *plf;
  TEXTMETRIC tm;
  HDC hdc;
  
  plf = (LOGFONT *)LocalAlloc(0x40,0x32);
  hdc = GetDC(hwnd);
  plf->lfHeight = -0x18;
  _strcpy(plf->lfFaceName,*(char (*) [32])(rgszArial + 1));
  hfont = CreateFontIndirect((LOGFONT *)CONCAT22(0x1120,plf));
  HVar1 = SelectObject(hdc,hfont);
  GetTextMetrics(hdc,(TEXTMETRIC *)CONCAT22(unaff_SS,&tm));
  dyBig = tm.tmHeight + tm.tmExternalLeading;
  DVar2 = GetTextExtent(hdc,(LPCSTR)0x1120135e,6);
  dx = (int)DVar2 + 8;
  GetClientRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc));
  rc.left = rc.right - dx;
  rc.bottom = rc.top + dyBig + 4;
  SelectObject(hdc,HVar1);
  DeleteObject(hfont);
  LocalFree((HLOCAL)plf);
  ReleaseDC(hwnd,hdc);
  InvalidateRect(hwnd,(RECT *)CONCAT22(unaff_SS,&rc),1);
  return;
}



// ======================================================================
// Function: DrawRaceAdvantagePoints
// Address: 10e0:55c6
// Segment: MEMORY_RACE
// ======================================================================


void DrawRaceAdvantagePoints(HDC hdc,RECT *prc,PLAYER *pplr)

{
  HGDIOBJ HVar1;
  uint uVar2;
  undefined2 unaff_SS;
  DWORD DVar3;
  HFONT hfontSav;
  RECT rc;
  short cch;
  short iPts;
  short dx;
  HFONT hfont;
  COLORREF crSav;
  short c;
  char szAdvantage [32];
  short dyBig;
  short bkMode;
  COLORREF crBkSav;
  LOGFONT *plf;
  TEXTMETRIC tm;
  
  plf = (LOGFONT *)LocalAlloc(0x40,0x32);
  plf->lfHeight = -0x18;
  CchGetString(idsArialBold,plf->lfFaceName);
  hfont = CreateFontIndirect((LOGFONT *)CONCAT22(0x1120,plf));
  HVar1 = SelectObject(hdc,hfont);
  GetTextMetrics(hdc,(TEXTMETRIC *)CONCAT22(unaff_SS,&tm));
  dyBig = tm.tmHeight + tm.tmExternalLeading;
  DVar3 = GetTextExtent(hdc,(LPCSTR)0x11201365,6);
  dx = (int)DVar3 + 8;
  rc.top = prc->top;
  rc.right = prc->right;
  rc.left = rc.right - dx;
  rc.bottom = rc.top + dyBig + 4;
  if (pplr == (PLAYER *)0x0) {
    pplr = (PLAYER *)&vplr;
  }
  iPts = CAdvantagePoints(pplr);
  bkMode = SetBkMode(hdc,2);
  if (iPts < 0) {
    uVar2 = 0x7f;
  }
  else {
    uVar2 = 0;
  }
  crSav = SetTextColor(hdc,(ulong)uVar2);
  crBkSav = SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace)
                      );
  c = _wsprintf(szWork,(char *)CONCAT22(0x1120,PCTD),iPts);
  RcCtrTextOut(hdc,&rc,(char *)szWork,-1);
  SetTextColor(hdc,0);
  SelectObject(hdc,rghfontArial8[1]);
  c = CchGetString(idsPointsLeft,(char *)szWork);
  DVar3 = GetTextExtent(hdc,szWork,c);
  dx = (short)DVar3;
  cch = CchGetString(idsAdvantage,szAdvantage);
  RightTextOut(hdc,rc.left,3,szAdvantage,cch,0);
  RightTextOut(hdc,rc.left,dyArial8 + 3,(char *)szWork,c,0);
  rc.left = rc.left - (dx + 4);
  PatBlt(hdc,rc.left + -1,0,1,rc.bottom + 1,0x42);
  PatBlt(hdc,rc.left + -4,0,2,rc.bottom + 4,0x42);
  PatBlt(hdc,rc.left,rc.bottom,rc.right - rc.left,1,0x42);
  PatBlt(hdc,rc.left + -2,rc.bottom + 2,(rc.right - rc.left) + 2,2,0x42);
  SetBkColor(hdc,crBkSav);
  SetTextColor(hdc,crSav);
  SetBkMode(hdc,bkMode);
  SelectObject(hdc,HVar1);
  DeleteObject(hfont);
  LocalFree((HLOCAL)plf);
  return;
}



// ======================================================================
// Function: IRaceChecksum
// Address: 10e0:5888
// Segment: MEMORY_RACE
// ======================================================================


ushort IRaceChecksum(PLAYER *pplr)

{
  short cs;
  short i;
  ushort *p;
  ushort ick;
  
  ick = 0;
  for (i = 0; i < 0x60; i = i + 1) {
    ick = ick ^ *(uint *)(pplr->rgEnvVar + i * 2 + -0x10);
  }
  return ick;
}



// ======================================================================
// Function: FSaveRace
// Address: 10e0:58d4
// Segment: MEMORY_RACE
// ======================================================================


short FSaveRace(char *szFileSuggest,PLAYER *pplr)

{
  int iVar1;
  char *sz;
  short sVar2;
  undefined2 unaff_SS;
  undefined2 ofn;
  undefined2 local_44e;
  HWND local_44c;
  char *local_448;
  int local_41c;
  char szFile [256];
  ushort i;
  char szFilter [256];
  undefined1 szDirName;
  ushort icksum;
  
  if (szFileSuggest == (char *)0x0) {
    szFile[0] = '\0';
  }
  else {
    _strcpy(szFile,szFileSuggest);
  }
  szDirName = 0;
  CchGetString(idsStarsRaceFilesR,szFilter);
  for (i = 0; szFilter[i] != '\0'; i = i + 1) {
    if (szFilter[i] == '|') {
      szFilter[i] = '\0';
    }
  }
  _memset(&ofn,0,0x48);
  ofn = 0x48;
  local_44e = 0;
  local_44c = hwndRaceParent;
  local_448 = szFilter;
  iVar1 = GetSaveFileName(0x1118,&ofn);
  if (iVar1 == 0) {
    sVar2 = 0;
  }
  else {
    sVar2 = FCreateFile(dtHist|dtLog,-1,szFile);
    if (sVar2 == 0) {
      sVar2 = 0x10;
      sz = PszFormatIds(idsStarsUnableSaveRaceDataFilePlease,(short *)0x0);
      AlertSz(sz,sVar2);
      sVar2 = 0;
    }
    else {
      WriteRtPlr(pplr,(byte *)0x0);
      icksum = IRaceChecksum(pplr);
      WriteRt(0,2,(ushort *)CONCAT22(unaff_SS,&icksum));
      StreamClose();
      _strcpy((char *)&szRaceFile,szFile + local_41c);
      sVar2 = 1;
    }
  }
  return sVar2;
}



// ======================================================================
// Function: SetRCWTitle
// Address: 10e0:5ab8
// Segment: MEMORY_RACE
// ======================================================================


void SetRCWTitle(HWND hwnd,short iStep)

{
  undefined2 unaff_SS;
  short cch;
  char szBuf [52];
  
  CchGetString(fRCWReadOnly + idsCustomRaceWizardStepD6,szBuf);
  _wsprintf(szWork,(char *)CONCAT22(unaff_SS,szBuf),iStep);
  SetWindowText(hwnd,szWork);
  return;
}



// ======================================================================
// Function: CreateRandomRace
// Address: 10e0:5b08
// Segment: MEMORY_RACE
// ======================================================================


void CreateRandomRace(PLAYER *pplr)

{
  PLAYER *pPVar1;
  undefined2 uVar2;
  undefined2 *puVar3;
  char cVar4;
  short sVar5;
  char *pcVar6;
  int iVar7;
  undefined2 *puVar8;
  PLAYER *pPVar9;
  undefined2 unaff_SS;
  undefined2 plrT [64];
  char local_54 [60];
  short local_18;
  int local_16;
  short k;
  short dAwayCur;
  short dAwayNew;
  short iVal;
  short j;
  short cPass;
  short i;
  short cPts;
  
  pplr->szNames[0] = '\0';
  iVal = Random(0x19);
  if (iVal < 4) {
    for (i = 0; i < 3; i = i + 1) {
      pplr->rgEnvVarMax[i] = -1;
      pplr->rgEnvVarMin[i] = -1;
      pplr->rgEnvVar[i] = -1;
    }
    sVar5 = Random(4);
    pplr->pctIdealGrowth = (char)sVar5 + '\x02';
  }
  else if (iVal < 7) {
    for (i = 0; i < 3; i = i + 1) {
      pplr->rgEnvVar[i] = '2';
      pplr->rgEnvVarMin[i] = '\0';
      pplr->rgEnvVarMax[i] = 'd';
    }
    sVar5 = Random(4);
    pplr->pctIdealGrowth = (char)sVar5 + '\x03';
  }
  else if (iVal < 9) {
    for (i = 0; i < 3; i = i + 1) {
      j = Random(2);
      if ((i == 2) && (local_16 = (int)pplr->rgEnvVar[0], local_16 == pplr->rgEnvVar[1])) {
        j = (short)(pplr->rgEnvVar[0] != '\0');
      }
      if (j == 0) {
        pplr->rgEnvVar[i] = '2';
        pplr->rgEnvVarMin[i] = '\0';
        pplr->rgEnvVarMax[i] = 'd';
      }
      else {
        sVar5 = Random(4);
        pplr->pctIdealGrowth = (char)sVar5 + '\x02';
      }
    }
    sVar5 = Random(5);
    pplr->pctIdealGrowth = (char)sVar5 + '\x02';
  }
  else {
    for (i = 0; i < 3; i = i + 1) {
      sVar5 = Random(0x28);
      j = sVar5 * 2 + 0x14;
      k = Random(0x65 - j);
      cVar4 = (char)k;
      pplr->rgEnvVar[i] = (char)(j / 2) + cVar4;
      pplr->rgEnvVarMin[i] = cVar4;
      pplr->rgEnvVarMax[i] = cVar4 + (char)j;
    }
    if (iVal < 0xc) {
      i = Random(3);
      pplr->rgEnvVarMax[i] = -1;
      pplr->rgEnvVarMin[i] = -1;
      pplr->rgEnvVar[i] = -1;
    }
    else if (iVal < 0xe) {
      i = Random(3);
      pplr->rgEnvVar[i] = '2';
      pplr->rgEnvVarMin[i] = '\0';
      pplr->rgEnvVarMax[i] = 'd';
    }
    else if (iVal < 0x11) {
      i = Random(3);
      j = Random(0x51);
      cVar4 = (char)j;
      pplr->rgEnvVar[i] = cVar4 + '\n';
      pplr->rgEnvVarMin[i] = cVar4;
      pplr->rgEnvVarMax[i] = cVar4 + '\x14';
    }
    sVar5 = Random(9);
    pplr->pctIdealGrowth = (char)sVar5 + '\a';
  }
  iVal = Random(3);
  for (i = 8; i < 0xe; i = i + 1) {
    if (iVal == 0) {
      sVar5 = 1;
    }
    else {
      sVar5 = Random(3);
    }
    SetRaceStat(pplr,i,sVar5);
  }
  sVar5 = Random(10);
  SetRaceStat(pplr,rsMajorAdv,sVar5);
  iVal = Random(4);
  for (i = 0; i < 0xe; i = i + 1) {
    if (iVal == 0) {
      sVar5 = 0;
    }
    else {
      sVar5 = Random(2);
    }
    SetRaceGrbit(pplr,i,sVar5);
  }
  sVar5 = Random(2);
  SetRaceGrbit(pplr,ibitRaceTech3,sVar5);
  sVar5 = Random(2);
  SetRaceGrbit(pplr,ibitRaceCheapFact,sVar5);
  iVal = Random(3);
  if (iVal == 0) {
    for (i = 0; i < 7; i = i + 1) {
      pplr->rgAttr[i] = *(char *)(i + 0xde0);
    }
    sVar5 = Random(5);
    pplr->rgAttr[7] = (char)sVar5;
  }
  else {
    for (i = 0; i < 8; i = i + 1) {
      local_16 = (int)((char *)rgRaceStatMin)[i];
      local_18 = Random((((char *)rgRaceStatMax)[i] + 1) - local_16);
      pplr->rgAttr[i] = ((char *)rgRaceStatMin)[i] + (char)local_18;
    }
  }
  pcVar6 = PszGetCompressedString(idsRandom2);
  sVar5 = _strcmp(pplr->szName,pcVar6);
  if (sVar5 == 0) {
    pcVar6 = pplr->szName;
    sVar5 = Random(0x18);
    CchGetString(sVar5 + idsBerserker,pcVar6);
  }
  cPts = CAdvantagePoints(pplr);
  if ((cPts < 0) || (0x32 < cPts)) {
    cPass = 0;
LAB_10e0_6072:
    cPts = CAdvantagePoints(pplr);
    if ((-1 < cPts) && (cPts < 0x33)) {
      return;
    }
    if (cPass < 0xfb) {
      cPass = cPass + 1;
      iVal = Random(10);
      if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
        dAwayCur = cPts + -0x32;
      }
      else {
        dAwayCur = -cPts;
      }
      if (iVal < 3) {
        i = Random(6);
        j = (short)pplr->rgAttr[i + 8];
        if (0 < j) goto LAB_10e0_6143;
        goto LAB_10e0_61ad;
      }
      if (iVal < 6) {
        iVal = Random(0xe);
        j = GetRaceGrbit(pplr,iVal);
        for (i = 0; i < 2; i = i + 1) {
          SetRaceGrbit(pplr,iVal,i);
          cPts = CAdvantagePoints(pplr);
          if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
            dAwayNew = cPts + -0x32;
          }
          else {
            dAwayNew = -cPts;
          }
          if (dAwayNew < dAwayCur) break;
        }
        if (1 < i) {
          SetRaceGrbit(pplr,iVal,j);
        }
      }
      else {
        if (8 < iVal) {
          sVar5 = Random(2);
          if (sVar5 == 0) {
            iVal = Random(3);
            if (pplr->rgEnvVar[iVal] < '\0') {
              j = Random(0x1f);
              cVar4 = (char)j;
              pplr->rgEnvVar[iVal] = cVar4 + '#';
              pplr->rgEnvVarMin[iVal] = cVar4;
              pplr->rgEnvVarMax[iVal] = cVar4 + 'F';
              cPts = CAdvantagePoints(pplr);
              if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
                dAwayNew = cPts + -0x32;
              }
              else {
                dAwayNew = -cPts;
              }
              if (dAwayCur <= dAwayNew) {
                pplr->rgEnvVarMax[iVal] = -1;
                pplr->rgEnvVarMin[iVal] = -1;
                pplr->rgEnvVar[iVal] = -1;
              }
            }
            else {
              puVar8 = plrT;
              pPVar9 = pplr;
              for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
                puVar3 = puVar8;
                puVar8 = puVar8 + 1;
                pPVar1 = pPVar9;
                pPVar9 = (PLAYER *)&pPVar9->cPlanet;
                *puVar3 = *(undefined2 *)pPVar1;
              }
              pplr->rgEnvVarMax[iVal] = -1;
              pplr->rgEnvVarMin[iVal] = -1;
              pplr->rgEnvVar[iVal] = -1;
              cPts = CAdvantagePoints(pplr);
              if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
                dAwayNew = cPts + -0x32;
              }
              else {
                dAwayNew = -cPts;
              }
              if (dAwayCur <= dAwayNew) {
                puVar8 = plrT;
                pPVar9 = pplr;
                for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
                  pPVar1 = pPVar9;
                  pPVar9 = (PLAYER *)&pPVar9->cPlanet;
                  puVar3 = puVar8;
                  puVar8 = puVar8 + 1;
                  uVar2 = *puVar3;
                  pPVar1->iPlayer = (char)uVar2;
                  pPVar1->cShDef = (char)((uint)uVar2 >> 8);
                }
              }
            }
            goto LAB_10e0_6072;
          }
          j = (short)pplr->pctIdealGrowth;
          if (1 < j) {
            pplr->pctIdealGrowth = pplr->pctIdealGrowth + -1;
            cPts = CAdvantagePoints(pplr);
            if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
              dAwayNew = cPts + -0x32;
            }
            else {
              dAwayNew = -cPts;
            }
            if (dAwayNew < dAwayCur) goto LAB_10e0_6072;
          }
          if (j < 0xf) {
            pplr->pctIdealGrowth = (char)j + '\x01';
            cPts = CAdvantagePoints(pplr);
            if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
              dAwayNew = cPts + -0x32;
            }
            else {
              dAwayNew = -cPts;
            }
            if (dAwayNew < dAwayCur) goto LAB_10e0_6072;
          }
          pplr->pctIdealGrowth = (char)j;
          goto LAB_10e0_6072;
        }
        iVal = Random(7);
        j = GetRaceStat(pplr,iVal);
        for (i = -1; i < 2; i = i + 2) {
          SetRaceStat(pplr,iVal,j + i);
          cPts = CAdvantagePoints(pplr);
          if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
            dAwayNew = cPts + -0x32;
          }
          else {
            dAwayNew = -cPts;
          }
          if (dAwayNew < dAwayCur) break;
        }
        if (1 < i) {
          SetRaceStat(pplr,iVal,j);
        }
      }
      goto LAB_10e0_6072;
    }
    puVar8 = plrT;
    pPVar9 = pplr;
    cPass = cPass + 1;
    for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
      puVar3 = puVar8;
      puVar8 = puVar8 + 1;
      pPVar1 = pPVar9;
      pPVar9 = (PLAYER *)&pPVar9->cPlanet;
      *puVar3 = *(undefined2 *)pPVar1;
    }
    puVar8 = (undefined2 *)&vrgplrDef;
    pPVar9 = pplr;
    for (iVar7 = 0x60; iVar7 != 0; iVar7 = iVar7 + -1) {
      pPVar1 = pPVar9;
      pPVar9 = (PLAYER *)&pPVar9->cPlanet;
      puVar3 = puVar8;
      puVar8 = puVar8 + 1;
      uVar2 = *puVar3;
      pPVar1->iPlayer = (char)uVar2;
      pPVar1->cShDef = (char)((uint)uVar2 >> 8);
    }
    _strcpy(pplr->szName,local_54);
  }
  return;
LAB_10e0_6143:
  pplr->rgAttr[i + 8] = pplr->rgAttr[i + 8] + -1;
  cPts = CAdvantagePoints(pplr);
  if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
    dAwayNew = cPts + -0x32;
  }
  else {
    dAwayNew = -cPts;
  }
  if (dAwayCur <= dAwayNew) {
    pplr->rgAttr[i + 8] = (char)j;
LAB_10e0_61ad:
    if (j < 2) {
      pplr->rgAttr[i + 8] = pplr->rgAttr[i + 8] + '\x01';
      cPts = CAdvantagePoints(pplr);
      if (-(cPts + -0x32) == cPts || -cPts < cPts + -0x32) {
        dAwayNew = cPts + -0x32;
      }
      else {
        dAwayNew = -cPts;
      }
      if (dAwayCur <= dAwayNew) {
        pplr->rgAttr[i + 8] = (char)j;
      }
    }
  }
  goto LAB_10e0_6072;
}



// ======================================================================
// Function: PctTrueMaxGrowth
// Address: 10e0:65d4
// Segment: MEMORY_RACE
// ======================================================================


short PctTrueMaxGrowth(short iplr)

{
  short sVar1;
  
  sVar1 = GetRaceStat((PLAYER *)rgplr + iplr,rsMajorAdv);
  if (sVar1 == raCheapCol) {
    sVar1 = (int)*(char *)((int)&rgplr[0].pctIdealGrowth + iplr * 0xc0) << 1;
  }
  else {
    sVar1 = (short)*(char *)((int)&rgplr[0].pctIdealGrowth + iplr * 0xc0);
  }
  return sVar1;
}



