// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: ZipOrderDlg
// Address: 1080:0000
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Variable defined which should be unmapped: iAction */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Restarted to delay deadcode elimination for space: ram */

short ZipOrderDlg(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  ushort *puVar1;
  ZIPORDER *pZVar2;
  char cVar3;
  char *pcVar4;
  HWND HVar5;
  short sVar6;
  int iVar7;
  ushort uVar8;
  undefined2 unaff_SI;
  ushort *puVar9;
  undefined2 unaff_DI;
  ZIPORDER *pZVar10;
  undefined2 unaff_SS;
  DWORD DVar11;
  ulong uVar12;
  char *pcVar13;
  char *pcVar14;
  undefined2 uVar15;
  HDC HVar16;
  short iAction;
  short xCtr;
  short cch;
  char *rcGBox;
  char *pszT;
  char *psz;
  HWND hwndRad;
  undefined8 rc;
  PAINTSTRUCT ps;
  short i;
  HDC hdc;
  
                    /* Segment:    17
                       Offset:     0007d700
                       Length:     39d7
                       Min Alloc:  39d7
                       Flags:      1d10
                           Code
                           Discardable
                           Moveable
                           LoadOnCall
                           Impure (Non-shareable)
                        */
  if (message == WM_PAINT) {
    hdc = BeginPaint(hwnd,&ps);
    GetClientRect(hwnd,&rc);
    HVar5 = GetDlgItem(hwnd,0x431);
    GetWindowRect(HVar5,&stack0xffc8);
    ScreenToClient(hwnd,&stack0xffc8);
    HVar5 = GetDlgItem(hwnd,0x434);
    GetWindowRect(HVar5,&rc);
    ScreenToClient(hwnd,(POINT *)((int)&rc + 4));
    psz = rc._4_2_;
    hwndRad = rc._6_2_;
    ExpandRc(&stack0xffc8,dyArial8,dyArial8 >> 1);
    _Draw3dFrame();
    SelectObject(hdc,rghfontArial8[1]);
    SetBkColor(hdc,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
    sVar6 = CchGetString(idsCustomOrders,(char *)szWork);
    TextOut(hdc,(short)(rcGBox + 8),(int)pszT - (dyArial8 >> 1),szWork,sVar6);
    pszT = (char *)(hwndRad + 8);
    if (*(char *)((int)&vrgZip[0].fValid + iResTechNow * 0x18) == '\0') {
      sVar6 = CchGetString(idsEmptyCustomSlot,(char *)szWork);
      TextOut(hdc,0xc,(short)pszT,szWork,sVar6);
    }
    else {
      DVar11 = GetTextExtent(hdc,pcRam112004d0,9);
      for (i = 0; i < 5; i = i + 1) {
        SetTextColor(hdc,CONCAT22(*(undefined2 *)(i * 4 + 0x44a),*(undefined2 *)(i * 4 + 0x448)));
        RightTextOut
                  (hdc,(int)DVar11 + 8,(short)pszT,(char *)*(undefined2 *)(i * 2 + 0x4cc),0,0);
        SetTextColor(hdc,0);
        sVar6 = CchGetString
                          (((((ZIPORDER *)vrgZip)[iResTechNow].txp.rgia + i)->
                            wFlags >> 0xc) + idsAction,(char *)szWork);
        if (*(char *)((int)(HCURSOR *)&hcurScanAdd + sVar6 + 1) == '.') {
          _wsprintf((char *)szBase + 0xff + sVar6,(char *)0x112016ba,
                    (((ZIPORDER *)vrgZip)[iResTechNow].txp.rgia + i)->wFlags &
                    0xfff);
        }
        iVar7 = (int)DVar11 + 0xe;
        uVar15 = 0x1120;
        pcVar14 = (char *)szWork;
        pcVar4 = pszT;
        HVar16 = hdc;
        uVar8 = _strlen((char *)szWork);
        TextOut(HVar16,iVar7,(short)pcVar4,(LPCSTR)CONCAT22(uVar15,pcVar14),uVar8);
        pszT = pszT + dyArial8;
      }
    }
    EndPaint(hwnd,&ps);
    sVar6 = 1;
  }
  else if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,&rc);
    FillRect(wParam,&rc,hbrButtonFace);
    sVar6 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      for (i = 0x431; i < 0x435; i = i + 1) {
        hwndRad = (HWND)lParam;
        HVar5 = GetDlgItem(hwnd,i);
        if (hwndRad == HVar5) break;
      }
      if (i < 0x435) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        HVar5 = hwnd;
        pcVar4 = PszGetCompressedString(idsCustomizeZipOrders);
        SetWindowText(HVar5,pcVar4);
        HVar5 = GetDlgItem(hwnd,0x417);
        ShowWindow(HVar5,0);
        hwndZipOrderDlg = hwnd;
        CheckRadioButton(hwnd,0x431,0x434,0x431);
        EnableZipBtns(hwnd,0);
        iResTechNow = 0;
        for (i = 0x431; i < 0x435; i = i + 1) {
          if (*(char *)((int)&vrgZip[0].fValid + (i + -0x431) * 0x18) == '\0') {
            psz = PszGetCompressedString(idsUnusedD);
            _wsprintf(szWork,psz,(char)psz,i + -0x430);
          }
          else {
            pszT = (char *)szWork;
            pcVar4 = pszT;
            psz = (char *)((int)vrgZip[0].szName + (i + -0x431) * 0x18);
            while (pszT = pcVar4, *psz != '\0') {
              pcVar14 = psz + 1;
              cVar3 = *psz;
              *pszT = cVar3;
              pcVar4 = pszT + 1;
              psz = pcVar14;
              if (cVar3 == '&') {
                pszT[1] = '&';
                pcVar4 = pszT + 2;
              }
            }
            *pszT = '\0';
          }
          psz = (char *)szWork;
          hwndRad = GetDlgItem(hwnd,i);
          SetWindowText(hwndRad,psz);
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyZipOrderDlg,1);
        if (((uint)gd.grBits >> 0xb & 1) != 0) {
          AdvanceTutor();
        }
        return 1;
      }
      if (message == WM_COMMAND) {
        uVar12 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),iAction);
        if ((((int)uVar12 == 0) && (0x430 < wParam)) && (wParam < 0x435)) {
          iResTechNow = wParam - 0x431;
          EnableZipBtns(hwnd,iResTechNow);
          InvalidateRect(hwnd,(RECT *)0x0,1);
        }
        else {
          if ((wParam == 1) || (wParam == 2)) {
            hwndZipOrderDlg = 0;
            StickyDlgPos(hwnd,(POINT *)&ptStickyZipOrderDlg,0);
            EndDialog(hwnd,(uint)(wParam == 1));
            if (((uint)gd.grBits >> 0xb & 1) != 0) {
              AdvanceTutor();
            }
            return 1;
          }
          if ((wParam == 0x816) || (wParam == 0x41b)) {
            if (*(char *)((int)&vrgZip[0].fValid + iResTechNow * 0x18) == '\0')
            {
              sVar6 = iResTechNow;
              pcVar4 = PszGetCompressedString(idsCustomD);
              _wsprintf(szWork,pcVar4,sVar6);
            }
            else {
              _strcpy((char *)szWork,
                              (char *)((int)vrgZip[0].szName +
                                      iResTechNow * 0x18));
            }
            pcVar13 = MakeProcInstance(RenameZipDlg,hInst);
            hwndRad = (HWND)((ulong)pcVar13 >> 0x10);
            psz = (char *)pcVar13;
            sVar6 = DialogBox(0,(LPCSTR)CONCAT22(0x7e3,hwndFrame),hwndRad,(char)pcVar13);
            if (sVar6 != 0) {
              if (szWork[0] == '\0') {
                sVar6 = iResTechNow;
                pcVar4 = PszGetCompressedString(idsCustomD);
                _wsprintf(szWork,pcVar4,sVar6);
              }
              _strcpy((char *)((int)vrgZip[0].szName +
                                      iResTechNow * 0x18),(char *)szWork);
              rcGBox = (char *)szWork + 0x40;
              pszT = (char *)szWork;
              pcVar4 = rcGBox;
              while (rcGBox = pcVar4, *pszT != '\0') {
                pcVar14 = pszT + 1;
                cVar3 = *pszT;
                *rcGBox = cVar3;
                pcVar4 = rcGBox + 1;
                pszT = pcVar14;
                if (cVar3 == '&') {
                  rcGBox[1] = '&';
                  pcVar4 = rcGBox + 2;
                }
              }
              *rcGBox = '\0';
              HVar5 = GetDlgItem(hwnd,iResTechNow + 0x431);
              SetWindowText(HVar5,szWork + 0x40);
              if (wParam == 0x816) {
                *(undefined1 *)((int)&vrgZip[0].fValid + iResTechNow * 0x18) = 1
                ;
                uVar15 = sel.fl.lpplord._2_2_;
                puVar9 = (ushort *)
                         ((int)(PLORD *)sel.fl.lpplord + sel.iwpAct * 0x12 + 0xc
                         );
                pZVar10 = (ZIPORDER *)vrgZip + iResTechNow;
                for (iVar7 = 5; iVar7 != 0; iVar7 = iVar7 + -1) {
                  pZVar2 = pZVar10;
                  pZVar10 = (pZVar10->txp).rgia + 1;
                  puVar1 = puVar9;
                  puVar9 = puVar9 + 1;
                  (pZVar2->txp).rgia[0].wFlags = *puVar1;
                }
                InvalidateRect(hwnd,(RECT *)0x0,1);
              }
              EnableZipBtns(hwnd,iResTechNow);
            }
            FreeProcInstance((char *)CONCAT22(hwndRad,psz));
            SetFocus(hwnd);
            gd.grBits2._0_2_ = (uint)gd.grBits2 & 0xffef | 0x10;
          }
          else if (wParam == 0x817) {
            *(undefined1 *)((int)&vrgZip[0].fValid + iResTechNow * 0x18) = 0;
            iVar7 = iResTechNow + 1;
            pcVar4 = PszGetCompressedString(idsUnusedD);
            _wsprintf(szWork,pcVar4,iVar7);
            HVar5 = GetDlgItem(hwnd,iResTechNow + 0x431);
            SetWindowText(HVar5,szWork);
            InvalidateRect(hwnd,(RECT *)0x0,1);
            gd.grBits2._0_2_ = (uint)gd.grBits2 & 0xffef | 0x10;
          }
          else if (wParam == 0x76) {
            WinHelp(hwnd,_szHelpFile,1,0x44a);
            return 1;
          }
        }
      }
    }
    sVar6 = 0;
  }
  return sVar6;
}



// ======================================================================
// Function: EnableZipBtns
// Address: 1080:0832
// Segment: MEMORY_SHIP2
// ======================================================================


void EnableZipBtns(HWND hwnd,short iSel)

{
  uint uVar1;
  HWND HVar2;
  short fEnabled;
  
  uVar1 = (uint)*(byte *)((int)&vrgZip[0].fValid + iSel * 0x18);
  HVar2 = GetDlgItem(hwnd,0x817);
  EnableWindow(HVar2,uVar1);
  HVar2 = GetDlgItem(hwnd,0x41b);
  EnableWindow(HVar2,uVar1);
  return;
}



// ======================================================================
// Function: RenameZipDlg
// Address: 1080:0880
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RenameZipDlg(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  char *pcVar1;
  HWND HVar2;
  uint uVar3;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar4;
  ushort in_stack_0000fff2;
  short ids;
  
  if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,&stack0xfff2);
    FillRect(wParam,&stack0xfff2,hbrButtonFace);
    return 1;
  }
  if (message == WM_CTLCOLOR) {
    uVar4 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000fff2);
    if ((int)uVar4 == 6) {
      SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
      return hbrButtonFace;
    }
  }
  else {
    if (message == WM_INITDIALOG) {
      if (hwndZipOrderDlg == 0) {
        ids = 0x4c3;
      }
      else {
        ids = 0x4c2;
      }
      HVar2 = hwnd;
      pcVar1 = PszGetCompressedString(ids);
      SetWindowText(HVar2,pcVar1);
      SetWindowPos(hwnd,0,ptStickyRenameDlg.x + 0x46,ptStickyRenameDlg.y + 0x46,0,0,
                   0x15);
      SendDlgItemMessage(hwnd,0x10c,0x415,0xc,0);
      HVar2 = GetDlgItem(hwnd,0x10c);
      SetWindowText(HVar2,szWork);
      StickyDlgPos(hwnd,(POINT *)&ptStickyRenameDlg,1);
      return 1;
    }
    if (message == WM_COMMAND) {
      if ((wParam == 1) || (wParam == 2)) {
        if (wParam == 1) {
          GetDlgItemText(hwnd,0x10c,szWork,0xe);
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyRenameDlg,0);
        EndDialog(hwnd,(uint)(wParam == 1));
        return 1;
      }
      if (wParam == 0x76) {
        if (hwndZipOrderDlg == 0) {
          uVar3 = 0x452;
        }
        else {
          uVar3 = 0xc1f;
        }
        WinHelp(hwnd,_szHelpFile,1,(ulong)uVar3);
        return 1;
      }
    }
  }
  return 0;
}



// ======================================================================
// Function: RenameDlg
// Address: 1080:0a68
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short RenameDlg(HWND hwnd,WMType message,ushort wParam,long lParam)

{
  char *pcVar1;
  HWND HVar2;
  short sVar3;
  undefined2 uVar4;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 unaff_SS;
  ulong uVar5;
  LRESULT LVar6;
  ushort in_stack_0000fff0;
  RECT rc;
  
  if (message == WM_ERASEBKGND) {
    GetClientRect(hwnd,&rc);
    FillRect(wParam,&rc,hbrButtonFace);
    sVar3 = 1;
  }
  else {
    if (message == WM_CTLCOLOR) {
      uVar5 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000fff0);
      if ((int)uVar5 == 6) {
        SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace))
        ;
        return hbrButtonFace;
      }
    }
    else {
      if (message == WM_INITDIALOG) {
        HVar2 = hwnd;
        pcVar1 = PszGetCompressedString(idsRenameFleet);
        SetWindowText(HVar2,pcVar1);
        SetWindowPos(hwnd,0,ptStickyRenameDlg.x + 0x46,ptStickyRenameDlg.y + 0x46,0,0,
                     0x15);
        SendDlgItemMessage(hwnd,0x10c,0x415,0x1f,0);
        HVar2 = GetDlgItem(hwnd,0x10c);
        SetWindowText(HVar2,szWork);
        StickyDlgPos(hwnd,(POINT *)&ptStickyRenameDlg,1);
        return 1;
      }
      if (message == WM_COMMAND) {
        if ((wParam == 1) || (wParam == 2)) {
          if (wParam == 1) {
            GetDlgItemText(hwnd,0x10c,szWork,0x20);
            FStringFitsScreen(szWork,0xa0);
          }
          StickyDlgPos(hwnd,(POINT *)&ptStickyRenameDlg,0);
          EndDialog(hwnd,(uint)(wParam == 1));
          return 1;
        }
        if (((wParam == 0x10c) &&
            (uVar5 = __aFulshr(CONCAT22(unaff_SI,unaff_DI),in_stack_0000fff0),
            (int)uVar5 == 0x400)) && (fInEditUpdate == 0)) {
          fInEditUpdate = 1;
          GetWindowText((HWND)lParam,szWork,0xfa);
          LVar6 = SendMessage((HWND)lParam,0x400,0,0);
          uVar4 = (undefined2)LVar6;
          sVar3 = FStringFitsScreen(szWork,0xa0);
          if (sVar3 == 0) {
            SetWindowText((HWND)lParam,szWork);
            SendMessage((HWND)lParam,0x401,0,CONCAT22((int)((ulong)LVar6 >> 0x10),uVar4));
          }
          fInEditUpdate = 0;
        }
        else if (wParam == 0x76) {
          WinHelp(hwnd,_szHelpFile,1,0x447);
          return 1;
        }
      }
    }
    sVar3 = 0;
  }
  return sVar3;
}



// ======================================================================
// Function: FStargateJump
// Address: 1080:0cfe
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x108013ce) */
/* WARNING: Removing unreachable block (ram,0x1080144f) */
/* WARNING: Removing unreachable block (ram,0x1080147f) */

short FStargateJump(FLEET *lpfl,short isbsSrc,short isbsDst,short dDist)

{
  FLEET *pFVar1;
  FLEET *pFVar2;
  short sVar3;
  uint uVar4;
  int iVar5;
  PLORD *pPVar6;
  undefined2 unaff_SI;
  FLEET *pFVar7;
  FLEET *pFVar8;
  undefined2 unaff_DI;
  undefined2 uVar9;
  undefined2 unaff_SS;
  bool bVar10;
  ulong uVar11;
  long lVar12;
  ulong uVar13;
  long lVar14;
  undefined4 uVar15;
  ushort in_stack_0000feb8;
  FLEET flDead;
  short cshDamagedOld;
  short dpPerShdefOld;
  undefined4 dp;
  short ishdef;
  short cshdef;
  short rgpct [16];
  short pct;
  uint cshKill;
  int local_98;
  short idm;
  uint cshOrig;
  int local_92;
  short i;
  byte pctKill;
  short cshT;
  FLEET flSrc;
  short id;
  int pt;
  ushort local_a;
  short dpShdef;
  short dpPerShdefNew;
  
  lVar14 = CONCAT22(unaff_SI,unaff_DI);
  cshdef = 0;
  cshKill = 0;
  local_98 = 0;
  cshOrig = 0;
  local_92 = 0;
  _memset(rgpct,0,0x20);
  pFVar8 = &flSrc;
  pFVar7 = (FLEET *)lpfl;
  for (iVar5 = 0x3e; iVar5 != 0; iVar5 = iVar5 + -1) {
    pFVar2 = pFVar8;
    pFVar8 = &pFVar8->iPlayer;
    pFVar1 = pFVar7;
    pFVar7 = &pFVar7->iPlayer;
    pFVar2->id = pFVar1->id;
  }
  uVar9 = (undefined2)((ulong)flSrc.lpplord >> 0x10);
  pPVar6 = (PLORD *)flSrc.lpplord;
  if (((pPVar6 + 7)->wFlags >> 8 & 0xf) == 1) {
    id = *(short *)&pPVar6[6].iordMax;
  }
  else {
    pt = *(int *)&pPVar6[5].iordMax;
    local_a = (pPVar6 + 6)->wFlags;
    id = 0;
    while ((id < game.cPlanMax &&
           ((*(int *)&pPVar6[5].iordMax != ((POINT *)rgptPlan + id)->x ||
            ((pPVar6 + 6)->wFlags != *(ushort *)((int)&rgptPlan[0].y + id * 4)))))) {
      id = id + 1;
    }
  }
  ishdef = 0;
  do {
    if (0xf < ishdef) {
      if (cshdef != 0) {
        _memset(&flDead,0,0x7c);
        for (ishdef = 0; ishdef < 0x10; ishdef = ishdef + 1) {
          if ((flSrc.rgcsh[ishdef] != 0) && (rgpct[ishdef] != 0)) {
            if (rgpct[ishdef] == 100) {
              uVar4 = flSrc.rgcsh[ishdef];
              bVar10 = CARRY2(cshKill,uVar4);
              cshKill = cshKill + uVar4;
              local_98 = local_98 + ((int)uVar4 >> 0xf) + (uint)bVar10;
              flSrc.rgcsh[ishdef] = 0;
              flSrc.rgcsh[ishdef + 0x10] = 0;
              cshdef = cshdef + -1;
            }
            else {
              cshT = flSrc.rgcsh[ishdef];
              sVar3 = GetRaceStat((PLAYER *)rgplr + ((FLEET *)lpfl)->iPlayer,
                                        rsMajorAdv);
              if (sVar3 == raStargate) {
                pctKill = 0;
              }
              else {
                pctKill = (byte)(rgpct[ishdef] / 3);
              }
              iVar5 = ((FLEET *)lpfl)->iPlayer * 4;
              dpShdef = *(short *)(*(int *)(iVar5 + 0xfe) + ishdef * 0x93 + 0x38);
              if (flSrc.rgcsh[ishdef + 0x10] == 0) {
                cshDamagedOld = 0;
              }
              else {
                lVar12 = 100;
                uVar11 = __aFulmul((long)cshT,
                                           (ulong)(uint)flSrc.rgcsh[ishdef + 0x10] & 0xffff007f);
                lVar12 = __aFldiv(uVar11,lVar12);
                cshDamagedOld = (short)lVar12;
                if (cshDamagedOld == 0) {
                  cshDamagedOld = 1;
                }
              }
              if (pctKill != 0) {
                for (i = 0; i < flSrc.rgcsh[ishdef]; i = i + 1) {
                  sVar3 = Random(100);
                  if ((sVar3 < (int)(uint)pctKill) && (cshT = cshT + -1, cshDamagedOld != 0)) {
                    uVar4 = Random(500);
                    if (uVar4 < (uint)flSrc.rgcsh[ishdef + 0x10] >> 7) {
                      cshDamagedOld = cshDamagedOld + -1;
                    }
                  }
                }
                uVar4 = flSrc.rgcsh[ishdef] - cshT;
                bVar10 = CARRY2(cshKill,uVar4);
                cshKill = cshKill + uVar4;
                local_98 = local_98 + ((int)uVar4 >> 0xf) + (uint)bVar10;
              }
              if (cshT != 0) {
                if (flSrc.rgcsh[ishdef + 0x10] == 0) {
                  dpPerShdefOld = 0;
                }
                else {
                  lVar12 = 500;
                  uVar11 = __aFulmul((long)dpShdef,
                                             (ulong)((uint)flSrc.rgcsh[ishdef + 0x10] >> 7));
                  lVar12 = __aFldiv(uVar11,lVar12);
                  dpPerShdefOld = (short)lVar12;
                  if (dpPerShdefOld == 0) {
                    dpPerShdefOld = 1;
                  }
                }
                lVar12 = 100;
                uVar11 = __aFulmul((long)dpShdef,(long)rgpct[ishdef]);
                lVar12 = __aFldiv(uVar11,lVar12);
                dpPerShdefNew = (int)lVar12;
                if ((int)lVar12 == 0) {
                  dpPerShdefNew = 1;
                }
                if ((cshDamagedOld != 0) && (dpShdef <= dpPerShdefNew + dpPerShdefOld)) {
                  bVar10 = CARRY2(cshKill,cshDamagedOld);
                  cshKill = cshKill + cshDamagedOld;
                  local_98 = local_98 + (cshDamagedOld >> 0xf) + (uint)bVar10;
                  cshT = cshT - cshDamagedOld;
                }
                if (cshT != 0) {
                  uVar11 = __aFulmul((long)dpPerShdefOld,(long)cshDamagedOld);
                  in_stack_0000feb8 = (ushort)uVar11;
                  uVar13 = __aFulmul((long)dpPerShdefNew,(long)cshT);
                  dp = uVar13 + CONCAT22((int)(uVar11 >> 0x10),in_stack_0000feb8);
                  lVar12 = (long)dpShdef;
                  uVar13 = 500;
                  uVar11 = __aFldiv(dp,(long)cshT);
                  uVar11 = __aFulmul(uVar11,uVar13);
                  lVar12 = __aFldiv(uVar11,lVar12);
                  pct = (int)lVar12;
                  if ((int)lVar12 == 0) {
                    pct = 1;
                  }
                  flSrc.rgcsh[ishdef + 0x10] = flSrc.rgcsh[ishdef + 0x10] & 0x7fU | pct << 7;
                  flSrc.rgcsh[ishdef + 0x10] = flSrc.rgcsh[ishdef + 0x10] & 0xff80U | 100;
                }
              }
              flSrc.rgcsh[ishdef] = cshT;
              if (cshT == 0) {
                flSrc.rgcsh[ishdef + 0x10] = 0;
                cshdef = cshdef + -1;
              }
            }
            flDead.rgcsh[ishdef] = ((FLEET *)lpfl)->rgcsh[ishdef] - flSrc.rgcsh[ishdef];
          }
        }
        if (cshdef != 0) {
          if ((cshKill != 0) || (local_98 != 0)) {
            if (local_98 == 0) {
              lVar12 = __aFlshr(lVar14,in_stack_0000feb8);
              if (CONCAT22(local_98,cshKill) < lVar12) {
                idm = 0xe8;
              }
              else {
                lVar14 = __aFlshr(lVar14,in_stack_0000feb8);
                if (lVar14 < CONCAT22(local_98,cshKill)) {
                  idm = 0xea;
                }
                else {
                  idm = 0xe9;
                }
              }
              FSendPlrMsg(((FLEET *)lpfl)->iPlayer,idm,lpfl->id | 0x8000,lpfl->id,
                               ((FLEET *)lpfl)->idPlanet,id,cshKill,0,0,0);
            }
            else {
              uVar15 = 0;
              uVar11 = __aFulshr(0,(ushort)lVar14);
              FSendPlrMsg(((FLEET *)lpfl)->iPlayer,
                               idmUsedStargateReachLosingUnbelievableShipsJump,lpfl->id | 0x8000,
                               lpfl->id,((FLEET *)lpfl)->idPlanet,id,cshKill,(short)uVar11,
                               (short)uVar15,(short)((ulong)uVar15 >> 0x10));
            }
            flDead.iPlayer = flSrc.iPlayer;
            flDead.wFlags_0x4 = flDead.wFlags_0x4 & 0xfb00 | 0x407;
            FleetTransferCargoBalance(&flSrc,&flDead);
          }
          pFVar8 = &flSrc;
          for (iVar5 = 0x3e; iVar5 != 0; iVar5 = iVar5 + -1) {
            pFVar2 = (FLEET *)lpfl;
            lpfl._0_2_ = &((FLEET *)lpfl)->iPlayer;
            pFVar1 = pFVar8;
            pFVar8 = &pFVar8->iPlayer;
            pFVar2->id = pFVar1->id;
          }
          return 1;
        }
      }
      ((FLEET *)lpfl)->wFlags_0x4 = ((FLEET *)lpfl)->wFlags_0x4 & 0xfbff | 0x400;
      FSendPlrMsg(flSrc.iPlayer,idmHeedlessDangerAttemptedUseStargateReachFleet,
                       flSrc.id | 0x8000,flSrc.id,flSrc.idPlanet,id,0,0,0,0);
      return 0;
    }
    if (flSrc.rgcsh[ishdef] != 0) {
      cshdef = cshdef + 1;
      uVar4 = flSrc.rgcsh[ishdef];
      bVar10 = CARRY2(cshOrig,uVar4);
      cshOrig = cshOrig + uVar4;
      local_92 = local_92 + ((int)uVar4 >> 0xf) + (uint)bVar10;
      sVar3 = MdCalcStargateDamage
                        (isbsSrc,isbsDst,dDist,
                         *(short *)(*(int *)(flSrc.iPlayer * 4 + 0xfe) + ishdef * 0x93 + 0x28),
                         rgpct + ishdef);
      if (sVar3 == -2) {
        FSendPlrMsg(flSrc.iPlayer,idmAttemptedUseStargateReachCouldBecauseShips,
                         flSrc.id | 0x8000,flSrc.id,flSrc.idPlanet,id,ishdef,0,0,0);
        return 0;
      }
      if (sVar3 == -1) {
        FSendPlrMsg(flSrc.iPlayer,idmAttemptedUseStargateReachCouldBecauseDestination,
                         flSrc.id | 0x8000,flSrc.id,flSrc.idPlanet,id,0,0,0,0);
        return 0;
      }
      if (sVar3 == 0) {
        cshdef = cshdef + -1;
      }
      else if (sVar3 == 1) {
        flSrc.wFlags_0x4 = flSrc.wFlags_0x4 & 0xbfff | 0x4000;
      }
    }
    ishdef = ishdef + 1;
  } while( true );
}



// ======================================================================
// Function: MdCalcStargateDamage
// Address: 1080:152e
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x108015a5) */
/* WARNING: Removing unreachable block (ram,0x1080178c) */
/* WARNING: Removing unreachable block (ram,0x108016f9) */
/* WARNING: Removing unreachable block (ram,0x1080183b) */

short MdCalcStargateDamage(short isbsSrc,short isbsDst,short dDist,short wt,short *ppctDmg)

{
  short sVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  ARMOR *pAVar5;
  undefined2 uVar6;
  ulong uVar7;
  ulong uVar8;
  long lVar9;
  ulong uVar10;
  char *pcVar11;
  uint pctSurvive;
  int local_1e;
  PART partSrc;
  PART partDst;
  char *dBaseDistance;
  int local_6;
  
  uVar8 = 10000;
  partDst.hs.grhst = hstSpecialSB;
  partSrc.hs.grhst = hstSpecialSB;
  partSrc.hs.wFlags_0x2 = partSrc.hs.wFlags_0x2 & 0xff00 | isbsSrc & 0xffU;
  partDst.hs.wFlags_0x2 = partDst.hs.wFlags_0x2 & 0xff00 | isbsDst & 0xffU;
  FLookupPart(&partSrc);
  FLookupPart(&partDst);
  dBaseDistance = (char *)((BEAM *)partSrc.u_PART_0x0004.pbeam)->dp;
  local_6 = (int)dBaseDistance >> 0xf;
  if (dBaseDistance == (char *)0xffff) {
    dBaseDistance = (char *)s_R6008___not_enough_space_for_arg_1120_1f2d + 0x13;
    local_6 = 0;
  }
  iVar2 = dDist >> 0xf;
  uVar7 = __aFulmul(CONCAT22(local_6,dBaseDistance),5);
  iVar3 = (int)(uVar7 >> 0x10);
  if ((iVar3 <= iVar2) && ((iVar3 < iVar2 || ((uint)uVar7 < (uint)dDist)))) {
    return -1;
  }
  iVar3 = wt >> 0xf;
  if (0 < ((ARMOR *)partSrc.u_PART_0x0004.parmor)->dp) {
    uVar7 = __aFulmul((long)((ARMOR *)partSrc.u_PART_0x0004.parmor)->dp,5);
    iVar4 = (int)(uVar7 >> 0x10);
    if (iVar4 < iVar3) {
      return -2;
    }
    if ((iVar4 <= iVar3) && ((uint)uVar7 < (uint)wt)) {
      return -2;
    }
  }
  if (0 < ((ARMOR *)partDst.u_PART_0x0004.parmor)->dp) {
    uVar7 = __aFulmul((long)((ARMOR *)partDst.u_PART_0x0004.parmor)->dp,5);
    iVar4 = (int)(uVar7 >> 0x10);
    if ((iVar4 <= iVar3) && ((iVar4 < iVar3 || ((uint)uVar7 < (uint)wt)))) {
      return -2;
    }
  }
  if ((iVar2 < local_6) || ((iVar2 <= local_6 && (uVar8 = 10000, (uint)dDist <= dBaseDistance)))) {
LAB_1080_170f:
    uVar6 = partSrc.u_PART_0x0004._2_2_;
    pAVar5 = (ARMOR *)partSrc.u_PART_0x0004.parmor;
    if ((pAVar5->dp < wt) && (0 < pAVar5->dp)) {
      lVar9 = (long)pAVar5->dp;
      uVar10 = 0x9c4;
      uVar7 = __aFulmul((long)pAVar5->dp,5);
      uVar7 = __aFulmul(uVar7 - (long)wt,uVar10);
      uVar7 = __aFldiv(uVar7,lVar9);
      if ((long)uVar7 < 1) goto SHIP2_TotalDeath;
      lVar9 = 10000;
      uVar8 = __aFulmul(uVar8,uVar7);
      uVar8 = __aFldiv(uVar8,lVar9);
    }
    uVar6 = partDst.u_PART_0x0004._2_2_;
    pAVar5 = (ARMOR *)partDst.u_PART_0x0004.parmor;
    if ((pAVar5->dp < wt) && (0 < pAVar5->dp)) {
      lVar9 = (long)pAVar5->dp;
      uVar10 = 0x9c4;
      uVar7 = __aFulmul((long)pAVar5->dp,5);
      uVar7 = __aFulmul(uVar7 - (long)wt,uVar10);
      uVar7 = __aFldiv(uVar7,lVar9);
      if ((long)uVar7 < 1) goto SHIP2_TotalDeath;
      lVar9 = 10000;
      uVar8 = __aFulmul(uVar8,uVar7);
      uVar8 = __aFldiv(uVar8,lVar9);
    }
    local_1e = (int)(uVar8 >> 0x10);
    pctSurvive = (uint)uVar8;
    lVar9 = __aFldiv(CONCAT22(-(uint)(10000 < pctSurvive) - local_1e,10000 - pctSurvive),100
                            );
    *ppctDmg = (short)lVar9;
    sVar1 = 1;
  }
  else {
    pcVar11 = (char *)CONCAT22(local_6,dBaseDistance);
    uVar7 = 0x9c4;
    uVar8 = __aFulmul(CONCAT22(local_6,dBaseDistance),5);
    uVar8 = __aFulmul(uVar8 - (long)dDist,uVar7);
    uVar8 = __aFldiv(uVar8,(long)pcVar11);
    if (0 < (long)uVar8) goto LAB_1080_170f;
SHIP2_TotalDeath:
    *ppctDmg = 100;
    sVar1 = 0;
  }
  return sVar1;
}



// ======================================================================
// Function: KillUsedWaypoints
// Address: 1080:189a
// Segment: MEMORY_SHIP2
// ======================================================================


void KillUsedWaypoints(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  FLEET *pFVar3;
  int iVar4;
  short sVar5;
  int iVar6;
  FLEET *pFVar7;
  short *psVar8;
  PLORD *pPVar9;
  undefined2 *puVar10;
  undefined2 *puVar11;
  undefined2 uVar12;
  undefined2 uVar13;
  FLEET *pFVar14;
  PLANET *pPVar15;
  PLANET *lppl;
  short fRep;
  FLEET *lpfl;
  short i;
  short j;
  
  if (0 < cFleet) {
    for (i = 0; i < cFleet; i = i + 1) {
                    /* WARNING: Load size is inaccurate */
      pFVar3 = ((FLEET **)rglpfl)[i];
      iVar4 = *(int *)((int)((FLEET **)rglpfl + i) + 2);
      lpfl = (FLEET *)CONCAT22(iVar4,pFVar3);
      if ((pFVar3 == (FLEET *)0x0) && (iVar4 == 0)) {
        return;
      }
      if (1 < pFVar3->cord) {
        if ((int)pFVar3->wFlags_0x4 < 0) {
          DeleteWpFar((FLEET *)CONCAT22(iVar4,pFVar3),1,0);
          FSendPlrMsg(pFVar3->iPlayer,idmHasExecutedOrdersFollowFleetAwaitsFurther,
                           lpfl->id | 0x8000,lpfl->id,0,0,0,0,0,0);
        }
        else {
          for (j = 1; j < pFVar3->cord; j = j + 1) {
            if ((*(uint *)(*(int *)&pFVar3->lpplord + j * 0x12 + 10) >> 8 & 0xf) == 2) {
              pFVar14 = LpflFromId(*(short *)(*(int *)&pFVar3->lpplord + j * 0x12 + 8));
              *(FLEET **)&pFVar3->lpflNext = (FLEET *)pFVar14;
              *(undefined2 *)((int)&pFVar3->lpflNext + 2) = (int)((ulong)pFVar14 >> 0x10);
              if ((*(int *)&pFVar3->lpflNext == 0) && (*(int *)((int)&pFVar3->lpflNext + 2) == 0)) {
                lppl._2_2_ = *(uint *)(*(int *)&pFVar3->lpplord + j * 0x12 + 10) & 0xf0ff | 0x400;
                *(uint *)(*(int *)&pFVar3->lpplord + j * 0x12 + 10) = lppl._2_2_;
                *(undefined2 *)(*(int *)&pFVar3->lpplord + j * 0x12 + 8) = 0;
              }
              else {
                if ((*(uint *)(*(int *)&pFVar3->lpplord + j * 0x12 + 10) >> 0xd & 1) == 0) {
                  uVar12 = (undefined2)((ulong)pFVar3->lpflNext >> 0x10);
                  pFVar7 = (FLEET *)pFVar3->lpflNext;
                  sVar5 = (pFVar7->pt).y;
                  uVar13 = *(undefined2 *)((int)&pFVar3->lpplord + 2);
                  psVar8 = (short *)(*(int *)&pFVar3->lpplord + 4 + j * 0x12);
                  *psVar8 = (&pFVar7->pt)->x;
                  psVar8[1] = sVar5;
                }
                *(undefined2 *)&pFVar3->lpflNext = 0;
                *(undefined2 *)((int)&pFVar3->lpflNext + 2) = 0;
              }
            }
          }
          uVar13 = (undefined2)((ulong)pFVar3->lpplord >> 0x10);
          pPVar9 = (PLORD *)pFVar3->lpplord;
          if (((&pFVar3->pt)->x == *(int *)&pPVar9[5].iordMax) &&
             ((pFVar3->pt).y == (pPVar9 + 6)->wFlags)) {
            uVar13 = *(undefined2 *)((int)&pFVar3->lpplord + 2);
            puVar10 = (undefined2 *)(*(int *)&pFVar3->lpplord + 0x16);
            uVar12 = *(undefined2 *)((int)&pFVar3->lpplord + 2);
            puVar11 = (undefined2 *)(*(int *)&pFVar3->lpplord + 4);
            for (iVar6 = 9; iVar6 != 0; iVar6 = iVar6 + -1) {
              puVar2 = puVar11;
              puVar11 = puVar11 + 1;
              puVar1 = puVar10;
              puVar10 = puVar10 + 1;
              *puVar2 = *puVar1;
            }
            if ((((*(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax >> 8 & 0xf) == 2) &&
                ((*(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf) != 1)) &&
               ((*(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf) != 4)) {
              if (pFVar3->idPlanet == -1) {
                *(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax =
                     *(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf0ff | 0x400;
                ((PLORD *)pFVar3->lpplord + 2)->wFlags = 0;
              }
              else {
                *(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax =
                     *(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf0ff | 0x100;
                ((PLORD *)pFVar3->lpplord + 2)->wFlags = pFVar3->idPlanet;
              }
            }
            if (((((PLORD *)pFVar3->lpplord + 7)->wFlags & 0xf) == 7) &&
               ((((PLORD *)pFVar3->lpplord + 7)->wFlags >> 8 & 0xf) == 2)) {
              fRep = 0;
            }
            else {
              fRep = pFVar3->wFlags_0x4 >> 9 & 1;
            }
            DeleteWpFar(lpfl,1,fRep);
            if (pFVar3->cord == 1) {
              switch(*(uint *)&((PLORD *)pFVar3->lpplord)[2].iordMax & 0xf) {
              case 1:
              case 2:
              case 3:
              case 5:
              case 6:
              case 7:
                break;
              case 8:
                if (pFVar3->idPlanet != -1) {
                  pPVar15 = LpplFromId(pFVar3->idPlanet);
                  uVar13 = (undefined2)((ulong)pPVar15 >> 0x10);
                  if ((((PLANET *)pPVar15)->iPlayer == pFVar3->iPlayer) &&
                     ((((PLANET *)pPVar15)->wRouting & 0x3ff) != 0)) break;
                }
              default:
                FSendPlrMsg(pFVar3->iPlayer,idmHasCompletedAssignedOrders,lpfl->id | 0x8000,
                                 lpfl->id,0,0,0,0,0,0);
              }
            }
          }
        }
      }
    }
  }
  return;
}



// ======================================================================
// Function: NoAutoTrackFleet
// Address: 1080:1d32
// Segment: MEMORY_SHIP2
// ======================================================================


void NoAutoTrackFleet(FLEET *lpflTarget)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  short sVar5;
  FLEET *pFVar6;
  ORDER *pOVar7;
  undefined2 uVar8;
  undefined2 uVar9;
  FLEET *lpfl;
  short ifl;
  ORDER *lpord;
  short i;
  short idTarget;
  short iplr;
  
  uVar8 = (undefined2)((ulong)lpflTarget >> 0x10);
  pFVar6 = (FLEET *)lpflTarget;
  iVar1 = pFVar6->iPlayer;
  iVar2 = lpflTarget->id;
  ifl = 0;
  while( true ) {
    if (cFleet <= ifl) {
      return;
    }
    iVar3 = *(int *)((FLEET **)rglpfl + ifl);
    iVar4 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
    if ((iVar3 == 0) && (iVar4 == 0)) break;
    if ((*(int *)(iVar3 + 2) != iVar1) && (1 < *(int *)(iVar3 + 0x62))) {
      lpord = (ORDER *)CONCAT22(*(undefined2 *)(iVar3 + 0x66),
                                (ORDER *)(*(int *)(iVar3 + 100) + 0x16));
      for (i = 1; i < *(int *)(iVar3 + 0x62); i = i + 1) {
        uVar9 = (undefined2)((ulong)lpord >> 0x10);
        pOVar7 = (ORDER *)lpord;
        if (((pOVar7->wFlags_0x6 >> 8 & 0xf) == 2) && (pOVar7->id == iVar2)) {
          pOVar7->wFlags_0x6 = pOVar7->wFlags_0x6 & 0xdfff | 0x2000;
          sVar5 = (pFVar6->pt).y;
          (lpord->pt).x = (&pFVar6->pt)->x;
          (pOVar7->pt).y = sVar5;
        }
        lpord = (ORDER *)CONCAT22(uVar9,pOVar7 + 1);
      }
    }
    ifl = ifl + 1;
  }
  return;
}



// ======================================================================
// Function: AutoRouteFleet
// Address: 1080:1e52
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Variable defined which should be unmapped: isbsSrc */
/* WARNING: Removing unreachable block (ram,0x10802151) */
/* WARNING: Removing unreachable block (ram,0x108021f3) */

void AutoRouteFleet(FLEET *lpfl,PLANET *lppl)

{
  int iVar1;
  undefined2 uVar2;
  undefined2 uVar3;
  PLANET *pPVar4;
  short sVar5;
  short isbsSrc_00;
  undefined2 uVar6;
  int iVar7;
  FLEET *pFVar8;
  PLANET *pPVar9;
  int iVar10;
  short unaff_SI;
  undefined2 uVar11;
  undefined2 uVar12;
  PLANET *lppl_00;
  HULDEF *pHVar13;
  long lVar14;
  long lVar15;
  short isbsSrc;
  short ishdefBig;
  short ishdef;
  short wtBig;
  short isbsDst;
  PLANET *lpplRoute;
  ORDER *lpord;
  short i;
  short wt;
  short pctDmg;
  short iWarp;
  long dTravel;
  
  uVar11 = (undefined2)((ulong)lpfl >> 0x10);
  pFVar8 = (FLEET *)lpfl;
  pFVar8->cord = 2;
  ((PLORD *)pFVar8->lpplord)->iordMac = 2;
  iVar1 = *(int *)&pFVar8->lpplord;
  uVar2 = *(undefined2 *)((int)&pFVar8->lpplord + 2);
  lpord = (ORDER *)CONCAT22(uVar2,(ORDER *)(iVar1 + 0x16));
  *(uint *)(iVar1 + 0x1c) = *(uint *)(iVar1 + 0x1c) & 0xfff0 | 8;
  *(uint *)(iVar1 + 0x1c) = *(uint *)(iVar1 + 0x1c) & 0xf0ff | 0x100;
  uVar12 = (undefined2)((ulong)lppl >> 0x10);
  pPVar9 = (PLANET *)lppl;
  *(int *)(iVar1 + 0x1a) = (pPVar9->wRouting & 0x3ff) - 1;
  lppl_00 = LpplFromId((pPVar9->wRouting & 0x3ff) - 1);
  uVar6 = (undefined2)((ulong)lppl_00 >> 0x10);
  pPVar4 = (PLANET *)lppl_00;
  iVar10 = (pPVar9->wRouting & 0x3ff) - 1;
  uVar3 = *(undefined2 *)((int)&rgptPlan[0].y + iVar10 * 4);
  (lpord->pt).x = ((POINT *)rgptPlan + iVar10)->x;
  *(undefined2 *)(iVar1 + 0x18) = uVar3;
  *(uint *)(iVar1 + 0x1c) = *(uint *)(iVar1 + 0x1c) & 0xefff | 0x1000;
  iWarp = IFindIdealWarp(lpfl,0);
  DGetDistance((double *)CONCAT22((pFVar8->pt).y,(double *)(&pFVar8->pt)->x),(lpord->pt).x,
                     *(short *)(iVar1 + 0x18),unaff_SI,isbsSrc);
  dTravel = __ftol((double)CONCAT26(ishdef,CONCAT24(ishdefBig,CONCAT22(isbsSrc,unaff_SI))));
  if (((pPVar9->iPlayer == pPVar4->iPlayer) && ((pPVar9->wFlags_0x4 >> 9 & 1) != 0)) &&
     ((pPVar4->wFlags_0x4 >> 9 & 1) != 0)) {
    sVar5 = IStargateFromLppl(lppl_00);
    isbsSrc_00 = IStargateFromLppl(lppl);
    i = 0;
    while (((i < 4 && ((int)pFVar8->rgwtMin[i] == 0)) &&
           (*(int *)((int)(pFVar8->rgwtMin + i) + 2) == 0))) {
      i = i + 1;
    }
    if (((i == 4) && (sVar5 != -1)) && (isbsSrc_00 != -1)) {
      wtBig = 0;
      for (ishdef = 0; ishdef < 0x10; ishdef = ishdef + 1) {
        iVar10 = wtBig;
        if ((pFVar8->rgcsh[ishdef] != 0) &&
           (iVar10 = pFVar8->iPlayer * 4,
           iVar10 = *(int *)(*(int *)(iVar10 + 0xfe) + ishdef * 0x93 + 0x28), iVar10 <= wtBig)) {
          iVar10 = wtBig;
        }
        wtBig = iVar10;
      }
      sVar5 = MdCalcStargateDamage(isbsSrc_00,sVar5,(short)dTravel,wtBig,&pctDmg);
      if ((sVar5 == 1) && (pctDmg == 0)) {
        iWarp = 0xb;
      }
    }
    if (iWarp < 9) {
      iVar10 = pFVar8->iPlayer * 4;
      pHVar13 = LphuldefFromId
                          (*(HullDef *)
                            (*(int *)(iVar10 + 0x14c) + (*(uint *)&pPVar4->lStarbase & 0xf) * 0x93))
      ;
      if ((((HULDEF *)pHVar13)->hul).wtCargoMax != 0) {
        for (iWarp = 9; 0 < iWarp; iWarp = iWarp + -1) {
          lVar14 = EstFuelUse(lpfl,0,iWarp,-1,1);
          if (dTravel <= lVar14) break;
        }
        *(uint *)(iVar1 + 0x1c) = *(uint *)(iVar1 + 0x1c) & 0xff0f | (iWarp & 0xfU) << 4;
      }
    }
  }
  if ((iWarp < 0xb) && (iWarp != 0)) {
    iVar10 = iWarp >> 0xf;
    sVar5 = iWarp;
    lVar14 = __aFldiv(dTravel,(long)iWarp);
    lVar14 = __aFldiv(lVar14,CONCAT22(iVar10,sVar5));
    do {
      if (iWarp < 3) goto LAB_1080_220b;
      iVar10 = iWarp + -1;
      iVar7 = iVar10 >> 0xf;
      iWarp = iVar10;
      lVar15 = __aFldiv(dTravel,(long)iVar10);
      lVar15 = __aFldiv(lVar15,CONCAT22(iVar7,iVar10));
    } while (lVar15 <= lVar14);
    iWarp = iWarp + 1;
LAB_1080_220b:
    do {
      if (iWarp == 0) break;
      lVar14 = EstFuelUse(lpfl,0,iWarp,dTravel,0);
      iVar7 = (int)((ulong)lVar14 >> 0x10);
      iVar10 = *(int *)((int)pFVar8->rgwtMin + 0x12);
      if ((iVar7 < iVar10) ||
         ((iVar7 <= iVar10 && ((uint)lVar14 <= *(uint *)(pFVar8->rgwtMin + 4))))) break;
      iWarp = iWarp + -1;
    } while( true );
  }
  *(uint *)(iVar1 + 0x1c) = *(uint *)(iVar1 + 0x1c) & 0xff0f | (iWarp & 0xfU) << 4;
  return;
}



// ======================================================================
// Function: FColonizer
// Address: 1080:227c
// Segment: MEMORY_SHIP2
// ======================================================================


short FColonizer(FLEET *lpfl)

{
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  ulong uVar1;
  long lVar2;
  short i;
  
  lVar2 = CONCAT22(unaff_SI,unaff_DI);
  i = 0;
  while( true ) {
    if (0xf < i) {
      return 0;
    }
    if ((((FLEET *)lpfl)->rgcsh[i] != 0) &&
       (uVar1 = __aFlshl(lVar2,1), (uVar1 & 0xc000) != 0)) break;
    i = i + 1;
  }
  return 1;
}



// ======================================================================
// Function: FScout
// Address: 1080:2322
// Segment: MEMORY_SHIP2
// ======================================================================


short FScout(FLEET *lpfl)

{
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  ulong uVar1;
  long lVar2;
  short i;
  
  lVar2 = CONCAT22(unaff_SI,unaff_DI);
  i = 0;
  while( true ) {
    if (0xf < i) {
      return 0;
    }
    if ((((FLEET *)lpfl)->rgcsh[i] != 0) && (uVar1 = __aFlshl(lVar2,1), (uVar1 & 0x70) != 0)
       ) break;
    i = i + 1;
  }
  return 1;
}



// ======================================================================
// Function: AutoFleetOrder
// Address: 1080:23c8
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10802543) */
/* WARNING: Removing unreachable block (ram,0x1080255a) */

void AutoFleetOrder(FLEET *lpfl,PLANET *lppl)

{
  int iVar1;
  undefined2 uVar2;
  FLEET *pFVar3;
  int iVar4;
  bool bVar5;
  short sVar6;
  FLEET *pFVar7;
  PLANET *pPVar8;
  undefined2 uVar9;
  undefined2 uVar10;
  long lVar11;
  short fFoundFleet;
  FLEET *lpflT;
  ORDER *lpord;
  short ifl;
  
  bVar5 = false;
  uVar9 = (undefined2)((ulong)lpfl >> 0x10);
  pFVar7 = (FLEET *)lpfl;
  iVar1 = *(int *)&pFVar7->lpplord;
  uVar2 = *(undefined2 *)((int)&pFVar7->lpplord + 2);
  uVar10 = (undefined2)((ulong)lppl >> 0x10);
  pPVar8 = (PLANET *)lppl;
  if (((pPVar8->iPlayer == -1) ||
      ((sVar6 = GetRaceStat((PLAYER *)rgplr + pFVar7->iPlayer,rsMajorAdv),
       sVar6 == raMacintosh && (pPVar8->iPlayer == pFVar7->iPlayer)))) &&
     (lVar11 = CMineFromLpfl(lpfl), lVar11 != 0)) {
    if (pPVar8->iPlayer == -1) {
      for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
        pFVar3 = ((FLEET **)rglpfl)[ifl];
        iVar4 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
        lpflT = (FLEET *)CONCAT22(iVar4,pFVar3);
        if ((pFVar3 == (FLEET *)0x0) && (iVar4 == 0)) break;
        if ((pFVar7->iPlayer <= pFVar3->iPlayer) &&
           (((pFVar3->wFlags_0x4 >> 10 & 1) == 0 && (lpfl != lpflT)))) {
          if (pFVar7->iPlayer < pFVar3->iPlayer) break;
          if (((((&pFVar3->pt)->x == (&pFVar7->pt)->x) && ((pFVar3->pt).y == (pFVar7->pt).y)) &&
              (lVar11 = CMineFromLpfl((FLEET *)CONCAT22(iVar4,pFVar3)), 0 < lVar11)) &&
             (lVar11 < 4000)) {
            bVar5 = true;
            break;
          }
        }
      }
    }
    if (bVar5) {
      *(uint *)(iVar1 + 10) = *(uint *)(iVar1 + 10) & 0xfff0 | 4;
      *(uint *)(iVar1 + 10) = *(uint *)(iVar1 + 10) & 0xf0ff | 0x200;
      *(short *)(iVar1 + 8) = lpflT->id;
    }
    else {
      *(uint *)(iVar1 + 10) = *(uint *)(iVar1 + 10) & 0xfff0 | 3;
    }
  }
  pFVar7->iplan = 0;
  return;
}



// ======================================================================
// Function: CMineFromLpfl
// Address: 1080:25d2
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10802697) */
/* WARNING: Removing unreachable block (ram,0x1080273a) */

long CMineFromLpfl(FLEET *lpfl)

{
  byte bVar1;
  long lVar2;
  HUL *pHVar3;
  int iVar4;
  HS *pHVar5;
  undefined2 uVar6;
  ulong uVar7;
  HS *lphs;
  short chs;
  PART part;
  HUL *lphuldef;
  short i;
  short j;
  ulong cMine;
  
  lVar2 = 0;
  for (i = 0; i < 0x10; i = i + 1) {
    if (0 < ((FLEET *)lpfl)->rgcsh[i]) {
      iVar4 = ((FLEET *)lpfl)->iPlayer * 4;
      uVar6 = *(undefined2 *)(iVar4 + 0x100);
      pHVar3 = (HUL *)(*(int *)(iVar4 + 0xfe) + i * 0x93);
      lphuldef = (HUL *)CONCAT22(uVar6,pHVar3);
      bVar1 = pHVar3->chs;
      cMine = 0;
      lphs = (HS *)CONCAT22(uVar6,pHVar3->rghs);
      for (j = 0; j < (int)(uint)bVar1; j = j + 1) {
        pHVar5 = (HS *)lphs;
        uVar6 = (undefined2)((ulong)lphs >> 0x10);
        if ((lphs->grhst == hstMining) && ((pHVar5->wFlags_0x2 & 0xff) < 7)) {
          part.hs.grhst = lphs->grhst;
          part.hs.wFlags_0x2 = pHVar5->wFlags_0x2;
          FLookupPart(&part);
          uVar7 = __aFulmul((ulong)(pHVar5->wFlags_0x2 >> 8),
                                    (long)((ARMOR *)part.u_PART_0x0004.parmor)->dp);
          cMine = uVar7 + cMine;
        }
        lphs = (HS *)CONCAT22(uVar6,pHVar5 + 1);
      }
      uVar7 = __aFulmul(cMine,(long)((FLEET *)lpfl)->rgcsh[i]);
      lVar2 = uVar7 + lVar2;
    }
  }
  if (3999 < lVar2) {
    lVar2 = 4000;
  }
  return lVar2;
}



// ======================================================================
// Function: PctTerraFromLpfl
// Address: 1080:275c
// Segment: MEMORY_SHIP2
// ======================================================================


long PctTerraFromLpfl(FLEET *lpfl)

{
  undefined2 uVar1;
  long lVar2;
  uint uVar3;
  int iVar4;
  bool bVar5;
  ulong uVar6;
  HS *lphs;
  short chs;
  HUL *lphuldef;
  uint pct;
  int local_e;
  short i;
  short j;
  
  lVar2 = 0;
  for (i = 0; i < 0x10; i = i + 1) {
    if (0 < ((FLEET *)lpfl)->rgcsh[i]) {
      iVar4 = ((FLEET *)lpfl)->iPlayer * 4;
      uVar1 = *(undefined2 *)(iVar4 + 0x100);
      iVar4 = *(int *)(iVar4 + 0xfe) + i * 0x93;
      pct = 0;
      local_e = 0;
      lphs = (HS *)CONCAT22(uVar1,(HS *)(iVar4 + 0x3a));
      for (j = 0; j < (int)(uint)*(byte *)(iVar4 + 0x7a); j = j + 1) {
        if ((lphs->grhst == hstMining) && ((((HS *)lphs)->wFlags_0x2 & 0xff) == 7)) {
          uVar3 = ((HS *)lphs)->wFlags_0x2 >> 8;
          bVar5 = CARRY2(pct,uVar3);
          pct = pct + uVar3;
          local_e = local_e + (uint)bVar5;
        }
        lphs = (HS *)lphs + 1;
      }
      uVar6 = __aFulmul(CONCAT22(local_e,pct),(long)((FLEET *)lpfl)->rgcsh[i]);
      lVar2 = uVar6 + lVar2;
    }
  }
  return lVar2;
}



// ======================================================================
// Function: CLayMinesFromLpfl
// Address: 1080:2886
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Variable defined which should be unmapped: lphs */
/* WARNING: Removing unreachable block (ram,0x10802adc) */

long CLayMinesFromLpfl(FLEET *lpfl,short iType,short ishdef)

{
  byte bVar1;
  HUL *pHVar2;
  int iVar3;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 uVar4;
  long lVar5;
  ulong uVar6;
  ulong uVar7;
  long lVar8;
  HS *lphs;
  short chs;
  PART part;
  HUL *lphul;
  short i;
  short j;
  undefined4 cMine;
  ushort iMax;
  ushort iMin;
  
  lVar8 = CONCAT22(unaff_SI,unaff_DI);
  uVar7 = 0;
  if (iType != -1) {
    if (iType == 0) {
      iMin = 0;
      iMax = 3;
      goto LAB_1080_28f9;
    }
    if (iType == 1) {
      iMin = 4;
      iMax = 6;
      goto LAB_1080_28f9;
    }
    if (iType == 2) {
      iMin = 7;
      iMax = 9;
      goto LAB_1080_28f9;
    }
  }
  iMin = 0;
  iMax = 9;
LAB_1080_28f9:
  for (i = 0; i < 0x10; i = i + 1) {
    if ((0 < ((FLEET *)lpfl)->rgcsh[i]) && ((ishdef == -1 || (i == ishdef)))) {
      iVar3 = ((FLEET *)lpfl)->iPlayer * 4;
      uVar4 = *(undefined2 *)(iVar3 + 0x100);
      pHVar2 = (HUL *)(*(int *)(iVar3 + 0xfe) + i * 0x93);
      lphul = (HUL *)CONCAT22(uVar4,pHVar2);
      bVar1 = pHVar2->chs;
      uVar6 = 0;
      lphs = (HS *)CONCAT22(uVar4,pHVar2->rghs);
      for (j = 0; cMine = uVar6, j < (int)(uint)bVar1; j = j + 1) {
        uVar4 = (undefined2)((ulong)lphs >> 0x10);
        if (((lphs->grhst == hstMines) && (iMin <= (((HS *)lphs)->wFlags_0x2 & 0xff))) &&
           ((((HS *)lphs)->wFlags_0x2 & 0xff) <= iMax)) {
          part.hs.grhst = lphs->grhst;
          part.hs.wFlags_0x2 = ((HS *)lphs)->wFlags_0x2;
          FLookupPart(&part);
          uVar6 = __aFulmul((ulong)(((HS *)lphs)->wFlags_0x2 >> 8),
                                    (long)((ARMOR *)part.u_PART_0x0004.parmor)->dp);
          uVar6 = uVar6 + cMine;
        }
        else if (((iType < 1) && (lphs->grhst == hstBeam)) &&
                ((((HS *)lphs)->wFlags_0x2 & 0xff) == 0x12)) {
          lVar5 = __aFlshl(lVar8,(ushort)(HS *)lphs);
          uVar6 = lVar5 + cMine;
        }
        lphs = (HS *)CONCAT22(uVar4,(HS *)lphs + 1);
      }
      if ((lphul->ihuldef == ihuldefMiniMineLayer) || (lphul->ihuldef == ihuldefSuperMineLayer)) {
        uVar6 = __aFlshl(lVar8,(ushort)(HS *)lphs);
      }
      cMine = uVar6;
      uVar6 = __aFulmul(uVar6,(long)((FLEET *)lpfl)->rgcsh[i]);
      uVar7 = uVar6 + uVar7;
    }
  }
  if (((long)uVar7 < 0x989681) && ((0xffff < (long)uVar7 || (-1 < (long)uVar7)))) {
    uVar7 = __aFulmul(uVar7,10);
  }
  else {
    uVar7 = 100000000;
  }
  return uVar7;
}



// ======================================================================
// Function: CMineSweepFromLpfl
// Address: 1080:2b26
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10802bd9) */

long CMineSweepFromLpfl(FLEET *lpfl)

{
  long lVar1;
  int iVar2;
  ulong uVar3;
  short i;
  
  lVar1 = 0;
  for (i = 0; i < 0x10; i = i + 1) {
    if (0 < ((FLEET *)lpfl)->rgcsh[i]) {
      iVar2 = ((FLEET *)lpfl)->iPlayer * 4;
      uVar3 = CMineSweepFromLphul((HUL *)CONCAT22(*(undefined2 *)(iVar2 + 0x100),
                                                  (HUL *)(*(int *)(iVar2 + 0xfe) + i * 0x93)));
      uVar3 = __aFulmul(uVar3,(long)((FLEET *)lpfl)->rgcsh[i]);
      lVar1 = uVar3 + lVar1;
    }
  }
  if (lVar1 < 1) {
    lVar1 = 0;
  }
  return lVar1;
}



// ======================================================================
// Function: CMineSweepFromLphul
// Address: 1080:2bfa
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10802d3d) */

long CMineSweepFromLphul(HUL *lphul)

{
  BEAM *pBVar1;
  undefined2 uVar2;
  bool bVar3;
  ulong uVar4;
  ulong uVar5;
  ulong uVar6;
  PART part;
  long lPow;
  short fStarbase;
  short j;
  uint lRange;
  int local_c;
  HS *lphs;
  short chs;
  
  fStarbase = (short)(0x1f < (int)lphul->ihuldef);
  uVar2 = (undefined2)((ulong)lphul >> 0x10);
  chs = (short)((HUL *)lphul)->chs;
  lPow = 0;
  j = 0;
  lphs = (HS *)CONCAT22(uVar2,((HUL *)lphul)->rghs);
  do {
    if (chs <= j) {
      if (lPow < 1) {
        lPow = 0;
      }
      return lPow;
    }
    if (lphs->grhst == hstBeam) {
      part.hs.grhst = lphs->grhst;
      part.hs.wFlags_0x2 = ((HS *)lphs)->wFlags_0x2;
      FLookupPart(&part);
      uVar2 = part.u_PART_0x0004._2_2_;
      pBVar1 = (BEAM *)part.u_PART_0x0004.pbeam;
      if ((pBVar1->grfAbilities & 2U) == 0) {
        if ((pBVar1->grfAbilities & 1U) != 0) goto LAB_1080_2c4d;
        lRange = pBVar1->dRangeMax;
        local_c = (int)lRange >> 0xf;
      }
      else {
        lRange = 4;
        local_c = 0;
      }
      if (fStarbase != 0) {
        bVar3 = 0xfffe < lRange;
        lRange = lRange + 1;
        local_c = local_c + (uint)bVar3;
      }
      uVar6 = (ulong)pBVar1->dp;
      uVar5 = (ulong)(((HS *)lphs)->wFlags_0x2 >> 8);
      uVar4 = __aFulmul(CONCAT22(local_c,lRange),CONCAT22(local_c,lRange));
      uVar4 = __aFulmul(uVar4,uVar5);
      uVar4 = __aFulmul(uVar4,uVar6);
      lPow = uVar4 + lPow;
    }
LAB_1080_2c4d:
    j = j + 1;
    lphs = (HS *)lphs + 1;
  } while( true );
}



// ======================================================================
// Function: PctCloakFromLpfl
// Address: 1080:2d5e
// Segment: MEMORY_SHIP2
// ======================================================================


short PctCloakFromLpfl(FLEET *lpfl)

{
  byte bVar1;
  bool bVar2;
  short sVar3;
  uint uVar4;
  int iVar5;
  FLEET *pFVar6;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 uVar7;
  ulong uVar8;
  long lVar9;
  HS *in_stack_0000ffca;
  undefined2 in_stack_0000ffcc;
  short chs;
  long wtFleetCur;
  long cPts;
  short cScore;
  long wtFleet;
  HUL *lphul;
  short fUseFloat;
  long cPtsCur;
  short i;
  double dwtFleet;
  double dcPts;
  short j;
  
  wtFleet = 0;
  cPts = 0;
  bVar2 = false;
  i = 0;
  while( true ) {
    pFVar6 = (FLEET *)lpfl;
    uVar7 = (undefined2)((ulong)lpfl >> 0x10);
    if (0xf < i) break;
    if (0 < pFVar6->rgcsh[i]) {
      iVar5 = pFVar6->iPlayer * 4;
      in_stack_0000ffcc = *(undefined2 *)(iVar5 + 0x100);
      iVar5 = *(int *)(iVar5 + 0xfe) + i * 0x93;
      bVar1 = *(byte *)(iVar5 + 0x7a);
      uVar8 = __aFulmul((long)pFVar6->rgcsh[i],(ulong)*(uint *)(iVar5 + 0x28));
      cPtsCur = 0;
      sVar3 = GetRaceStat((PLAYER *)rgplr + pFVar6->iPlayer,rsMajorAdv);
      if (sVar3 == raStealth) {
        cPtsCur = 300;
      }
      j = 0;
      in_stack_0000ffca = (HS *)(iVar5 + 0x3a);
      while( true ) {
        if ((int)(uint)bVar1 <= j) break;
        uVar4 = CPtsCloakFromLphs((HS *)CONCAT22(in_stack_0000ffcc,in_stack_0000ffca));
        cPtsCur = CONCAT22(cPtsCur._2_2_ + ((int)uVar4 >> 0xf) + (uint)CARRY2((uint)cPtsCur,uVar4),
                           (uint)cPtsCur + uVar4);
        j = j + 1;
        in_stack_0000ffca = in_stack_0000ffca + 1;
      }
      wtFleetCur._0_2_ = (uint)uVar8;
      wtFleetCur._2_2_ = (int)(uVar8 >> 0x10);
      if ((-1 < cPtsCur) && ((0 < cPtsCur._2_2_ || ((uint)cPtsCur != 0)))) {
        if ((!bVar2) &&
           ((((0 < cPtsCur._2_2_ ||
              ((((-1 < cPtsCur && (4000 < (uint)cPtsCur)) || (7 < wtFleetCur._2_2_)) ||
               ((6 < wtFleetCur._2_2_ && (0xa120 < (uint)wtFleetCur)))))) || (0x5f5 < cPts._2_2_))
            || (((0x5f4 < cPts._2_2_ && (0xe100 < (uint)cPts)) ||
                ((0x2f9 < wtFleet._2_2_ && ((0x2fa < wtFleet._2_2_ || (0xf080 < (uint)wtFleet)))))))
            ))) {
          bVar2 = true;
        }
        if (!bVar2) {
          uVar8 = __aFulmul(cPtsCur,uVar8);
          cPts = uVar8 + cPts;
        }
      }
      if (!bVar2) {
        wtFleet = CONCAT22(wtFleet._2_2_ + wtFleetCur._2_2_ +
                           (uint)CARRY2((uint)wtFleet,(uint)wtFleetCur),
                           (uint)wtFleet + (uint)wtFleetCur);
      }
    }
    i = i + 1;
  }
  if (((bVar2) || ((uint)cPts != 0)) || (cPts._2_2_ != 0)) {
    sVar3 = GetRaceStat((PLAYER *)rgplr + pFVar6->iPlayer,rsMajorAdv);
    if (sVar3 != raStealth) {
      if (bVar2) {
        for (i = 0; i < 4; i = i + 1) {
        }
      }
      else {
        for (i = 0; i < 4; i = i + 1) {
          uVar4 = *(uint *)(pFVar6->rgwtMin + i);
          wtFleet = CONCAT22(wtFleet._2_2_ + *(uint *)((int)(pFVar6->rgwtMin + i) + 2) +
                             (uint)CARRY2((uint)wtFleet,uVar4),(uint)wtFleet + uVar4);
        }
      }
    }
    if (bVar2) {
      lVar9 = __ftol((double)CONCAT26(in_stack_0000ffcc,
                                              CONCAT24(in_stack_0000ffca,CONCAT22(unaff_SI,unaff_DI)
                                                      )));
    }
    else {
      lVar9 = __aFldiv(cPts,wtFleet);
    }
    cPts._2_2_ = (int)((ulong)lVar9 >> 0x10);
    if ((cPts._2_2_ < 1) && (lVar9 < 0)) {
      sVar3 = 0;
    }
    else {
      cPts._0_2_ = (uint)lVar9;
      if ((int)(uint)cPts < 0x65) {
        sVar3 = (int)(uint)cPts >> 1;
      }
      else if ((int)((uint)cPts + -100) < 0xc9) {
        sVar3 = ((int)((uint)cPts + -100) >> 3) + 0x32;
      }
      else if ((int)((uint)cPts + -300) < 0x139) {
        sVar3 = (int)((uint)cPts + -300) / 0x18 + 0x4b;
      }
      else {
        iVar5 = (uint)cPts + -0x264;
        if (iVar5 < 0x201) {
          sVar3 = (iVar5 >> 6) + 0x58;
        }
        else if (iVar5 < 1000) {
          sVar3 = (0x2ff < iVar5) + 0x60;
        }
        else {
          sVar3 = 0x62;
        }
      }
    }
  }
  else {
    sVar3 = 0;
  }
  return sVar3;
}



// ======================================================================
// Function: CPtsCloakFromLphs
// Address: 1080:3170
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x108031b3) */

short CPtsCloakFromLphs(HS *lphs)

{
  HullSlotType HVar1;
  HS *pHVar2;
  undefined2 uVar3;
  PART part;
  short cPts;
  
  cPts = 0;
  uVar3 = (undefined2)((ulong)lphs >> 0x10);
  pHVar2 = (HS *)lphs;
  if (pHVar2->wFlags_0x2 >> 8 == 0) {
    cPts = 0;
  }
  else {
    HVar1 = lphs->grhst;
    if (HVar1 == hstEngine) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 8) {
        cPts = 0x14;
      }
    }
    else if (HVar1 == hstScanner) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 6) {
        cPts = 0x28;
      }
    }
    else if (HVar1 == hstShield) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 4) {
        cPts = 0x46;
      }
      else if ((pHVar2->wFlags_0x2 & 0xff) == 6) {
        cPts = 0x14;
      }
    }
    else if (HVar1 == hstArmor) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 7) {
        cPts = 0x32;
      }
      else if ((pHVar2->wFlags_0x2 & 0xff) == 9) {
        cPts = 0x28;
      }
    }
    else if (HVar1 == hstBeam) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 0x12) {
        cPts = 0x14;
      }
    }
    else if (HVar1 == hstMining) {
      if ((pHVar2->wFlags_0x2 & 0xff) == 6) {
        cPts = 0x3c;
      }
      else if ((pHVar2->wFlags_0x2 & 0xff) == 7) {
        cPts = 0x32;
      }
    }
    else if (HVar1 == hstSpecialE) {
      if ((pHVar2->wFlags_0x2 & 0xff) < 5) {
        part.hs.grhst = lphs->grhst;
        part.hs.wFlags_0x2 = pHVar2->wFlags_0x2;
        FLookupPart(&part);
        cPts = ((ARMOR *)part.u_PART_0x0004.parmor)->dp;
      }
    }
    else if ((HVar1 == hstSpecialM) && ((pHVar2->wFlags_0x2 & 0xff) == 4)) {
      cPts = 0x14;
    }
    if (1 < pHVar2->wFlags_0x2 >> 8) {
      cPts = cPts * (pHVar2->wFlags_0x2 >> 8);
    }
  }
  return cPts;
}



// ======================================================================
// Function: MergeFleetsDlg
// Address: 1080:3376
// Segment: MEMORY_SHIP2
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

short MergeFleetsDlg(HWND hwnd,ushort msg,ushort wParam,long lParam)

{
  char *pcVar1;
  WPARAM WVar2;
  HWND HVar3;
  short sVar4;
  undefined2 unaff_SS;
  LRESULT LVar5;
  char *psz;
  char szT [78];
  HWND local_10;
  RECT rc;
  short i;
  
  if (msg == 0x14) {
    GetClientRect(hwnd,&rc);
    FillRect(wParam,&rc,hbrButtonFace);
    return 1;
  }
  if (msg == 0x19) {
    local_10 = (HWND)lParam;
    HVar3 = GetDlgItem(hwnd,0x51);
    if (local_10 != HVar3) {
      SetBkColor(wParam,CONCAT22(crButtonFace._2_2_,(undefined2)crButtonFace));
      return hbrButtonFace;
    }
  }
  else {
    if (msg == 0x110) {
      StickyDlgPos(hwnd,(POINT *)&ptStickyMergeFleetsDlg,1);
      for (i = 0; i < vcflMerge; i = i + 1) {
        pcVar1 = PszGetFleetName(((FLEET **)rglpfl)[vrgiflMerge[i]]->id);
        _strcpy(szT,pcVar1);
        if (1 < ((FLEET *)((FLEET **)rglpfl)[vrgiflMerge[i]])->cord) {
          _strcat(szT,(char *)0x16c4);
        }
        HVar3 = GetDlgItem(hwnd,0x51);
        SendMessage(HVar3,0x401,0,(LPARAM)szT);
        HVar3 = GetDlgItem(hwnd,0x51);
        if ((vcflMerge == 2) ||
           (((FLEET **)rglpfl)[vrgiflMerge[i]]->id == sel.fl.id)) {
          WVar2 = 1;
        }
        else {
          WVar2 = 0;
        }
        SendMessage(HVar3,0x406,WVar2,(long)i);
      }
      if (((uint)gd.grBits >> 0xb & 1) != 0) {
        AdvanceTutor();
      }
      return 1;
    }
    if (msg == 0x111) {
      if ((wParam == 1) || (wParam == 2)) {
        for (i = 0; i < vcflMerge; i = i + 1) {
          HVar3 = GetDlgItem(hwnd,0x51);
          LVar5 = SendMessage(HVar3,0x408,i,0);
          if (LVar5 == 0) {
            vrgiflMerge[i] = -1;
          }
        }
        if (((wParam == 1) && (((uint)gd.grBits >> 0xb & 1) != 0)) &&
           (sVar4 = FOKMergeDialog(), sVar4 == 0)) {
          return 1;
        }
        StickyDlgPos(hwnd,(POINT *)&ptStickyMergeFleetsDlg,0);
        EndDialog(hwnd,(uint)(wParam == 1));
        return 1;
      }
      if (wParam == 0x76) {
        WinHelp(hwnd,_szHelpFile,1,0x453);
        return 1;
      }
      if ((wParam == 0x7f8) || (wParam == 0x7f9)) {
        for (i = 0; i < vcflMerge; i = i + 1) {
          HVar3 = GetDlgItem(hwnd,0x51);
          SendMessage(HVar3,0x406,(uint)(wParam == 0x7f8),(long)i);
        }
        return 1;
      }
    }
  }
  return 0;
}



// ======================================================================
// Function: MarkTechsSeen
// Address: 1080:36b6
// Segment: MEMORY_SHIP2
// ======================================================================


void MarkTechsSeen(HUL *lphul,short iplr)

{
  byte bVar1;
  HUL *pHVar2;
  undefined2 uVar3;
  PART part;
  short ihs;
  short iTech;
  short iplrSav;
  
  iplrSav = idPlayer;
  idPlayer = iplr;
  part.hs.grhst = hstHull;
  part.hs.wFlags_0x2 = part.hs.wFlags_0x2 & 0xff00 | lphul->ihuldef & 0xff;
  FLookupPart(&part);
  for (iTech = 0; iTech < 6; iTech = iTech + 1) {
    if ((int)(part.u_PART_0x0004.parmor._0_2_)->rgTech[iTech] <
        (int)(uint)((byte *)rgTechBattle)[iTech]) {
      bVar1 = ((byte *)rgTechBattle)[iTech];
    }
    else {
      bVar1 = (part.u_PART_0x0004.parmor._0_2_)->rgTech[iTech];
    }
    ((byte *)rgTechBattle)[iTech] = bVar1;
  }
  ihs = 0;
  while( true ) {
    uVar3 = (undefined2)((ulong)lphul >> 0x10);
    pHVar2 = (HUL *)lphul;
    if ((int)(uint)pHVar2->chs <= ihs) break;
    if (pHVar2->rghs[ihs].wFlags_0x2 >> 8 != 0) {
      part.hs.grhst = (pHVar2->rghs + ihs)->grhst;
      part.hs.wFlags_0x2 = pHVar2->rghs[ihs].wFlags_0x2;
      FLookupPart(&part);
      for (iTech = 0; iTech < 6; iTech = iTech + 1) {
        if ((int)(part.u_PART_0x0004.parmor._0_2_)->rgTech[iTech] <
            (int)(uint)((byte *)rgTechBattle)[iTech]) {
          bVar1 = ((byte *)rgTechBattle)[iTech];
        }
        else {
          bVar1 = (part.u_PART_0x0004.parmor._0_2_)->rgTech[iTech];
        }
        ((byte *)rgTechBattle)[iTech] = bVar1;
      }
      iTech = -1;
      if (part.hs.grhst == hstEngine) {
        if ((part.hs.wFlags_0x2 & 0xff) == 8) {
          iTech = 9;
        }
      }
      else if (part.hs.grhst == hstShield) {
        if ((part.hs.wFlags_0x2 & 0xff) == 6) {
          iTech = 2;
        }
      }
      else if (part.hs.grhst == hstArmor) {
        if ((part.hs.wFlags_0x2 & 0xff) == 9) {
          iTech = 3;
        }
      }
      else if (part.hs.grhst == hstBeam) {
        if ((part.hs.wFlags_0x2 & 0xff) == 0x12) {
          iTech = 7;
        }
      }
      else if (part.hs.grhst == hstTorp) {
        if ((part.hs.wFlags_0x2 & 0xff) == 7) {
          iTech = 6;
        }
      }
      else if (part.hs.grhst == hstBomb) {
        if ((part.hs.wFlags_0x2 & 0xff) == 8) {
          iTech = 5;
        }
      }
      else if (part.hs.grhst == hstMining) {
        if ((part.hs.wFlags_0x2 & 0xff) == 6) {
          iTech = 4;
        }
      }
      else if (part.hs.grhst == hstSpecialE) {
        if ((part.hs.wFlags_0x2 & 0xff) == 4) {
          iTech = 1;
        }
      }
      else if (part.hs.grhst == hstSpecialM) {
        if ((part.hs.wFlags_0x2 & 0xff) == 4) {
          iTech = 0;
        }
        else if ((part.hs.wFlags_0x2 & 0xff) == 9) {
          iTech = 0xb;
        }
      }
      if (((iTech != -1) && (((byte *)rgTechTrader)[iTech] < 0x19)) &&
         (((byte *)rgTechTrader)[iTech] =
               ((byte *)rgTechTrader)[iTech] + (char)(part.hs.wFlags_0x2 >> 8),
         0x19 < ((byte *)rgTechTrader)[iTech])) {
        ((byte *)rgTechTrader)[iTech] = 0x19;
      }
    }
    ihs = ihs + 1;
  }
  idPlayer = iplrSav;
  return;
}



