// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: PszGetCompressedString
// Address: 1010:743a
// Segment: MEMORY_STRINGS
// ======================================================================


char * PszGetCompressedString(StringId ids)

{
  int iVar1;
  byte *pbVar2;
  bool bVar3;
  short fHigh;
  short iOffset;
  char *pszOut;
  byte *pch;
  short iLen;
  short i;
  short iNibble;
  short iBuild;
  byte *pchLen;
  short iChunk;
  
  iNibble = 0;
  if (ids != (int)iLastStrGet) {
    pchLen = (byte *)acSTR + ((int)ids >> 6) * 0x40;
    for (i = 0; i < (int)(ids & idsShieldAlsoContainsArmorComponentWhichWill); i = i + 1) {
      iNibble = iNibble + (uint)*pchLen;
      pchLen = (byte *)pchLen + 1;
    }
    pch = (byte *)(((short *)aiSTRChunkOffset)[(int)ids >> 6] + (iNibble >> 1));
    bVar3 = (iNibble & 1U) == 0;
    pszOut = (char *)szLastStrGet;
    iBuild = 0;
    iLen = (uint)*pchLen;
    while (pbVar2 = pch, iVar1 = iLen + -1, iLen != 0) {
      if (bVar3) {
        i = (int)(uint)*pch >> 4;
      }
      else {
        pch = (byte *)pch + 1;
        i = *pbVar2 & 0xf;
      }
      bVar3 = !bVar3;
      iBuild = iBuild + i;
      iLen = iVar1;
      if (i != 0xf) {
        *pszOut = ((char *)rgSTRLookupTable)[iBuild];
        pszOut = pszOut + 1;
        iBuild = 0;
      }
    }
    *pszOut = '\0';
  }
  return (char *)szLastStrGet;
}



