// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: LAB_1118_204a
// Address: 1118:204a
// Segment: _TEXT
// ======================================================================


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Instruction at (ram,0x11180bd4) overlaps instruction at (ram,0x11180bd2)
    */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Removing unreachable block (ram,0x111832c3) */
/* WARNING: Removing unreachable block (ram,0x1118211d) */
/* WARNING: Removing unreachable block (ram,0x1118212c) */
/* WARNING: Removing unreachable block (ram,0x11182c3e) */
/* WARNING: Type propagation algorithm not settling */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void LAB_1118_204a(void)

{
  int *piVar1;
  char *pcVar2;
  byte *pbVar3;
  uint *puVar4;
  byte *pbVar5;
  undefined2 *puVar6;
  char cVar7;
  code *pcVar8;
  undefined2 *puVar9;
  char cVar10;
  undefined1 uVar11;
  uint *puVar12;
  longdouble *plVar13;
  byte bVar14;
  byte bVar15;
  uint uVar16;
  uint uVar17;
  int iVar18;
  int iVar19;
  byte *pbVar20;
  byte bVar21;
  uint in_DX;
  uint uVar22;
  uint uVar23;
  uint uVar24;
  byte bVar25;
  char *pcVar26;
  byte bVar36;
  uint *puVar27;
  uint uVar28;
  int iVar29;
  byte *pbVar30;
  uint uVar31;
  uint uVar32;
  uint uVar33;
  byte *pbVar34;
  uint *puVar35;
  undefined2 *puVar37;
  int *piVar38;
  int unaff_BP;
  uint uVar39;
  uint uVar40;
  uint uVar41;
  int iVar42;
  undefined2 *puVar43;
  uint uVar44;
  longdouble *unaff_SI;
  uint uVar45;
  uint uVar46;
  uint uVar47;
  int iVar48;
  longdouble *plVar49;
  uint *unaff_DI;
  uint *puVar50;
  char *pcVar51;
  undefined2 unaff_ES;
  longdouble *unaff_SS;
  undefined2 uVar52;
  undefined1 uVar53;
  byte bVar54;
  bool bVar55;
  bool bVar56;
  undefined2 in_FPUControlWord;
  uint in_FPUStatusWord;
  undefined2 in_FPUTagWord;
  undefined2 in_FPULastInstructionOpcode;
  undefined4 in_FPUDataPointer;
  longdouble in_ST0;
  longdouble lVar57;
  longdouble in_ST1;
  DWORD DVar58;
  long lVar59;
  undefined4 uVar60;
  longdouble *plVar61;
  HLOCAL HStack_14;
  undefined2 uStack_12;
  int iStack_10;
  undefined2 uStack_e;
  int iStack_c;
  undefined2 uStack_a;
  int iStack_2;
  
  puVar12 = (uint *)0x1120;
  iStack_2 = unaff_BP + 1;
  if (DAT_1120_1c28 == '\0') {
    DOUBLE_0_0__1120_1a74 = (double)in_ST0;
  }
  __trandisp1();
  piVar38 = &iStack_2;
LAB_1118_20a9:
  plVar61 = (longdouble *)CONCAT22(in_DX,unaff_SI);
  UINT_1120_1aa4._0_1_ = '\x01';
  cVar10 = *(char *)((int)piVar38 + -0x11);
  if ((cVar10 < '\x01') || (cVar10 == '\x06')) {
    in_FPUStatusWord = (in_FPUStatusWord >> 8 & 0x7f) << 8;
    DOUBLE_0_0__1120_1706 = (double)in_ST0;
    piVar38[-5] = in_FPUStatusWord;
    if ((piVar38[-5] & 8U) == 0) {
      if (cVar10 != '\x06') goto LAB_1118_20c9;
    }
    else {
      cVar10 = '\x03';
    }
  }
  plVar13 = (longdouble *)(int)cVar10;
  DAT_1120_1a70 = plVar13;
  puVar27 = (uint *)(piVar38[-8] + 1);
  DAT_1120_1a72 = puVar27;
  UINT_1120_1aa2._1_1_ = '\0';
  if (((*puVar27 == 0x6f6c) && (*(char *)(piVar38[-8] + 3) == 'g')) && (cVar10 == '\x02')) {
    UINT_1120_1aa2._1_1_ = '\x01';
  }
  bVar15 = ((byte *)((int)puVar27 + (int)plVar13))[5];
  uVar17 = (uint)bVar15;
  lVar59 = CONCAT22(puVar27,uVar17);
  bVar54 = 0xe573 < uVar17;
  puVar50 = (uint *)((int)(uint *)&switchD_1118:213f::switchdataD_1120_1a8c + uVar17);
switchD_1118_213f_switchD:
  bVar36 = (byte)unaff_SI;
  bVar14 = (byte)((uint)unaff_SI >> 8);
  bVar21 = (byte)in_DX;
  cVar10 = (char)(in_DX >> 8);
  bVar25 = (byte)puVar27;
  switch(bVar15) {
  case 0:
    goto code_r0x1118216e;
  case 1:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 2:
    in_ST0 = (longdouble)0;
    goto code_r0x1118216e;
  case 3:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 4:
    lVar57 = (longdouble)0;
    piVar38[-5] = (uint)(in_ST0 < lVar57) << 8 | (uint)(NAN(in_ST0) || NAN(lVar57)) << 10 |
                  (uint)(in_ST0 == lVar57) << 0xe;
    if ((*(byte *)((int)piVar38 + -9) & 1) == 0) {
      in_ST0 = (longdouble)DOUBLE_1_79769313486e308__1120_1c20;
      goto code_r0x1118216e;
    }
  case 6:
    in_ST0 = (longdouble)DOUBLE_1_79769313486e308__1120_1c20;
code_r0x1118216b:
    in_ST0 = -in_ST0;
code_r0x1118216e:
    DOUBLE_0_0__1120_1a84 = (double)in_ST0;
    puVar43 = (undefined2 *)&DAT_1120_1a70;
    __matherr();
    if (puVar43 == (undefined2 *)0x0) {
      cVar10 = '!';
      if ((UINT_1120_1aa2._1_1_ != '\0') || ((longdouble *)0x2 < DAT_1120_1a70)) {
        cVar10 = '\"';
      }
      DAT_1120_1710 = (int)cVar10;
      if (((uint *)&UINT_1120_1a92)[(int)plVar13] != 0) {
        __wrt2err();
        __wrt2err();
        __NMSG_WRITE();
      }
    }
    in_ST0 = (longdouble)DOUBLE_0_0__1120_1a84;
    DOUBLE_0_0__1120_1706 = DOUBLE_0_0__1120_1a84;
LAB_1118_20c9:
    if ((char)UINT_1120_1aa4 == '\0') {
      DOUBLE_0_0__1120_1706 = (double)in_ST0;
    }
    return;
  case 5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 7:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 8:
    ((byte *)((int)piVar38 + (int)plVar13))[0x171f] =
         ((byte *)((int)piVar38 + (int)plVar13))[0x171f] + bVar14;
    goto LAB_1118_007c;
  case 9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 10:
    goto switchD_1118_213f_caseD_a;
  default:
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
  case 0x38:
  case 0x3c:
  case 0x40:
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    iVar18 = (uint)bVar14 << 8;
    goto LAB_1118_0012;
  case 0xf:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x10:
    unaff_SS = unaff_SI;
    puVar12 = unaff_DI;
LAB_1118_007c:
    while( true ) {
      WAITEVENT();
      iVar19 = INITAPP();
      iVar18 = 0;
      if (iVar19 != 0) break;
LAB_1118_0012:
      do {
        do {
          uVar52 = 0x1a;
          __exit(CONCAT11((char)((uint)iVar18 >> 8),0xff));
          piVar38 = (undefined2 *)0x0;
          lVar59 = INITTASK(uVar52);
          iVar18 = 0;
        } while ((int)lVar59 == 0);
code_r0x11180026:
        iVar18 = (int)lVar59;
        *(undefined2 *)&DAT_1120_1716 = unaff_ES;
        bVar55 = 0xfeff < uVar17;
        uVar17 = uVar17 + 0x100;
      } while (bVar55);
      *(uint *)&DAT_1120_16e0 = uVar17;
      *(undefined2 *)&DAT_1120_16e2 = plVar13;
      *(undefined2 *)&DAT_1120_16e4 = puVar50;
      *(undefined2 *)&DAT_1120_16e6 = puVar27;
      *(undefined2 *)&DAT_1120_16e8 = unaff_ES;
      *(undefined2 *)&DAT_1120_16ea = (int)((ulong)lVar59 >> 0x10);
      DVar58 = GetVersion();
      *(undefined2 *)&DAT_1120_1718 = CONCAT11((char)DVar58,(char)(DVar58 >> 8));
      if ((___wflags & 1) == 0) {
        pcVar8 = (code *)swi(0x21);
        uVar52 = (*pcVar8)();
      }
      else {
        uVar52 = DOS3CALL();
      }
      *(undefined2 *)&DAT_1120_171c = uVar52;
      *(undefined2 *)&DAT_1120_171a = CONCAT11((char)uVar52,(char)((uint)uVar52 >> 8));
      if ((___wflags & 1) == 0) {
        unaff_SI = (longdouble *)0x0;
switchD_1118_213f_caseD_a:
        *(undefined1 *)&DAT_1120_171f = (char)unaff_SI;
      }
    }
    __cinit();
    __setargv();
    __setenvp();
    __wcexit();
    unaff_SI = (longdouble *)__stubmain();
    bVar54 = (undefined1 *)0xfff9 < &stack0xffe4;
switchD_1118_213f_caseD_cf:
    *(byte **)((byte *)((int)piVar38 + (int)puVar50) + 0x6c4) =
         (byte *)((int)unaff_SI +
                 (uint)(CARRY1((byte)puVar27,*(byte *)((int)puVar27 + (int)plVar13)) ||
                       CARRY1((byte)puVar27 + *(byte *)((int)puVar27 + (int)plVar13),bVar54)) +
                 *(int *)((byte *)((int)piVar38 + (int)puVar50) + 0x6c4));
    _exit((short)unaff_SI);
    __amsg_exit();
    return;
  case 0x13:
  case 0x39:
  case 0x3d:
    in(in_DX);
    goto code_r0x11180208;
  case 0x14:
    goto switchD_1118_213f_caseD_14;
  case 0x15:
    goto switchD_1118_213f_caseD_15;
  case 0x16:
    lVar59 = (ulong)CONCAT21(in_DX,bVar14) << 8;
    *(byte *)(plVar13 + -2) = 0;
    goto code_r0x11180026;
  case 0x22:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x23:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x24:
  case 0x9c:
  case 0x9d:
  case 0x9e:
  case 0x9f:
  case 0xa0:
  case 0xa1:
  case 0xa2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x25:
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    pbVar3 = (byte *)((int)puVar27 + (int)plVar13) + -0x3d;
    bVar15 = *pbVar3;
    *pbVar3 = *pbVar3 + bVar21;
    if (SCARRY1(bVar15,bVar21)) {
      unaff_SI = *(longdouble **)(byte *)((int)puVar27 + (int)plVar13);
    }
    cVar10 = (char)unaff_SI;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + cVar10;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + cVar10;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + cVar10;
    *(byte *)plVar13 = *(byte *)plVar13 + (char)((uint)unaff_SI >> 8);
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  case 0x26:
  case 0x4c:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x27:
  case 0x4d:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x28:
  case 0x4e:
    *(byte *)plVar13 = *(byte *)plVar13 & bVar25;
    goto code_r0x1118216b;
  case 0x29:
  case 0x4f:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x2a:
  case 0x50:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x2b:
  case 0x51:
    iVar18 = uVar17 + 0x1a8d;
    uVar17 = ~uVar17;
    if (bVar36 != (byte)*puVar50) {
      iVar18 = iVar18 - uVar17;
      uVar17 = uVar17 + 1;
    }
    pbVar20 = (byte *)(iVar18 - uVar17);
    uVar52 = piVar38[4];
    if (uVar17 == 0) {
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 2;
      *(undefined2 *)plVar13 = *(undefined2 *)pbVar3;
      uVar17 = 0xfffe;
      plVar49 = (longdouble *)((int)plVar13 + 2);
    }
    else {
      plVar49 = plVar13;
      if (((uint)pbVar20 & 1) != 0) {
        plVar49 = (longdouble *)((int)plVar13 + 1);
        pbVar3 = pbVar20;
        pbVar20 = pbVar20 + 1;
        *(byte *)plVar13 = *pbVar3;
        uVar17 = uVar17 - 1;
      }
    }
    for (uVar16 = uVar17 >> 1; uVar16 != 0; uVar16 = uVar16 - 1) {
      plVar61 = plVar49;
      plVar49 = (longdouble *)((int)plVar49 + 2);
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 2;
      *(undefined2 *)plVar61 = *(undefined2 *)pbVar3;
    }
    for (uVar17 = (uint)((uVar17 & 1) != 0); uVar17 != 0; uVar17 = uVar17 - 1) {
      plVar61 = plVar49;
      plVar49 = (longdouble *)((int)plVar49 + 1);
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 1;
      *(byte *)plVar61 = *pbVar3;
    }
    return;
  case 0x2c:
  case 0x52:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x2d:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x2e:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x2f:
    if (uVar17 == 0) goto LAB_1118_017f;
    pbVar20 = (byte *)0x0;
    goto LAB_1118_0145;
  case 0x30:
    goto switchD_1118_213f_caseD_30;
  case 0x31:
  case 0x35:
code_r0x11180208:
    FUN_1118_026a();
    FUN_1118_026a();
    __ctermsub();
    if ((char)((ulong)_HStack_14 >> 0x18) == '\0') {
      if ((___wflags & 1) == 0) {
        pcVar8 = (code *)swi(0x21);
        (*pcVar8)();
      }
      else {
        DOS3CALL();
      }
    }
    return;
  case 0x32:
  case 0x36:
    DAT_1120_1a70 = plVar13;
    DAT_1120_1a72 = puVar27;
    UINT_1120_1aa4._0_1_ = 1;
    return;
  case 0x33:
  case 0x34:
  case 0x37:
    puVar4 = (uint *)((byte *)((int)puVar27 + (int)puVar50) + -0x6f);
    *puVar4 = *puVar4 >> 1 | (uint)((*puVar4 & 1) != 0) << 0xf;
    return;
  case 0x3a:
  case 0x3e:
    goto switchD_1118_213f_caseD_3a;
  case 0x3b:
  case 0x3f:
    goto code_r0x11180407;
  case 0x41:
    *(longdouble *)(piVar38 + -8) = in_ST0;
    puVar9 = piVar38 + -0xe;
    *puVar9 = in_FPUControlWord;
    puVar9[2] = in_FPUStatusWord;
    puVar9[4] = in_FPUTagWord;
    *(undefined4 *)(puVar9 + 10) = in_FPUDataPointer;
    *(undefined4 *)(puVar9 + 6) = 0x11182a00;
    puVar9[9] = in_FPULastInstructionOpcode;
    DAT_1120_1bfa = 2;
    if ((piVar38[-0xb] & 0xfU) != 0xf) {
      DAT_1120_1bfa = 1;
    }
    return;
  case 0x42:
    if (piVar38 == (undefined2 *)0x1) {
      unaff_SI = (longdouble *)0xf;
    }
    iVar18 = 0x22;
    pbVar20 = (byte *)((int)puVar50 + (int)unaff_SI);
    goto code_r0x1118153a;
  case 0x43:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x44:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x45:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x46:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x47:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x48:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x49:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x4a:
  case 0x54:
  case 0xa4:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x4b:
    pbVar3 = (byte *)((int)piVar38 + (int)puVar50) + 0xd0;
    bVar15 = *pbVar3;
    *pbVar3 = *pbVar3 + bVar36;
    if (CARRY1(bVar15,bVar36)) {
      unaff_SI = (longdouble *)((uint)unaff_SI | 0x8000);
      piVar38[-1] = piVar38[-1] + 1;
    }
    if ((uint)piVar38[-1] < 0x7fff) {
      if ((piVar38[-1] == 0) &&
         (((unaff_SI == (longdouble *)0x0 && puVar27 == (uint *)0x0) && uVar17 == 0) && in_DX == 0))
      {
        piVar38[-7] = piVar38[-7] | 1;
        puVar9 = *(undefined2 **)(piVar38 + 7);
        puVar43 = (undefined2 *)puVar9;
        for (iVar18 = 5; iVar18 != 0; iVar18 = iVar18 + -1) {
          puVar6 = puVar43;
          puVar43 = puVar43 + 1;
          *puVar6 = 0;
        }
      }
      else {
        puVar4 = *(uint **)(piVar38 + 7);
        uVar52 = (undefined2)((ulong)puVar4 >> 0x10);
        puVar12 = (uint *)puVar4;
        puVar12[3] = (uint)unaff_SI;
        puVar12[2] = (uint)puVar27;
        puVar12[1] = uVar17;
        *puVar4 = in_DX;
        puVar12[4] = piVar38[-1] | piVar38[-10];
      }
    }
    else {
      piVar38[-7] = piVar38[-7] | 2;
      puVar9 = *(undefined2 **)(piVar38 + 7);
      uVar52 = (undefined2)((ulong)puVar9 >> 0x10);
      puVar43 = (undefined2 *)puVar9;
      puVar43[4] = piVar38[-10] | 0x7fff;
      puVar43[3] = 0x8000;
      puVar43[2] = 0;
      puVar43[1] = 0;
      *puVar9 = 0;
    }
    puVar9 = *(undefined2 **)(piVar38 + 5);
    *puVar9 = piVar38[-9];
    ((undefined2 *)puVar9)[1] = piVar38[-8];
    return;
  case 0x53:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x55:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x56:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x57:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x58:
    pcVar8 = (code *)swi(4);
    if (SCARRY2(uVar17,0x1a8c)) {
      plVar61 = (longdouble *)(*pcVar8)();
    }
    uVar16 = (uint)((ulong)plVar61 >> 0x10);
    pbVar34 = (byte *)((int)puVar27 + (int)plVar13) + bVar54;
    pbVar20 = (byte *)((int)(longdouble *)plVar61 + (int)plVar13) +
              (CARRY2((uint)puVar27,(uint)plVar13) ||
              CARRY2((uint)((int)puVar27 + (int)plVar13),(uint)bVar54));
    if (*(char *)((int)piVar38 + -1) == '\0') {
      uVar22 = uVar16 + *unaff_DI;
      uVar16 = (uint)CARRY2(uVar16,*unaff_DI);
      uVar39 = uVar17 + unaff_DI[1];
      uVar45 = uVar39 + uVar16;
      uVar17 = (uint)(CARRY2(uVar17,unaff_DI[1]) || CARRY2(uVar39,uVar16));
      pbVar30 = pbVar34 + unaff_DI[2] + uVar17;
      uVar17 = (uint)(CARRY2((uint)pbVar34,unaff_DI[2]) ||
                     CARRY2((uint)(pbVar34 + unaff_DI[2]),uVar17));
      bVar55 = CARRY2((uint)pbVar20,unaff_DI[3]);
      pbVar20 = pbVar20 + unaff_DI[3];
      pbVar34 = pbVar20 + uVar17;
      if (bVar55 || CARRY2((uint)pbVar20,uVar17)) {
        uVar40 = (uint)pbVar30 >> 1 | (uint)(((uint)pbVar34 & 1) != 0) << 0xf;
        uVar39 = uVar45 >> 1 | (uint)(((uint)pbVar30 & 1) != 0) << 0xf;
        uVar45 = uVar22 >> 1 | (uint)((uVar45 & 1) != 0) << 0xf;
        uVar16 = (uint)((uVar22 & 1) != 0);
        uVar22 = uVar45 + uVar16;
        uVar16 = (uint)CARRY2(uVar45,uVar16);
        uVar45 = uVar39 + uVar16;
        uVar16 = (uint)CARRY2(uVar39,uVar16);
        pbVar30 = (byte *)(uVar40 + uVar16);
        pbVar34 = (byte *)(((uint)pbVar34 >> 1 |
                           (uint)(bVar55 || CARRY2((uint)pbVar20,uVar17)) << 0xf) +
                          (uint)CARRY2(uVar40,uVar16));
        piVar38[-2] = piVar38[-2] + 1;
      }
      goto LAB_1118_2e21;
    }
    uVar22 = uVar16 - *unaff_DI;
    uVar16 = (uint)(uVar16 < *unaff_DI);
    uVar39 = uVar17 - unaff_DI[1];
    uVar45 = uVar39 - uVar16;
    uVar17 = (uint)(uVar17 < unaff_DI[1] || uVar39 < uVar16);
    uVar16 = (int)pbVar34 - unaff_DI[2];
    pbVar30 = (byte *)(uVar16 - uVar17);
    uVar17 = (uint)(pbVar34 < (byte *)unaff_DI[2] || uVar16 < uVar17);
    uVar16 = (int)pbVar20 - unaff_DI[3];
    pbVar34 = (byte *)(uVar16 - uVar17);
    if (pbVar20 < (byte *)unaff_DI[3] || uVar16 < uVar17) {
      uVar17 = ~uVar22;
      uVar16 = ~uVar45;
      uVar39 = ~(uint)pbVar30;
      uVar22 = uVar17 + 1;
      uVar17 = (uint)(0xfffe < uVar17);
      uVar45 = uVar16 + uVar17;
      uVar17 = (uint)CARRY2(uVar16,uVar17);
      pbVar30 = (byte *)(uVar39 + uVar17);
      pbVar34 = (byte *)(~(uint)pbVar34 + (uint)CARRY2(uVar39,uVar17));
      if ((int)pbVar34 < 0) goto LAB_1118_2e21;
      if ((pbVar34 == (byte *)0x0) && ((uVar22 == 0 && uVar45 == 0) && pbVar30 == (byte *)0x0))
      goto LAB_1118_2e5f;
    }
    else {
      if (((uVar22 == 0 && uVar45 == 0) && pbVar30 == (byte *)0x0) && pbVar34 == (byte *)0x0)
      goto LAB_1118_2e5f;
      *(byte *)(piVar38 + -1) = *(byte *)(piVar38 + -1) ^ 0x80;
      if ((int)pbVar34 < 0) goto LAB_1118_2e21;
    }
    uVar17 = piVar38[-2];
    if ((char)((uint)pbVar34 >> 8) != '\0') goto LAB_1118_2ebb;
    goto LAB_1118_2ea2;
  case 0x59:
    LocalSize(HStack_14);
    return;
  case 0x5a:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x5b:
  case 0x6b:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x5c:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x5d:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x5e:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x5f:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x60:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x61:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x62:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 99:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 100:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x65:
    goto switchD_1118_213f_caseD_65;
  case 0x66:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x67:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x68:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x69:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x6a:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x6c:
    goto switchD_1118_213f_caseD_6c;
  case 0x6d:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x6e:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x6f:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x70:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x71:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x72:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x73:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x74:
    for (; puVar50 != (uint *)0x0; puVar50 = (uint *)((uint)puVar50 >> 3)) {
    }
    return;
  case 0x75:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x76:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x77:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x78:
    while( true ) {
      *(char *)(piVar38 + -3) = (char)*puVar27;
      *(undefined1 *)puVar27 = *(undefined1 *)(piVar38 + -2);
      *(undefined1 *)(piVar38 + -2) = *(undefined1 *)(piVar38 + -3);
      piVar38[3] = piVar38[3] + 1;
      if ((char)*puVar27 == '\0') break;
      puVar27 = (uint *)piVar38[3];
    }
    return;
  case 0x79:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x7a:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x7b:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x7c:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x7d:
    goto switchD_1118_213f_switchD;
  case 0x7e:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x7f:
    if (bVar21 == 0 && *(char *)((int)piVar38 + -0x75) == '\0') {
      plVar49 = (longdouble *)((int)plVar13 + 1);
    }
    else {
      plVar49 = plVar13;
      if ((int)plVar13 < 0) {
        DAT_1120_1710 = 9;
        DAT_1120_1a70 = plVar13;
        DAT_1120_1a72 = puVar27;
        UINT_1120_1aa4._0_1_ = 1;
        return;
      }
    }
    iVar18 = DAT_1120_1722;
    if (UINT_1120_1aa6 != 0) {
      iVar18 = DAT_1120_1726;
    }
    if (iVar18 <= (int)plVar49) {
      UINT_1120_1aa4._0_1_ = 1;
      DAT_1120_1a72 = puVar27;
      DAT_1120_1a70 = plVar13;
      DAT_1120_1710 = 9;
      return;
    }
    lVar59 = __lseek((short)plVar49,0,1);
    piVar38[-5] = (int)lVar59;
    piVar38[-4] = (int)((ulong)lVar59 >> 0x10);
    if (lVar59 == -1) {
      piVar38[-3] = 0xffff;
      piVar38[-2] = 0xffff;
      return;
    }
    lVar59 = __lseek((short)plVar49,0,2);
    iVar18 = (int)((ulong)lVar59 >> 0x10);
    piVar38[-3] = (int)lVar59;
    piVar38[-2] = iVar18;
    if (((int)lVar59 == piVar38[-5]) && (iVar18 == piVar38[-4])) {
      return;
    }
    __lseek((short)plVar49,CONCAT22(piVar38[-4],piVar38[-5]),0);
    return;
  case 0x80:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x81:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x82:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x83:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x84:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x85:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x86:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x87:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x88:
    lVar57 = (longdouble)DOUBLE_0_0__1120_1e66;
    piVar38[-2] = (uint)(in_ST0 < lVar57) << 8 | (uint)(NAN(in_ST0) || NAN(lVar57)) << 10 |
                  (uint)(in_ST0 == lVar57) << 0xe;
    return;
  case 0x89:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x8a:
    return;
  case 0x8b:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x8c:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x8d:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x8e:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x8f:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x90:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x91:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x92:
    goto switchD_1118_213f_caseD_92;
  case 0x93:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x94:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x95:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x96:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x97:
    goto code_r0x11182c66;
  case 0x98:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x99:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x9a:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0x9b:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xa3:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xa5:
    puVar37 = (undefined2 *)&stack0xffe6;
    puVar43 = (undefined2 *)&stack0xffe6;
    cVar10 = '\x02';
    do {
      piVar38 = piVar38 + -1;
      puVar37 = puVar37 + -1;
      *puVar37 = *piVar38;
      cVar10 = cVar10 + -1;
    } while ('\0' < cVar10);
    uVar16 = (uint)unaff_SI & 0xff;
code_r0x11182f13:
    puVar43[-1] = uVar16 | in_DX;
    lVar59 = (ulong)*(uint *)plVar13 * (ulong)*(uint *)((int)(uint *)&UINT_1120_1a92 + uVar17);
    uVar28 = (uint)((ulong)lVar59 >> 0x10);
    uVar16 = (uint)lVar59;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 2) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a90 + uVar17);
    uVar41 = (uint)((ulong)lVar59 >> 0x10);
    uVar39 = (uint)lVar59;
    uVar45 = uVar16 + uVar39;
    uVar16 = (uint)CARRY2(uVar16,uVar39);
    uVar22 = uVar28 + uVar41;
    uVar31 = uVar22 + uVar16;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 4) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a8e + uVar17);
    uVar47 = (uint)((ulong)lVar59 >> 0x10);
    uVar39 = (uint)lVar59;
    uVar46 = uVar45 + uVar39;
    uVar39 = (uint)CARRY2(uVar45,uVar39);
    uVar40 = uVar31 + uVar47;
    uVar32 = uVar40 + uVar39;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 6) * (ulong)*puVar50;
    uVar24 = (uint)((ulong)lVar59 >> 0x10);
    uVar45 = (uint)lVar59;
    uVar23 = uVar46 + uVar45;
    uVar45 = (uint)CARRY2(uVar46,uVar45);
    uVar46 = uVar32 + uVar24;
    uVar33 = uVar46 + uVar45;
    uVar31 = (uint)(CARRY2(uVar28,uVar41) || CARRY2(uVar22,uVar16)) +
             (uint)(CARRY2(uVar31,uVar47) || CARRY2(uVar40,uVar39)) +
             (uint)(CARRY2(uVar32,uVar24) || CARRY2(uVar46,uVar45));
    lVar59 = (ulong)*(uint *)((int)plVar13 + 2) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a92 + uVar17);
    uVar28 = (uint)((ulong)lVar59 >> 0x10);
    uVar16 = (uint)lVar59;
    uVar45 = uVar33 + uVar16;
    uVar16 = (uint)CARRY2(uVar33,uVar16);
    uVar22 = uVar31 + uVar28;
    uVar32 = uVar22 + uVar16;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 4) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a90 + uVar17);
    uVar41 = (uint)((ulong)lVar59 >> 0x10);
    uVar39 = (uint)lVar59;
    uVar46 = uVar45 + uVar39;
    uVar39 = (uint)CARRY2(uVar45,uVar39);
    uVar40 = uVar32 + uVar41;
    uVar33 = uVar40 + uVar39;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 6) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a8e + uVar17);
    uVar47 = (uint)((ulong)lVar59 >> 0x10);
    uVar45 = (uint)lVar59;
    uVar24 = uVar46 + uVar45;
    uVar45 = (uint)CARRY2(uVar46,uVar45);
    uVar46 = uVar33 + uVar47;
    uVar44 = uVar46 + uVar45;
    uVar40 = (uint)(CARRY2(uVar31,uVar28) || CARRY2(uVar22,uVar16)) +
             (uint)(CARRY2(uVar32,uVar41) || CARRY2(uVar40,uVar39)) +
             (uint)(CARRY2(uVar33,uVar47) || CARRY2(uVar46,uVar45));
    lVar59 = (ulong)*(uint *)((int)plVar13 + 4) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a92 + uVar17);
    uVar28 = (uint)((ulong)lVar59 >> 0x10);
    uVar16 = (uint)lVar59;
    uVar22 = uVar44 + uVar16;
    uVar16 = (uint)CARRY2(uVar44,uVar16);
    uVar45 = uVar40 + uVar28;
    uVar46 = uVar45 + uVar16;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 6) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a90 + uVar17);
    uVar41 = (uint)((ulong)lVar59 >> 0x10);
    uVar39 = (uint)lVar59;
    in_DX = uVar22 + uVar39;
    uVar39 = (uint)CARRY2(uVar22,uVar39);
    uVar22 = uVar46 + uVar41;
    lVar59 = (ulong)*(uint *)((int)plVar13 + 6) *
             (ulong)*(uint *)((int)(uint *)&UINT_1120_1a92 + uVar17) +
             CONCAT22((uint)(CARRY2(uVar40,uVar28) || CARRY2(uVar45,uVar16)) +
                      (uint)(CARRY2(uVar46,uVar41) || CARRY2(uVar22,uVar39)),uVar22 + uVar39);
    iVar18 = puVar43[-1];
    if (-1 < lVar59) {
      iVar18 = iVar18 + -1;
      bVar55 = (int)uVar23 < 0;
      uVar23 = uVar23 * 2;
      bVar56 = (int)uVar24 < 0;
      uVar24 = uVar24 * 2 | (uint)bVar55;
      bVar55 = (int)in_DX < 0;
      in_DX = in_DX * 2 | (uint)bVar56;
      lVar59 = CONCAT22((int)((ulong)lVar59 >> 0x10) << 1 | (uint)((int)lVar59 < 0),
                        (int)lVar59 << 1 | (uint)bVar55);
    }
    puVar50 = (uint *)0x0;
    plVar13 = (longdouble *)(uVar24 + (0x7fff < uVar23));
    uVar17 = (uint)CARRY2(uVar24,(uint)(0x7fff < uVar23));
    bVar55 = CARRY2(in_DX,uVar17);
    in_DX = in_DX + uVar17;
code_r0x11182fc4:
    uVar16 = (uint)((ulong)lVar59 >> 0x10);
    pbVar34 = (byte *)((uint)lVar59 + (int)puVar50);
    pbVar20 = pbVar34 + bVar55;
    uVar17 = (uint)(CARRY2((uint)lVar59,(uint)puVar50) || CARRY2((uint)pbVar34,(uint)bVar55));
    pbVar30 = (byte *)(uVar16 + (int)puVar50);
    pbVar34 = pbVar30 + uVar17;
    if (CARRY2(uVar16,(uint)puVar50) || CARRY2((uint)pbVar30,uVar17)) {
      iVar18 = iVar18 + 1;
      pbVar34 = (byte *)CONCAT11(0x80,(char)pbVar34);
    }
LAB_1118_2fcd:
    puVar43 = (undefined2 *)puVar43[2];
    puVar43[4] = iVar18;
    puVar43[3] = pbVar34;
    puVar43[2] = pbVar20;
    puVar43[1] = in_DX;
    *puVar43 = plVar13;
    return;
  case 0xa6:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xa7:
    *(byte *)((int)piVar38 + (int)puVar50) = *(byte *)((int)piVar38 + (int)puVar50) | bVar15;
    *(byte *)((int)plVar13 + -0x1f) = 0;
    pbVar3 = (byte *)((int)piVar38 + -1 + (int)puVar50);
    *pbVar3 = *pbVar3 | bVar15;
    puVar43 = (undefined2 *)*(undefined2 *)((int)piVar38 + -1);
    if (*pbVar3 != 0) {
      in_DX = (uint)unaff_SI & 0x8000;
      uVar16 = ((uint)unaff_SI & 0x7fff) + (uint)bVar15 + 0xc002;
      if (-1 < (int)uVar16) goto code_r0x11182f13;
    }
    iVar18 = 0;
    pbVar34 = (byte *)0x0;
    pbVar20 = (byte *)0x0;
    in_DX = 0;
    plVar13 = (longdouble *)0x0;
    goto LAB_1118_2fcd;
  case 0xa8:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xa9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xaa:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xab:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xac:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xad:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xae:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xaf:
    pbVar3 = (byte *)((int)piVar38 + (int)puVar50);
    bVar55 = CARRY1(*pbVar3,bVar21);
    *pbVar3 = *pbVar3 + bVar21;
    *(uint *)((int)piVar38 + (int)puVar50) = ~*(uint *)((int)piVar38 + (int)puVar50);
    iVar18 = CONCAT11(bVar14,*(undefined1 *)(ulong)((int)puVar27 + ((uint)unaff_SI & 0xff)));
    puVar43 = piVar38;
    goto code_r0x11182fc4;
  case 0xb0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb1:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb3:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb4:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb6:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb7:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb8:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xb9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xba:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xbb:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xbc:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xbd:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xbe:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xbf:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc1:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc3:
    *(uint *)(byte *)((int)piVar38 + (int)plVar13) =
         *(int *)(byte *)((int)piVar38 + (int)plVar13) + -0x7e71 +
         (uint)(((uint)unaff_SI & 0x100) != 0);
    return;
  case 0xc4:
    uVar17 = (uint)unaff_SI | 0x478b;
    if (-1 < (int)plVar13) {
      uVar17 = piVar38[7];
    }
    piVar38[7] = uVar17;
    FUN_1118_1fe6(uVar17,piVar38[-4]);
    __fmemset((void *)CONCAT22(piVar38[-3],(void *)piVar38[-4]),0x30,piVar38[7]);
    return;
  case 0xc5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc6:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 199:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 200:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xca:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcb:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcc:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcd:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xce:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcf:
    goto switchD_1118_213f_caseD_cf;
  case 0xd0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd1:
    plVar13 = unaff_SI;
    __fltout();
    *(undefined2 *)&DAT_1120_227a = plVar13;
    *(int *)&DAT_1120_1a66 = *(int *)(byte *)((int)plVar13 + 2) + -1;
    pcVar26 = (char *)((uint)(*(int *)plVar13 == 0x2d) + iStack_10);
    uVar52 = uStack_e;
    __fptostr();
    iVar18 = *(int *)(*(int *)&DAT_1120_227a + 2) + -1;
    *(bool *)0x1a68 = *(int *)&DAT_1120_1a66 < iVar18;
    *(int *)&DAT_1120_1a66 = iVar18;
    if ((iVar18 < -4) || (iStack_c <= iVar18)) {
      FUN_1118_1cec(HStack_14,uStack_12,iStack_10,uStack_e,iStack_c,uStack_a);
    }
    else {
      if (*(char *)&DAT_1120_1a68 != '\0') {
        do {
          pcVar51 = pcVar26;
          pcVar26 = pcVar51 + 1;
        } while (*(char *)CONCAT22(uVar52,pcVar51) != '\0');
        pcVar51[-1] = '\0';
      }
      FUN_1118_1e70(HStack_14,uStack_12,iStack_10,uStack_e,iStack_c);
    }
    return;
  case 0xd2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd3:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd4:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd6:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd7:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd8:
    goto switchD_1118_213f_caseD_d8;
  case 0xd9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xda:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xdb:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xdc:
    if ((___wflags & 1) == 0) {
      pcVar8 = (code *)swi(0x21);
      (*pcVar8)();
    }
    else {
      DOS3CALL(0x1118);
    }
    __dosret0();
    return;
  case 0xdd:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xde:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xdf:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe1:
    DOS3CALL();
    if ((bool)bVar54) goto LAB_1118_034f;
switchD_1118_213f_caseD_92:
    *(byte *)(puVar27 + 0xb94) = (byte)puVar27[0xb94] & 0xfd;
LAB_1118_034f:
    __dosretax();
    return;
  case 0xe2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe3:
    *(byte *)((int)puVar27 + (int)plVar13) =
         *(byte *)((int)puVar27 + (int)plVar13) + bVar36 + bVar54;
    pbVar3 = (byte *)((int)puVar27 + (int)plVar13);
    *(byte **)pbVar3 = (byte *)(*(int *)pbVar3 + (int)unaff_SI);
    if (*(int *)pbVar3 == 0) {
      pcVar8 = (code *)swi(0x21);
      (*pcVar8)();
    }
    else {
      DOS3CALL();
    }
    __dosret0();
    return;
  case 0xe4:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe6:
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    ((byte *)((int)puVar27 + (int)plVar13))[0x4002] =
         ((byte *)((int)puVar27 + (int)plVar13))[0x4002] + bVar14;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar36;
    unaff_SI = (longdouble *)(CONCAT11(bVar14,bVar36 + bVar15) + 0x40);
switchD_1118_213f_caseD_65:
    bVar15 = (byte)unaff_SI;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) | bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    ((byte *)((int)puVar27 + (int)plVar13))[-100] =
         ((byte *)((int)puVar27 + (int)plVar13))[-100] + bVar15;
    bVar15 = bVar15 | 0x40;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    *(byte *)((int)puVar27 + (int)plVar13) = *(byte *)((int)puVar27 + (int)plVar13) + bVar15;
    return;
  case 0xe7:
    if (unaff_SI == (longdouble *)0x0 && *(int *)(byte *)((int)plVar13 + 6) == 0) {
      _DAT_1120_1c38 = 0x3001;
      return;
    }
    if ((~uVar17 & 0x7ff0) == 0) {
      return;
    }
    DAT_1120_1c65 = (undefined1)in_FPUControlWord;
    DAT_1120_1c67._0_1_ = DAT_1120_1c65;
    in_ST0 = (longdouble)*(double *)plVar13;
    in_ST1 = in_ST0;
    _DAT_1120_1c65 = in_FPUControlWord;
code_r0x11182c66:
    *plVar13 = in_ST0;
    _i8_tpwr10();
    DAT_1120_1c63 =
         (uint)(_DAT_1118_2bc4 < in_ST1) << 8 | (uint)(NAN(_DAT_1118_2bc4) || NAN(in_ST1)) << 10 |
         (uint)(_DAT_1118_2bc4 == in_ST1) << 0xe;
    if (_DAT_1118_2bc4 < in_ST1 || (_DAT_1118_2bc4 == in_ST1) != 0) {
      in_ST1 = _DAT_1118_2bce * in_ST1;
    }
    DOUBLE_0_0__1120_1c2c._0_2_ = SUB102(in_ST1,0);
    DOUBLE_0_0__1120_1c2c._2_2_ = (uint)((unkuint10)in_ST1 >> 0x10);
    DOUBLE_0_0__1120_1c2c._4_2_ = (uint)((unkuint10)in_ST1 >> 0x20);
    DOUBLE_0_0__1120_1c2c._6_2_ = (uint)((unkuint10)in_ST1 >> 0x30);
    DAT_1120_1c34 = (int)((unkuint10)in_ST1 >> 0x40);
    bVar55 = false;
    bVar15 = 0;
    for (iVar18 = -(DAT_1120_1c34 + -0x3ffe); iVar18 != 0; iVar18 = iVar18 + -1) {
      uVar16 = DOUBLE_0_0__1120_1c2c._6_2_ & 1;
      DOUBLE_0_0__1120_1c2c._6_2_ = DOUBLE_0_0__1120_1c2c._6_2_ >> 1;
      uVar17 = DOUBLE_0_0__1120_1c2c._4_2_ & 1;
      DOUBLE_0_0__1120_1c2c._4_2_ = DOUBLE_0_0__1120_1c2c._4_2_ >> 1 | (uint)(uVar16 != 0) << 0xf;
      uVar16 = DOUBLE_0_0__1120_1c2c._2_2_ & 1;
      DOUBLE_0_0__1120_1c2c._2_2_ = DOUBLE_0_0__1120_1c2c._2_2_ >> 1 | (uint)(uVar17 != 0) << 0xf;
      uVar17 = DOUBLE_0_0__1120_1c2c._0_2_ & 1;
      DOUBLE_0_0__1120_1c2c._0_2_ = DOUBLE_0_0__1120_1c2c._0_2_ >> 1 | (uint)(uVar16 != 0) << 0xf;
      bVar55 = (bVar15 & 1) != 0;
      bVar15 = bVar15 >> 1 | (uVar17 != 0) << 7;
    }
    uVar45 = DOUBLE_0_0__1120_1c2c._0_2_ + 0x39a + (uint)bVar55;
    uVar17 = (uint)(0xfc65 < DOUBLE_0_0__1120_1c2c._0_2_ ||
                   CARRY2(DOUBLE_0_0__1120_1c2c._0_2_ + 0x39a,(uint)bVar55));
    uVar39 = DOUBLE_0_0__1120_1c2c._2_2_ + uVar17;
    uVar17 = (uint)CARRY2(DOUBLE_0_0__1120_1c2c._2_2_,uVar17);
    uVar16 = DOUBLE_0_0__1120_1c2c._4_2_ + uVar17;
    uVar17 = DOUBLE_0_0__1120_1c2c._6_2_ + CARRY2(DOUBLE_0_0__1120_1c2c._4_2_,uVar17);
    iVar18 = 0x10;
    pcVar26 = (char *)&DAT_1120_1c39;
    _DOUBLE_0_0__1120_1c2c = in_ST1;
    do {
      pcVar51 = pcVar26;
      iVar19 = iVar18;
      uVar46 = uVar45 << 1 | (uint)((int)((uint)bVar15 << 8) < 0);
      uVar40 = uVar39 << 1 | (uint)((int)uVar45 < 0);
      uVar22 = uVar16 << 1 | (uint)((int)uVar39 < 0);
      bVar55 = (int)uVar17 < 0;
      uVar28 = uVar17 << 1 | (uint)((int)uVar16 < 0);
      uVar47 = uVar46 << 1 | (uint)((char)(bVar15 << 1) < '\0');
      uVar41 = uVar40 << 1 | (uint)((int)uVar46 < 0);
      uVar23 = uVar22 << 1 | (uint)((int)uVar40 < 0);
      uVar46 = uVar28 << 1 | (uint)((int)uVar22 < 0);
      cVar10 = bVar15 * '\x05';
      uVar22 = (uint)CARRY1(bVar15 * '\x04',bVar15);
      uVar40 = uVar47 + uVar45;
      iVar48 = uVar40 + uVar22;
      uVar45 = (uint)(CARRY2(uVar47,uVar45) || CARRY2(uVar40,uVar22));
      uVar22 = uVar41 + uVar39;
      iVar42 = uVar22 + uVar45;
      uVar39 = (uint)(CARRY2(uVar41,uVar39) || CARRY2(uVar22,uVar45));
      uVar45 = uVar23 + uVar16;
      iVar18 = uVar45 + uVar39;
      uVar22 = (uint)(CARRY2(uVar23,uVar16) || CARRY2(uVar45,uVar39));
      bVar56 = CARRY2(uVar46,uVar17);
      uVar46 = uVar46 + uVar17;
      iVar29 = uVar46 + uVar22;
      bVar15 = bVar15 * '\n';
      uVar45 = iVar48 * 2 | (uint)(cVar10 < '\0');
      uVar39 = iVar42 * 2 | (uint)(iVar48 < 0);
      uVar16 = iVar18 * 2 | (uint)(iVar42 < 0);
      uVar17 = iVar29 * 2 | (uint)(iVar18 < 0);
      *pcVar51 = (((bVar55 << 1 | (int)uVar28 < 0) + (bVar56 || CARRY2(uVar46,uVar22))) * '\x02' |
                 iVar29 < 0) + 0x30;
      iVar18 = iVar19 + -1;
      pcVar26 = pcVar51 + 1;
    } while (iVar18 != 0);
    iVar19 = iVar19 + -2;
    break;
  case 0xe8:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xe9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xea:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xeb:
    bVar36 = (byte)((uint)puVar27 >> 8) | bVar36;
    pcVar2 = (char *)CONCAT11(bVar36,bVar25);
    *pcVar2 = *pcVar2 + bVar21;
    cVar7 = *(char *)((int)piVar38 + -0x75);
    *(longdouble **)(byte *)((int)plVar13 + 4) = unaff_SI;
    *(uint *)(byte *)((int)plVar13 + 2) = CONCAT11(bVar36,bVar25);
    *(uint *)((int)plVar13 + 6) = uVar17;
    *(uint *)plVar13 = CONCAT11(cVar10,bVar21 + cVar7);
    return;
  case 0xec:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xed:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xee:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xef:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf1:
    DOUBLE_0_0__1120_1706 =
         (double)CONCAT62(CONCAT42(DOUBLE_0_0__1120_1706._4_4_,
                                   (int)unaff_SI << 5 | DAT_1120_1bdc >> 0xb),
                          DAT_1120_1bdc << 5 | DAT_1120_1bda >> 0xb);
    return;
  case 0xf2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf3:
    out(in_DX,unaff_SI);
    __rtindfnpop();
    return;
  case 0xf4:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf5:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf6:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf7:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf8:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xf9:
    uVar11 = in(in_DX);
    uVar53 = 0;
    if ((___wflags & 1) == 0) {
      pcVar8 = (code *)swi(0x21);
      uVar60 = (*pcVar8)();
    }
    else {
      uVar60 = DOS3CALL();
    }
    pcVar26 = (char *)((ulong)uVar60 >> 0x10);
    if ((!(bool)uVar53) || ((int)uVar60 != 0x10)) goto LAB_1118_0a7b;
    goto LAB_1118_0aa8;
  case 0xfa:
    pbVar34 = (byte *)((int)(uint *)&switchD_1118:213f::switchdataD_1120_1a8c + uVar17 + 1);
    pbVar20 = (byte *)((int)plVar13 + 1);
    *(byte *)puVar50 = *(byte *)plVar13;
    for (uVar16 = uVar17 - 1 >> 1; uVar16 != 0; uVar16 = uVar16 - 1) {
      pbVar5 = pbVar34;
      pbVar34 = pbVar34 + 2;
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 2;
      *(undefined2 *)pbVar5 = *(undefined2 *)pbVar3;
    }
    for (uVar17 = (uint)((uVar17 - 1 & 1) != 0); uVar17 != 0; uVar17 = uVar17 - 1) {
      pbVar5 = pbVar34;
      pbVar34 = pbVar34 + 1;
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 1;
      *pbVar5 = *pbVar3;
    }
    return;
  case 0xfb:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xfc:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xfd:
    *(char *)(piVar38 + 2) = *(char *)(piVar38 + 2) + cVar10;
    *(undefined2 *)0xc = unaff_SI;
    *(uint *)((int)unaff_SI + -2) = in_DX;
    *(uint **)(byte *)((int)unaff_SI + -4) = puVar27;
    return;
  case 0xfe:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xff:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  do {
    if (iVar19 == 0) break;
    iVar19 = iVar19 + -1;
    pcVar2 = pcVar51;
    pcVar51 = pcVar51 + -1;
  } while (*pcVar2 == '0');
  _DAT_1120_1c38 = CONCAT11(DAT_1120_1c39,(char)iVar19 + '\x12');
  return;
LAB_1118_0aa8:
  cVar10 = *pcVar26;
  pcVar26 = pcVar26 + 1;
  if (cVar10 == '\0') {
LAB_1118_0a7b:
    __dosret0();
    return;
  }
  if ((cVar10 == '?') || (cVar10 == '*')) goto LAB_1118_0a7b;
  goto LAB_1118_0aa8;
LAB_1118_016b:
  pbVar3 = pbVar20;
  pbVar30 = pbVar20 + 1;
  if (*pbVar3 < 0x41) goto LAB_1118_017f;
  pbVar20 = pbVar20 + 2;
  if (*pbVar30 < 0x41) goto LAB_1118_017f;
  pbVar5 = pbVar34;
  pbVar34 = pbVar34 + 1;
  *pbVar5 = *pbVar30 + 0xbf | (*pbVar3 + 0xbf) * '\x10';
  goto LAB_1118_016b;
switchD_1118_213f_caseD_15:
  puVar43 = (undefined2 *)*piVar38;
  DOUBLE_0_0__1120_1a74 = (double)in_ST0;
  DOUBLE_0_0__1120_1a7c = (double)in_ST1;
  *piVar38 = (int)((char *)s_M6102__MATH___floating_point_err_1120_2022 + 0xf);
  lVar57 = in_ST0;
  __trandisp2();
  piVar38 = puVar43;
  unaff_SI = plVar13;
  unaff_DI = puVar50;
  in_ST0 = in_ST1;
  in_ST1 = lVar57;
  goto LAB_1118_20a9;
switchD_1118_213f_caseD_3a:
  while( true ) {
    cVar10 = (char)unaff_SI + 'T';
    puVar4 = puVar27;
    puVar27 = (uint *)((int)puVar27 + 1);
    if ((((char)*puVar4 != cVar10) &&
        (bVar15 = (char)unaff_SI + 0x13, bVar54 = (char)*puVar4 + 0xbf,
        cVar10 = bVar54 + (-(bVar54 < 0x1a) & 0x20U) + 'A',
        cVar10 != (byte)(bVar15 + (-(bVar15 < 0x1a) & 0x20U) + 'A'))) || (cVar10 == '\0')) break;
    plVar61 = plVar13;
    plVar13 = (longdouble *)((int)plVar13 + 1);
    unaff_SI = (longdouble *)(uint)*(byte *)plVar61;
  }
  return;
switchD_1118_213f_caseD_30:
  do {
    if (uVar17 == 0) {
      DAT_1120_1a70 = plVar13;
      DAT_1120_1a72 = puVar27;
      UINT_1120_1aa4._0_1_ = 1;
      return;
    }
    uVar17 = uVar17 - 1;
    puVar4 = puVar50;
    puVar50 = (uint *)((int)puVar50 + 1);
  } while (bVar36 != (byte)*puVar4);
code_r0x11180407:
  UINT_1120_1aa4._0_1_ = 1;
  DAT_1120_1a72 = puVar27;
  DAT_1120_1a70 = plVar13;
  return;
  while( true ) {
    uVar17 = uVar17 - 1;
    puVar4 = puVar50;
    puVar50 = (uint *)((int)puVar50 + 1);
    if (bVar36 == (byte)*puVar4) break;
switchD_1118_213f_caseD_d8:
    if (uVar17 == 0) break;
  }
  uVar17 = ~uVar17;
  puVar12 = puVar27;
  do {
    if (uVar17 == 0) {
      DAT_1120_1a70 = plVar13;
      DAT_1120_1a72 = puVar27;
      UINT_1120_1aa4._0_1_ = 1;
      return;
    }
    uVar17 = uVar17 - 1;
    puVar4 = puVar12;
    puVar12 = (uint *)((int)puVar12 + 1);
  } while (*(char *)(piVar38 + 4) != (char)*puVar4);
  return;
  while (pbVar34 = (byte *)CONCAT11(cVar10,(char)uVar16), cVar10 != '\0') {
LAB_1118_2ea2:
    cVar10 = (char)pbVar34;
    uVar16 = (uint)pbVar30 >> 8;
    pbVar30 = (byte *)CONCAT11((char)pbVar30,(char)(uVar45 >> 8));
    uVar45 = CONCAT11((char)uVar45,(char)(uVar22 >> 8));
    uVar22 = uVar22 << 8;
    bVar55 = uVar17 < 8;
    uVar17 = uVar17 - 8;
    if (bVar55 || uVar17 == 0) goto LAB_1118_2e5f;
  }
LAB_1118_2ebb:
  pbVar20 = pbVar34;
  if (uVar17 == 0) {
LAB_1118_2e5f:
    *(undefined2 *)unaff_SI = 0;
    ((byte *)((int)unaff_SI + 2))[0] = 0;
    ((byte *)((int)unaff_SI + 2))[1] = 0;
    ((byte *)((int)unaff_SI + 4))[0] = 0;
    ((byte *)((int)unaff_SI + 4))[1] = 0;
    ((byte *)((int)unaff_SI + 6))[0] = 0;
    ((byte *)((int)unaff_SI + 6))[1] = 0;
    *(undefined2 *)(double *)((int)unaff_SI + 8) = 0;
  }
  else {
    while (-1 < (int)pbVar20) {
      uVar17 = uVar17 - 1;
      if (uVar17 == 0) goto LAB_1118_2e5f;
      bVar55 = (int)uVar22 < 0;
      uVar22 = uVar22 << 1;
      bVar56 = (int)uVar45 < 0;
      uVar45 = uVar45 << 1 | (uint)bVar55;
      bVar55 = (int)pbVar30 < 0;
      pbVar30 = (byte *)((int)pbVar30 << 1 | (uint)bVar56);
      pbVar20 = (byte *)((int)pbVar34 << 1);
      pbVar34 = (byte *)CONCAT11((char)((uint)pbVar20 >> 8),(byte)pbVar20 | bVar55);
    }
    piVar38[-2] = uVar17;
LAB_1118_2e21:
    *(uint *)unaff_SI = uVar22;
    *(uint *)((int)unaff_SI + 2) = uVar45;
    *(byte **)(byte *)((int)unaff_SI + 4) = pbVar30;
    *(byte **)(byte *)((int)unaff_SI + 6) = pbVar34;
    *(uint *)(double *)((int)unaff_SI + 8) =
         CONCAT11((byte)((uint)piVar38[-2] >> 8) | *(byte *)(piVar38 + -1),(char)piVar38[-2]);
  }
  return;
  while( true ) {
    iVar18 = iVar18 + -1;
    pbVar3 = pbVar20;
    pbVar20 = pbVar20 + 1;
    if (*pbVar3 == 0xd) break;
code_r0x1118153a:
    if (iVar18 == 0) break;
  }
  pbVar20[-1] = bVar25;
  FatalAppExit((UINT)puVar27,(LPCSTR)(byte *)((int)puVar50 + (int)unaff_SI));
  cVar10 = (char)(in_DX >> 8);
  FatalExit(0xff);
  *(byte *)((int)plVar13 + (int)(piVar38 + 0xf)) =
       *(byte *)((int)plVar13 + (int)(piVar38 + 0xf)) + cVar10;
switchD_1118_213f_caseD_6c:
  return;
LAB_1118_0145:
  do {
    if (*pbVar20 == 0) break;
    iVar18 = 0xd;
    pbVar34 = (byte *)s__C_FILE_INFO__1120_16f4;
    bVar55 = false;
    do {
      if (iVar18 == 0) break;
      iVar18 = iVar18 + -1;
      pbVar5 = pbVar20;
      pbVar20 = pbVar20 + 1;
      pbVar3 = pbVar34;
      pbVar34 = pbVar34 + 1;
      bVar55 = *pbVar3 == *pbVar5;
    } while (bVar55);
    if (bVar55) {
      pbVar34 = (byte *)&DAT_1120_1728;
      goto LAB_1118_016b;
    }
    iVar18 = 0x7fff;
    bVar55 = true;
    do {
      if (iVar18 == 0) break;
      iVar18 = iVar18 + -1;
      pbVar3 = pbVar20;
      pbVar20 = pbVar20 + 1;
      bVar55 = *pbVar3 == 0;
    } while (!bVar55);
  } while (bVar55);
LAB_1118_017f:
  FUN_1118_026a();
  FUN_1118_026a();
  FUN_1118_026a();
  return;
switchD_1118_213f_caseD_14:
  while( true ) {
    puVar35 = puVar27;
    plVar13 = (longdouble *)((int)plVar13 + 2);
    uVar17 = uVar17 - 1;
    uVar16 = uVar17;
    plVar49 = plVar13;
    puVar12 = puVar50;
    if (uVar17 == 0) break;
    do {
      uVar40 = (uint)((ulong)*puVar12 * (ulong)*(uint *)plVar49 >> 0x10);
      uVar45 = (uint)((ulong)*puVar12 * (ulong)*(uint *)plVar49);
      puVar4 = puVar35 + 1;
      uVar39 = *puVar4;
      *puVar4 = *puVar4 + uVar45;
      puVar4 = puVar35 + 2;
      uVar45 = (uint)CARRY2(uVar39,uVar45);
      uVar39 = *puVar4;
      uVar22 = *puVar4 + uVar40;
      *puVar4 = uVar22 + uVar45;
      puVar35[3] = puVar35[3] + (uint)(CARRY2(uVar39,uVar40) || CARRY2(uVar22,uVar45));
      uVar16 = uVar16 - 1;
      puVar27 = puVar35 + 1;
      plVar49 = (longdouble *)((int)plVar49 + 2);
      puVar12 = puVar12 + -1;
    } while (uVar16 != 0);
  }
  puVar12 = (uint *)piVar38[4];
  uVar17 = piVar38[-8];
  uVar16 = piVar38[-7];
  uVar39 = piVar38[-6];
  uVar45 = piVar38[-5];
  uVar22 = piVar38[-4];
  if (0 < (int)puVar12[5]) {
    do {
      if ((int)uVar22 < 0) goto LAB_1118_3a3d;
      piVar1 = piVar38 + -9;
      iVar18 = *piVar1;
      *piVar1 = *piVar1 << 1;
      bVar55 = (int)uVar17 < 0;
      uVar17 = uVar17 << 1 | (uint)(iVar18 < 0);
      bVar56 = (int)uVar16 < 0;
      uVar16 = uVar16 << 1 | (uint)bVar55;
      bVar55 = (int)uVar39 < 0;
      uVar39 = uVar39 << 1 | (uint)bVar56;
      bVar56 = (int)uVar45 < 0;
      uVar45 = uVar45 << 1 | (uint)bVar55;
      uVar22 = uVar22 << 1 | (uint)bVar56;
      puVar4 = puVar12 + 5;
      *puVar4 = *puVar4 - 1;
    } while (*puVar4 != 0);
  }
  puVar12[5] = puVar12[5] - 1;
  do {
    uVar46 = uVar22 & 1;
    uVar22 = uVar22 >> 1;
    uVar40 = uVar45 & 1;
    uVar45 = uVar45 >> 1 | (uint)(uVar46 != 0) << 0xf;
    uVar46 = uVar39 & 1;
    uVar39 = uVar39 >> 1 | (uint)(uVar40 != 0) << 0xf;
    uVar40 = uVar16 & 1;
    uVar16 = uVar16 >> 1 | (uint)(uVar46 != 0) << 0xf;
    uVar46 = uVar17 & 1;
    uVar17 = uVar17 >> 1 | (uint)(uVar40 != 0) << 0xf;
    puVar4 = (uint *)(piVar38 + -9);
    uVar40 = *puVar4;
    *puVar4 = *puVar4 >> 1 | (uint)(uVar46 != 0) << 0xf;
    piVar38[-2] = piVar38[-2] + (uint)((uVar40 & 1) != 0);
    puVar4 = puVar12 + 5;
    *puVar4 = *puVar4 + 1;
  } while (*puVar4 != 0);
  if (piVar38[-2] != 0) {
    piVar38[-9] = piVar38[-9] | 1;
  }
LAB_1118_3a3d:
  if ((0x7fff < (uint)piVar38[-9]) && ((0x8000 < (uint)piVar38[-9] || ((uVar17 & 1) != 0)))) {
    bVar56 = 0xfffe < uVar17;
    uVar17 = uVar17 + 1;
    bVar55 = CARRY2(uVar16,(uint)bVar56);
    uVar16 = uVar16 + bVar56;
    uVar40 = (uint)bVar55;
    bVar55 = CARRY2(uVar39,uVar40);
    uVar39 = uVar39 + uVar40;
    uVar40 = (uint)bVar55;
    bVar55 = CARRY2(uVar45,uVar40);
    uVar45 = uVar45 + uVar40;
    uVar40 = (uint)bVar55;
    bVar55 = CARRY2(uVar22,uVar40);
    uVar22 = uVar22 + uVar40;
    if (bVar55) {
      uVar22 = 0x8000;
      puVar12[5] = puVar12[5] + 1;
    }
  }
  if (puVar12[5] < 0x7fff) {
    puVar12[4] = uVar22;
    puVar12[3] = uVar45;
    puVar12[2] = uVar39;
    puVar12[1] = uVar16;
    *puVar12 = uVar17;
    puVar12[5] = puVar12[5] | piVar38[-1];
  }
  else {
    puVar12[5] = piVar38[-1] | 0x7fff;
    puVar12[4] = 0;
    puVar12[3] = 0;
    puVar12[2] = 0;
    puVar12[1] = 0;
    *puVar12 = 0;
  }
  return;
}



// ======================================================================
// Function: FUN_1118_24c7
// Address: 1118:24c7
// Segment: _TEXT
// ======================================================================


void FUN_1118_24c7(void)

{
  int unaff_BP;
  undefined2 unaff_SS;
  
  *(undefined1 *)(unaff_BP + -0x11) = 1;
  return;
}



// ======================================================================
// Function: LAB_1118_24e0
// Address: 1118:24e0
// Segment: _TEXT
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void LAB_1118_24e0(void)

{
  uint uVar1;
  bool bVar2;
  bool bVar3;
  unkbyte10 in_ST0;
  
  DAT_1120_1bd8 = (uint)((unkuint10)in_ST0 >> 0x40);
  DAT_1120_1bf2 = 1;
  DAT_1120_1bf4 = 0;
  _DAT_1120_1bd0 = CONCAT28(DAT_1120_1bd8 & 0x7fff,(sqword)in_ST0);
  FUN_1118_26cd();
  __FASTLDMULT();
  DAT_1120_1bf8 = 7;
  if ((DAT_1120_1bee & 1) == 0) {
    FUN_1118_25d4();
    __FASTLDMULT();
  }
  else {
    FUN_1118_25d4();
  }
  bVar3 = 0xfbff < DAT_1120_1bda;
  DAT_1120_1bda = DAT_1120_1bda + 0x400;
  bVar2 = CARRY2(DAT_1120_1bdc,(uint)bVar3);
  DAT_1120_1bdc = DAT_1120_1bdc + bVar3;
  uVar1 = (uint)bVar2;
  bVar2 = CARRY2(DAT_1120_1bde,uVar1);
  DAT_1120_1bde = DAT_1120_1bde + uVar1;
  uVar1 = (uint)bVar2;
  bVar2 = CARRY2(DAT_1120_1be0,uVar1);
  DAT_1120_1be0 = DAT_1120_1be0 + uVar1;
  if (bVar2) {
    DAT_1120_1be0 = 0x8000;
    DAT_1120_1be2 = DAT_1120_1be2 + 1;
  }
  DOUBLE_0_0__1120_1706._6_2_ =
       ((DAT_1120_1be2 + -0x3c00) * 0x10 | (DAT_1120_1be0 & 0x7fff) >> 0xb) ^ DAT_1120_1bf4 & 0x8000
  ;
  DOUBLE_0_0__1120_1706._4_2_ = DAT_1120_1be0 << 5 | DAT_1120_1bde >> 0xb;
  DOUBLE_0_0__1120_1706._2_2_ = DAT_1120_1bde * 0x20 | DAT_1120_1bdc >> 0xb;
  DOUBLE_0_0__1120_1706._0_2_ = DAT_1120_1bdc * 0x20 | DAT_1120_1bda >> 0xb;
  return;
}



// ======================================================================
// Function: LAB_1118_24f7
// Address: 1118:24f7
// Segment: _TEXT
// ======================================================================


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void LAB_1118_24f7(void)

{
  uint uVar1;
  bool bVar2;
  bool bVar3;
  unkbyte10 in_ST0;
  
  DAT_1120_1bd8 = (uint)((unkuint10)in_ST0 >> 0x40);
  DAT_1120_1bf2 = 0;
  DAT_1120_1bf4 = DAT_1120_1bd8;
  _DAT_1120_1bd0 = CONCAT28(DAT_1120_1bd8 & 0x7fff,(sqword)in_ST0);
  FUN_1118_26cd();
  __FASTLDMULT();
  DAT_1120_1bf8 = 7;
  if ((DAT_1120_1bee & 1) == 0) {
    FUN_1118_25d4();
    __FASTLDMULT();
  }
  else {
    FUN_1118_25d4();
  }
  bVar3 = 0xfbff < DAT_1120_1bda;
  DAT_1120_1bda = DAT_1120_1bda + 0x400;
  bVar2 = CARRY2(DAT_1120_1bdc,(uint)bVar3);
  DAT_1120_1bdc = DAT_1120_1bdc + bVar3;
  uVar1 = (uint)bVar2;
  bVar2 = CARRY2(DAT_1120_1bde,uVar1);
  DAT_1120_1bde = DAT_1120_1bde + uVar1;
  uVar1 = (uint)bVar2;
  bVar2 = CARRY2(DAT_1120_1be0,uVar1);
  DAT_1120_1be0 = DAT_1120_1be0 + uVar1;
  if (bVar2) {
    DAT_1120_1be0 = 0x8000;
    DAT_1120_1be2 = DAT_1120_1be2 + 1;
  }
  DOUBLE_0_0__1120_1706._6_2_ =
       ((DAT_1120_1be2 + -0x3c00) * 0x10 | (DAT_1120_1be0 & 0x7fff) >> 0xb) ^ DAT_1120_1bf4 & 0x8000
  ;
  DOUBLE_0_0__1120_1706._4_2_ = DAT_1120_1be0 << 5 | DAT_1120_1bde >> 0xb;
  DOUBLE_0_0__1120_1706._2_2_ = DAT_1120_1bde * 0x20 | DAT_1120_1bdc >> 0xb;
  DOUBLE_0_0__1120_1706._0_2_ = DAT_1120_1bdc * 0x20 | DAT_1120_1bda >> 0xb;
  return;
}



