// Decompiled code from stars.exe
// Generated by Ghidra - ExportAllDecompiled.py
// Grouped by nb09_ghidra_globals.json segmap.segname
// 

// ======================================================================
// Function: LpthNew
// Address: 1110:0000
// Segment: MEMORY_THING
// ======================================================================


THING * LpthNew(short iplr,ThingType ith)

{
  undefined2 unaff_SS;
  THING *pTVar1;
  THING thNew;
  THING *lpth;
  short i;
  short iItem;
  
                    /* Segment:    35
                       Offset:     000f8f00
                       Length:     1b9f
                       Min Alloc:  1b9f
                       Flags:      1d50
                           Code
                           Discardable
                           Moveable
                           Preload
                           Impure (Non-shareable)
                        */
  if (cThing < 0xfd2) {
    _memset(&thNew,0,0x12);
    thNew.idFull = thNew.idFull & 0x1ffU | (iplr & 0xfU) << 9 | ith << 0xd;
    i = 0;
    lpth = lpThings;
    while ((i < cThing && ((uint)lpth->idFull < (uint)thNew.idFull))) {
      i = i + 1;
      lpth = (THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1);
    }
    if ((i < cThing) && (thNew.idFull == lpth->idFull)) {
      iItem = lpth->idFull & 0x1ff;
      for (; i < cThing; i = i + 1) {
        if (0x1fe < iItem) {
          lpth._0_2_ = (THING *)0x0;
          lpth._2_2_ = 0;
          pTVar1 = lpThings;
          goto LAB_1110_021d;
        }
        if (lpth->idFull != thNew.idFull) break;
        thNew.idFull = thNew.idFull & 0xfe00U | thNew.idFull + 1U & 0x1ff;
        lpth = (THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1);
        iItem = iItem + 1;
      }
    }
    if (cThingAlloc <= cThing) {
      cThingAlloc = cThingAlloc + 10;
      if (lpThings == (THING *)0x0) {
        pTVar1 = LpAlloc(cThingAlloc * 0x12,htThings);
      }
      else {
        pTVar1 = LpReAlloc(lpThings,cThingAlloc * 0x12,htThings);
      }
      lpThings._2_2_ = (undefined2)((ulong)pTVar1 >> 0x10);
      lpThings._0_2_ = (THING *)pTVar1;
      lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings + i);
      lpThings = pTVar1;
    }
    if (i < cThing) {
      __fmemmove((THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1),lpth,
                         (cThing - i) * 0x12);
    }
    cThing = cThing + 1;
    __fmemcpy(lpth,(THING *)CONCAT22(unaff_SS,&thNew),0x12);
    pTVar1 = lpThings;
  }
  else {
    lpth._0_2_ = (THING *)0x0;
    lpth._2_2_ = 0;
    pTVar1 = lpThings;
  }
LAB_1110_021d:
  lpThings._2_2_ = (undefined2)((ulong)pTVar1 >> 0x10);
  lpThings._0_2_ = (THING *)pTVar1;
  return (THING *)CONCAT22(lpth._2_2_,(THING *)lpth);
}



// ======================================================================
// Function: FreeLpth
// Address: 1110:0224
// Segment: MEMORY_THING
// ======================================================================


void FreeLpth(THING *lpth)

{
  if ((THING *)lpth < (THING *)lpThings + cThing + -1) {
    __fmemmove(lpth,(THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1),
                       ((cThing - ((int)(THING *)lpth - (int)(THING *)lpThings) / 0x12
                        ) + -1) * 0x12);
  }
  cThing = cThing + -1;
  return;
}



// ======================================================================
// Function: CPlanetsInCircle
// Address: 1110:02a0
// Segment: MEMORY_THING
// ======================================================================


short CPlanetsInCircle(POINT pt,long r2)

{
  int iVar1;
  int iVar2;
  POINT *pPVar3;
  int iVar4;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  long lVar5;
  ulong uVar6;
  ulong uVar7;
  undefined2 in_stack_0000ffe2;
  undefined2 in_stack_0000ffe4;
  short xEnd;
  short dx;
  short cPl;
  short r;
  short i;
  short yStart;
  POINT *pptEnd;
  short dy;
  short yEnd;
  POINT *ppt;
  short xStart;
  
  _sqrt(SUB84((double)r2,0),
                (double)CONCAT26(unaff_SI,CONCAT24(unaff_DI,(long)((qword)(double)r2 >> 0x20))));
  lVar5 = __ftol((double)CONCAT26(in_stack_0000ffe4,
                                          CONCAT24(in_stack_0000ffe2,CONCAT22(unaff_SI,unaff_DI))));
  iVar1 = (int)lVar5;
  cPl = 0;
  pPVar3 = (POINT *)rgptPlan + game.cPlanMax;
  iVar2 = ((POINT *)rgptPlan + game.cPlanMax + -1)->x - rgptPlan[0].x;
  iVar4 = iVar2 >> 0xf;
  uVar6 = __aFulmul((long)(pt.x - rgptPlan[0].x),(long)game.cPlanMax);
  lVar5 = __aFldiv(uVar6,CONCAT22(iVar4,iVar2));
  i = (short)lVar5;
  if (game.cPlanMax <= i) {
    i = game.cPlanMax + -1;
  }
  if (i < 0) {
    i = 0;
  }
  for (ppt = (POINT *)rgptPlan + i;
      (pt.x - iVar1 <= ppt->x && ((POINT *)((int)&rgptPlan[0].x + 1U) <= ppt));
      ppt = ppt + -1) {
  }
  for (; (ppt->x <= pt.x + iVar1 && (ppt < pPVar3)); ppt = ppt + 1) {
    if (((pt.x - iVar1 <= ppt->x) && (pt.y - iVar1 <= ppt->y)) && (ppt->y <= pt.y + iVar1)) {
      iVar2 = ppt->x - pt.x;
      iVar4 = ppt->y - pt.y;
      uVar6 = __aFulmul((long)iVar4,(long)iVar4);
      uVar7 = __aFulmul((long)iVar2,(long)iVar2);
      iVar2 = (int)(uVar7 + uVar6 >> 0x10);
      if ((iVar2 <= r2._2_2_) && ((iVar2 < r2._2_2_ || ((uint)(uVar7 + uVar6) <= (uint)r2)))) {
        cPl = cPl + 1;
      }
    }
  }
  return cPl;
}



// ======================================================================
// Function: DrawThingGauge
// Address: 1110:044e
// Segment: MEMORY_THING
// ======================================================================


void DrawThingGauge(HDC hdc,RECT *prc,THING *lpth,short md)

{
  int iVar1;
  bool bVar2;
  short sVar3;
  THING *pTVar4;
  undefined2 uVar5;
  ulong cTot;
  long lVar6;
  DWORD DVar7;
  long l;
  long lMax;
  long rgSize [5];
  short i;
  short c;
  ushort rghbr [5];
  short fDisabled;
  short cSections;
  short iMode;
  
  bVar2 = false;
  SelectObject(hdc,rghfontArial8[1]);
  cSections = 1;
  uVar5 = (undefined2)((ulong)lpth >> 0x10);
  pTVar4 = (THING *)lpth;
  cTot = __aFulmul((ulong)(*(uint *)(pTVar4->rgb + 8) & 0x3fff),10);
  if ((md < 0) || (4 < md)) {
    if (md == 5) {
      for (i = 0; i < 3; i = i + 1) {
        rghbr[i] = ((ushort *)rghbrMineral)[i];
        iVar1 = *(int *)(pTVar4->rgb + i * 2 + 2);
        *(int *)(rgSize + i) = iVar1;
        *(int *)((int)rgSize + i * 4 + 2) = iVar1 >> 0xf;
      }
      cSections = 3;
      rgSize[0] = CONCAT22(rgSize[0]._2_2_,(undefined2)rgSize[0]);
    }
  }
  else if ((md == 4) || (md == 3)) {
    rghbr[0] = hbrButtonShadow;
    bVar2 = true;
    rgSize[0] = cTot;
  }
  else {
    rghbr[0] = ((ushort *)rghbrMineral)[md];
    rgSize[0] = (long)*(int *)(pTVar4->rgb + md * 2 + 2);
  }
  lVar6 = LDrawGauge(hdc,prc,cSections,rgSize,rghbr,cTot);
  sVar3 = SetBkMode(hdc,1);
  if (bVar2) {
    lVar6 = 0;
  }
  l._0_2_ = (undefined2)lVar6;
  if (cSections == 1) {
    c = _WSPRINTF((LPSTR)CONCAT22((undefined2)l,(char *)&DAT_1120_1120),(LPCSTR)0x16a01120,
                  (char *)szWork);
  }
  else {
    c = _WSPRINTF((LPSTR)CONCAT22((undefined2)l,(char *)&DAT_1120_1120),(LPCSTR)0x16a61120,
                  (char *)szWork);
  }
  DVar7 = GetTextExtent(hdc,szWork,c);
  if ((int)DVar7 < (prc->right - prc->left) + -3) {
    RcCtrTextOut(hdc,prc,(char *)szWork,c);
  }
  SetBkMode(hdc,sVar3);
  return;
}



// ======================================================================
// Function: IValidateWormholePos
// Address: 1110:064c
// Segment: MEMORY_THING
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x11100a9a) */
/* WARNING: Removing unreachable block (ram,0x11100a64) */
/* WARNING: Removing unreachable block (ram,0x11100994) */
/* WARNING: Removing unreachable block (ram,0x1110095e) */
/* WARNING: Removing unreachable block (ram,0x1110091a) */
/* WARNING: Removing unreachable block (ram,0x111008e4) */
/* WARNING: Removing unreachable block (ram,0x111008fc) */
/* WARNING: Removing unreachable block (ram,0x11100938) */
/* WARNING: Removing unreachable block (ram,0x11100976) */
/* WARNING: Removing unreachable block (ram,0x111009b2) */
/* WARNING: Removing unreachable block (ram,0x11100a7c) */
/* WARNING: Removing unreachable block (ram,0x11100ab8) */

short IValidateWormholePos(THING *lpthWorm)

{
  int iVar1;
  int iVar2;
  int iVar3;
  long lVar4;
  int iVar5;
  int iVar6;
  THING *pTVar7;
  THING *pTVar8;
  undefined2 uVar9;
  undefined2 uVar10;
  ulong uVar11;
  ulong uVar12;
  long l;
  long dx;
  short dUni;
  THING *lpth;
  short i;
  short ifl;
  FLEET *lpfl;
  THING *lpthMac;
  long dy;
  POINT pt;
  short iRet;
  
  iRet = 0;
  iVar5 = game.mdSize * 400;
  uVar9 = (undefined2)((ulong)lpthWorm >> 0x10);
  pTVar8 = (THING *)lpthWorm;
  iVar1 = (&pTVar8->pt)->x;
  iVar2 = (pTVar8->pt).y;
  if ((iVar1 < 1000) || (iVar2 < 1000)) {
    iRet = 0xf;
  }
  else if ((iVar5 + 0x578 < iVar1) || (iVar5 + 0x578 < iVar2)) {
    iRet = 0xf;
  }
  else {
    lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
    while ((THING *)lpth < (THING *)lpThings + cThing) {
      uVar10 = (undefined2)((ulong)lpth >> 0x10);
      if (((iVar1 == (&((THING *)lpth)->pt)->x) && (iVar2 == (((THING *)lpth)->pt).y)) &&
         (lpthWorm != lpth)) {
        return 0xf;
      }
      lpth = (THING *)CONCAT22(uVar10,(THING *)lpth + 1);
    }
    for (i = 0; i < game.cPlanMax; i = i + 1) {
      if ((iVar1 == ((POINT *)rgptPlan + i)->x) &&
         (iVar2 == *(int *)((int)&rgptPlan[0].y + i * 4))) {
        return 0xf;
      }
    }
    for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
      iVar6 = *(int *)((FLEET **)rglpfl + ifl);
      iVar3 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
      if ((iVar6 == 0) && (iVar3 == 0)) break;
      if ((iVar1 == *(int *)(iVar6 + 8)) && (iVar2 == *(int *)(iVar6 + 10))) {
        return 0xf;
      }
    }
    if ((((iVar1 < 0x3f2) || (iVar2 < 0x3f2)) || (iVar5 + 0x56e < iVar1)) || (iVar5 + 0x56e < iVar2)
       ) {
      iRet = 4;
    }
    pTVar7 = (THING *)lpThings + cThing;
    lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
    while ((THING *)lpth < pTVar7) {
      uVar10 = (undefined2)((ulong)lpth >> 0x10);
      if (((uint)lpth->idFull >> 0xd == 2) && (lpthWorm != lpth)) {
        iVar5 = iVar1 - (&((THING *)lpth)->pt)->x;
        iVar6 = iVar2 - (((THING *)lpth)->pt).y;
        uVar11 = __aFulmul((long)iVar6,(long)iVar6);
        uVar12 = __aFulmul((long)iVar5,(long)iVar5);
        lVar4 = uVar12 + uVar11;
        if (lpth->idFull == *(int *)(pTVar8->rgb + 6)) {
          if (lVar4 < 0x1324) {
            if (lVar4 < 0x19) {
              iRet = iRet | 8;
            }
            else if (lVar4 < 100) {
              iRet = iRet | 4;
            }
            else if (lVar4 < 900) {
              iRet = iRet | 2;
            }
            else {
              iRet = iRet | 1;
            }
          }
        }
        else if (lVar4 < 900) {
          if (lVar4 < 0x10) {
            iRet = iRet | 8;
          }
          else if (lVar4 < 0x40) {
            iRet = iRet | 4;
          }
          else if (lVar4 < 0xe1) {
            iRet = iRet | 2;
          }
          else {
            iRet = iRet | 1;
          }
        }
      }
      lpth = (THING *)CONCAT22(uVar10,(THING *)lpth + 1);
    }
    for (i = 0; i < game.cPlanMax; i = i + 1) {
      iVar5 = iVar1 - ((POINT *)rgptPlan + i)->x;
      iVar6 = iVar2 - *(int *)((int)&rgptPlan[0].y + i * 4);
      uVar11 = __aFulmul((long)iVar6,(long)iVar6);
      uVar12 = __aFulmul((long)iVar5,(long)iVar5);
      lVar4 = uVar12 + uVar11;
      if (lVar4 < 0x310) {
        if (lVar4 < 0x19) {
          iRet = iRet | 8;
        }
        else if (lVar4 < 100) {
          iRet = iRet | 4;
        }
        else if (lVar4 < 400) {
          iRet = iRet | 2;
        }
        else {
          iRet = iRet | 1;
        }
      }
    }
  }
  return iRet;
}



// ======================================================================
// Function: PctWormholeMoves
// Address: 1110:0adc
// Segment: MEMORY_THING
// ======================================================================


short PctWormholeMoves(THING *lpth)

{
  undefined2 uVar1;
  short pct;
  
  uVar1 = (undefined2)((ulong)lpth >> 0x10);
  pct = (*(uint *)((THING *)lpth)->rgb >> 2 & 0x3ff) / 5 - (2 - (*(uint *)((THING *)lpth)->rgb & 3))
  ;
  if (pct < 0) {
    pct = 0;
  }
  else if (6 < pct) {
    pct = 6;
  }
  return pct;
}



// ======================================================================
// Function: DoThingInteractions
// Address: 1110:0b3a
// Segment: MEMORY_THING
// ======================================================================


/* WARNING: Variable defined which should be unmapped: cGive */
/* WARNING: Removing unreachable block (ram,0x11101776) */
/* WARNING: Removing unreachable block (ram,0x11100ed1) */
/* WARNING: Removing unreachable block (ram,0x11101129) */

void DoThingInteractions(short fPostMove)

{
  uint *puVar1;
  long *plVar2;
  int *piVar3;
  char *pcVar4;
  undefined *puVar5;
  HUL *pHVar6;
  int iVar7;
  int iVar8;
  FLEET *pFVar9;
  uint uVar10;
  ushort uVar11;
  short sVar12;
  undefined *puVar13;
  short sVar14;
  byte bVar15;
  int iVar16;
  SHDEF *pSVar17;
  int iVar18;
  short *psVar19;
  FLEET *pFVar20;
  PLORD *pPVar21;
  undefined2 unaff_SI;
  HUL *pHVar22;
  undefined2 unaff_DI;
  SHDEF *pSVar23;
  undefined2 uVar24;
  undefined2 uVar25;
  undefined2 unaff_SS;
  bool bVar26;
  long lVar27;
  SHDEF *pSVar28;
  FLEET *lpfl_00;
  ulong uVar29;
  short p3;
  short p4;
  short p5;
  short p6;
  short p7;
  long lVar30;
  short cGive;
  FLEET *lpflNew;
  SHDEF *lpshdefDest;
  HUL HStack_e8;
  undefined4 uStack_5a;
  short ish;
  uint uStack_54;
  short iOffset;
  short cTry;
  short iPass;
  short iLvl;
  long l;
  short fMaxTech;
  long dx;
  short cPlrTrueMaxTech;
  short idm;
  THING *lpth;
  FLEET *lpfl;
  short ifl;
  short i;
  PLANET *lppl;
  PLANET *lpplMac;
  THING *lpthMac;
  long dy;
  long wtNext;
  byte rgTech [6];
  short iplrSav;
  POINT pt;
  long wtMin;
  short iplr;
  ushort grbitPlrTrader;
  long wtThreshhold;
  
  lVar30 = CONCAT22(unaff_SI,unaff_DI);
  if (fPostMove != 0) {
    iPass = (short)(THING *)lpThings;
    iLvl = lpThings._2_2_;
    lpthMac._0_2_ = (THING *)lpThings + cThing;
    lpthMac._2_2_ = lpThings._2_2_;
    lpth = (THING *)CONCAT22(lpThings._2_2_,(THING *)lpThings);
    while ((THING *)lpth < (THING *)lpthMac) {
      if ((uint)lpth->idFull >> 0xd == 3) {
        uVar24 = (undefined2)((ulong)lpth >> 0x10);
        iVar7 = (&((THING *)lpth)->pt)->x;
        iVar8 = (((THING *)lpth)->pt).y;
        for (ifl = 0; ifl < cFleet; ifl = ifl + 1) {
                    /* WARNING: Load size is inaccurate */
          pFVar9 = ((FLEET **)rglpfl)[ifl];
          iVar16 = *(int *)((int)((FLEET **)rglpfl + ifl) + 2);
          lpfl = (FLEET *)CONCAT22(iVar16,pFVar9);
          if ((pFVar9 == (FLEET *)0x0) && (iVar16 == 0)) break;
          if ((((uint)pFVar9->wFlags >> 10 & 1) == 0) &&
             (((&pFVar9->pt)->x == iVar7 && ((pFVar9->pt).y == iVar8)))) {
            wtMin._0_2_ = 0;
            wtMin._2_2_ = 0;
            for (i = 0; i < 3; i = i + 1) {
              uVar10 = *(uint *)(pFVar9->rgwtMin + i);
              bVar26 = CARRY2((uint)wtMin,uVar10);
              wtMin._0_2_ = (uint)wtMin + uVar10;
              wtMin._2_2_ = wtMin._2_2_ + *(uint *)((int)(pFVar9->rgwtMin + i) + 2) + (uint)bVar26;
            }
            if ((wtMin._2_2_ < 1) && ((wtMin._2_2_ < 0 || ((uint)wtMin < 5000)))) {
              if (((uint)pFVar9->wFlags >> 0xd & 1) == 0) {
                FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,
                                  idmMysteryTraderHasRefusedGiveCaptainAudience,lpfl->id | 0x8000,
                                  lpfl->id,0);
              }
            }
            else {
              if ((*(uint *)((int)&rgplr[0].wFlags + pFVar9->iPlayer * 0xc0) >> 1 & 1) ==
                  0) {
                cPlrTrueMaxTech = 0x1a;
              }
              else {
                cPlrTrueMaxTech = 10;
              }
              i = 0;
              while ((i < 6 && (cPlrTrueMaxTech <= *(char *)(pFVar9->iPlayer * 0xc0 + 0x59bc + i))))
              {
                i = i + 1;
              }
              fMaxTech = (short)(i == 6);
              uVar10 = *(uint *)((int)&rgplr[0].grbitTrader + pFVar9->iPlayer * 0xc0);
              sVar14 = pFVar9->iPlayer;
              bVar15 = (byte)sVar14;
              uVar24 = (undefined2)((ulong)lpth >> 0x10);
              if ((1 << (bVar15 & 0x1f) & *(uint *)(((THING *)lpth)->rgb + 6)) == 0) {
                puVar1 = (uint *)(((THING *)lpth)->rgb + 6);
                *puVar1 = *puVar1 | 1 << (bVar15 & 0x1f);
                FRemovePlayerMessage(sVar14,idmHasCompletedAssignedOrders,lpfl->id | 0x8000);
                uVar24 = (undefined2)((ulong)lpfl >> 0x10);
                ((FLEET *)lpfl)->wFlags = ((FLEET *)lpfl)->wFlags & 0xfbffU | 0x400;
                uVar24 = (undefined2)((ulong)lpth >> 0x10);
                if ((*(int *)(((THING *)lpth)->rgb + 8) == 0) ||
                   ((*(uint *)(((THING *)lpth)->rgb + 8) & uVar10) != 0)) {
                  if (fMaxTech == 0) {
                    iOffset = 0;
                    lVar27 = __aFldiv(CONCAT22(wtMin._2_2_ + -1 + (uint)(4999 < (uint)wtMin)
                                                       ,(uint)wtMin + 0xec78),0x4b0);
                    lVar27 = lVar27 + 6;
                    i = 0;
                    while( true ) {
                      if (5 < i) break;
                      iOffset = iOffset + *(char *)(((FLEET *)lpfl)->iPlayer * 0xc0 + 0x59bc + i);
                      i = i + 1;
                    }
                    if (10 < lVar27) {
                      lVar27 = 10;
                    }
                    iLvl = (short)((ulong)lVar27 >> 0x10);
                    iPass = (short)lVar27;
                    if (iOffset < 0x6c) {
                      if (iOffset < 0x60) {
                        if (iOffset < 0x54) {
                          if (iOffset < 0x48) {
                            if (0x3b < iOffset) {
                              lVar27 = CONCAT22(iLvl - (uint)(iPass == 0),iPass + -1);
                            }
                          }
                          else {
                            lVar27 = CONCAT22(iLvl - (uint)((uint)iPass < 2),iPass + -2);
                          }
                        }
                        else {
                          lVar27 = CONCAT22(iLvl - (uint)((uint)iPass < 3),iPass + -3);
                        }
                      }
                      else {
                        lVar27 = 2;
                      }
                    }
                    else {
                      lVar27 = 1;
                    }
                    iLvl = (short)((ulong)lVar27 >> 0x10);
                    iPass = (short)lVar27;
                    if ((uVar10 & 0x1fff) == 0x1fff) {
                      idm = 0x10a;
                    }
                    else {
                      idm = 0x109;
                    }
                    p7 = 0;
                    p6 = 0;
                    p5 = 0;
                    p4 = 0;
                    p3 = 0;
                    sVar12 = iPass;
                    uVar11 = WFromLpfl(lpfl);
                    FSendPlrMsg((uint)lpfl->id >> 9 & 0xf,idm,-1,uVar11,sVar12,p3,p4,p5,p6,p7);
                    while( true ) {
                      iVar16 = iPass + -1;
                      iVar18 = iLvl - (uint)(iPass == 0);
                      if ((iPass == 0) &&
                         (bVar26 = iLvl == 0, iPass = iVar16, iLvl = iVar18, bVar26)) break;
                      iPass = iVar16;
                      iLvl = iVar18;
                      sVar12 = Random(4);
                      lVar27 = uStack_5a;
                      if (sVar12 < 3) {
                        cTry = Random(6);
                        lVar27 = uStack_5a;
                        if (cPlrTrueMaxTech <= *(char *)(sVar14 * 0xc0 + 0x59bc + cTry))
                        goto LAB_1110_1010;
                      }
                      else {
LAB_1110_1010:
                        uStack_5a._2_2_ = (int)((ulong)lVar27 >> 0x10);
                        uStack_5a._0_2_ = (undefined2)lVar27;
                        cTry = 0;
                        i = 1;
                        while( true ) {
                          lVar27 = CONCAT22(uStack_5a._2_2_,(undefined2)uStack_5a);
                          if (5 < i) break;
                          uStack_5a._2_2_ = (int)*(char *)(sVar14 * 0xc0 + 0x59bc + i);
                          if (uStack_5a._2_2_ < *(char *)(sVar14 * 0xc0 + 0x59bc + cTry)) {
                            cTry = i;
                          }
                          i = i + 1;
                        }
                        if (cPlrTrueMaxTech <= *(char *)(sVar14 * 0xc0 + 0x59bc + cTry)) break;
                      }
                      uStack_5a = lVar27;
                      _memcpy(rgTech,(void *)((int)rgplr[0].rgTech + sVar14 * 0xc0
                                                     ),6);
                      sVar12 = idPlayer;
                      rgTech[cTry] = rgTech[cTry] + 1;
                      idPlayer = sVar14;
                      lVar27 = CostOfDevelopingItem((char *)CONCAT22(unaff_SS,rgTech));
                      psVar19 = (short *)(sVar14 * 0xc0 + 0x59c2 + cTry * 4);
                      ish = *psVar19;
                      uStack_54 = psVar19[1];
                      wtNext = lVar27;
                      idPlayer = sVar12;
                      lVar27 = __aFlshl(lVar30,cGive);
                      if (0 < wtNext) {
                        lVar27 = lVar27 + wtNext;
                      }
                      uStack_54 = (uint)((ulong)lVar27 >> 0x10);
                      ish = (short)lVar27;
                      psVar19 = (short *)(sVar14 * 0xc0 + 0x59c2 + cTry * 4);
                      *psVar19 = ish;
                      psVar19[1] = uStack_54;
                      uStack_5a = lVar27;
                      UpdateResearchStatus(0);
                    }
                  }
                  else {
                    sVar12 = Random(5);
                    if (sVar12 != 0) goto THING_LGivePart;
                    idm = 0x10e;
                    sVar14 = 0;
                    uVar11 = WFromLpfl(lpfl);
                    FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,idm,-1,uVar11,sVar14);
                  }
                }
                else {
THING_LGivePart:
                  cTry = 0x19;
                  iPass = *(short *)(((THING *)lpth)->rgb + 8);
                  if (iPass == 0) {
                    sVar12 = Random(0xd);
                    iPass = 1 << ((byte)sVar12 & 0x1f);
                  }
                  while (((iPass & uVar10) != 0 &&
                         (iVar16 = cTry + -1, bVar26 = 0 < cTry, cTry = iVar16, bVar26))) {
                    sVar12 = Random(0xd);
                    iPass = 1 << ((byte)sVar12 & 0x1f);
                  }
                  if (cTry < 1) {
                    iPass = 0x1000;
                  }
                  puVar1 = (uint *)(((THING *)lpth)->rgb + 6);
                  *puVar1 = *puVar1 | 1 << (bVar15 & 0x1f);
                  if (iPass == 0x1000) {
                    if ((*(uint *)((int)&rgplr[0].wMdPlr + sVar14 * 0xc0) >> 9 & 1) == 0)
                    {
                      iOffset = Random(4 - (uint)(100 < (uint)game.turn));
                      if (0 < iOffset) {
                        sVar12 = Random(2);
                        iOffset = sVar12 + 1;
                      }
                      pSVar28 = LpshdefT();
                      uVar24 = (undefined2)((ulong)pSVar28 >> 0x10);
                      pSVar17 = (SHDEF *)pSVar28 + iOffset + 0x13;
                      pHVar22 = &HStack_e8;
                      for (iVar16 = 0x49; iVar16 != 0; iVar16 = iVar16 + -1) {
                        pHVar6 = pHVar22;
                        pHVar22 = (HUL *)pHVar22->rgTech;
                        pSVar28 = pSVar17;
                        pSVar17 = (SHDEF *)(pSVar17->hul).rgTech;
                        pHVar6->ihuldef = (pSVar28->hul).ihuldef;
                      }
                      *(char *)&pHVar22->ihuldef = (char)(pSVar17->hul).ihuldef;
                      uStack_54 = IshFindSimilarDesign
                                            ((HUL *)CONCAT22(unaff_SS,&HStack_e8),sVar14);
                      if ((int)uStack_54 < 0) {
                        do {
                          uStack_54 = uStack_54 + 1;
                          if (0xf < (int)uStack_54) break;
                        } while ((*(uint *)(*(int *)(sVar14 * 4 + 0xfe) + uStack_54 * 0x93 + 0x7b)
                                  >> 9 & 1) == 0);
                      }
                      if (((int)uStack_54 < 0x10) &&
                         ((*(uint *)((int)&rgplr[0].wFlags +
                                    ((uint)lpfl->id >> 9 & 0xf) * 0xc0) & 0xfff) < 0x200)) {
                        sVar12 = Random(3);
                        if (sVar12 == 0) {
                          cGive = 2;
                        }
                        else {
                          cGive = 1;
                        }
                        if ((100 < (uint)game.turn) &&
                           (((uint)game.wCrap >> 2 & 1) == 0)) {
                          sVar12 = Random((uint)game.turn / 100 + 1);
                          cGive = cGive + sVar12;
                        }
                        if (5 < cGive) {
                          cGive = 5;
                        }
                        if (0 < iOffset) {
                          sVar12 = Random(cGive + 1);
                          cGive = cGive + sVar12;
                        }
                        lpfl_00 = LpflNew(sVar14,((FLEET *)lpfl)->idPlanet);
                        iVar16 = (int)((ulong)lpfl_00 >> 0x10);
                        pFVar9 = (FLEET *)lpfl_00;
                        if ((pFVar9 != (FLEET *)0x0) || (iVar16 != 0)) {
                          sVar12 = cGive;
                          uVar11 = WFromLpfl(lpfl);
                          FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,
                                            idmHasAbsorbedMysteryTraderReturnHaveGiven3,
                                            lpfl_00->id | 0x8000,uVar11,sVar12);
                          if (lpfl_00->id < lpfl->id) {
                            ifl = ifl + 1;
                          }
                          uVar24 = (undefined2)((ulong)lpfl >> 0x10);
                          pFVar20 = (FLEET *)lpfl;
                          sVar12 = (pFVar20->pt).y;
                          (&pFVar9->pt)->x = (&pFVar20->pt)->x;
                          (pFVar9->pt).y = sVar12;
                          sVar12 = (pFVar20->pt).y;
                          uVar25 = (undefined2)((ulong)pFVar9->lpplord >> 0x10);
                          pPVar21 = (PLORD *)pFVar9->lpplord;
                          (pPVar21 + 1)->wFlags = (&pFVar20->pt)->x;
                          *(short *)&pPVar21[1].iordMax = sVar12;
                          pFVar9->wFlags = pFVar9->wFlags & 0xdfffU | 0x2000;
                          uVar24 = *(undefined2 *)(sVar14 * 4 + 0x100);
                          pSVar17 = (SHDEF *)(*(int *)(sVar14 * 4 + 0xfe) + uStack_54 * 0x93);
                          if (((uint)pSVar17->wFlags >> 9 & 1) != 0) {
                            pHVar22 = &HStack_e8;
                            pSVar23 = pSVar17;
                            for (iVar18 = 0x49; iVar18 != 0; iVar18 = iVar18 + -1) {
                              pSVar28 = pSVar23;
                              pSVar23 = (SHDEF *)(pSVar23->hul).rgTech;
                              pHVar6 = pHVar22;
                              pHVar22 = (HUL *)pHVar22->rgTech;
                              (pSVar28->hul).ihuldef = pHVar6->ihuldef;
                            }
                            *(char *)&(pSVar23->hul).ihuldef = (char)pHVar22->ihuldef;
                            pSVar17->wFlags = pSVar17->wFlags & 0x83ffU | (uStack_54 & 0x1f) << 10;
                            pSVar17->wFlags = pSVar17->wFlags & 0x7fffU | 0x8000;
                            *(undefined2 *)&pSVar17->cBuilt = 0;
                            *(undefined2 *)((int)&pSVar17->cBuilt + 2) = 0;
                            *(undefined2 *)&pSVar17->cExist = 0;
                            *(undefined2 *)((int)&pSVar17->cExist + 2) = 0;
                            pcVar4 = (char *)((int)&rgplr[0].cShDef + sVar14 * 0xc0);
                            *pcVar4 = *pcVar4 + '\x01';
                            idPlayer = (uint)lpfl->id >> 9 & 0xf;
                            UpdateShdefCost((SHDEF *)CONCAT22(uVar24,pSVar17));
                            idPlayer = -1;
                          }
                          puVar1 = (uint *)&pSVar17->cBuilt;
                          uVar10 = *puVar1;
                          *puVar1 = *puVar1 + cGive;
                          piVar3 = (int *)((int)&pSVar17->cBuilt + 2);
                          *piVar3 = *piVar3 + (cGive >> 0xf) + (uint)CARRY2(uVar10,cGive);
                          puVar1 = (uint *)&pSVar17->cExist;
                          uVar10 = *puVar1;
                          *puVar1 = *puVar1 + cGive;
                          piVar3 = (int *)((int)&pSVar17->cExist + 2);
                          *piVar3 = *piVar3 + (cGive >> 0xf) + (uint)CARRY2(uVar10,cGive);
                          pFVar9->rgcsh[uStack_54] = cGive;
                          lVar27 = LGetFleetStat(lpfl_00,1);
                          *(int *)(pFVar9->rgwtMin + 4) = (int)lVar27;
                          *(undefined2 *)((int)pFVar9->rgwtMin + 0x12) =
                               (int)((ulong)lVar27 >> 0x10);
                          goto LAB_1110_0bac;
                        }
                      }
                      sVar14 = 0;
                      uVar11 = WFromLpfl(lpfl);
                      FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,
                                        idmHasAbsorbedMysteryTraderReturnTraderTried,-1,uVar11,
                                        sVar14);
                    }
                  }
                  else {
                    idm = IdmGiveTraderPart(iPass,sVar14,(ushort *)&iLvl);
                    sVar14 = 0;
                    uVar11 = WFromLpfl(lpfl);
                    FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,idm,iLvl,uVar11,sVar14);
                  }
                }
              }
              else {
                FSendPlrMsg2((uint)lpfl->id >> 9 & 0xf,
                                  idmMysteryTraderEyesCaptainSuspiciouslySuggestsHe,
                                  lpfl->id | 0x8000,lpfl->id,0);
              }
            }
          }
LAB_1110_0bac:
        }
        iPass = (short)(PLANET *)lpPlanets;
        iLvl = lpPlanets._2_2_;
        lpplMac._0_2_ = (PLANET *)lpPlanets + cPlanet;
        lppl = (PLANET *)CONCAT22(lpPlanets._2_2_,(PLANET *)lpPlanets);
        lpplMac._2_2_ = iLvl;
        while ((PLANET *)lppl < (PLANET *)lpplMac) {
          uVar24 = (undefined2)((ulong)lppl >> 0x10);
          if ((((((PLANET *)lppl)->iPlayer != -1) &&
               (((uint)((PLANET *)lppl)->wFlags >> 9 & 1) != 0)) &&
              ((*(uint *)((int)&rgplr[0].wMdPlr + ((PLANET *)lppl)->iPlayer * 0xc0) >> 9 &
               1) != 0)) &&
             ((1 < (*(uint *)((int)&rgplr[0].wMdPlr + ((PLANET *)lppl)->iPlayer * 0xc0) >>
                    10 & 7) &&
              ((1 << ((byte)((PLANET *)lppl)->iPlayer & 0x1f) & *(uint *)(((THING *)lpth)->rgb + 6))
               == 0)))) {
            dx._0_2_ = ((POINT *)rgptPlan + lppl->id)->x - iVar7;
            dx._2_2_ = (int)(uint)dx >> 0xf;
            if ((-1 < dx._2_2_) && ((0 < dx._2_2_ || (100 < (uint)dx)))) break;
            dy._0_2_ = *(int *)((int)&rgptPlan[0].y + lppl->id * 4) - iVar8;
            dy._2_2_ = (int)dy >> 0xf;
            uVar29 = __aFulmul((long)(int)dy,(long)(int)dy);
            iLvl = (short)(uVar29 >> 0x10);
            iPass = (short)uVar29;
            uVar29 = __aFulmul(CONCAT22(dx._2_2_,(uint)dx),CONCAT22(dx._2_2_,(uint)dx));
            l = uVar29 + CONCAT22(iLvl,iPass);
            if (l < 0x2711) {
              wtNext._0_2_ = (undefined *)0x0;
              wtNext._2_2_ = 0;
              i = 0;
              while( true ) {
                if (2 < i) break;
                uVar10 = *(uint *)(((PLANET *)lppl)->rgwtMin + i);
                bVar26 = CARRY2((uint)(undefined *)wtNext,uVar10);
                wtNext._0_2_ = (undefined *)wtNext + uVar10;
                wtNext._2_2_ = wtNext._2_2_ + *(uint *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2) +
                               (uint)bVar26;
                i = i + 1;
              }
              iVar16 = ((PLANET *)lppl)->iPlayer;
              if ((*(uint *)((int)&rgplr[0].wMdPlr + iVar16 * 0xc0) >> 10 & 7) == 2) {
                puVar13 = (undefined *)0xdac;
              }
              else {
                puVar13 = (undefined *)&DAT_1120_1388;
              }
              if ((0 < wtNext._2_2_) || ((-1 < wtNext._2_2_ && (puVar13 <= (undefined *)wtNext)))) {
                uVar24 = (undefined2)((ulong)lpth >> 0x10);
                if (*(int *)(((THING *)lpth)->rgb + 8) == 0) {
THING_LAutoTech:
                  iLvl = 0;
                  for (i = 0; i < 6; i = i + 1) {
                    iLvl = iLvl + *(char *)(iVar16 * 0xc0 + 0x59bc + i);
                  }
                  if ((*(uint *)((int)&rgplr[0].wFlags + ((FLEET *)lpfl)->iPlayer * 0xc0)
                       >> 1 & 1) == 0) {
                    cPlrTrueMaxTech = 0x1a;
                  }
                  else {
                    cPlrTrueMaxTech = 10;
                  }
                  if (cPlrTrueMaxTech * 6 + -6 <= iLvl) goto LAB_1110_1a6b;
                  for (iPass = 0; iPass < 6; iPass = iPass + 1) {
                    iLvl = 0;
                    for (i = 1; i < 6; i = i + 1) {
                      cTry = (short)*(char *)(iVar16 * 0xc0 + 0x59bc + i);
                      if (cTry < *(char *)(iVar16 * 0xc0 + 0x59bc + iLvl)) {
                        iLvl = i;
                      }
                    }
                    pcVar4 = (char *)(iVar16 * 0xc0 + 0x59bc + iLvl);
                    *pcVar4 = *pcVar4 + '\x01';
                  }
                  wtNext._2_2_ = 0;
                  wtNext._0_2_ = puVar13;
                }
                else {
                  iPass = 0x32;
                  iLvl = *(short *)(((THING *)lpth)->rgb + 8);
                  while (((iLvl & *(uint *)((int)&rgplr[0].grbitTrader + iVar16 * 0xc0))
                          != 0 && (iVar18 = iPass + -1, bVar26 = 0 < iPass, iPass = iVar18, bVar26))
                        ) {
                    sVar14 = Random(0xd);
                    iLvl = 1 << ((byte)sVar14 & 0x1f);
                  }
                  if (iPass < 1) goto THING_LAutoTech;
                  puVar1 = (uint *)((int)&rgplr[0].grbitTrader + iVar16 * 0xc0);
                  *puVar1 = *puVar1 | iLvl;
                }
                puVar1 = (uint *)(((THING *)lpth)->rgb + 6);
                *puVar1 = *puVar1 | 1 << ((byte)iVar16 & 0x1f);
                for (i = 2; (-1 < wtNext._2_2_ &&
                            (((0 < wtNext._2_2_ || ((undefined *)wtNext != (undefined *)0x0)) &&
                             (-1 < i)))); i = i + -1) {
                  iVar16 = *(int *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
                  if ((iVar16 < wtNext._2_2_) ||
                     ((puVar13 = (undefined *)wtNext, iVar18 = wtNext._2_2_, iVar16 <= wtNext._2_2_
                      && (*(undefined **)(((PLANET *)lppl)->rgwtMin + i) <= (undefined *)wtNext))))
                  {
                    puVar13 = *(undefined **)(((PLANET *)lppl)->rgwtMin + i);
                    iVar18 = *(int *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
                  }
                  plVar2 = ((PLANET *)lppl)->rgwtMin + i;
                  puVar5 = *(undefined **)plVar2;
                  *(int *)plVar2 = (int)*plVar2 - (int)puVar13;
                  piVar3 = (int *)((int)(((PLANET *)lppl)->rgwtMin + i) + 2);
                  *piVar3 = (*piVar3 - iVar18) - (uint)(puVar5 < puVar13);
                  bVar26 = (undefined *)wtNext < puVar13;
                  wtNext._0_2_ = (undefined *)wtNext + -(int)puVar13;
                  wtNext._2_2_ = (wtNext._2_2_ - iVar18) - (uint)bVar26;
                }
              }
            }
          }
LAB_1110_1a6b:
          lppl = (PLANET *)CONCAT22(lppl._2_2_,(PLANET *)lppl + 1);
        }
      }
      lpth = (THING *)CONCAT22(lpth._2_2_,(THING *)lpth + 1);
    }
  }
  return;
}



// ======================================================================
// Function: IdmGiveTraderPart
// Address: 1110:1a96
// Segment: MEMORY_THING
// ======================================================================


short IdmGiveTraderPart(ushort grbitTrader,short iplr,ushort *piGoto)

{
  uint *puVar1;
  short idm;
  ushort iGoto;
  
  puVar1 = (uint *)((int)&rgplr[0].grbitTrader + iplr * 0xc0);
  *puVar1 = *puVar1 | grbitTrader;
  idm = 0x10b;
  if (grbitTrader != 1) {
    if (grbitTrader == 2) {
      iGoto = 0xcb04;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 4) {
      iGoto = 0xc206;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 8) {
      iGoto = 0xc309;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x10) {
      iGoto = 0xc706;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x20) {
      iGoto = 0xc608;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x40) {
      iGoto = 0xc507;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x80) {
      iGoto = 0xc412;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x100) {
      idm = 0x10c;
      iGoto = 0xce1e;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x200) {
      iGoto = 0xc008;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x400) {
      idm = 0x10f;
      iGoto = 0xcf0e;
      goto LAB_1110_1b8b;
    }
    if (grbitTrader == 0x800) {
      iGoto = 0xcc09;
      goto LAB_1110_1b8b;
    }
  }
  iGoto = 0xcc04;
LAB_1110_1b8b:
  *piGoto = iGoto;
  return idm;
}



